### ISSUE TITLE
Similar project, bin-parser for Python

### ISSUE THREAD

**Issue by jfjlaros** [kaitai-io/kaitai_struct#1]
Hi Mikhail,

Nice project. It looks a lot like [something](https://github.com/jfjlaros/bin-parser/) I have been working on last year. Perhaps we could exchange some ideas?

**Comment by GreyCat** [comment]
Hi Jeron,

Great project you have there :) It seems that it's closer to the ideas of [DFDL](https://en.wikipedia.org/wiki/Data_Format_Description_Language), though — i.e. separate concepts of "data definition" and "representation definition".

What exchange do you have it mind? I thought that we could, for example, make a standardized set of stream runtimes for various languages, but on the second thought (and more detailed view of your project), I guess it won't be any help — if I understood correctly, you don't actually use a concept of primitive types, you define them right in the `types.yml` + use functions to convert.

**Comment by jfjlaros** [comment]
Indeed I don't use primitive data types, but that can be added by defining the proper functions I think. At this moment, the `types.yml` can be empty, as long as default types are used.

If I have some time, I will try to use one of your definitions using my parser.

**Comment by GreyCat** [comment]
No discussions occuring for more than 2 years, so I guess we can close this for now. Feel free to reopen, or come to our chat, or open more issues, etc.
