### ISSUE TITLE
Support for custom size integers

### ISSUE THREAD

**Issue by xuio** [kaitai-io/kaitai_struct#100]
It would be nice if Kaitai would support custom length integers (i.e. uint12, uint10), especially when using it a microcontroller or with wireless communication, where minimum packet size is vital.

**Comment by GreyCat** [comment]
Probably you mean arbitrary bit-sized integers? There is already support for it - #9 - it's available in current git.

**Comment by xuio** [comment]
Oh nice! I didn't find it because it wasn't in the wiki. Thanks anyway.

**Comment by GreyCat** [comment]
You're welcome :) We'll update the documentation eventually, when we'll make an official release of v0.6.
