### ISSUE TITLE
error:  unable to find type 'u6'

### ISSUE THREAD

**Issue by CodingPapi** [kaitai-io/kaitai_struct#1014]
Below code raises unable to find type 'u6' error, is 'u6' not supported? then how can I achieve such format? thanks!

- id: address_codes
        type:
          switch-on: net_info.ip_type
          cases:
            0: u2
            1: u4
            **2: u6**
            3: u8

**Comment by generalmimon** [comment]
@CodingPapi:

> Below code raises unable to find type 'u6' error,

Standard types are only `[us]{1,2,4,8}`, because these are commonly implemented natively in target languages.

> is 'u6' not supported? then how can I achieve such format?

You can use [bit-sized integers](https://doc.kaitai.io/user_guide.html#_bit_sized_integers):

```ksy
seq:
  - id: foo
    type: b48 # 8 * 6 = 48 bits
```

**Comment by CodingPapi** [comment]
> @CodingPapi:
> 
> > Below code raises unable to find type 'u6' error,
> 
> Standard types are only `[us]{1,2,4,8}`, because these are commonly implemented natively in target languages.
> 
> > is 'u6' not supported? then how can I achieve such format?
> 
> You can use [bit-sized integers](https://doc.kaitai.io/user_guide.html#_bit_sized_integers):
> 
> ```yaml
> seq:
>   - id: foo
>     type: b48 # 8 * 6 = 48 bits
> ```

Thanks!
