### ISSUE TITLE
implement void

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#102]
void is a type to be used in cases when a field must be missing, but usage of ```if``` is inconvenient.

```yaml
        type:
          switch-on: type
          cases:
            'type::double': f8
            'type::string': string
            'type::document': document
            'type::array': document
            'type::null': void
            'type::undefined': void
            'type::min_key': void
            'type::max_key': void
            'type::binary': binary
            'type::object_id': object_id
            'type::boolean': u1
            'type::utc_datetime': i8 #The int64 is UTC milliseconds since the Unix epoch.
            'type::regex': regex
            'type::db_pointer': db_pointer
            'type::javascript': string
            'type::symbol': string
            'type::javascript_unscoped': code_w_s
            'type::int32': i4
            'type::timestamp': u8 #Special internal type used by MongoDB replication and sharding. First 4 bytes are an increment, second 4 are a timestamp.
            'type::int64': i8
            'type::decimal128': f16
```

**Comment by GreyCat** [comment]
I don't know what you mean by `void`, but you can just omit the condition in `cases`. In this case, if you have `size` defined, you'll get raw byte array of that size, and if you don't, nothing would be read.

**Comment by koczkatamas** [comment]
Also you can create empty types like the None in this format: https://github.com/kaitai-io/kaitai_struct_formats/blob/master/executable/python_pyc_27.ksy

This way you will get None instances, so there always will be an instance in the value field (but in this case it won't use singleton instances, so it will not be as performant as it could be).

(As I don't really tested this solution I don't want to encourage the usage of it, but I wanted to note that you can do this too).

**Comment by KOLANICH** [comment]
>you can just omit the condition in cases

Shouldn't an exception be thrown / error value returned in such cases?

**Comment by GreyCat** [comment]
> Shouldn't an exception be thrown / error value returned in such cases?

In majority of programming languages, `switch` / `case` statement does not throw an exception / error on missing case. Basically, the only exception is functional strongly typed languages (Scala actually behaves that way), where you can derive whole domain of possible values and want it to be as strict as possible.

May be in future we can add extra options to make switching "strict" and throw an error on missed case.
