### ISSUE TITLE
switching on values from multiple enums

### ISSUE THREAD

**Issue by demberto** [kaitai-io/kaitai_struct#1025]
I have a TLV type, whose **type** is basically a single byte enum value. So its 256 values.

```ksy
event:
  seq:
    - id: id
      type: u1
    - id: len
    - id: value
      type:
        switch-on: id
        cases:
          'a::A': u2
          'b::A': u4
```

Putting them all in a single enum makes it look extremely redundant when switching, so I divided the enums into different ones.
I did all this manually and now I find out that the **type** field must have an `enum` attribute for it to be swtched over in the **value** field.

Is there any workaround this? I am wary of having to refactor it all.

**Comment by GreyCat** [comment]
Can you clarify what do you mean by "extremely redundant" and what would be your ideal way to express this in KSY?

So far, if `id` enum indeed has 256 different values, I don't see any good way around that not to mention them all one way or another. If you have some internal structure inside that enum (e.g. 2 bits out of 8 designate some group, and 6 other bits designate something within that group) — sure, that can be expressed. But if there's no structure per se, I don't see any other way rather then create values and specifications for all of them.

**Comment by generalmimon** [comment]
@demberto You can keep `id` an integer and use the [`to_i` method](https://doc.kaitai.io/user_guide.html#enum-methods) to convert the enum value to an integer:

```ksy
event:
  seq:
    - id: id
      type: u1
    # ...
    - id: value
      type:
        switch-on: id
        cases:
          'a::A.to_i': u2
          'b::A.to_i': u4
```

---

I don't think the uppercase identifier `A` of your enum members will be accepted by `kaitai-struct-compiler`, though (to my knowledge, all KS identifiers are required to match the pattern `/^[a-z][a-z0-9_]*$/`, i.e. must start with a lowercase letter and can continue with lowercase letters, digits or underscores - unless there is some bug that allows an identifier that doesn't match).

What version of KSC do you use?

**Comment by generalmimon** [comment]
@demberto:

> Will using `to_i` make the generated parsers slower?

Depends on the target language, but for the most part, I don't think there will be any measurable difference. And even if there was, I guess it will be only a **very** tiny slice of what generated parsers spend time on, so it's not really worth thinking about.
