### ISSUE TITLE
Using enum as type

### ISSUE THREAD

**Issue by demberto** [kaitai-io/kaitai_struct#1026]
I cannot use an enum in a `type` using `cases`. I need to make a separate wrapper type for the enum itself. How can I use the enum directly as a type?

Maybe I could use a parametric type which accepts an actual type (`u1`, `u2`, `u4`) and the enum type, but that will still mean another level of nesting.

**Comment by KOLANICH** [comment]
>How can I use the enum directly as a type?

In no way.

>Maybe I could use a parametric type

#135 are not implemented for now.
