### ISSUE TITLE
about unsigned_to_decimal(-static_cast<uint64_t>(val), &buf[1]);

### ISSUE THREAD

**Issue by lintianfang** [kaitai-io/kaitai_struct#1039]
Dear guys,

I met a C2220 error at row 249 of kaitaistream.h, here why put minus "-" to an unsigned number? could you give a hint?

static to_string(I val) {
        // in theory, `digits10 + 3` would be enough (minus sign + leading digit
        // + null terminator), but let's add a little more to be safe
        char buf[std::numeric_limits<I>::digits10 + 5];
        if (val < 0) {
            buf[0] = '-';
            // get absolute value without undefined behavior (https://stackoverflow.com/a/12231604)
            unsigned_to_decimal(-static_cast<uint64_t>(val), &buf[1]);   //C2220 occurs
        } else {
            unsigned_to_decimal(val, buf);
        }
        return std::string(buf);
    }

Thank you very much!

**Comment by GreyCat** [comment]
@lintianfang I believe this was addressed in https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/pull/56.

Also, please please please use proper Markdown formatting on your posts — i.e using triple backticks to delimit code.
