### ISSUE TITLE
How to add padding information 

### ISSUE THREAD

**Issue by abhijitraut** [kaitai-io/kaitai_struct#1041]
Please consider following structure

struct sample
{
	uint8_t field1;
	int32_t field2;
	int16_t field3;
	uint32_t field4;
};

offset and size information for above structure fields is as below:

field1 -> offset=0, size=1
field2 -> offset=4, size=4
field3 -> offset=8, size=2
field4 -> offset=12, size=4

In our case, while retrieving binary information, we are not interested in field 2 and field 3. So, we won't be populating Kaitai struct information with these fields
Generated Kaitai file will look like as follows:

meta:
  id: sample
  endian: be
seq:
  - id: field1
    type: u1
    size: 1
  - id: field4
    type: u4
    size: 4

We have questions as follows:
1. How to add padding information which will cover the space for field2 and field3
Simple answer from your side would be to populate Kaitai struct information with field2 and field3 and ignore them after reading. However we don't have access to this data. but we have offset information for these fields as shown above.
Please suggest how can we add some padding information for field2 and field3

2. In general, suppose we want to make use of field2 as well, how to add padding information between field1 and field2, as you can see size of field1 is 1 and offset of field 2 is 4

Thanks!

**Comment by Mingun** [comment]
Use `instances`:
```yaml
meta:
  id: sample
  endian: be
instances:
  field1:
    pos: 0
    type: u1
    size: 1
  field4:
    pos: 8
    type: u4
    size: 4
```

**Comment by abhijitraut** [comment]
Thanks @Mingun for your quick help :)

**Comment by generalmimon** [comment]
@Mingun:

> Use `instances`:

```diff
 meta:
   id: sample
   endian: be
 instances:
   field1:
     pos: 0
     type: u1
-    size: 1
   field4:
     pos: 8
     type: u4
-    size: 4
```

Just noting that the `size` fields have no effect here and will be ignored. In some future version, the compiler will throw a compile error on an unused superfluous field like this to prevent confusion.

**Comment by Mingun** [comment]
@generalmimon, Instead of throwing an error I strongly suggest to change the model as described in the #788

**Comment by generalmimon** [comment]
> @generalmimon, Instead of throwing an error I strongly suggest to change the model as described in the #788

Fine, but when you're answering someone's question, it makes little sense to provide an incorrect snippet without mentioning that fact.
