### ISSUE TITLE
Loss of Travis control

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#1042]
@GreyCat:

> * Travis still works (kind of), but effectively we've lost control of it. At least for me, it requires me to sign on some kind of trial plan, which I don't really want to invest time exploring (and potentially lose money).

Hmm... Can you elaborate on the "lost control" part - show screenshots and stuff? I must admit that I'm a bit worried right now, because at https://app.travis-ci.com/account/repositories where a week ago was the `kaitai-io` org tab is now this:

![image](https://github.com/kaitai-io/kaitai_struct/assets/47499687/64d2ed87-18e9-4782-bd90-f63c54bab595)

Were you adjusting some settings? What do you see there? What does the prompt to sign up for the "trial plan" as you mentioned look like?

_Originally posted by @generalmimon in https://github.com/kaitai-io/kaitai_struct/issues/824#issuecomment-1619065730_

**Comment by GreyCat** [comment]
Let me split this into a separate conversation. Here's what I'm seeing in my account after I've logged in after these couple of years:

![image](https://github.com/kaitai-io/kaitai_struct/assets/157154/0ffdd24f-3ddb-44e2-bf89-d746ccd4fe75)

Note:

* "Please select a plan to use Travis" banner at the top.
* "ORGANIZATIONS: You are not currently a member of any organization." at the left sidebar.
* "Repositories" tab lacks any repos and says that I need to perform some kind of migration.

> Were you adjusting some settings? What do you see there? What does the prompt to sign up for the "trial plan" as you mentioned look like?

I was not adjusting any settings or changing anything, at least not consciously. I might have tried clicking that "Review and add your authorized organizations." button, which initiated OAuth query to GitHub, which I've passed, but nothing has changed at all from my perspective in Travis.

As far as I understand, you say that it's probably possible to resolve this by escalating to Travis support, but even if that's the case, I'm not sure it's time well spent.

**Comment by generalmimon** [comment]
I'm still able to manage Travis, but given that we've successfully migrated all our repos away (see https://github.com/kaitai-io/kaitai_struct/issues/824#issuecomment-1807111128), it doesn't much matter anymore.

@GreyCat You can check if the procedure I shared in https://github.com/kaitai-io/kaitai_struct/issues/1042#issuecomment-1619812238 works for you too, but as I said, we're no longer using Travis, so it's not a big deal.

We could now cut off Travis for good (like disconnect it from GitHub, remove permissions, etc.), but I don't know whether the history of build logs will still be accessible after that. So it's probably best to leave it as it is for now.

**Comment by GreyCat** [comment]
@generalmimon You're right, let's leave it be, and then probably in several years we can consider removing it for good.
