### ISSUE TITLE
GHA migration: publication of JS packages to npm as vnext

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#1054]

**Comment by generalmimon** [comment]
I think I've already done this - see https://github.com/kaitai-io/kaitai_struct/compare/2bf973d6eb28d99521a8a533d2a1f15292801c30...ba2b6f8f52afcdfe62c3502bb2772829922eca9a:

https://github.com/kaitai-io/kaitai_struct/blob/ba2b6f8f52afcdfe62c3502bb2772829922eca9a/.github/workflows/main.yml#L41-L45

So I'm closing this issue.
