### ISSUE TITLE
# type: ignore generated Python files 

### ISSUE THREAD

**Issue by davetapley** [kaitai-io/kaitai_struct#1058]
As indicated in [PEP 484](https://peps.python.org/pep-0484/#compatibility-with-other-uses-of-function-annotations):

> To mark portions of the program that should not be covered by type hinting, you can use one or more of the following:
>
> a `# type: ignore` comment;

---

Kaitai generated Python code doesn't include type hints,
so I propose `# type: ignore`  be appended to the top of generated Python files, e.g.:

```py
# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild
# type: ignore

import kaitaistruct
from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO
```

This prevents tools such as `pyright` failing when it encounters these files.

---

I'm not too familiar with Scala, but I'm happy to have a go at a PR if someone can point me in the right direction.

**Comment by davetapley** [comment]
Also, since the files don't appear to be [PEP8](https://peps.python.org/pep-0008/) compliant we should append`# flake8: noqa` for [Flake8](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#ignoring-entire-files).

**Comment by GreyCat** [comment]
Thanks for the suggestion, @davetapley! Please also take a look at https://github.com/kaitai-io/kaitai_struct/issues/846 where there seems to be some discussion on implementation of Python type annotations.

I agree that in absence of complete solution, marking this as "not in scope of type hinting" makes sense, and that one is fairly easy to implement.

For PEP8 compliance, let me split this into a separate discussion.

**Comment by KOLANICH** [comment]
#675

**Comment by GreyCat** [comment]
@davetapley Please take a look if this solves at least the type hinting lack issue?
