### ISSUE TITLE
`meta`->`xref`->`forensicswiki`: Forensics Wiki is no longer a Mediawiki site

### ISSUE THREAD

**Issue by LikeLakers2** [kaitai-io/kaitai_struct#1066]
Hi, I found that the Forensics Wiki is no longer a MediaWiki site. Their new domain, <https://forensics.wiki/> (which I found by google searching "Forensics Wiki"), links to [a blogpost explaining that they're transitioning the site to Github](https://osdfir.blogspot.com/2022/11/transitioning-forensics-wiki-to-github.html).

This means that the `forensicswiki` links should probably be reconstructed to something like `https://forensics.wiki/{value}/`.

While normally I would leave this be, as the blogpost mentions forwarding `forensicswiki.xyz` (which is what the KSY Syntax Diagram links to in its documentation) to `forensics.wiki`, it appears `forensicswiki.xyz` is now a parked domain. I'm unsure if the people running Forensics Wiki lost control of that domain.

In any case, it appears updating how the `forensicswiki` links are generated, is probably something you want to do.

**Comment by generalmimon** [comment]
Good catch, thanks for reporting this! Yeah, we should migrate all links to the new site as fast as possible - we definitely don't want to link to `forensicswiki.xyz` anymore that is redirected to some fishy sites.

Unfortunately, the page slugs in the URL have changed too, so we probably have to change the `meta/xref/forensicswiki` values in the .ksy specs too: https://github.com/search?q=repo%3Akaitai-io%2Fkaitai_struct_formats+path%3A*.ksy+forensicswiki&type=code

But it's great to see that ForensicsWiki keeps going.

**Comment by generalmimon** [comment]
All <code>~~forensicswiki.xyz~~</code> occurrences in Kaitai Struct repos should now be updated to the new <code><ins>forensics.wiki</ins></code> domain.
