### ISSUE TITLE
JavaScript generator should wrap integer constants in objects' keys into brackets when creating code for enums

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#109]
otherwise we can have invalid code
```javascript
  SomeFormat.SomeEnum = Object.freeze({
    OFF: -1,
    ...
    -1: "OFF"
   ...
  });
```
But only the strings and symbols can be object keys according to JS spec, so ve lose nothing (except size) when converting it to
```javascript
  SomeFormat.SomeEnum = Object.freeze({
    OFF: -1,
    ...
    "-1": "OFF"
   ...
  });
```

The number must be in base 10 representation in inverted index part, since js casts a number to string first, [this cast produces base 10 representation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString).

One of possible solutions is to use [Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map), which allows the key to be any object (but it looks not very good since there is no literal map and access to its content through ```[]``` operator. The issue with ```[]``` can be solved using custom object with [Proxyies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)).

**Comment by GreyCat** [comment]
According to [CI](http://kaitai.io/ci/), it seems to work with quoting now. @KOLANICH, @Natronium — please take a look? I'll update https://ide.kaitai.io/devel/ with the new compiler shortly.

**Comment by GreyCat** [comment]
Nobody complained, so closing this one.
