### ISSUE TITLE
Invalid Java code generated: Incompatible types: possible lossy conversion from int to byte

### ISSUE THREAD

**Issue by Gamebuster19901** [kaitai-io/kaitai_struct#1097]
This is the compiler error:

```
2024-03-27T15:30:47.494-0400 [ERROR] [system.err] /home/gamebuster/Desktop/Modding/ExciteModder/build/generated/kaitai/src/com/gamebuster19901/excite/modding/kaitai/TocMonster.java:194: error: incompatible types: possible lossy conversion from int to byte
2024-03-27T15:30:47.494-0400 [ERROR] [system.err]             this.filename = new String(this._io.readBytesTerm(0, false, true, true), Charset.forName("utf-8"));
2024-03-27T15:30:47.494-0400 [ERROR] [system.err]                                                               ^
```

The generated .java file and the .ksy file are in TocMonster.zip

[TocMonster.zip](https://github.com/kaitai-io/kaitai_struct/files/14780457/TocMonster.zip)

**Comment by generalmimon** [comment]
I see that you're using `kaitai-struct-compiler 0.8`, i.e. a long outdated version [from 2018](https://kaitai.io/news/2018/02/05/kaitai-struct-v0.8-released.html) (check `kaitai-struct-compiler --version`). I strongly recommend using the latest KSC 0.10 (you can get it from https://github.com/kaitai-io/kaitai_struct_compiler/releases/tag/0.10, the download/installation instructions are here: https://kaitai.io/#download).

If (for some reason) you don't want to switch to KS 0.10, you can technically keep using the 0.8 compiler, but you also have to use the [`0.8` version](https://github.com/kaitai-io/kaitai_struct_java_runtime/tree/0.8) of the runtime library for Java (also published in the [Maven Central repository](https://central.sonatype.com/artifact/io.kaitai/kaitai-struct-runtime/0.8)). But keep in mind that this is not recommended and not supported, and at the very least you won't get any of the numerous bug fixes between 0.8 and 0.10.

**Comment by Gamebuster19901** [comment]
Thank you, I will try that soon and see if that resolves the issue.

**Comment by Gamebuster19901** [comment]
I had to do some modifications to my buildscript to ensure the generated directory was cleared of old data every run, and so that the compiler would run for all gradle tasks, but I was able to get it done and it appears to compile fine.

https://github.com/TheGameCommunity/ExciteModder/commit/298711daad4c8ad254388a7d4dd5552976997b3b
