### ISSUE TITLE
Basic C# support

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#11]
C# support is 78% done, according to the CI.

@LogicAndTrick, do you have plans to continue working on this support in a next week or two? I'd like to release v0.4 about that time, and it would be great to have working C# support in it. If you're busy right now, just tell me, I'll try to take on it myself - probably it shouldn't be that difficult given Java vs C# similarities.

**Comment by LogicAndTrick** [comment]
Sure, I can finish it off. If I updated the test cases that are currently causing naming conflicts in C#, could you fix the unit tests for the other languages?

**Comment by LogicAndTrick** [comment]
Ah, if I change the instance class names instead of the attribute names, than the unit tests might not need to change at all. I'll try that.

**Comment by LogicAndTrick** [comment]
C# is 100% passing now! http://kaitai.io/ci/

**Comment by GreyCat** [comment]
That's great! Thanks!
