### ISSUE TITLE
Error: Could not find or load main class io.kaitai.struct.JavaMain

### ISSUE THREAD

**Issue by Sylordis** [kaitai-io/kaitai_struct#1110]
Hi all,

I encountered the following error (had to obfuscate paths with `<workspace>`):

```
$ kaitai-struct-compiler -v --version
# Executing command line:
java
-cp
<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/io.kaitai.kaitai-struct-compiler-0.11-SNAPSHOT.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/org.scala-lang.scala-library-2.12.18.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/com.github.scopt.scopt_2.12-4.1.0.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/com.lihaoyi.fastparse_2.12-2.3.3.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/org.yaml.snakeyaml-2.0.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/com.lihaoyi.sourcecode_2.12-0.2.3.jar:<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/lib/com.lihaoyi.geny_2.12-0.6.10.jar
io.kaitai.struct.JavaMain
--version

Error: Could not find or load main class io.kaitai.struct.JavaMain
Caused by: java.lang.ClassNotFoundException: io.kaitai.struct.JavaMain
```

There seem to be a problem in the launcher files for the struct compiler once compiled on the machine. It was trying to get all the jars from `jvm/target/universal/scripts/lib/` though they were located in `jvm/target/universal/stage/lib/`.

After a few `find`, I realised the classpath was off. Creating a symlink works fine.

System: Debian 12 with WSL on Windows 11.
Java: build 21.0.3+7-LTS-152

**Comment by generalmimon** [comment]
@Sylordis:

> There seem to be a problem in the launcher files for the struct compiler once compiled on the machine.

1. Which commit of https://github.com/kaitai-io/kaitai_struct_compiler did you build?
2. What command did you use to build the compiler? Did you run it on the Windows host or in WSL?

**Comment by Sylordis** [comment]
1 & 2. I used these instructions: https://doc.kaitai.io/serialization.html
2. I first built it on Windows, after some time and frustration I removed the whole repo and started from scratch on the WSL. Same instructions though.
3.  `/usr/local/bin/kaitai-struct-compiler` which is a link to `<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/bin/kaitai-struct-compiler`

**Comment by generalmimon** [comment]
> 3. `/usr/local/bin/kaitai-struct-compiler` which is a link to `<workspace>/kaitai_struct_compiler/jvm/target/universal/scripts/bin/kaitai-struct-compiler`

This is a mistake - it should point to <code>&lt;workspace&gt;/kaitai_struct_compiler/jvm/target/universal/<del>scripts/</del><ins>**stage/**</ins>bin/kaitai-struct-compiler</code>.

I think the instructions at https://doc.kaitai.io/serialization.html#_building_the_compiler_from_source are clear enough - the full path `jvm/target/universal/stage/bin/kaitai-struct-compiler` is used everywhere. If you want to create a symlink, feel free to do so, but better point to the same path.

As an alternative to symlink, you might consider adding `<workspace>/jvm/target/universal/stage/bin` to `PATH`.

**Comment by Sylordis** [comment]
I see, for future reference, why is there the same content in `scripts/bin` directory?
