### ISSUE TITLE
KSC issue report

### ISSUE THREAD

**Issue by mstup** [kaitai-io/kaitai_struct#1119]
Is there ant way to report or discuss [kaitai_struct_compiler](https://github.com/kaitai-io/kaitai_struct_compiler/tree/master) related issues ?

**Comment by generalmimon** [comment]
Yes, here (https://github.com/kaitai-io/kaitai_struct/issues) is the right place.

https://github.com/kaitai-io/kaitai_struct_compiler used to have "Issues" enabled, but this led to people often incorrectly posting issues there that belong elsewhere, requiring frequent transfers to other repositories. Having just one issue tracker for "core KS issues" is easier for everyone.

**Comment by mstup** [comment]
Nice, thanks
