### ISSUE TITLE
How to read from a socket in Python?

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#1122]
> @GreyCat thank you for all the comments so far. I'm currently using the following (old style syntax) and it works fine:
> 
> ```python
> sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> server_address = (host, port)
> sock.connect(server_address)
> stream = KaitaiStream(BytesIO(sock.recv(4)))
> obj = GeneratedProtocol(stream)
> print(obj.attribute)
> ```
> 
> I was just wondering if there is a smarter way to specify how many bytes should be read from the socket (`sock.recv(max_bytes)`)? I was not able to figure out the size based on the kaitai_struct object. Especially reading arrays or other dynamically sized objects seem to be difficult to read (always reading the length first and then element by element?). Maybe there is a cleaner and less error prone way to do this?

_Originally posted by @fabolhak in https://github.com/kaitai-io/kaitai_struct/issues/162#issuecomment-2229131081_

**Comment by generalmimon** [comment]
@fabolhak You can let Kaitai Struct read from the socket directly. The [`KaitaiStream`](https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/9bdaeb32a844dd1ed44c83ef969e483e5d7b736e/kaitaistruct.py#L73) class in the KS Python runtime library will generally accept with any [file-like object](https://docs.python.org/3/glossary.html#term-file-object). And the docs of the `io` module happen to mention how to convert a `socket` to it, see [`io` > Binary I/O](https://docs.python.org/3/library/io.html#binary-i-o):

> Other library modules may provide additional ways to create text or binary streams. See [`socket.socket.makefile()`](https://docs.python.org/3/library/socket.html#socket.socket.makefile) for example.

So you should be able to do this (untested):

```python
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = (host, port)
sock.connect(server_address)

with sock.makefile('rb') as f:
    stream = KaitaiStream(f)
    obj = GeneratedProtocol(stream)
    print(obj.attribute)
```

(And BTW, you should probably also use the `with` statement to manage the `socket.socket` object so that the socket is properly closed.)

Note that the fact that the underlying stream is a socket means that .ksy features that rely on seeking (i.e. `instances` having `pos`, `_io.pos`, `_io.size`, `_io.eof` or anything related to `_io.eof`, i.e. `size-eos: true` and `repeat: eos`) won't work as long as you're in the root stream (once you enter a [substream](https://doc.kaitai.io/user_guide.html#_specifying_size_creates_a_substream), everything should work normally). But what you write that is in your format:

> Especially reading arrays or other dynamically sized objects seem to be difficult to read (always reading the length first and then element by element?).

... sounds to me like it should work fine.

**Comment by fabolhak** [comment]
@generalmimon thank you so much. I tried you proposed solution and it works fine for me. Thank you again for picking up the topic and answering it so detailed and lengthy :)

**Comment by generalmimon** [comment]
@fabolhak Thanks for your response! I'm glad it works for you.
