### ISSUE TITLE
Add title="$lang" for table cells in CI results

### ISSUE THREAD

**Issue by markbook2** [kaitai-io/kaitai_struct#113]
Could you please add the `title="$lang"` where `$lang` is for e.g. PHP or Ruby here http://kaitai.io/ci/index.html. E.g.:
```html
<td class="passed" title="PHP">passed</td>
```
It should cause of showing a tooltip in a browser when a mouse is over the cell and should help us identify the language for a broken or passed test. I think it is the https://github.com/kaitai-io/kaitai_struct_tests/blob/master/aggregate/report_table.html.erb file. Adding a name of the test would be useful too:
```
<td class="passed" title="PHP DebugEnumName">passed</td>
```

**Comment by GreyCat** [comment]
I thought of adding a fixed column headers, but this one would actually help too — and it's super easy to implement. Done, should be at CI soon, please take a look.

**Comment by markbook2** [comment]
@GreyCat, Great thanks! Could you do the same for the `didn't run` cells, now they don't have the titles:
```
<td class="no-run">didn't run</td>
```

**Comment by GreyCat** [comment]
Here you are :) Take a look?

**Comment by markbook2** [comment]
Great, thank you. I will close this issue as it was solved.
