### ISSUE TITLE
Extend terminator option to all types

### ISSUE THREAD

**Issue by neepolas** [kaitai-io/kaitai_struct#114]
Please implement `terminator` option for all types not only to `strz`. It will allow to use it like `split` function. Thanks.

**Comment by GreyCat** [comment]
Implemented in https://github.com/kaitai-io/kaitai_struct_compiler/commit/88469f722158287e520106df01e66c0ba78a9d2e — should work now at least for strings and byte arrays. New test [term_bytes](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/term_bytes.ksy) tests exactly that — byte arrays with `terminator`. Results should be at [our CI](http://kaitai.io/ci) in several minutes.

`terminator` + user type implementation is coming soon too.

**Comment by GreyCat** [comment]
User types support for `terminator` and other custom byte preprocessing is done too.

**Comment by GreyCat** [comment]
It seems to be working, so I'm closing this issue. @neepolas, feel free to reopen if something's wrong.
