### ISSUE TITLE
Migrate to PHPUnit 6.0 (related to PHP runtime)

### ISSUE THREAD

**Issue by markbook2** [kaitai-io/kaitai_struct#117]
Now [PHPUnit 6.x is stable](https://phpunit.de/) and previous versions (< 6.0) are outdated. The main change is changing the naming of classes and introducing namespaces: the old class names in format `PHPUnit_Framework_TestCase` (no namespaces) was replaced with `\PHPUnit\Framework\TestCase` (i.e. class TestCase under the PHPUnit\Framework namespace).

Here are steps to migrate to PHPUnit 6.0:
- [x] Fix [.travis.yml](https://github.com/kaitai-io/kaitai_struct/blob/61a4b676912fc3f8dc57e15cb10906c138fae554/.travis.yml) - it seems like it uses local outdated `phpunit` executable and not downloaded one, here is an excerpt from CI logs:
```sh
$ wget https://phar.phpunit.de/phpunit.phar
# ...
# PHPUnit 6.0.6 is downloaded
Location: https://phar.phpunit.de/phpunit-6.0.6.phar [following]
...
# but the next command displays 5.x.y version:
$ phpunit --version
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.
```
To fix it we could use absolute paths or remove the existing already installed phpunit, something like that:
```yaml
  # PHP: newer PHPUnit, as the one in the repos is very old
  - phpenv global 7.0.7
  - php --version
  - "sudo rm -f $(command -v phpunit) && sudo curl -oL /usr/local/bin/phpunit https://phar.phpunit.de/phpunit.phar && sudo chmod +x /usr/local/bin/phpunit"
  # Should show `PHPUnit 6.x.y by Sebastian Bergmann and contributors.`
  - phpunit --version
```
- [x] Change  [kaitai_struct_tests/spec/php/TestCase.php](https://github.com/kaitai-io/kaitai_struct_tests/blob/0eb8c274628c4745088dd4b08ea01b5231d4e001/spec/php/TestCase.php) to inherit from \PHPUnit\Framework\TestCase:
```php
<?php
namespace Kaitai\Struct\Tests;

abstract class TestCase extends \PHPUnit\Framework\TestCase {
    const SRC_DIR_PATH = __DIR__ . '/../../src';
}
```
- [x] Update [kaitai_struct_php_runtime](https://github.com/kaitai-io/kaitai_struct_php_runtime) to use the PHPUnit 6.x.

@GreyCat I will update the kaitai_struct_php_runtime to use PHPUnit 6.x.

**Comment by GreyCat** [comment]
Would having `language: php` (and thus using PHP-specific Travis VM) help in this case? If yes, then may be we can postpone it until #62?

**Comment by markbook2** [comment]
I don't have info about what version of PHPUnit they have installed for the `language: php`.

**Comment by markbook2** [comment]
Here is a list of changes: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0#backwards-compatibility-issues

**Comment by GreyCat** [comment]
I've updated `.travis.yml` and TestCase.php, now it seems that PHPUnit 6 is working: http://kaitai.io/ci/

However, a few tests seems to be broken with "Risky test" diagnosis. Can you take a look?

**Comment by markbook2** [comment]
OK

**Comment by markbook2** [comment]
Risky tests are tests without assertions, i.e. without any `$this->assert*() method`, they can be considered as notification for developers. If test should not do any assertions, the easiest way to fix such test is adding `$this->assertTrue(true);`, e.g.:
```php
class DocstringsTest extends TestCase {
    public function testDocstrings() {
        $r = Docstrings::fromFile(self::SRC_DIR_PATH . "/fixed_struct.bin");
        // This test should not do any assertions, so use $this->assertTrue(true) to mark it as not Risky (R).
        $this->assertTrue(true); 
    }
}
```

We could move the `$this->assertTrue(true)` into the Kaitai\Struct\Tests\TestCase to avoid adding comments as above:
```
    protected function markTestAsNotRisky() {
        // Another way to do this: $this->addToAssertionCount(1);
        $this->assertTrue(true) may work too.
    }
```

***

There are 2 useful methods also:
```
// Mark test incomplete, it is useful for not completed yet tests, which should be completed later.
$this->markTestIncomplete();

// Mark test as skipped, it is useful for tests, which should be ignored and marked as Skipped (S).
// E.g. tests which should work only under Linux and ignored under Windows.
$this->markTestSkipped();
```
E.g. of usage:
```php
class DebugEnumNameTest extends TestCase {
    public function testDebugEnumName() {
        $r = DebugEnumName::fromFile(self::SRC_DIR_PATH . "/fixed_struct.bin");

        # this test is meaningful only for languages that have --debug and do
        # not save enum type info
        $this->markTestSkipped();
    }
}
```

**Comment by GreyCat** [comment]
Thanks for the explanation! Could you add these fixes then? I'll analyze and add support for skipped tests as "green" ones.

**Comment by markbook2** [comment]
Ok, the [pull request](https://github.com/kaitai-io/kaitai_struct_tests/pull/32) has been created.

**Comment by markbook2** [comment]
Is that ok for you if we close this issue?

**Comment by GreyCat** [comment]
Just a little more, I'd like to ensure that "risky" and "skipped" are now rendered properly ;)

**Comment by GreyCat** [comment]
Ok, better late than never ;) Sorry for the delays. Got it working, result can be seen on CI. PHP should be back to 100% now.

**Comment by markbook2** [comment]
Great, thank you!
