### ISSUE TITLE
Type re-use

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#120]
I am defining a family of .ksy files representing binary messages. Each of these have a header with some magic numbers and 12 (integer) fields. It would be nice to define a header type in a single location, but if I understand well, this type now has to be specified/repeated in each of the .ksy files. 
Would it be possible to define types 'externally'? If not, could it be made possible, in a similar way that for example an XSD schema (and I think this works for JSON too) can import other schema where such a type could be defined?

**Comment by GreyCat** [comment]
Actually, it's already possible, see #71 ;)
Just started implementing it a few days ago, basic functionality works.

**Comment by JaapAap** [comment]
Sounds great! Thanks for that - I looked over the issues list before entering this but didn't spot this....
