### ISSUE TITLE
Problem reading large bit fields (C++)

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#122]
I had to change a line in the routine `read_bits_int(int n)`  to make it work correctly when n equals 32. 

The original line uses a 32-bit integer literal:
```
    // raw mask with required number of 1s, starting from lowest bit
    uint64_t mask = (1 << n) - 1;
```
which overflows for n==32 (or larger). I had to change it to:
```
    // raw mask with required number of 1s, starting from lowest bit
    uint64_t mask = (uint64_t(1) << n) - 1;
```
to work correctly. I am using Visual Studio 2015.

**Comment by GreyCat** [comment]
I believe it's been already fixed in latest c++ runtime - it should work with everything up to 64 bit inclusive. Could you take a look?

**Comment by JaapAap** [comment]
Yes - I can confirm that the latest runtime has fixed this issue. Thanks!
