### ISSUE TITLE
Support for Visual C++

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#124]
Would there be any interest in providing better support for Visual C++ out-of-the-box? I have done the exercise and while this was not at all hard, the process could have been simpler, e.g. by avoiding use of non-standard types (`ssize_t`), and by collecting configuration details (such as those governed by `KS_STR_ENCODING_ICONV` (which currently causes compilation errors when undefined) and `KS_ZLIB` in a separate header file) and allowing them to be undefined for certain platforms of compilers.

I also needed to whip up an alternative implementation for  `endian.h` and` byteswap.h` (which I have produced for my own purpose based on a public domain implementation, which should also work for other platforms by forwarding the MACROs to their intrinsic variants) - admittedly these are untested for other platforms but they do work for native windows. I'd be happy to provide these to you.

**Comment by GreyCat** [comment]
Of course :) Actually, C++ runtime is not tested right now on anything beyond basic Linux that Travis CI provides. There are at least [one known issue](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/issues/10) with it on OS X as well. Let's try to whip it up to shape, so it will run on most major platforms without issues ;)

Hopefully, I'll try to do something to arrange a OS testing matrix for it soon, but testing it manually is ok too ;)

**Comment by JaapAap** [comment]
Thanks - I will have a look. I will also try the unit tests just to make sure that I am not overlooking stuff.

**Comment by GreyCat** [comment]
Generally, there is [Appveyor CI](https://www.appveyor.com/) that offers Windows boxes for CI. If you'd figure out how to run C++ tests there, it would be just awesome :)

Technically, right now running tests boils down to [1 command](https://github.com/kaitai-io/kaitai_struct/blob/master/.travis.yml#L80) (given that .ksy → .cpp+.h step was done already) ­— but I guess it would require some effort to get it running on Windows.

**Comment by GreyCat** [comment]
Hey, @JaapAap, I've recently started some work on modular CI, and tried to build C++ tests on Windows box provided by Appveyor. If you're still up to this, please take a look: https://github.com/kaitai-io/kaitai_struct/issues/62#issuecomment-292644928

**Comment by JaapAap** [comment]
Hi there -  I am afraid that the whole CI workings are new to me – locally I have boost installed but have not succeeded (yet) to include zlib…

**Comment by JaapAap** [comment]
I am now doing some work on using VC++/Windows are used. Some findings so far: 
- imports don't work when forward slashes are used in the path. Not sure how/where to best solve this.
- zlib seems to work when including its source code (with some minor changes) - in the sense that the zlib_with_header_78 test runs fine
- I have solved endianess/byteswap issues (for which Linux-specific headers were used) using code from boost.endian (which I simplified and made standalone) - it has the added advantage of being valid and easily extendible to other OSs/architectures 
- I have not been able to find a replacement for the iconv library yet. There is some source code on the web but it is under GPL which would contaminate the codebase
- Some minor changes to the CPP library were necessary to solve both compilation  and runtime issues (the latter related to zero-sized read actions)

**Comment by GreyCat** [comment]
> imports don't work when forward slashes are used in the path. Not sure how/where to best solve this.

Can you describe this one in more detail? I.e. a ksc fails to generate any output at all, or it generates a particular .h / .cpp file which fails to get compiled by MSVC?

> zlib seems to work when including its source code

Are there any Windows-specific zlib implementations, i.e. may be in WinAPI, which we can reuse? Or, technically, we can ask to link against zlib (we just need to figure out how to install a library on a CI then, I guess)?

> I have solved endianess/byteswap issues (for which Linux-specific headers were used) using code from boost.endian (which I simplified and made standalone)

Sure, why not :) Feel free to send in a pull request.

> I have not been able to find a replacement for the iconv library yet. There is some source code on the web but it is under GPL which would contaminate the codebase

1. [libiconv](https://www.gnu.org/software/libiconv/), as far as I see, is LGPL, so it doesn't really contaminate anything anyway.
2. Technically, Windows has its own character conversion routines - i.e. [WideCharToMultiByte](https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130(v=vs.85).aspx) and [MultiByteToWideChar](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx). They are somewhat limited in terms of which character sets are supported (and there are some rumors that they're slightly buggy), but this is a solution as well.

> Some minor changes to the CPP library were necessary to solve both compilation and runtime issues (the latter related to zero-sized read actions)

Sure, these would be most welcome too ;)

**Comment by JaapAap** [comment]
Note sure about the slashes - just tried it and it now seems to work without problems (so I might have had another problem - I don't recall the error message, and the generated C++ code for both types is identical).

All I did for now is include zlib source files in my project and made some minor changes to it (the source showed its age at some points, but I now noticed that there is an updated version which I will test) - I am not aware of a windows-specific solution. Indeed, it could best be linked against using a compiler switch to allow/disallow this functionality.

I will surely share the endian stuff with you - together with the bit-field types. It will come with an updated C++ runtime. All works well now, but I would like to include some more tests and the test code I have now can't be shared.

I looked at libiconv and while it claims to be LGPL, at least some of the source files contain a GPL license statement, so this would need to be sorted out. Using native routines (or another library) would actually be a nicer solution (in my view), but is not something I would be able to look into anytime soon.

**Comment by GreyCat** [comment]
Hurray, MSVC support at CI is now a reality: http://kaitai.io/ci/ci.html => cpp_stl_98 msvc141_windows_x64

At least 1, or may be 3 more targets incoming next:

* cpp_stl_11 msvc141_windows_x64 (testing C++11 support, which is now half-broken)
* cpp_stl_98 msvc141_windows_x86 (testing the same in 32-bit builds)
* cpp_stl_11 msvc141_windows_x86

**Comment by KOLANICH** [comment]
>msvc141_windows_x64

How about `msvc141_clang_linux`?

**Comment by GreyCat** [comment]
Both cpp_stl_98 and cpp_stl_11 now build in CI as x64 projects, proving that, in general, we have some support for MSVC.

There are still some errors with x86 build, but that's probably has something to do with Appveyor CI configuration. That's not a high-priority and needs to be dealt with separately: https://github.com/kaitai-io/kaitai_struct/issues/543

Considering MSVC support done, closing the ticket.
