### ISSUE TITLE
Make KS extendable with plugins

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#126]
We need a way to extend KS functionality with plugins because we surely shouldn't embed everything in the world into KS ~com~transpiler and runtimes.
A plugin should be a combination of
* a runtime module for KS ~com~transpiler to add new syntax and semantics to ks language
* a module for a runtime library for any subset of supported languages to implement this functionality in the code.

The proposed design is hook-based.
0 Any entities in the ks* (ksy, ksj) are processed with objects having access to shared state. These objects are registered in a hash-map-based table dedicated for this. The keys are entity names, the values are objects used to process entities.
1 The compiler loads plugins and initializes them. The built-in features are also plugins, but they are more tightly coupled with the core. Plugins should also have table to allow hooking its internals.
2 Plugins hook the default implementations: replace them with own ones. Own implementations can use default ones internally. 
3 Plugins can add own entities to tables, but to be able use them they need to hook some default entity.
4 Each ksy must declare which plugins it uses.
5 core is a special kind of plugin: it is not, but fron user's perspective it also has the name and version
6 ks version is just a set of built-in plugins with their versions
7 ks core is core: it provides plugins with facilities to read and store data, interact with each other, and it calls them initially.

**Comment by GreyCat** [comment]
@KOLANICH Please don't take offense, but it looks like that your understanding of current reference compiler's architecture is somewhat vague. Most of the stuff you've suggested here is either way too generic, or I can't really understand what exactly you've meant. For example:

> Any entities in the ks* (ksy, ksj) are processed with objects having access to shared state. These objects are registered in a hash-map-based table dedicated for this. The keys are entity names, the values are objects used to process entities.

What is "entity", "object", "shared state"? Why do I need to "register" "objects"? What constitutes an entity's "name"?

> 1 The compiler loads plugins and initializes them.

Ok, that's how 100% of plugin systems work. Main application "loads and initializes" plugins.

> The built-in features are also plugins, but they are more tightly coupled with the core.

What's a "feature" exactly? How they interact with previously mentioned "entities", "objects", "shared state", "keys", "names" etc?

> Plugins should also have table to allow hooking its internals.

It's all just very generic talk, if we don't understand what a plugin is, what API it uses, etc, etc.

> ks core is core: it provides plugins with facilities to read and store data, interact with each other, and it calls them initially.

Any operating system does that. You imply that we need to develop an OS? etc, etc.

To start from the very beginning, I don't see any merits of spending lots of time rewriting compiler to use any other architecture just for the sake of rewriting. Actually, I'm kind of opposing the whole idea of fragmenting KS infrastructure into many deliberately incompatible implementations, when instead of "write once → run everywhere", one will struggle to endlessly search for "plugins" which will achieve the task for a given target platform(s). If someone wants to contribute a certain functionality into the compiler — why not add it directly into the compiler and language, so it will be available everywhere?

**Comment by KOLANICH** [comment]
>What is "entity"

a syntax feature

for example in js-json-oriented pseudo-bnf of KS grammar subset
```
document = {meta, ...type}
type = { seq, instances?, enums?}
seq = [val]
instances = {[instance]}
instance = {...val, pos?}
enums = {[enum]}
enum = {[ enum_value ]}
```
? means optionality,
{entity_name } means that there is a subblock
[entity_name] means array of entities
{[entity_name]} means object of entities as table
```...``` means [what it means in JS](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator) but extended with [python semantics](https://www.python.org/dev/peps/pep-0448/) allowing to do the same on dicts, which js usual counterpart is objects.

entity is a structure in the right side of the rule
entity name is in the left side

>What's a "feature" exactly

a group of entityes implementing some separate piece of functionality, s.a. repeat or enums or bit-precision types or switch.

>You imply that we need to develop an OS? 

any application allowing plugins is a very primitive and dumb kind of OS running on virtual hardware which is real os :).

>Actually, I'm kind of opposing the whole idea of fragmenting KS infrastructure into many deliberately incompatible implementations,

The original idea was to allow ks users to get a functionality which will never be in KS itself by using a plugin. Then I thought that it'd be nice to abstract more and split ks itself in plugins. This should allow versioning the features.

**Comment by GreyCat** [comment]
> entity is a structure in the right side of the rule
> entity name is in the left side
> is the object of programming language, in your case it is Scala

Ok, then how exactly it is different from what exists there already? These "objects" are ClassSpec, AttrSpec, InstanceSpec, MetaSpec, etc.

Going further, this makes even less sense now:

> These objects are registered in a hash-map-based table dedicated for this. The keys are entity names, the values are objects used to process entities.

"Objects are registered" in some table, "dedicated for this" — i.e. it's some sort of hash-map-based table that exists solely for the purpose of registering objects. I have no idea why it would be useful. And, if "entity name" is stuff like "document", "type", "seq", etc, as you've suggested, this "table" would quickly get duplicate keys, as soon as we'll get two types or two seq entries in a single .ksy.

Instead, now we have a hierarchy of model objects: ClassSpec has `meta`, which points to MetaSpec, `seq`, which is a sequence of AttrSpecs, `types`, which is map that maps identifiers into other ClassSpecs, etc. AttrSpec has `type`, which points to one of the dozens of supported DataType implementations.

>> What's a "feature" exactly

> a group of entities implementing some separate piece of functionality, s.a. repeat or enums or bit-precision types or switch.

That's all cool and stuff, but model objects are only the very beginning of the path. They need to be preprocessed before the compilation to do type inferring, preload imports, do various resolutions, etc. Then comes the actual compilation: again, it's complex enough to be done by the separate code, not by model object themselves. Besides, compilation is somewhat tightly coupled process: for example, you can't really compile variable assignments inside "repeat", as they heavily depend on that "repeat" type. Etc, etc.

I'm leaning towards closing this issue as non-constructive. If you want to discuss compiler architecture, I'd expect you to at least get acquainted with compiler sources and not invent tons of new terms and suggest to do what's already been done.
