### ISSUE TITLE
Enable issues in kaitai_struct_formats repo

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#129]
This is needed to prevent situations when the same format is implemented by multiple people independently.

**Comment by GreyCat** [comment]
Frankly, I don't think that it will prevent such situations. I wouldn't have figured it out to check it there, if I were a contributor, for example.

The whole point of disabling issues in individual repositories was to collect them all in a single place, and that's https://github.com/kaitai-io/kaitai_struct/issues. So, why not just create such issues here. We can assign a distinct label for them, like "formats", or "format-development" or something like that. Would it be ok?

**Comment by KOLANICH** [comment]
14 марта 2017 г. 19:21:58 GMT+03:00, Mikhail Yakshin <notifications@github.com> пишет:
>Frankly, I don't think that it will prevent such situations. I wouldn't
>have figured it out to check it there, if I were a contributor, for
>example.
>
>The whole point of disabling issues in individual repositories was to
>collect them all in a single place, and that's
>https://github.com/kaitai-io/kaitai_struct/issues. So, why not just
>create such issues here. We can assign a distinct label for them, like
>"formats", or "format-development" or something like that. Would it be
>ok?

Are you sure we should bloat this repo with large quantities of issues "i'm implementing format %formatname%"?

**Comment by GreyCat** [comment]
I haven't see *any* such issues in the whole last year, so I highly doubt that we'll suddeny get hit by large quantities of them. Having many distinct places to look for such issues is certainly worse than having a single place for them.
