### ISSUE TITLE
Better folder path for images, sounds, etc

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#138]
```image``` and ```media``` folders make a bit odd sense. There are lot of kind of data which are not images and sounds but which can be stored or showed as images and sounds: matrices, time series (e.g. oscillogram), spectra. So I propose to move images formats to the folder ```grid/2d``` and sounds to ```grid/1d```, also create folders ```grid/multi``` (formats which can pack multidimensional gridded data like tensors), ```grid/mixed``` (formats which can pack several formats of different dimension, like cern root) and ```grid/3d``` (voxel graphics, spatial 2d distributions of 1d data). Vector images and 3d models formats should be put into a separate folder using the same convention depending on the dimensions of the points.

**Comment by GreyCat** [comment]
The main purpose of any classification is to help people find whatever they're looking for faster. It took me more than several seconds to guess what `grid/2d`, `grid/1d`, `grid/3d`, `grid/mixed`, etc, is supposed to be → that's a fair indication of the fact that's it's a bad idea. I'm more than sure that nobody would ever search for something very common like a .png or .gif format in `grid/2d`.

Besides, all that "dimensions" stuff make little sense. Should regular 2D video be considered 3D (width * height * time)? Should a collection of mipmaps in a 2D texture be considered 3D (width * height * mipmap level)? How about DX10 DDS texture array — would it be 4D (width * height * mipmap level * texture frame)?
