### ISSUE TITLE
Max/min function

### ISSUE THREAD

**Issue by SuperDisk** [kaitai-io/kaitai_struct#139]
A max/min function (or property) for arrays such that you could do `array_type.max` or `array_type.min` and you could get the highest or lowest number value from the array.

**Comment by GreyCat** [comment]
I believe it would be undefined for arrays of user types, but should work for arrays of integers, floats and, maybe, strings?

**Comment by SuperDisk** [comment]
One possible solution would be the implementation of an `apply` function like found in Lisp, where you could do `apply(max, list)` or `apply(min, list)` and it would call the max/min functions with the contents of the list as arguments. Obviously they would have to be implemented to use varargs, but this approach could also be used with other existing functions for more extensibility.

**Comment by GreyCat** [comment]
Just committed the implementation for all languages. Results should be on our [CI](http://kaitai.io/ci) soon — check out [expr_array](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/expr_array.ksy) test.

Please check and see if it works for you.

**Comment by GreyCat** [comment]
A month passed, so I'm considering this done and closing this issue. Feel free to reopen, if something's not right.

**Comment by SuperDisk** [comment]
Hey, thanks for this! I didn't notice the initial reply saying it had been implemented.
