### ISSUE TITLE
identifiers

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#148]
Is there a reason why identifiers are limited to be all lower case ("^[a-z][a-z0-9_]*$".r)?

**Comment by GreyCat** [comment]
There is: they're meant to be converted automatically to whatever style is preferred to target language / chosen by the user. So, to get `foo_bar` in C++, Ruby and Python, `fooBar` in Java and `FooBar` in C#, we have to choose some baseline. And that "lower underscore case" is that baseline.

**Comment by GreyCat** [comment]
I guess that question is answered, no followups happened, so I'm closing it. Feel free to reopen if you want to discuss more :)

**Comment by vmartyanov** [comment]
I think it wasn't a good idea. For example, there is a structure with well-known name: IMAGE_NT_HEADERS (https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms680336(v=vs.85).aspx) and it has well-known. Suppose I made ksy-file for it and I can(!) import it by its real name, it's OK. I have to write meta: id: image_dos_header and it's not OK. Then I made two parsers: in C++ and in Python and I had ImageDosHeader in python and image_dos_header_t in CPP, so I have to dig into sources to know what's the class name. It's not OK at all.
My suggestion: add some option to prevent ANY(!) name transformation.

**Comment by GreyCat** [comment]
One can supply original IDs for purpose of documentation using `-orig-id` tags. For example, [this field](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/ico.ksy#L16-L19) in .ico file is called "num_images" in ksy, but it was originally called "idCount" in Microsoft's documentation.

I don't really understand these examples with "it's OK, it's not OK, it's not OK at all". You just can't have a class name "IMAGE_NT_HEADERS" or "imageNtHeaders" in some languages, so we have to do something about it — some kind of transformation is inevitable.

I agree that documentation is lacking. Probably names transformation should be available for every supported language in language-specific notes. [It is so](http://doc.kaitai.io/lang_java.html#_naming) for Java, for example.

There are plans to add options to adjust name transformation in command line, so it would be possible to adjust compiler output to get results more suited to your environment.

**Comment by vmartyanov** [comment]
If we can't have some name in some language - we could transform it. If we can have some name in some language - we should give an option to prevent any name transormation, I think.

**Comment by GreyCat** [comment]
> If we can't have some name in some language - we could transform it.

To do any kind of transformation, we must have some source form. It's impossible to apply transform if part of your identifiers are `like_this`, part are `LikeThis` and part are `LIKE_THISandSoMeThing_even_Weirder`. So that's why we've fixed a single source form - lower underscore case.

**Comment by vmartyanov** [comment]
Could you please add some option to not transform the names at all?

**Comment by GreyCat** [comment]
That won't really help: it is essentially the same as "keep everything in lower underscore case". And it will break many languages (for example, Ruby classes must start with upper case letter).
