### ISSUE TITLE
Missing round() or int() function in the parser language

### ISSUE THREAD

**Issue by FilipDominec** [kaitai-io/kaitai_struct#160]
I am trying to parse variable-length files (Avaspec *.ROH spectral data), whose length is stored as *float* in the header. It is a somewhat stupid approach, but I did not define this file format and can not do anything with that. 

No matter that this float number is obviously always a round one, say 2000.0, still I cannot convince Kaitai to treat it as an integer so that it reads a given number of datapoints:

    invalid type: expected integer, got FloatMultiType(Width4,le)

Is there any trick to convert float to integer within the *.KSY file? If not, I suggest to add the int() function.  If yes, then I could not find it in the documentation. If it is indeed somewhere in the documentation, I apologize for missing it.

**Comment by GreyCat** [comment]
Not yet. In spirit of all other conversion methods, it should be probably `.to_i` method. To be frank, we don't even have any global functions in KS expression language, at least yet.

Also, I remember that @KOLANICH was interested in spectral data formats as well and even [started ksys for several of them](https://github.com/KOLANICH/kaitai_struct_formats) - also as specified in https://github.com/kaitai-io/kaitai_struct/issues/134. May be you'd want to collaborate with him on Avaspec files as well.

**Comment by FilipDominec** [comment]
Thank you. Do you have any tip for a workaround? Else I will just set the dataset length fixed.

**Comment by GreyCat** [comment]
Probably it's easier to just wait a bit for implementation — I'll try to make haste ;)
In theory you can parse IEEE float manually (i.e. extract mantissa bits and do relevant calculations). Not really worth the hassle, though.

**Comment by GreyCat** [comment]
Gathering preliminary intelligence. Main "convert/cast to integer" operation in various languages behave like that:

| Lang  | Operation | -1.7 | -1.5 | -1.2 | 1.2 | 1.5 | 1.7 |
| - | - | - | - | - | - | - | - |
| C | `(int) x` | -1 | -1 | -1 | 1 | 1 | 1 |
| C# | `(int) x` | -1 | -1 | -1 | 1 | 1 | 1 |
| Java | `(int) x` | -1 | -1 | -1 | 1 | 1 | 1 |
| Perl | `int(x)` | -1 | -1 | -1 | 1 | 1 | 1 |
| PHP | `intval(x)` | -1 | -1 | -1 | 1 | 1 | 1 |
| Python | `int(x)` | -1 | -1 | -1 | 1 | 1 | 1 |
| Ruby | `x.to_i` | -1 | -1 | -1 | 1 | 1 | 1 |

JavaScript offers [tons of methods](http://stackoverflow.com/a/596503/487064), but, unfortunately, all have their cons:

* bitwise-like methods are pretty fast, but are limited to int32 range
* Math.floor / Math.ceil / Math.round are good, but behave differently from majority of languages shown above
* Math.trunc is good, but only available in ES6+
* parseInt() does the job, but it's 2x slower on modern Chrome, and *very* slow in FF/IE (probably due to real-to-string-to-int conversion)

Any ideas?

**Comment by FilipDominec** [comment]
```int(x)``` is the number-one choice for me.

**Comment by GreyCat** [comment]
Implemented type detector + base translator support as `.to_i` parameterless method.
Added implementations for Ruby, PHP, Perl and Python: see FloatToI test at http://kaitai.io/ci/

**Comment by GreyCat** [comment]
All languages are supported now, soon to be seen at [CI](http://kaitai.io/ci). Please check if new compiler works for you?

**Comment by FilipDominec** [comment]
I am sorry, but I am an employed man and the recursion in my head has gone too deep now. I will set the spectrum as fixed-length and wait for some official release of the compiler's deb package. 

Correct retrieval of spectral data from our lab -needs- flexible reading of avaspec file -whichneeds- re-compiling the KSY file with to_int support -whichneeds- re-compiling the compiler -whichneeds- fixing the following error:

    [error] (compilerJVM/debian:stage) java.lang.IllegalArgumentException: requirement failed: Source file '/home/dominecf/b/kaitai_struct/compiler/jvm/src/main/resources' does not exist.

What i run so far:

    wget http://dl.bintray.com/sbt/debian/sbt-0.13.5.deb
    sudo apt-get update
    sudo dpkg -i sbt-0.13.5.deb
    
    git clone --recursive https://github.com/kaitai-io/kaitai_struct.git
    cd kaitai_struct/compiler
    ##firefox http://doc.kaitai.io/developers.html
    sbt compilerJVM/debian:packageBin

**Comment by GreyCat** [comment]
Eh, sorry, you've stumbled into a build bug. The easy solution for now is just to create that empty directory:

    mkdir -p /home/dominecf/b/kaitai_struct/compiler/jvm/src/main/resources

I'll try to fix it ASAP and also update http://kaitai.io/repl/ for you to try, if everything else will fail.

**Comment by FilipDominec** [comment]
OK, thank you! Updating your recent changes...

    git pull origin master
    sbt compilerJVM/debian:packageBin

And finishing the installation with 

    sudo apt-get remove kaitai-struct-compiler -y
    sudo dpkg -i     jvm/target/kaitai-struct-compiler_*_all.deb
    kaitai-struct-compiler roh.ksy -t python

Now returning to compilation of the parser. I define two fields in my *.ROH format as such:

      - id: ipixfirst
        type: f4
      - id: ipixlast
        type: f4
      - id: spectrum
        type: f4
        repeat: expr
        repeat-expr: ipixlast.to_int ipixfirst.to_int

Yesterday ```kaitai-struct-compiler``` complained about 

    /types/header/seq/10/repeat-expr: don't know how to call anything on FloatMultiType(Width4,le)

Now it complains about 
    
    /types/header/seq/10/repeat-expr: called invalid attribute 'to_int' on expression of type FloatMultiType(Width4,le)

From this message, I have no clue what goes wrong. Thank you for any tip.

**Comment by GreyCat** [comment]
It's `to_i`, not `to_int`:

> Implemented type detector + base translator support as `.to_i` parameterless method.

**Comment by FilipDominec** [comment]
Yes, I have updated the comment. Perhaps it would be useful for somebody else.

**Comment by GreyCat** [comment]
Thanks for your patience :) Looking forward for Avaspec ROH format spec.

A quick reminder that might save some time: please include some `meta/license` header there with a valid open source license (as [SPDX license expression](https://spdx.org/licenses/)) — we can't accept licenseless files as contributions.
