### ISSUE TITLE
How to parse binary from memory in python?

### ISSUE THREAD

**Issue by sonusz** [kaitai-io/kaitai_struct#162]
Hi,

I was hoping to use this parser to parse some network protocol. But I just reallized that there is no method to read received bytes from a socket. Save the receieved byte to file then use KaitaiStruct.from_file() is too slow for my application. 

Is there any way to read binary then parse it without using from_file()?

Thank you,

**Comment by GreyCat** [comment]
Sure, just use KaitaiStream directly. It allows to use arbitrary IO-compatible object to read from, and you can use BytesIO to read from memory:

```python
from kaitaistruct import KaitaiStream, BytesIO
# or use native Python import:
# from io import BytesIO (for Python 3+)
# import cStringIO (for Python 2.7)

s = b"acb123"
stream = KaitaiStream(BytesIO(s))
obj = GeneratedProtocol(stream)
# access obj.whatever_attribute_you_would_want_here
```

**Comment by sonusz** [comment]
That's very helpful!

Thank you,

**Comment by GreyCat** [comment]
Closing this question then. Feel free to reopen if you have anything more on this issue.

**Comment by GreyCat** [comment]
For those who find this question in search engine in 2024 — the modern way of doing it looks like this:

```python
s = b"acb123"
obj = GeneratedProtocol.from_bytes(s)
```

**Comment by fabolhak** [comment]
@GreyCat thank you for all the comments so far. I'm currently using the following (old style syntax) and it works fine: 

```python
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = (host, port)
sock.connect(server_address)
stream = KaitaiStream(BytesIO(sock.recv(4)))
obj = GeneratedProtocol(stream)
print(obj.attribute)
```

I was just wondering if there is a smarter way to specify how many bytes should be read from the socket (`sock.recv(max_bytes)`)? I was not able to figure out the size based on the kaitai_struct object. Especially reading arrays or other dynamically sized objects seem to be difficult to read (always reading the length first and then element by element?). Maybe there is a cleaner and less error prone way to do this?
