### ISSUE TITLE
Compiler option to specify Python package prefix

### ISSUE THREAD

**Issue by martinpelikan** [kaitai-io/kaitai_struct#169]
I'm packaging an application that will include some protocol parsing logic using KS. I made fairly extensive use of `meta/imports` to minimize spec duplication. When compiling to Python however, the resulting imports end up not being scoped to any package, as in the example below for `MyImportedType`:

```Python
...
from my_imported_type import MyImportedType
class MyBaseType(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
...
```

The becomes an issue when running this application, as that module does not exist anywhere in `$PYTHONPATH` but instead gets installed as part of my application's Python package. It should be something more like `from application.protocol.my_imported_type import MyImportedType`, or perhaps a relative import.

I'm not sure if this is as simple as providing a flag to the compiler that will prepend the imports with the given string:
`kaitai-struct-compiler --target python --python-package "application.protocol" --import-path ksy/ ksy/*`

**Comment by GreyCat** [comment]
I've implemented `--python-package`, probably it should work as you specified: https://github.com/kaitai-io/kaitai_struct_compiler/commit/08593c3d24f25beb8fcae82ce8ad9eac58899345. Could you check if it works for you?

**Comment by martinpelikan** [comment]
Hey @GreyCat, many thanks for fixing this so quickly!

I've verified that `--help` shows the documentation for this option, and that `--python-package test.foo.bar` will correctly prepend the import path as expected.

There is an edge case which I think could be worth considering, possibly as a potential future improvement. Someone may want to use relative imports, via something like `--python-package .`, but this will result in: `from ..my_type import MyType`. This path is valid, but there is a superfluous dot that will result in imports looking in the parent directory, making it impossible for someone to use this feature for relative imports. Arguably, the relative import case might be more practical than the absolute imports from the root directory as is the default now (since this likely means mangling `$PYTHONPATH`.

However, your fix addresses my original feature request and I'm happy with it as it is!

I also see that unused imports of `array`, `struct`, `zlib` and `enum` are no longer in the compiled code, so :+1: for that too!

**Comment by GreyCat** [comment]
@martinpelikan Sorry for late reply.

Could you please specify how do you want `--python-package .` to behave exactly, i.e. what it should generate?

**Comment by GreyCat** [comment]
Suggested by @ujjwal96 in Gitter chat, writing it down here for the history purposes:

> --python-package flag should work (y) As for the relative imports, you can have a look at this https://stackoverflow.com/a/12173406
> So, if the import originally was `from my_type import MyType` with `--python-package .` it should look like `from .my_type import MyType` which tells python to import the module from the same directory.
> Relative imports may be useful because it won't require the main package to be in sys.path (the list of paths where python looks for files to be imported)

**Comment by martinpelikan** [comment]
@GreyCat Entering `--python-package .` would generate `from .my_imported_type import MyImportedType`. Since all the modules end up being generated in the same package level, supporting any other relative import path like `..` wouldn't make sense, IMO.

**Comment by GreyCat** [comment]
Ok, guys, would it make sense, for example, to use the following rule?

* If `--python-package` ends with `.`, we generate `from ${python_package}${type} import ${Type}`
* Otherwise, we generate `from ${python_package}.${type} import ${Type}`

Alternatively, if it's not, shall we just make exception for `.` argument only, and consider stuff like `..` or `a.b.c.` to be an error?

**Comment by martinpelikan** [comment]
As I see it, these are the possible types of input and what their corresponding outputs should be. I don't often use relative imports so perhaps I'm missing some variations?

| Input      | Error                            |
| ---------- | -------------------------------- |
| .          | from .type import Type           |
| root       | from root.type import Type       |
| root.child | from root.child.type import Type |
| ..         | error                            |
| parent.    | error                            |

**Comment by GreyCat** [comment]
@martinpelikan @ujjwal96 I've [implemented this](https://github.com/kaitai-io/kaitai_struct_compiler/commit/4c6d54a9a303728418e87aae1f50190a709fe719) as requested, please take a look. After some thought, I've opted to not implement specific error checks here, as, technically, there are many more things that need checking, so it's better to either check all of them or check none.

**Comment by martinpelikan** [comment]
@GreyCat LGTM
