### ISSUE TITLE
Failures compiling test formats

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#173]
I obtain the  following failures when compiling test formats (using v0.7 of the compiler, or the online version):

I:\Kaitai\test\formats>kaitai-struct-compiler -t cpp_stl switch_integers2.ksy
(main): /instances/len_mod_str/value: can't apply operator Mult to SwitchType(Name(identifier(code)),Map(IntNum(1) -> Int1Type(false), IntNum(2) -> IntMultiType(false,Width2,le), IntNum(4) -> IntMultiType(false,Width4,le), IntNum(8) -> IntMultiType(false,Width8,le))) and Int1Type(true)

I:\Kaitai\test\formats>kaitai-struct-compiler -t cpp_stl float_to_i.ksy
(main): /instances/float1_i/value: don't know how to call anything on CalcFloatType

**Comment by GreyCat** [comment]
Current git version of compiler passes both SwitchIntegers2 and FloatToI, see [our CI](http://kaitai.io/ci/). These tests were added after v0.7 release and are supposed to test new features / bugfixes.

**Comment by JaapAap** [comment]
Thanks - seems I got slightly out of sync here...

**Comment by GreyCat** [comment]
I believe this is solved, so I'm closing this one.
