### ISSUE TITLE
Add logo / icon

### ISSUE THREAD

**Issue by cugu** [kaitai-io/kaitai_struct#186]
Kaitai Struct needs a logo!  

This could increase the recognition of the project on github, twitter any all the other places. 

There has been discussion about that on twitter ([1](https://twitter.com/thegrugq/status/856473921318604800)) and gitter ([1](https://gitter.im/kaitai_struct/Lobby?at=5837fb998d65e3830e9a3c85), [2](https://gitter.im/kaitai_struct/Lobby?at=583310775eb8ea792a4a2911)) without any (final) result. Getting a designer on board seems to be difficult. Maybe a post to http://opensourcedesign.net/ would help?

Requirements for the logo:
 - Clean and simple
 - Square (if possible)
 - Free

Proposals for a logo: 
 - https://twitter.com/vervalkon/status/859795787097755648
 - https://twitter.com/kaitai_io/status/753930879370756096 (old version?)

**Comment by GreyCat** [comment]
Actually, we're in the middle of putting final touches on a logo project with [Verneri Kontto](https://twitter.com/vervalkon), who has been super helpful and provided many ideas :) I hope we'll publish it soon.

**Comment by cugu** [comment]
That's great news! I'm looking forward to it :)

**Comment by arekbulski** [comment]
So what is the status of that logo?

**Comment by GreyCat** [comment]
It's ready to be published.

**Comment by arekbulski** [comment]
I'd say add those files to some repo and close this issue? If docs need to be updated to show that logo, that can be done with separate issues, as needed.

**Comment by GreyCat** [comment]
Um, that was supposed to be a suprise reveal on v0.8 release... I'll try to add them all to websites, docs, etc, at once during the release.
