### ISSUE TITLE
Fix mobile view of doc.kaitai.io

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#191]
Currently the menu is opened by default and takes half of the screen on my Android+Chrome device.

**Comment by GreyCat** [comment]
Um, ok ;) Patches are welcome, if anyone knows how to fix that.

**Comment by koczkatamas** [comment]
I'll solve it (hopefully in the next days).

**Comment by koczkatamas** [comment]
Fixed in https://github.com/kaitai-io/kaitai_struct_doc/commit/44e0cfcbe31022131ed09e6e432eff5287d5ec12 and https://github.com/kaitai-io/kaitai_struct_doc/commit/f2c8763e2c3fd917b47e24c43def9aae802e1781

**Comment by GreyCat** [comment]
Really cool! Thanks!
