### ISSUE TITLE
JavaScript CI is broken

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#197]
After latest commits, JavaScript runtime is broken, at least for CI purposes:

```
$ ./run-javascript 
kaitai_struct/tests/spec/javascript/test_default_endian_expr_exception.js:3
testHelperThrows('DefaultEndianExprException', 'src/endian_expr.bin', KaitaiUndecidedEndiannessError);
                                                                      ^

ReferenceError: KaitaiUndecidedEndiannessError is not defined
    at Object.<anonymous> (kaitai_struct/tests/spec/javascript/test_default_endian_expr_exception.js:3:71)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at kaitai_struct/tests/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (kaitai_struct/tests/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (kaitai_struct/tests/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (kaitai_struct/tests/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by koczkatamas** [comment]
Uh yeah sorry, I had to put those errors into `KaitaiStream`. So we should replace the `Kaitai*Error`s to `KaitaiStream.Kaitai*Error`.

The reason we I did this is that the exports (like KaitaiUndecidedEndiannessError) were inconsistent depending how you included the runtime (Node.js import / AMD or just globally include).

Actually I think previously we mistakenly polluted the global namespace even for Node.js imports.

**Comment by GreyCat** [comment]
So, I believe we have to:

- [ ] Fix test specs
- [ ] Fix compiler (replaced `Kaitai*Error` => `KaitaiStream.Kaitai*Error` in generated code)
- [ ] Write a note for release notes about this incompatibility

Could you take (1) and (3)? I'll fix the compiler.

**Comment by koczkatamas** [comment]
Yes, I'll fix the test specs, and I'll write the release not, but I don't know where should I put the release notes.

Also it may worth to solve this issue too https://github.com/kaitai-io/kaitai_struct/issues/180 if we modify the compiler. I'll find out how to generate UMD compatible classes.

Btw sorry, I didn't know the compiler also uses these classes. I thought only the KaitaiStream throws these typed exceptions.

**Comment by GreyCat** [comment]
> but I don't know where should I put the release notes.

Well, we don't have anything preliminary, so I usually start to write them directly into [compiler/RELEASE_NOTES.md](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/RELEASE_NOTES.md). Probably we should add 0.8 section there, but not set the exact release date yet.

Alternatively, we might use [0.8 milestone description on GH](https://github.com/kaitai-io/kaitai_struct/milestone/5), but this is kinda awkward and probably not very collaborative.

> Btw sorry, I didn't know the compiler also uses these classes. I thought only the KaitaiStream throws these typed exceptions.

Compiler sometimes needs to generate calls to throw these exceptions directly. Namely, for JavaScript, it's [used for KaitaiUndecidedEndiannessError](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/languages/JavaScriptCompiler.scala#L128).

By the way, given that we're effectively moving these errors into the namespace, may be we should drop the `Kaitai` prefix? i.e. just `KaitaiStream.UndecidedEndiannessError`, instead of `KaitaiUndecidedEndiannessError`?

**Comment by koczkatamas** [comment]
Probably it's a good idea to drop that prefix now.

**Comment by GreyCat** [comment]
Looks like it's fixed now.
