### ISSUE TITLE
Maven coordinates

### ISSUE THREAD

**Issue by jvmlet** [kaitai-io/kaitai_struct#2]
Hello
Would you please provide maven coordinates of java artifacts in the documentation/dev guide?
Thanks

**Comment by GreyCat** [comment]
Neither the compiler, nor the runtime library is published yet in maven repositories, but note taken.

Integrating usage of the compiler in regular maven build flow is one of the not-so-distant goals.

**Comment by GreyCat** [comment]
I've just finished setting up maven deployment and published Kaitai Struct Java runtime into central repo. The coordinates are:

```
io.kaitai:kaitai-struct-runtime:0.4-SNAPSHOT
```

`0.4-SNAPSHOT` will be likely switched to `0.4`, as 0.4 release will come and features will be frozen for 0.4.

**Comment by GreyCat** [comment]
Finally, `0.4` version was published as a "release":

https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.kaitai%22

`0.5-SNAPSHOT` is available in [snapshots repository](https://oss.sonatype.org/content/repositories/snapshots/io/kaitai/kaitai-struct-runtime/0.5-SNAPSHOT/) and `0.5` will be published to main releases repository when it will be released (simultaneously with the compiler).
