### ISSUE TITLE
Range Validation

### ISSUE THREAD

**Issue by rkukuchka** [kaitai-io/kaitai_struct#201]
Hello, 
     New to the project, looking at it for some personal coding. Is there any plan to add some sort of range validation to values? I'm doing some work where I know the expected values of a particular field will be between say 0-100, and I'd like some means to specify it in the ksy file. I was thinking something similar to JSON schema's minimum / maximum fields. 

Thoughts?

**Comment by koczkatamas** [comment]
Currently there is no such feature, but we are planning one. This is the related issue: https://github.com/kaitai-io/kaitai_struct/issues/81

It maybe a good idea to describe some constraints (eg. range or regex, etc) declaratively instead of using a more generic `guard` field.

**Comment by arekbulski** [comment]
Construct has a Check class that does that.
https://construct.readthedocs.io/en/latest/misc.html#check

**Comment by generalmimon** [comment]
This is resolved by https://github.com/kaitai-io/kaitai_struct/issues/435.

Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/435
