### ISSUE TITLE
128-bit integers do not serialize accurately in javascript

### ISSUE THREAD

**Issue by johnwbyrd** [kaitai-io/kaitai_struct#206]
While developing my wave file ksy, I found that generated JavaScript code does not accurately serialize 8-byte integers, i.e. u8's.  Precision is lost in the low bits of the u8 when a WAV file is parsed. 

I noticed this specifically when parsing a GuidType in my wav.ksy, which under normal circumstances would contain a u8.

I am supposing that JavaScript stores these values as floats or some other reduced precision format and then moves them back to integer format, thus losing low bits of precision.

All formats should be sanity checked to make sure they handle u8's with sufficient bits of precision.  If a format contains a u8, it really ought to have test data proving that u8's can be serialized correctly on all platforms.

A sort-of-workaround for ksy authors is to use a pair of u4's to insure that all bits are serialized.

**Comment by johnwbyrd** [comment]
On javascript specifically, a possible workaround involves the use of big.js or some other bignum library.

**Comment by GreyCat** [comment]
That's actually 64-bit integers, and, yeah, it's a known problem. Let's go to #183 to discuss that.

As for GUID matching, I would actually advise to just make them raw byte arrays of 16 bytes, and compare them, if needed. Actual internal UUID/GUID structure is pretty complicated, and for 99.9% of purposes it's not worth digging into.

**Comment by GreyCat** [comment]
There was a [PR that tried to add UUID as common/ type](https://github.com/kaitai-io/kaitai_struct_formats/pull/26/files/7ccec35afe1db702d4acb83a14344f739630e925#diff-41ae24d8c274ff4c5736769fc5bdff01), yet it was unfinished and, as I said there in my comments, it's main purpose would be to debug UUID-generating applications & libraries, rather than use directly in normal apps.
