### ISSUE TITLE
Question: conditionally parse fields

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#210]
I am parsing a format that has optional fields at the very end of the message. Unfortunately, this part of the message is parsed as part of a subtype that has no awareness of its length (the message length is stored in a field on message level, but not in the subtype's part). Is there a way to conditionally parse the optional fields?

**Comment by koczkatamas** [comment]
Kaitai support `if` statement and `io.eof` property. Also the current `io` substream has length internally, so you can use `size: eos` if needed.

**Comment by JaapAap** [comment]
Thanks Tamas - works like a charm!

**Comment by koczkatamas** [comment]
Nice to hear that!

(Please reopen if you have further question regarding the topic.)
