### ISSUE TITLE
Question: importing files

### ISSUE THREAD

**Issue by JaapAap** [kaitai-io/kaitai_struct#212]
I am using the imports construct to import some files. I am calling the compiler from a number of different working directories, and noticed that the path is considered to be relative to this working directory. Is it possible to add the directory of the .ksy script that loads the import as a directory to search as well, to allow calling this script from different working directories? Or maybe I misperceive things here?

**Comment by GreyCat** [comment]
Relative imports are somewhat broken now in that respect. I expect to fix them to be work strictly relatively to the file that they are located in.

**Comment by JaapAap** [comment]
Thanks - yes, that would help!

**Comment by GreyCat** [comment]
KSPATH only works for absolute paths (i.e. if you import stuff like `/foo` or `/network/ipv4_packet`, for example). If you're ok with using these — sure, go ahead.

**Comment by fallenoak** [comment]
Just wanted to chime in and mention that it'd be fantastic if the JS compiler can support `.ksy` file-relative paths, too. I'm trying to figure out how to get imports working in `kaitai-struct-loader`, and this is one of the issues impacting that, too.

Since the JS compiler doesn't see the filesystem (as I understand it), this might require some adjustments to `compile()` and `importYaml()`.

**Comment by GreyCat** [comment]
I've committed basic fixes, all paths:

* anything into absolute
* relative into relative
* absolute into relative

should work properly now, compiler would handle resolving proper full paths relative to original working dir. Results should be available at [the CI](http://kaitai.io/ci/) shortly — see new tests "imports_rel_1", "imports_abs_abs", "imports_abs_rel". Only Ruby specs for now, but compiler should work for all the languages. I'll finish porting the specs later.

**Comment by fallenoak** [comment]
Thumbs up! I'm now able to trivially resolve paths to imports in `kaitai-struct-loader`. Have tried with only relative paths so far: both `some/subdir/here` and `../up/a/level` work great!

**Comment by GreyCat** [comment]
Looks like the main problem is fixed, so closing this one. Feel free to reopen if anything arises.
