### ISSUE TITLE
Opaque parametric types

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#220]
Original issue in https://github.com/kaitai-io/kaitai_struct_compiler/issues/101 by @SpenserStyles:

> Is there a way to do opaque parametric types without Kaitai references in the constructor?  I have a large code base and would like to start integrating the use of Kaitai but currently it would require some additional code to connect to the two.
> 
> Example:
>
> ```
> meta:
>   id: main
>   file-extension: main
>   endian: be
>   ks-opaque-types: true
> 
> seq:
>   - id: buff
>     size: 31
>   - id: result
>     type: custom(buff)
> ```
>
> This would generate:
> Custom result = new Custom(buff);
>
> This seems to be similar to custom processes minus the decode step.

**Comment by GreyCat** [comment]
Hmm, that might be a good idea. A few notes:

* These objects are expected to be KaitaiStruct-compatible, thus, at the very least, they should have `_io`, and they would be provided `_io` in invocation, i.e. probably something closer to `new Custom(_io, buff)`.
* We thought of doing that in more "legitimate" way, i.e. by importing/declaring some sort of interface for such external classes, as in #188, but "opaque" way seems to be ok too.

**Comment by SpenserStyles** [comment]
I just started looking at this project last week and coming at it from a beginner's perspective the opaque way seemed the most intuitive.  It seemed more of a natural extension to parametric types discussed in #192.   Looking at #188 it seems more convoluted.  

Being able to exclude the Kaitai references would allow re-use of existing classes within the target code platform.  For example:

```
meta:
  id: main
  file-extension: main
  endian: be
  ks-opaque-types: true

seq:
  - id: year
    type: u1
  - id: month
    type: u1
  - id: day
    type: u1
  - id: date_time
    type: System.DateTime(year, month, day)

```
This would allow me to re-use System.DateTime from .NET framework.  Granted, if this code was compiled for another language then System.DateTime would have to be implemented in that language but it would still be on the user to do so and could still be made to work.  

As far as my use case goes I have a lot of classes and static functions based on binary blobs that have no idea about Kaitai.  It would be nice to be able to avoid writing that glue code.  So maybe it could be possible to put an additional field tied to opaque parametric types that disables Kaitai compatibility (Kaitai compatibility would be enabled by default).

**Comment by GreyCat** [comment]
Hmm, this is tempting, yet pretty controversal propsal. It breaks several important design points/goals for KS that I'm not sure we should break:

* KS is supposed to be target-language neutral; obviously, referencing individual target language constructs is a bad idea, as this makes whole KSY valid only for one certain language
* KS is supposed to be neutral to libraries used, i.e. we're not supposed to be tying oneself to one particular crypto library, compression library, etc, even in context of a single language
* `seq` is supposed to be attribute sequence, which literally shows what kind of data follows what in the stream; adding such "invocations", which are not connected to the stream in any way breaks that contract.
* `type: XXX` notation does not support anything beyond KS-valid identifiers (which do not allow uppercase letters, dots to specify namespacing, etc)

But you're totally correct about potential benefits of easy integration into existing infrastructures.

I might suggest alternative way to implement this. Right now we have `instances` for such out-of-band data, as instances can be:

* "Parse instances", which parse something from a stream on a certain point (specified by additional `pos: XXX` clause)
* "Value instances", which are basically calculated expressions that don't touch the stream directly in any way, but rather derive its value from other existing attributes in current and/or other classes

May be we could add third "instance" type, something like "external instance"? There are two major implementation problems here:

1. We need to derive resulting type to be used in class declarations
2. Many languages use very non-trivial invocations to instantiate the desired type (i.e. factory classes/methods, etc)

For example, in C# you might use `new System.DateTime(Year, Month, Day)`, and that yields `System.DateTime`. But in Java, you'd use `java.time.LocalDate.of(year(), month(), day())` and that yields `java.time.LocalDate`.

**Comment by koczkatamas** [comment]
@SpenserStyles we are generating partial classes for C#, maybe it's easier just to create an other part of the partial class put a DateTime property there?

```csharp
partial class Main {
  public DateTime Date { get { return new DateTime(Year, Month, Day); } }
}
```

I think everything which is language-specific should go elsewhere than the ksy file or at least a separate "language-specific" part(s) of the ksy file.

**Comment by SpenserStyles** [comment]
After reading your responses I agree that the System.DateTime example would break many of the goals of KS and is not worth it.  I also agree that adding language specific fields via an extra part of the partial class is the way to go - I'm already doing that for serialization/packing methods.    

I still see a usefulness for opaque parametric types (`new Custom(_io, buff)` concept from GreyCat's original response).  This would give an easier path to integration with existing code bases - I could add constructors to handle KaitaiStream as needed.  I think this feature (and a serialization feature :)) would go long way in helping fit Kaitai into my current work flow.  Either way I've been extremely impressed by KS and how easy it has been to learn.

**Comment by KOLANICH** [comment]
>May be we could add third "instance" type, something like "external instance"?

Parametric types syntax?

>Many languages use very non-trivial invocations to instantiate the desired type (i.e. factory classes/methods, etc)

Factory method?

Also I have a kne more idea. We need packages. I mean a user implements custom factory functions for every KS language, creates packages where the language has default package manager like pip, otherwise puts the code into a publicly available git repo or zip archive, creates manifest file where references the public locations. A user then refernces the feature in ksy. Then the tools automatically check the dependences. For example for python they may add a dependency into setup.cfg, for rust into Cargo.toml, for c++ do according to OS, for example in linux distros it can advise to install a package.

**Comment by GreyCat** [comment]
@SpenserStyles I've implemented opaque types with parameters, it should work with all supported languages expect for Perl (see test OpaqueWithParam at the [CI](http://kaitai.io/ci)). Could you please take a look if that would be of any help for you?

**Comment by SpenserStyles** [comment]
I'm trying to check it out but I'm running into some problems.  First I got the latest from git and built from src using: `sbt compilerJVM/universal:packageBin`.  It successfully built to: kaitai-struct-compiler-0.8-SNAPSHOT.  Using this compiled version I try: `kaitai-struct-compiler -t csharp opaque_with_param.ksy` and it gives me and error: "/seq/0/type: parameter count mismatch: 0 declared, but 2 used".  I then went to http://kaitai.io/repl/ to see what it would do.  It compiles the opaque_with_param.ksy but the result is incorrect.  I produces:

```
private void _parse()
{
    _one = new ParamsDef(5, true)(m_io);
}
private ParamsDef(5, true) _one;
```
I'm not sure what version the repl is running.
Any thoughts on what I'm screwing up?

**Comment by GreyCat** [comment]
Hmm, that's strange. Current compiler generates OpaqueWithParam like this: https://github.com/kaitai-io/ci_targets/blob/master/compiled/csharp/OpaqueWithParam.cs

Can you check if that's really the latest version?

REPL compiler runs latest stable, i.e. 0.7.
Note that `_parse` is nowadays generated as `_read`.

**Comment by SpenserStyles** [comment]
I checked out your OpaqueWithParam.cs and that works perfect for me.  Thanks for implementing it so quickly!

**Comment by GreyCat** [comment]
Cool, thanks!
