### ISSUE TITLE
mach_o.ksy: vm_prot should behave like a bit mask

### ISSUE THREAD

**Issue by FilippoBiga** [kaitai-io/kaitai_struct#222]
Hi,

I'm new to the project and I'm looking at it for some personal projects.

In the specification of the Mach-O file format, the `vm_prot_t` type is represented by `vm_prot`, which is defined as an enum which can have the following values:

```
vm_prot:
  0x00: none
  0x01: read
  0x02: write
  0x04: execute
  0x08: no_change
  0x10: copy
```

However, `vm_prot_t` values are used as bit masks by all the tools producing, analyzing and using Mach-O files in Apple's operating systems. 

For example, by examining `/bin/cat` with `otool`, we can see that the __TEXT segment has an initprot of 0x5 (`VM_PROT_READ|VM_PROT_EXECUTE`) and maxprot of 0x7 (`VM_PROT_READ|VM_PROT_WRITE|VM_PROT_EXECUTE`)
```
sh-3.2$ otool -l /bin/cat
...
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 552
  segname __TEXT
   vmaddr 0x0000000100000000
   vmsize 0x0000000000002000
  fileoff 0
 filesize 8192
  maxprot 0x00000007
 initprot 0x00000005
...
```

Therefore, it should be possible to combine different values of the `vm_prot` enum. 

I can think of two ways this could be implemented in the format specification:

1. Add all the valid combinations to the vm_prot enum, keeping it as it is. This approach would be extremely simple to implement but would not capture the semantics of the field very well. 
2. Parse the field using value instances:
	```
	vm_prot:
	  seq:
	    - id: val
	      type: u4
	  instances:
	    read:
	      value: ...
	    write:
	      value: ...
	...      
	```
	
	In this case, I think there could be two approaches to dealing with the values. 
	1. Capture the value: `(val & 0x01)` (for `VM_READ`)
	2. Capture whether or not the bit was set, treating it as a boolean: `(val & 0x01) == 0x01`
	
	What would be the best alternative? I've quickly tested all the aforementioned approaches by generating a MachO parser in Python. I've attached a (trivial) patch (mach_o.ksy.patch) which implements 2.2.
	
As I mentioned, I'm new to the project so I might have missed some features that could allow different implementations. Thank you for your work!

```
141,147d140
<   vm_prot:
<     0x00: none
<     0x01: read
<     0x02: write
<     0x04: execute
<     0x08: no_change
<     0x10: copy
194a188,202
>   vm_prot:
>     seq:
>       - id: val
>         type: u4
>     instances:
>       read:
>         value: (val & 0x01) == 0x01
>       write:
>         value: (val & 0x02) == 0x02
>       execute:
>         value: (val & 0x04) == 0x04
>       no_change:
>         value: (val & 0x08) == 0x08
>       copy:
>         value: (val & 0x10) == 0x10
257,258c265
<         type: u4
<         enum: vm_prot
---
>         type: vm_prot
260,261c267
<         type: u4
<         enum: vm_prot
---
>         type: vm_prot
```

**Comment by GreyCat** [comment]
Thanks for your suggestion!

There is another approach, which is similar, yet more concise and slightly more readable — to use `type: bX` (see [bit-sized integers](http://doc.kaitai.io/user_guide.html#_bit_sized_integers) in the doc). It would go like that:

```yaml
vm_prot:
  seq:
    - id: reserved
      type: b27
    - id: copy
      type: b1
    - id: no_change
      type: b1
    - id: execute
      type: b1
    - id: write
      type: b1
    - id: read
      type: b1
```

That's all. In all other respects, it generates the API equivalent to the one that you've provided in your patch. All these members like `copy`, `no_change`, etc, would be boolean values, so, for example, in Python, one can do stuff like

```python
p = some_segment.init_prot
if p.read and p.write:
    # do stuff as we ensured that it's initialially readable + writable
```

Also, it won't hurt to add `doc: ` documentation string to every such member, and probably `-orig-id` (along with our `id`) to specify IDs used in original documentation (i.e. stuff like that `VM_PROT_READ` with prefix and upper case).

**Comment by FilippoBiga** [comment]
Thanks for your reply, I knew about bit sized integers (as per our Twitter discussion) but I did not know it would have been alright to just skip the first 27 bits.

Additional question: `vm_prot_t` is used throughout the system for scopes broader than Mach-O segments, i.e. mapping arbitrary memory regions. There are certain values which are not used for Mach-O segments, such as `VM_PROT_NO_CHANGE` and `VM_PROT_COPY`. Should we strive towards providing a complete representation of `vm_prot_t` or limit it to only the values being actually used for Mach-O segments? This would generate APIs that only expose read, write and execute, and then the user would need to retrieve other bits manually from the `reserved` field. 

Finally: would you like me to just provide the patch here or open a pull request? 

Thank you again!

**Comment by GreyCat** [comment]
> Should we strive towards providing a complete representation of `vm_prot_t` or limit it to only the values being actually used for Mach-O segments? 

I'd stick with the type specs suggested by Apple (i.e. their `vm_prot_t` specifying all 5 bits), unless there is a very good reason not to (I can't think of a reason why having 2 extra members unused in *some* cases would hurt anyone).

> Finally: would you like me to just provide the patch here or open a pull request?

Pull requests would be the best — they are somewhat easier to apply properly (i.e. saving your authorship and change dates, etc) ;)

**Comment by koczkatamas** [comment]
> However, vm_prot_t values are used as bit masks by all the tools producing, analyzing and using Mach-O files in Apple's operating systems.

The current implementation can be used as a bit mask, while the new proposed (`bX`-based) solution can not.

I don't understand how this helps in the original issue.

**Comment by GreyCat** [comment]
@koczkatamas What exactly do you mean by "can be used as a bit mask", and why `bX`-based solution does not fit this criteria? Since we've introduced it, I've always assumed that it should be the only way we use to describe bitmasks.

**Comment by FilippoBiga** [comment]
@koczkatamas To my understanding, the current implementation does not allow representing values such as 0x05 (`VM_PROT_READ | VM_PROT_EXECUTE`). There needs to be ways to represent combinations of the values described in the enum. Am I mistaken?

**Comment by koczkatamas** [comment]
I am not sure about the target language but I presumed from `vm_prot_t` it's C++.

So this is the generated code:

```c
    enum vm_prot_t {
        VM_PROT_NONE = 0,
        VM_PROT_READ = 1,
        VM_PROT_WRITE = 2,
        VM_PROT_EXECUTE = 4,
        VM_PROT_NO_CHANGE = 8,
        VM_PROT_COPY = 16
    };
```

Currently you can execute operations like `VM_PROT_READ | VM_PROT_EXECUTE` and get `0x5`. Or cast the enum's value to int and print out things like
```
  maxprot 0x00000007
 initprot 0x00000005
```

If you modify the implementation to a `bX`-based one, then you lose this opportunity. And from the original issue I presumed the current problem is that we parse values differently than the vast majority of tools. I think it's the opposite: if we modify the implementation to the proposed one than we'll be much further from other tools than now.

With the current implementation you can interpret values like `0x5` correctly, some tools like the WebIDE does it already:

![image](https://user-images.githubusercontent.com/2608082/29486312-1da80d36-84e3-11e7-8bcb-ec94df57b6d9.png)

**Comment by FilippoBiga** [comment]
> I am not sure about the target language but I presumed from `vm_prot_t` it's C++.

`vm_prot_t` is the type defined by Apple in vm_prot.h to represent protection bits.

Using the current specification of mach_o.ksy to generate a Python parser for Mach-O files, the code generated for VmProt is as follows:
```
class VmProt(Enum):
    none = 0
    read = 1
    write = 2
    execute = 4
    no_change = 8
    copy = 16
```

and `initprot`/`maxprot` are read as follows:
```
self.maxprot = self._root.VmProt(self._io.read_u4le())
self.initprot = self._root.VmProt(self._io.read_u4le())
```

When trying to parse /bin/cat from a standard installation of macOS, an error is thrown because the parser does not accept 0x07 (`VM_PROT_READ | VM_PROT_WRITE | VM_PROT_EXECUTE`):
```
ValueError: 7 is not a valid VmProt
```
I am not exactly sure then why it is accepted in other languages.

**Comment by koczkatamas** [comment]
Then I think the solution is to introduce an option in ksy to flag enums as `flags`, so generated (python, etc) code will be `class VmProt(Flag):` (or `IntFlag`) instead of `class VmProt(Enum):`.

Otherwise the library's user won't have any chance to get the meaning of values like `VM_PROT_READ` or use them outside of Kaitai (other than re-implementing it again but IMHO the whole point of Kaitai is to not to separately re-implement things).

**Comment by FilippoBiga** [comment]
@koczkatamas I see your point and I agree that it should be possible for the user to access the concrete values.

Apparently, the hard restriction on the values of `vm_prot` is not enforced in all languages: I have verified that for cpp_stl and perl targets the values of `initprot`/`maxprot` could be anything. The parser will happily accept them and not throw any error. Assuming this is the intended behaviour, then the only problem arises from how the Python code is generated (possibly applicable to other targets too, but I cannot check as of now).

**Comment by GreyCat** [comment]
@koczkatamas I believe there's some deep misunderstanding here.

> Currently you can execute operations like VM_PROT_READ | VM_PROT_EXECUTE and get 0x5.

No, generally you can't. It only works in languages that don't do any conversion to the integer and only provide constants to match against. AFAIR, this is JS, Perl and PHP, and, to some extent, C++.

For example, in Java we generate enum and `byId()` method, which is used to convert integer into proper enum instance:

```java
    public enum VmProt {
        NONE(0),
        READ(1),
        WRITE(2),
        EXECUTE(4),
        NO_CHANGE(8),
        COPY(16);

        private final long id;
        VmProt(long id) { this.id = id; }
        public long id() { return id; }
        private static final Map<Long, VmProt> byId = new HashMap<Long, VmProt>(6);
        static {
            for (VmProt e : VmProt.values())
                byId.put(e.id(), e);
        }
        public static VmProt byId(long id) { return byId.get(id); }
    }
```

Given how Java works, this `byId.get(id)` would just return `null` when no matching value is found => the information is lost forever. The situation with Ruby, Python, and, I believe, C# is pretty much similar. Python even raises an exception, I guess, when a enum value is not found.

Moreover, I definitely don't like pushing any bit arithmetics down to the application layer. If you need to check "if given vm_prot instance supports both read AND execute" or "if given vm_prot instance supports read OR execute", then you just do something like

```python
p.read and p.execute
p.read or p.execute
```

not a much more obscure (and implementation-dependent) stuff like

```c
p & (VM_PROT_READ | VM_PROT_EXECUTE) == VM_PROT_READ | VM_PROT_EXECUTE`
p & (VM_PROT_READ | VM_PROT_EXECUTE) != 0
```

This is proper encapsulation, and I throughly believe that this is the proper way to handle bitmasks.

> With the current implementation you can interpret values like 0x5 correctly, some tools like the WebIDE does it already:

I've never heard of this feature, how does it work? It somehow analyzes if given enum is one-bit-only for every value, and then tries to match that?

**Comment by FilippoBiga** [comment]
@GreyCat If I understood it correctly, the correct behaviour is the one exposed by Python, @koczkatamas was also referring to being able to access the values VM_PROT_READ, VM_PROT_EXECUTE, etc. without having to re-define them somewhere. This can be useful indeed. However, I agree with you that the application should not be *required* to know about them.

**Comment by GreyCat** [comment]
@FilippoBiga There is no "correct" or "incorrect" behavior. We try to no invent the rules as much as we can — we just use whatver practices are popular in particular language. Python has more or less standard enums which behave like that. Java has standard enums which are also like that — they only allow single value. If you think of it, "enum" = "enumeration" is by definition a single named value, not a "bitmask that allows several bits to be on and off".

All that manual bit juggling and definition of constants like "VM_PROT_EXECUTE = 0x04" actually comes straight from C, where there's no higher level constructs to work with individual bit fields (or at least they are way too clumsy / too inefficient to be used).

So, the basic idea is that "enums" are enums, and that's a bad idea to abuse them for bitmask purposes. They work consistently when the values are defined and the behavior is undefined (language-specific) when there's an undefined value. Again, it's not us who invented that, it's designers of every particular language.

**Comment by FilippoBiga** [comment]
@GreyCat Thank you for the clarification.

**Comment by koczkatamas** [comment]
@GreyCat in C# you can add the `[Flags]` attribute to the enum and use the HasFlag method to check if an item is set in the enum. And AFAIK this is the expected form.

Not sure about other langs.

**Comment by koczkatamas** [comment]
(sorry for the double)

Just to be clear: of course if currently the Python implementation simply does not work, then switch to the `bX` implementation.

But in the long run I am not 100% sure that form is the expected in every situation for everybody.

**Comment by FilippoBiga** [comment]
I have provided a set of changes implementing the alternative we discussed through a pull request. Please let me know if I can improve it in any way. Thank you!

**Comment by GreyCat** [comment]
@koczkatamas Thanks for the insight on `[Flags]`, now I see what is your point ;)

I don't think that there are many similar features in other languages, though. For example, in Java, `enum` is basically a named symbol. They carry no IDs or any other numerical equivalents at all by default, you add all that stuff manually, i.e.:

```java
public enum Animal {
    DOG(4),
    CAT(7),
    CHICKEN(12);

    private final long id;
    Animal(long id) { this.id = id; }
    public long id() { return id; }
}
```

This basically creates N objects of compatible type (i.e. they all are guaranteed to have `id()`), and that's it. When you do:

```java
Animal myAnimal = Animal.CAT;
```

you just store a reference to pre-created `CAT` object in that `myAnimal` variable. Thus, it is physically impossible to store anything beyond references to these pre-created objects, i.e. any intermediate values like `Animal.CAT | Animal.DOG`.

When one wants to store multiple values in a enum, there is `EnumSet` in Java, but that one, again, does not expose any low-level interface to what it uses internally. From the regular developer's perspective, you again just get and set references to pre-created enum objects.

In Ruby, the situation is pretty similar, may be even worse ;) You use "symbols" created on the fly using `:symbol_name`, and that's it. There are no built-in ways to translate to and from some sort of integer equivalents, so we create them ourselves — by adding forward and reverse translation maps:

```ruby
  ANIMAL = {
    4 => :animal_dog,
    7 => :animal_cat,
    12 => :animal_chicken,
  }
  I__ANIMAL = ANIMAL.invert
```

This, again, makes it kind of impossible to keep original integer values (although we do keep them using simple trick in `--debug` mode for visualization purposes, when the values is unresolved).

In Python, it is again so. Language-standard-since-3.4 `Enum` implementation can only keep single values, not flags.

**Comment by koczkatamas** [comment]
Using `IntFlag` in Python works mostly as flags in C#. Maybe I am accustomed to C#, but this is the behaviour I would expect from a bitmask enum:

```python
from enum import IntFlag
class VmProt(IntFlag):
     Read = 1
     Write = 2
     Exec = 4

VmProt(7) ==> <VmProt.Exec|Write|Read: 7>
int(VmProt(7)) ==> 7
int(VmProt(8)) ==> 8
repr(VmProt(8)) ==> '<VmProt.8: 8>'
repr(VmProt(7)) ==> '<VmProt.Exec|Write|Read: 7>'
repr(VmProt(0)) ==> '<VmProt.0: 0>'
VmProt.Read | VmProt.Write ==> <VmProt.Write|Read: 3>
int(VmProt.Read|VmProt.Exec) ==> 5

x = VmProt.Read|VmProt.Exec
VmProt.Read in x ==> True
VmProt.Write in x ==> False
```

**Comment by KOLANICH** [comment]
@filpabiggo, for a bit mask I usually define a type with b1 fields

**Comment by FilippoBiga** [comment]
@KOLANICH Something similar to what my pull request included or a different alternative?

**Comment by GreyCat** [comment]
@koczkatamas If you'd really prefer that form of output — why don't we implement some kind of CLI switch that would turn stuff like

```yaml
my_flags:
  seq:
    - id: reserved
      type: b5
    - id: flag_c
      type: b1
    - id: flag_b
      type: b1
    - id: flag_a
      type: b1
```

into that stuff where it's possible — i.e.

```python
from enum import IntFlag
class MyFlags(IntFlag):
    FlagA = 1
    FlagB = 2
    FlagC = 4
    Reserved = 248
```

It's generally a matter of desired output, I'd like to keep source ksy as unambiguous as possible.

**Comment by GreyCat** [comment]
Given that original objective of this issue was achieved, I'm closing this. If anyone wants to discuss / implement stuff like C#'s `[Flags]` or Python's `IntFlag`, feel free to open a separate issue for that.
