### ISSUE TITLE
C++: Conditional fields ("if:") not processed

### ISSUE THREAD

**Issue by tempelmann** [kaitai-io/kaitai_struct#226]
I see that not working in 0.7 for C++. For instance:

      - id: bar
        type: u4
        if: foo > 2

The test for foo is missing from the generated C++ class, so that all struct fields past this are shifted by this field unconditionally, making it simply not work right.

**Comment by tempelmann** [comment]
I wonder how that can be solved. I suspect the code generation has to be changed so that there are no private var declarations at all in each class, and the offsets to each field are hard-coded in the accessors, instead, so that a class would not look like this:

    class flex_idpair_record_t : public kaitai::kstruct {
      public:
        flex_idpair_record_t(kaitai::kstream* p_io, kaitai::kstruct* p_parent = 0, root_t* p_root = 0);
        ~flex_idpair_record_t();

      private:
        uint64_t m_node_id;
        uint16_t m_namelength;
        std::string m_dirname;
        root_t* m__root;
        kaitai::kstruct* m__parent;

      public:
        uint64_t node_id() const { return m_node_id; }
        uint16_t namelength() const { return m_namelength; }
        std::string dirname() const { return m_dirname; }
        root_t* _root() const { return m__root; }
        kaitai::kstruct* _parent() const { return m__parent; }
    };

but rather like this:

    class flex_idpair_record_t : public kaitai::kstruct {
      public:
        flex_idpair_record_t(kaitai::kstream* p_io, kaitai::kstruct* p_parent = 0, root_t* p_root = 0);
        ~flex_idpair_record_t();

      private:
        char *m_data;
        root_t* m__root;
        kaitai::kstruct* m__parent;

      public:
        uint64_t node_id() const { return *(uint64_t*)(m_data + 0); }
        uint16_t namelength() const { return *(uint64_t*)(m_data + 8); }
        std::string dirname() const { return *(uint64_t*)(m_data + 10); }
        root_t* _root() const { return m__root; }
        kaitai::kstruct* _parent() const { return m__parent; }
    };

And, of course, if there are conditional fields in there, then the offsets would be different depending on that.

In that case, functions to calculate the offset would be needed, and they would be chained (their results added up) when accessing fields beyond such conditionally existing fields.
For the sake of performance, though, the classic code should remain used where there are no dynamic field sizes involved. Tricky.

**Comment by tempelmann** [comment]
Huh - I only realize now that the C++ output is not complete anyway. While the generated python code builds the structures as intended, the C++ code only defines the structures, and the code that would create the structures based on the actual input stream is completely missing from the generated code. Or am I missing something big here?

**Comment by GreyCat** [comment]
Um, you're listing and looking only at .h file here. There's also a .cpp file that includes `_read()` method (or class constructor in 0.7) that does all the parsing. Here's what would be generated there:

```cpp
    n_bar = true;
    if (foo() > 2) {
        n_bar = false;
        m_bar = m__io->read_u4le();
    }
```

**Comment by tempelmann** [comment]
Ahh! I did not realize that the WebIDE, which I used to create the file, did open two tabs for both the c and the h file. Sorry, and thanks.
