### ISSUE TITLE
Opaque Parametric Processes

### ISSUE THREAD

**Issue by SpenserStyles** [kaitai-io/kaitai_struct#235]
KSY has opaque parametric types (thank you very much!) is it possible to do the same for processes?  The rules for processes (User Guide section 4.14) would not change but would allow processes outside of KaitaiStream to be used.

**Comment by GreyCat** [comment]
There is ongoing initiative to do that - see #51 for details. It would probably make it one way or the other into 0.8, there are already existing implementations for C++, Java & Ruby (see [process_custom](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/process_custom.ksy) test).
