### ISSUE TITLE
allow switch-on/cases for every attribute

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#236]
I have encountered compilation errors when tried to switch encoding and something else. I guess we need to implement switch in the way allowing to use it nearly on any attribute. I guess switch should be translated into switch or analogues. And in python where possible it should use a look-up dictionary instead of elif.

**Comment by GreyCat** [comment]
First of all, you've probably meant "YAML map key" or something like that. "Attribute" is that you have in `seq` and `instances`.

At the current stage, it is next to impossible. There are too many combinations and/or complex implications on other stages of parsing to consider.
