### ISSUE TITLE
C++ codegen: "void _read();" needs to be made private

### ISSUE THREAD

**Issue by tempelmann** [kaitai-io/kaitai_struct#243]
As the _read() function is currently not freeing any objects it may have allocated in a previous invocation, it should not be called more than once. Therefore, it should be made private to indicate it's not available for calling by the user.

**Comment by GreyCat** [comment]
Should be fixed, please take a look.

**Comment by tempelmann** [comment]
Confirmed fixed.

**Comment by GreyCat** [comment]
Thanks!
