### ISSUE TITLE
_io.pos, _io.eof

### ISSUE THREAD

**Issue by sergeyzelenyuk** [kaitai-io/kaitai_struct#25]
According to a problem described in #24, we need an ability to use `_io.pos` and `_io.eof` in expressions to use, for example, inside `size` or `if` attributes. They will be additions to `_io.size` which can be used already.

`_io.pos` - get position in current stream;
`_io.eof` - `true` if current position at the end of file, `false` otherwise.

**Comment by GreyCat** [comment]
Thanks!

**Comment by GreyCat** [comment]
@LogicAndTrick @sergeyzelenyuk Can anyone provide any meaningful examples for these to make tests? I keep thinking about it and the more I think, the more I don't like the idea actually ;) All examples I can come up with are very artificial and mostly can be achieved through other means.

What I don't like about these vars as well is that they are very context-dependent, while we generally strive to achieve "pure functional returns" without any side-effects, i.e. no matter where in the algorithm you access the field and what field type that is (i.e. sequence attribute, parsed instance or value instance), the result is going to be the same. It's not 100% true (as we don't have any checks for use of uninitialized variables before their usage), but it's fairly close. Exposing very state-related stuff like `_io.pos` and `_io.eof` aids in breaking this paradigm and I'm not sure what it brings anything.

**Comment by LogicAndTrick** [comment]
There might be another way to cover this scenario, but I have a format which has an optional information block at the end of the file. There's no flag in the file to indicate if it's there, it's just either there at the end of the file or it isn't. Using a manually-coded parser, I currently do an EOF check to see if the additional block is present or not.

```csharp
var mainPart = ReadMainPart(stream);
var infoPart = stream.IsEof() ? null : ReadInfoPart(stream);
```

It would be useful to be able to do something like this:

```yaml
seq:
  - id: main_part
    type: main
  - id: info_part
    type: info
    if: not _io.eof
```

Even though it would technically work in this situation, I wouldn't want to use a `repeat` structure in this case because the result isn't a list, it's always a single object or a null.

**Comment by GreyCat** [comment]
Ok, `_io.eof` is mostly there:

* C# test is failing - @LogicAndTrick, could you take a look? I've upgraded by Mono installation and now it's broken, so I can't even build the tests :(
* Perl test is missing - @sergeyzelenyuk, any news on the autoconversion script?

**Comment by LogicAndTrick** [comment]
Fixed for C# in d9609e2b32cdf64a60298e9b50a572c410085f10. `IsEof` was a function in the runtime but it was being called like a property. I changed it into a property for consistency with the others, and updated the compiler to match. Minor changes to runtime, tests, and compiler.

**Comment by GreyCat** [comment]
`_io.pos` test is there, and, again, C# test seems to fail :( @LogicAndTrick, can you come to the rescue again?

**Comment by GreyCat** [comment]
Ok, looks like both tests are fine now. Closing this one, phew.
