### ISSUE TITLE
C++: Replace ! and && with "not" and "or"

### ISSUE THREAD

**Issue by tempelmann** [kaitai-io/kaitai_struct#250]
C++ has, since its beginning, supported the more explicit operators "not", "and" and "or" in place for "!", "&&" and"||". I propose to use them because they're more readable.

**Comment by GreyCat** [comment]
Related PR: https://github.com/kaitai-io/kaitai_struct_compiler/pull/108

I'm inviting everyone interested in C++ support to discuss this — cc @scottmsilver @Newlifer @berkus @JaapAap @MariaChakchurina @AlexAltea.

I've actually never encountered these alternate forms of C++ operators before, so it's kind of new to me — but it's not like I have tons of C++ experience. I'll try to look into various C++ style guides to see if anyone actually specifies which kind of operators could/should be used.

**Comment by JaapAap** [comment]
They might be more readable to some, but I agree with the statements [here](http://en.cppreference.com/w/cpp/language/operator_alternative) that they are not the primary representation of these operators. Admittedly, they are not more readable to me, simply because I don't encounter them frequently and are used to the 'primary' representation

**Comment by GreyCat** [comment]
I've done some digging and analysis on alternative operators. None of the major C++ style guides mention them — thus it's not very clear if they (could|should|must) (be|not be) used.

Judging from the most popular open source C++ projects I've found, virtually everybody uses "traditional" operators:

### Mature projects

* [Qt](https://www.openhub.net/p/qt5) (~8M LOC) — [example](https://github.com/qt/qtbase/blob/5.9/src/corelib/kernel/qbasictimer.cpp#L123)
* [Firefox](https://www.openhub.net/p/firefox) (~18M LOC) — [example](https://hg.mozilla.org/mozilla-central/file/tip/browser/app/nsBrowserApp.cpp#l174)
* [Chromium](https://www.openhub.net/p/chrome) (~16M LOC) — [example]( https://cs.chromium.org/chromium/src/url/url_parse_file.cc?l=160)

### "Modern age" projects

* [LLVM/Clang](https://www.openhub.net/p/clang/enlistments) (~1.3M LOC) — [example](https://github.com/llvm-mirror/clang/blob/master/lib/Basic/VirtualFileSystem.cpp#L92)
* [Bitcoin](https://www.openhub.net/p/bitcoin) (~171K LOC) — [example](https://github.com/bitcoin/bitcoin/blob/master/src/addrman.cpp#L35)
* [Tensorflow](https://www.openhub.net/p/tensorflow) (~1M LOC) — [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/core/coding.cc#L139)
* [Krita](https://www.openhub.net/p/krita) (~1M LOC) — [example](https://github.com/KDE/krita/blob/master/krita/main.cc#L134)

Actually, I've never found a single use of alternative operators in the wild yet. Given such an overwhelming bias towards "traditional" operators in C++ projects, I'm tending towards not doing this fix.

**Comment by TanninOne** [comment]
Don't, just don't. These alternative operators were introduced to C in ancient times when they needed to support character encodings that may not have some of the special characters, i.e. the german DIN 66003 had to replace the pipe symbol, tilde, curly brackets, ... with german umlauts to fit into a 7-bit encoding.

These operators have been considered obsolete for easily 30 years, are barely documented and there are even considerations of removing them from future c++ standards. No one  should write code using them. ever.

**Comment by tempelmann** [comment]
@TanninOne That's so much misinformation: The "and", "or" and "not" operators were not introduced by C but by C++ (https://en.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#C.2B.2B_operator_synonyms). And later C standards even added them, too (https://en.wikipedia.org/wiki/C_alternative_tokens). And they make code more readable and thereby avoid mistakes. And the German argument is nonsense, too - if it would be the reason for the introduction of "and" for "&&", then they'd also have to offer alternatives for [] because they were also gone, see for yourself: https://de.wikipedia.org/wiki/DIN_66003 - instead, according to https://en.wikipedia.org/wiki/C_alternative_tokens, were to make typing easier on those kbds, but not, as you say, required for that.

Still, if there's strong opposition, I won't push it. I thought it would help to make code more readable.

**Comment by berkus** [comment]
Sad, they are quite a bit more readable.

**Comment by GreyCat** [comment]
Well, it's not that a huge deal to add it as an option if there are at least a handful of people who like that ;)

**Comment by berkus** [comment]
I use them in my code whenever possible.
