### ISSUE TITLE
C++: Fix import of kaitai headers

### ISSUE THREAD

**Issue by tempelmann** [kaitai-io/kaitai_struct#251]
The current import statements in the generated .h file are:

      #include <kaitai/kaitaistruct.h>
      #include <kaitai/kaitaistream.h>
 
There are two things to improve here:

1. kaitaistruct.h already includes kaitaistream.h, so the second #import can be removed.
2. The use of angled brackets ("<...>") is incorrect. They're meant for system libs, but these are primarily not system libs. Therefore, the import should use double quotes instead, like this:

      #include "kaitai/kaitaistruct.h"

Users who prefer to place these into their system headers path can still do so - it won't affect them, as the system paths will be searched if the headers are not found in the user's paths. The opposite is not true: Compilers will not look by default in the user paths if <..> is used.

Even better, should they download a new version of the source, then any locally available headers will be preferred if they forget to copy them to their system headers, preventing compilation errors.

Also, see this for clarification on the correct use of these: https://stackoverflow.com/a/41646905/43615

**Comment by GreyCat** [comment]
Seems to be fixed in https://github.com/kaitai-io/kaitai_struct_compiler/pull/109 and https://github.com/kaitai-io/kaitai_struct_compiler/pull/109/commits/f18ae3ec3a2f9de4ef271c1ced14323d03b34e5e. Thanks!
