### ISSUE TITLE
Support list in doc-ref

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#269]

**Comment by GreyCat** [comment]
I'm really inclined to close these one-liner "issues" right away without any comments, if you don't want to spend a minute and explain what is it about, why is this important, and in which cases you need such support.

**Comment by KOLANICH** [comment]
It's obvious:  information about the format can be taken from multiple sources.

**Comment by GreyCat** [comment]
I've implemented it. Now `doc-ref` accepts both string and a list of strings: https://github.com/kaitai-io/kaitai_struct_compiler/commit/f2c12d41b8f79661b0eb5103e37c0b8bf112e24f

New test is called DocstringsDocrefMulti and will appear shortly at CI. KST is there, but it is essentially no-op, as we can't test it automatically.

**Comment by GreyCat** [comment]
Most of languages are commited, so considering this done.

**Comment by KOLANICH** [comment]
Thank you.
