### ISSUE TITLE
Support BibJSON in doc-ref

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#270]

**Comment by GreyCat** [comment]
Same stuff here. I have no idea of what a BibJSON is, and I don't want to spend another half-an-hour researching that and making guesses on why would you suggest that, and what would be the benefits.

**Comment by KOLANICH** [comment]
Thought about it a bit more, you are right, an URI (not only ```(f|ht)tps?``` one...) must be enough for everything.
