### ISSUE TITLE
Cannot build compiler for JVM as Debian package

### ISSUE THREAD

**Issue by deefha** [kaitai-io/kaitai_struct#276]
When building compiler from source (by installing sbt, all dependencies and running `sbt compilerJVM/debian:packageBin`) I've got this error:

```
[error] (compilerJVM/debian:stage) java.lang.IllegalArgumentException: requirement failed: Source file '/some/not/important/path/kaitai_struct_compiler/jvm/src/main/resources' does not exist.
```

As a dirty workaround I manually created empty directory `resources`, package was then successfully created. I guess it has something to do with this lines in file `build.sbt`:

```
linuxPackageMappings += LinuxPackageMapping(Map(
      new File("jvm/src/main/resources") -> "/usr/share/kaitai-struct"
    )),
```

Or maybe I am missing something?

**Comment by GreyCat** [comment]
Uhh, it's kind of known bug that I haven't yet managed to close. You're completely right, the workaround is just to make an empty dir, i.e `mkdir -p jvm/src/main/resources` in compiler.

If you know how to fix build.sbt to avoid that, I'd be really grateful :)

**Comment by deefha** [comment]
Well, I'm not (yet) familiar with Scala, but I can try it :-) Anyways, thank you for a quick reply and confirmation.

**Comment by GreyCat** [comment]
Yeah, it is a bug, but I remember about that very rarely in normal development flow, as it ceases to exist after first successful build. Actually, the only thing needed here:

```scala
linuxPackageMappings += LinuxPackageMapping(Map(
      new File("jvm/src/main/resources") -> "/usr/share/kaitai-struct"
    )),
```

is *any* directory that is guaranteed to be empty. Unfortunately, it's impossible to have a truly empty directory in a git checkout, so we need to create it somehow in sbt :(

**Comment by GreyCat** [comment]
Hmm, actually there seem to be [official way to add empty dirs](http://www.scala-sbt.org/sbt-native-packager/formats/linux.html#add-empty-directories) in sbt-native-packager.

**Comment by GreyCat** [comment]
Hey, I think I've done the fix — could you take a look if it works for you?

**Comment by deefha** [comment]
Yes, building process is without error now, so it works. Thank you!

**Comment by GreyCat** [comment]
Cool, thanks!
