### ISSUE TITLE
Add to FAQ differences between this and cap'nproto

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#28]

**Comment by GreyCat** [comment]
Actually, everything that's mentioned about Google Protobuf, ASN.1, Thrift, Avro, BSON, etc, would apply to Cap'n Proto as well. It uses a couple of interesting tricks to map the data in a manner that is closer to memory layout, thus achieving faster serialization / deserialization, but from user's POV it uses the same paradigm as Protobuf. You can't parse arbitrary binary formats with Cap'n Proto.

**Comment by KOLANICH** [comment]
OK, thank you. Could you put this into the wiki?

**Comment by GreyCat** [comment]
Here you go: https://github.com/kaitai-io/kaitai_struct/wiki/FAQ#-capn-proto
