### ISSUE TITLE
Java output directory is prepending src

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#287]
Original was submitted by @daviderickson in https://github.com/kaitai-io/kaitai_struct_compiler/issues/118:

> Hi I am overriding both the java package and the output directory (ie --java-package com.test and --outdir ../java).  I'd expect my Test.java file to end up in ../java/com/test/Test.java, but instead it is being created as ../java/src/com/test/Test.java
> 
> I am assuming this is default behavior, but shouldn't happen when overriding the output directory.  The culprit seems to be https://github.com/kaitai-io/kaitai_struct_compiler/blob/2bd8834f65e392d8eb2fc7776861b3050d73d085/shared/src/main/scala/io/kaitai/struct/languages/JavaCompiler.scala#L45
> 
> Thanks!

**Comment by GreyCat** [comment]
Uhh, this is kind of awkward and I tend to agree with you now.

Originally, it was more or less organized like that due to tests compilation, as it is kind of useful to have src/ and bin/ separately, and it kind of matches IDEA/Eclipse requirements on basic dirs. However, probably the time has come to reconsider that decision and move forward.

One thing that stops me is how to make it somehow compatible with current implementation. I wonder if stuff like `--java-path-prefix`, which would be `src` by default, would work, and final path would be constructed using `--out-dir` + `--java-path-prefix` + relevant package dirs?

**Comment by jadzdotcom** [comment]
I also suffer from the hard coded source output. I end up running a batch file that generates the sources, and then copies them into the correct folder for my project.

**Comment by daviderickson** [comment]
@GreyCat Another option would be to add a flag, something like --no-src-prefix that disables that current default behavior, as I'm not sure someone would really want to use a prefix other than 'src', that they wouldn't just place into the out-dir parameter.  You could also indicate that the 'src' prefix is deprecated and schedule removing that behavior entirely for a future release.

**Comment by GreyCat** [comment]
Well, to be frank, probably nobody would ever use `--target all` and generate multiple per-language paths except for running tests. So may be we could just make that `java/src` automatic for `--target all` and that's it...

**Comment by brunchboy** [comment]
This is a problem for me as well, because even though I am only generating java classes, because of the multi-language-nature of my Maven project, they need to go into `src/main/java/` followed by the package directories. There is no way to configure ksc to do that, so I need to move them after generating them.
