### ISSUE TITLE
RegEx support

### ISSUE THREAD

**Issue by jvmlet** [kaitai-io/kaitai_struct#3]
Hi
Are you planning to support regular expression for parsing text  fields  ?

**Comment by GreyCat** [comment]
Not really. Could you explain the use case for that or provide an example where it would be useful?

**Comment by jvmlet** [comment]
Consider the input text file :
fieldName1: some arbitrary uninteresting text with known pattern for value extraction
fieldName2: another arbitrary uninteresting text with known pattern for value extraction
....
fieldNameN: value


Is it possible to extract values for fieldName1,2 and 5 with current syntax?
How do I skip lines between fieldName2 and fieldNameN?

**Comment by GreyCat** [comment]
If it's all-text file, then it would be kind of pointless to employ Kaitai Struct to parse it. It's exactly where using regular expressions alone would shine: you just search for stuff like `^fieldName1` to confirm that it's the line you need and then run regex on that. Bringing KS into picture here would probably only complicate things a lot, but won't get you any additional benefits.

**Comment by jvmlet** [comment]
OK, but it might be the payload of some binary protocol... What is your suggestion in this case ?

**Comment by GreyCat** [comment]
It's perfectly fine to have XML, JSON, YAML, source code in some programming language, just text or something like that as a payload in a binary protocol. KS can help you to process this binary protocol and extract payload as a stream of bytes — then you're basically free to give it to any other processing library better suited for the purpose of processing stuff like text-based formats, text markup languages, etc.

KS is by no means a universal answer for all the possible parsing in the universe. For example, it might be technically possible to parse JSON in KS, but the result probably won't satisfy you for end-user purposes. You'll end up with a file chopped in very small physical pieces, with no logical structure, no easy means to access stuff like "map element by key", etc, etc.

**Comment by jvmlet** [comment]
Ok, thanks for the detailed answer
