### ISSUE TITLE
Python compiler: ensure_fixed_contents uses struct not literal

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#310]
I was looking at Bitmap example, Python gen in particular and noticed that Magic field emits a line:
http://formats.kaitai.io/bmp/python.html
```py
self.magic = self._io.ensure_fixed_contents(struct.pack('2b', 66, 77))
```

Struct.pack is not particularly speedy. It would be good to have a literal instead. I am not sure if that should be done in preprocessing or in python-specific compiler. I tracked the emit to this line and got lost:
https://github.com/kaitai-io/kaitai_struct_compiler/blob/349015054f016f345f95d0a8adde344d6eaf1512/shared/src/main/scala/io/kaitai/struct/languages/PythonCompiler.scala#L167
```scala
  override def attrFixedContentsParse(attrName: Identifier, contents: String): Unit =
    out.puts(s"${privateMemberName(attrName)} = self._io.ensure_fixed_contents($contents)")
```

This is a low priority upgrade, because Magic is sporadically used and its already fast enough. Its just that it could be little faster.

**Comment by GreyCat** [comment]
`ensure_fixed_contents` call normally just provides a byte array literal, which is generated in `*Translators`, and used for multitude of other reasons (for example, an expression like `a == [1, 2, 3]` would be compiled to something like `self.a == struct.pack('3b', 1, 2, 3)`. So [this is the ultimate culprit](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/translators/PythonTranslator.scala#L39-L42).

Feel free to suggest a change. For example, if generating stuff like `b"\x12\x34\x56"` would be faster, then we other have languages that use similar approach, i.e. C++, PHP, etc. Let's just reuse it.

**Comment by arekbulski** [comment]
Ohh if I only knew Scala... you would need to change line 41 with something equivalent to string.join(hex of each byte). I will ask on SO how to code it and get back to you. 

And yes, struct.pack is definately slower than just a literal.
```py3
In [11]: timeit("struct.pack('2b',0,0)", setup="import struct")
Out[11]: 0.18611988000338897

In [12]: timeit("b'00'")
Out[12]: 0.015497082989895716
```

I am happy that changing this is this easy. One line in the compiler. Huh.

**Comment by GreyCat** [comment]
Just look it up in other languages' translators? For example, [in C++](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/translators/CppTranslator.scala#L57-L58).

**Comment by arekbulski** [comment]
Here is a patch for your testing, I dont know how to run testsuite on the PR.
https://github.com/kaitai-io/kaitai_struct_compiler/pull/122

**Comment by GreyCat** [comment]
Right now you can run the tests on your box... Running it on CI requires update to submodule reference in main umbrella repo, which I'll do a little bit later :)

**Comment by arekbulski** [comment]
Uhm, which test cases exactly are testing Magic field?
