### ISSUE TITLE
Compiler: field returning different types on different targets

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#315]
This is something that occured to me when discussing the bitmaps topic. **Can same field result in different types on different target runtimes?** I would appreciate an authoritative anwer on current consensus on this semantic.
If yes, that would be very useful for selectively implementing new and complex types like bitmaps/narrays.

Obvious case: If target does not support bigints, then u1024 type would result in 64-bit int on C target but bigint on Python/Ruby targets. 

Complex case: If target does not support multidimensional arrays, then array discussed in https://github.com/kaitai-io/kaitai_struct/issues/188#issuecomment-358642550 would result in char* or bytearray on C target but numpy arrays on Python.

**Comment by KOLANICH** [comment]
Numpy arrays for python should be a manually enabled option because numpy is dependency and is mainly used in scientific computing.

**Comment by GreyCat** [comment]
Technically, same attribute resolves to *different types* in different targets, just by definition. C++ `std::string` is not the same as Java's `String` and it's not equivalent to Ruby's `String`.

What you're asking if we can make some exceptions and generate differently (may be *slightly* differently) behaving code for different targets — and the answer is "yes, we actually already do that". For example, JavaScript's concept of numbers is limited in some cases to 32-bit integers, and in some cases to 53-bit mantissa of double IEEE float. So, right now, reading 64-bit integer in JavaScript yields a value with some error. It's not bad for smaller values, but it leads to various misbehaviors with values like `0xffff_ffff_ffff_ffff`.

When discussing various types of fallback, I guess it's better to be more down to point. Namely, there are two different models of "degradation":

* "Most" or "some" languages get proper complex type (like bitmap, or 1D array, or something), and others, non-supported languages just get a raw byte array. This boils down to two conditions:
  * Nothing inside KS should rely on various properties of that "complex type". In other words, KS (and ksy) just treats it as opaque type, never accessing anything inside.
  * There should be an easy way to get size of the value of that complex type, so non-supporting languages would just skip it (rendering it as byte array) without any consequences to further sequence attributes.
* "Some" languages get some richer functionality (like bigint, or a string with some intricate methods enabled on it), and others get something more primitive (like regular fixed-size int / long, or just a regular string). This is probably ok too (we do it right now anyway). However, it's not as simple as in previous cases, as something might depend on this rich functionality in ksy file — for example, querying for 100th bit in 150-bit value would obviously fail if we just supply it as 64-bit integer. I don't know a single right answer for that one.

**Comment by arekbulski** [comment]
The difference between 64-bit integer and bigint is not what I am asking. That is just integers and buggy-integers to me. Its apples and shiny apples, not apples and oranges. :laughing: 

Could python target return a numpy multidimensional array (instead of bytes) while other targets return a bytearray (with no multidimensional array equivalent)? That means expressions could refer to some properties of the numpy array, but it would not compile for other targets. If someone is using Kaitai with the purpose of just using it for Python only, he would not care about other targets. This could be construded as "different semantics" on different targets. Somehow analog to varint implementations returning a struct with value field, or an integer, depending on target.

**Comment by KOLANICH** [comment]
1 I guess the purpose of KS is to make every ksy compilabke for every supported language.
2 Again, I vote against hard dependency of numpy. Numpy should be asked to be used on demand if it's convenienter and faster for the end user of ksy - app developer to use numpy in its app then to convert lists to numpy.

**Comment by arekbulski** [comment]
I am suggesting that code like this
```yaml
- id: array
  type: numpy
```
would result in numpy array on python target and result in bytearray on other non-python targets, instead of just erroring. Do you see my point? 

Re 1, compilable for every language does not imply resulting in same type for every language (same type meaning similar, int64=bigint for that purpose). 
Re 2, its not hard dependency. Using type "numpy" is user's choice.  Numpy would not be required for Kaitai-compiler, and resulting .py would require numpy only if numpy type was used.

**Comment by KOLANICH** [comment]
No, no, and again no. KS defititions are language- and library-neutral, they mustn't contain this kind of stuff.

**Comment by arekbulski** [comment]
I think the consensus is that: Kaitai does not or rather will not support types that do not exist in all runtimes. I am talking about things like Numpy-serialized arrays, not 64-bit integers vs bigintegers.
