### ISSUE TITLE
personal, write access to repo

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#319]
Thank you for inviting me to python runtime repo. Could you also grant me access to few other repos? 
- this one 
- https://github.com/kaitai-io/kaitai_struct_compiler
- https://github.com/kaitai-io/kaitai_struct_tests
- https://github.com/kaitai-io/kaitai_struct_benchmarks
- https://github.com/kaitai-io/kaitai_struct_formats

Its somewhat more convenient to to push directly. I promise to use separate branches.
I also kinda tiggles my ego, you know, being a co..main..tain..er :smile:

**Comment by GreyCat** [comment]
No problems with ticking the ego, invited you to the organization that should grant access to most repositories.

Please be careful with direct pushes, though. If you have any doubts that it would be good to have some discussion, please do a PR.

**Comment by arekbulski** [comment]
Agreed.
