### ISSUE TITLE
C#: suboptimal instances already calculated check

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#32]
It dawned upon me that the current "is instance already calculated" check in C# is so-so. It was copied from Java, and, while Java has both nullable and non-nullable types (as `Integer` and `int`), C# seems to only have non-nullable primitive types, such as `int`, and thus they always have a default value (which is 0), not null. Because of that, this turns out bad:

```c#
        private int _foo;
        public int Foo
        {
            get
            {
                if (_foo != default(int))
                    return _foo;
                _foo = ...
                return _foo;
            }
        }
```

If calculated value of `_foo` is 0, it will get calculated again and again. This (1) breaks API contract - instance's value is supposed to be calculated once and never change afterwards, (2) might get really slow, if instance calculation is some kind of really slow operation, which will get executed repeatedly.

Is there something we can do about it? For example, C++ solves the same problem by introducing distinct flag variables - i.e. `f_foo` - `false` by default, set to `true` after the instance have been calculated.

**Comment by LogicAndTrick** [comment]
Good catch. I copied most of the C++ implementation, but the `EveryReadIsExpression` trait uses `instanceClear` and `instanceSetCalculated` for `if` expressions as well (seems to be needed in C++, something about destructors). I'll add `condIfClear` and `condIfSetCalculated` for the C++ compiler and use those in the trait instead.

**Comment by GreyCat** [comment]
Thanks for the prompt response! I've merged all your proposals, off to CI they go.

**Comment by LogicAndTrick** [comment]
No problem! Looks like the CI failed but it doesn't seem to be related to these changes.

**Comment by GreyCat** [comment]
Yeah, I've already fixed it, it was a stack trace parsing problem ;)
