### ISSUE TITLE
construct related, pypi description update

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#320]
As the developer of Construct (not Kaitai, although I am somewhat proud of joining your effort :)
I would like to request an update of Kaitai pypi page, this one:
https://pypi.org/project/kaitaistruct/

- update Construct link to this one
https://construct.readthedocs.io/en/latest/
- remove Construct3 because it was abandoned years ago and never released
it doesnt have one feature that Construct 2.8 doesnt have, beacause I imported C3 features into C2
the blogpost is a nice read but the implementation is nothing but useful

**Comment by GreyCat** [comment]
As far as I understand, it completely comes from [this README file](https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/README.md). Just feel free to edit/reword that in any fashion you'd like. Probably we can't revoke v0.7 description, but at least we'll be sure that v0.8 description will be right.

Also, while you're at it, may be you can advice if it's possible somehow to use Markdown features properly on that page? Or, may be, it will work if we'll convert it from Markdown to something else (RST, or what's the standard in Python world)?

**Comment by arekbulski** [comment]
Pypi page does not show 3.6 on the list, should I add it?

**Comment by GreyCat** [comment]
Yeah, probably :)

**Comment by arekbulski** [comment]
The classiffiers even have 3.7, which Construct also "officially" supports BTW. I mean Construct runs on Travis 3.7 env, otherwise I have never even seen a 3.7 python runtime. Its like a ghost ship.

**Comment by arekbulski** [comment]
I rewrote it into reST and updated links. After 10 days... :sweat:

**Comment by GreyCat** [comment]
Cool, thanks
