### ISSUE TITLE
issues labels

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#321]
I realize that pretty much everything else is higher priority than... labels... colors, but if you would want to spare 5 minutes to look at Construct labels and maybe adjust some colors? :wink: 
https://github.com/construct/construct/labels

- remove duplicate, invalid, wontfix
- adjust colors to more ahem bright

If you feel like this issue is just too unimportant, just close it.

**Comment by GreyCat** [comment]
I see that you've remapped colors for label. Right now, "infrastructure", "new language support" and "enhancement" are all the same — i.e. yellow. Is there any idea behind that? I heavily prefer them to be very distinct, especially the infrastructure ones.

**Comment by arekbulski** [comment]
I figured that you are too busy with the important stuff, so I took the liberty of changing it on my own authority. I followed Construct in that regard, red is for bugs, yellow for anything like features and upgrades,  blue for general questions. There used to be a green for "requesting help/assissance" but I came to a conclusion that green would apply to all tickets.

**Comment by arekbulski** [comment]
I just changed those. How do you like it now?

**Comment by GreyCat** [comment]
The basic idea is that these 3 are fundamentally different, and using "green-yellow-red" indication that suggests severity and/or stages of solving the issue (like "red" = bad, there is a problem, "green" = solved) is generally a bad idea.

"New language support" is something that happens rarely, and these issues must stand out, as they tend to be very long and intense (like 100-200 comments, and lots of work). And "infrastructure" is different in a fact that it's not something that affects end users, but it's something that hinders us as developers.

I'll try to configure them a little bit differently.

**Comment by arekbulski** [comment]
Actually you got that wrong. Its not severity that defines those colors. I have "bug" tickets that are lower priority than "questions" or anything else for that matter. Your assumption was reasonable but wrong.

I simply like the colors, clean, bright, well colorful. Those that you had are just hurting my eyes. :face_with_head_bandage: 

That said, I agree that distinct colors would be a good thing. And I put your personal tastes over mine on this one. But maybe try some colors that are more... you know, lively?
