### ISSUE TITLE
Documentation updates remain uncommited

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#323]
There are 2 open PRs with plenty of documentation text, and we should sort it out before shipping 0.8. I am opening this Issue so that it doesnt get forgotten. 
- [ ] https://github.com/kaitai-io/kaitai_struct_doc/pull/7
- [ ] https://github.com/kaitai-io/kaitai_struct_doc/pull/5

I am asssigning @GreyCat because he seems to be the ultimate authority here and noone else will merge it on his own.

**Comment by arekbulski** [comment]
This is one of last 2 tickets before 0.8 is ready to ship. @GreyCat

**Comment by GreyCat** [comment]
I don't think it's actually a stopper for v0.8. Anyway, these documentation contributions refer to older sections. And, even if we're missing some docs for v0.8, probably it's still ok release and finish documentation later (as we don't ship it together with the compiler, we just update http://doc.kaitai.io).
