### ISSUE TITLE
adding people to developers team

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#324]
For your discretion @GreyCat, you may consider adding @Arlorean to developers team. I have no idea what one needs to do or how long to be part of this project to get listed there, but I guess its more like a mailinglist subsciption rather than a hall of fame? :) EDIT: I already got there yay!
https://github.com/orgs/kaitai-io/teams

**Comment by arekbulski** [comment]
@Arlorean In case you havent done that already, you could subscribe to CSharp repo ("Watch" button) to be notified of all new issues and PRs. I did that for Python and C# repos. You can depend on me to respond and solve new issues in those repos, when I am able.

**Comment by Arlorean** [comment]
Thanks. I’ve pressed the watch button on that repo now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GreyCat** [comment]
@arekbulski 
> I have no idea what one needs to do or how long to be part of this project to get listed there, but I guess its more like a mailinglist subsciption rather than a hall of fame?

It's actually simple: ["developers" team](https://github.com/orgs/kaitai-io/teams/developers) inside kaitai-io org gives r/w access to most repositories, including [main umbrella repository](http://github.com/kaitai-io/kaitai_struct/). This technically allows:

* push anything into any sensible part of project
* merge in PRs (coming from people outside of the team)
* run CI jobs (i.e. by updating submodules references and pushing a commit into main umbrella repository)

Running CI jobs is, unfortunately, risky, and so far I haven't found out any way to mitigate these risks. Travis CI has secret vars (with private access keys) set up in its variables, so it can push build test formats to [this repo](https://github.com/kaitai-io/ci_targets) and, potentially, "nightly build" packages to some package hosting. So it's normally handed out when a person needs that kind of access and understands the implications.

There's nothing like "one needs to do" anything, and there's nothing like a mailing list based on that GH team.

As far as I understand, @Arlorean might be interested in contributing more stuff to C# runtime. If ability to push code right into C# repository would be beneficial in some way, let me know — I'll add the access. However, note that there's at least few people caring about that repo (me, @koczkatamas, @LogicAndTrick, may be @arekbulski to some extent?), so normally even smaller changes would be better off peer reviewed, and thus submitted via the PR, even if one has the direct push access.

**Comment by arekbulski** [comment]
I thought that its something like hall of fame, nothing more than that. I stand wiser. 

You can consider me co-maintainer of Python runtime, am not interested in C# runtime myself. Its a language I am proficient in but did not use for like 8 years. I just took a look at it and pointed out few things. Thats it. If you need any major work on Python runtime in the future, let me know. If you gonna need C# work, I suggest asking others, but you can keep me in reserve.

**Comment by GreyCat** [comment]
Well, to be frank, runtimes itselves are pretty much static and they don't see much development. When something changes, that's like a 1-2 lines of new minor function or something, it's usually needed to be added to all runtimes, so it's usually me who's doing that ;)

There's only one runtime that needs lots of work invested into, and that's C++ — because of sheer amount of different environments and compilers and stuff like that. It's much-much-much easier on that account with C#, Ruby, Python, JS, etc, as there are much clearer and more stable standards.

**Comment by arekbulski** [comment]
How about you leave adding the C runtime to me, then? :grin:

**Comment by GreyCat** [comment]
Feel free to contribute :)

**Comment by arekbulski** [comment]
Just so you know, I am working on a MAJOR feature added to Construct (internal compilation for performance only). It will take about a month to finish it. Wont be available for major Kaitai work until then. But in meantime, I welcome  you to read this:
https://construct.readthedocs.io/en/latest/compilation.html

I am aware that KS opted to not use inlined code so compiled parsers are readable. I went the inline the shit out of it way, to squeeze performance out of it. And thats without Cython. 

Please read it and let me know what you think of it. :kissing_smiling_eyes:

**Comment by GreyCat** [comment]
Well, good luck, it looks like an interesting opportunity to explore ;)

> I am aware that KS opted to not use inlined code so compiled parsers are readable. I went the inline the shit out of it way, to squeeze performance out of it. And thats without Cython.

Manual inlining for compiled languages (like C++, C#, Java, etc) is pretty much pointless — the target language's compiler will do a much better job at it anyway. And, for script languages, usually more generic solutions exist, if you want aggressive inlining — i.e. something like [that](https://tomforb.es/automatically-inline-python-function-calls) for Python.

**Comment by arekbulski** [comment]
Very useful link, thank you! I will look into it, second thing I am considering is generating Cython code, which probably inlines as well, among other things.

**Comment by Arlorean** [comment]
I'm happy to have my code peer reviewed and not be on the full access developer list. No need to do anything special for me.

**Comment by arekbulski** [comment]
I use PRs, not commit directly to master, either. Buts its somewhat easier to operate on branches in same repo than forks.

**Comment by KOLANICH** [comment]
The good think about doing the things in own repo is that you can rewrite history and noone is harmed.

**Comment by arekbulski** [comment]
You can rebase/squash private branches just the same.

**Comment by KOLANICH** [comment]
I mean that you send PR, it is reviewed, then you do the changes, ```git commit --amend```, then ```git push --force``` and the pr is updated, but there is still a single commit, not multiple ones "added ..." -> "fixed according to review" -> "fixed according to review again"
