### ISSUE TITLE
unforking repositories

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#325]
Some repositories are forks of some external repos. This creates problems when submitting PRs. It would be better if those were unforked. Admin would need to contact GitHub support and ask them to effectuate it. 
- [x] https://github.com/kaitai-io/kaitai_struct_csharp_runtime

Procedure explained at
https://stackoverflow.com/a/44140289/2375119
When contacting staff, please mention to keep "fork forks" on our network.

**Comment by GreyCat** [comment]
Sent the request, thanks! I've never ever realized that it was possible.

**Comment by GreyCat** [comment]
Considered done, thanks again!
