### ISSUE TITLE
Support for LEB128 format as primitive type

### ISSUE THREAD

**Issue by hugsy** [kaitai-io/kaitai_struct#329]
Hi,

First of, thanks for `kaitai-struct`, it's a fantastic tool.

I am writing a parser for a format that uses [LEB128](https://en.wikipedia.org/wiki/LEB128) format (both signed and unsigned). Since the encoding/decoding of the values requires [a little bit of logic](https://en.wikipedia.org/wiki/LEB128#C-like_pseudo-code) maybe it would be cleaner to implement it as a primitive type in kaitai. I tried to implement it hackishly using value instances, but that didn't work.

I believe that would be a great extension (there is simply no tool out there that supports it), as it would allow to parse stuff like DWARF, WebAssembly and more.

Thanks.

**Comment by arekbulski** [comment]
Maybe its this one?
http://formats.kaitai.io/vlq_base128_le/index.html

**Comment by hugsy** [comment]
You just saved my day! Sorry about the RTFM fail ...

Thanks so much for this tool !
