### ISSUE TITLE
Mod operation consistency

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#33]
Regarding "positive mod" operation consistency. Unfortunately, many C-derived languages (including C++, Java, C# and PHP) do not feature "mod" operation, but instead use remainder calculation, which may result in negative answer. [Wikipedia article on modulo](https://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation) has comprehensive list of how languages behave here.

I'm strongly vouching to have consistent "positive mod" operation in KS, so here's a summary of what can be done:

* in Java - there is [Math.floorMod](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#floorMod-int-int-) which does exactly what we want — yet, unfortunately, it is available only since Java 8.
* in C++ - there seems to be no simple solution (SO people suggest macros, inline functions, etc)
* in JavaScript - [these](http://www.sitecrafting.com/blog/modulus-remainder/) [people](http://stackoverflow.com/questions/4467539/javascript-modulo-not-behaving) basically suggest that there's no ready-made function and propose to roll your own

Stuff to be investigated:

* in C#
* in PHP
* in Perl

**Comment by GreyCat** [comment]
For all languages that don't have internal support for this operation, it seems that adding a small static function (which can be auto-inlined and/or JIT-compiled) seems to be the best option so far. For consistency, I'm adding these as `KaitaiStream::mod(a, b)`

**Comment by GreyCat** [comment]
Current status:

- [x] C++
- [x] C#
- [ ] Java
- [ ] JavaScript
- [x] Perl
- [ ] PHP
- [x] Python
- [x] Ruby

**Comment by GreyCat** [comment]
@markbook2 Could you investigate what's the usual method to achieve positive mod in PHP? Shall we add a small function to PHP runtime as well?

**Comment by markbook2** [comment]
@GreyCat ok, I will investigate it and provide results later.

**Comment by markbook2** [comment]
floorMod for PHP:
```php
function floorMod(int $divident, int $divisor): int {
    return $divident - intdiv($divident, $divisor) * $divisor;
}
```

**Comment by markbook2** [comment]
Replaced the intdiv() with floor() in 2ae810c6cf526456c998c5b71f3ae3ac6977d14c, ExprModTest now passes.

**Comment by GreyCat** [comment]
Thanks! Looks like everything's finally done about this one.
