### ISSUE TITLE
Close https://github.com/kaitai-io/kaitai_struct_compiler/issues/

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#330]
https://github.com/kaitai-io/kaitai_struct_compiler/issues/
This issue tracker should be deprecated, all bugs either closed or moved here.

**Comment by arekbulski** [comment]
Could you ask GitHub support if its possible for them to move the tickets between repos?

**Comment by GreyCat** [comment]
I've seen that being asked before. The usual answer is "no". We can try, though, but there's still no good answer for that — i.e. links will become broken, etc.

**Comment by arekbulski** [comment]
There is a tool: https://github.com/holman/ama/issues/413#issuecomment-60070074

**Comment by arekbulski** [comment]
Should those have separate Issue trackers?
https://github.com/kaitai-io/kaitai_struct_shippable
https://github.com/kaitai-io/kaitai_struct_benchmarks  (tests repo doesnt)
https://github.com/kaitai-io/kaitai_struct_webide_docs
https://github.com/kaitai-io/kaitai_struct_examples
https://github.com/kaitai-io/webide-usercontent.kaitai.io
https://github.com/kaitai-io/edid.ksy

**Comment by koczkatamas** [comment]
I disabled on those which were created by me:
https://github.com/kaitai-io/kaitai_struct_webide_docs
https://github.com/kaitai-io/kaitai_struct_examples
https://github.com/kaitai-io/webide-usercontent.kaitai.io

**Comment by GreyCat** [comment]
I wish GitHub created projects with everything being disabled by default... Let's stick to the "not needed unless proven otherwise" rule? No issues, no Wiki, no projects, etc, etc.

**Comment by GreyCat** [comment]
Closed after transferring everything to main repo.
