### ISSUE TITLE
Last call for 0.8 critical issues

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#334]
@GreyCat Are there any issues left that are critical to 0.8 milestone and are not tagged? Just a quick survey. If you find any, assign someone to them, if possible.

**Comment by KOLANICH** [comment]
I guess broken ```pcap.ksy``` (I guess it wasn't broken somewhen, was it?) is a critical regression.

**Comment by arekbulski** [comment]
Could you open an Issue for that and mark it 0.8? We should have everything that is critical, be listed in the milestone page.

**Comment by GreyCat** [comment]
Closing this one, hopefully the list is finalized.
