### ISSUE TITLE
Make backward-compatible .deb packages, accepted by BinTray

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#336]
After recent sbt / sbt-native-packager updates, it turns out that BinTray does not accept the .deb packages build by our build process. Closer examination reveals that the problem is subtle change of .deb format, which evolved from traditional .tar.gz packing => .tar packing => .tar.xz packing. I've contacted BinTray support, and they've confirmed that they currently only support .tar.gz, and plans to support more formats are there, but these are pretty long-term goals.

For gory details, see `dpkg-buildpackage` and `dpkg-source` manpages (`-z` and `-Z` options). Large changes came around dpkg 1.15.5.

I've picked up dialogue at sbt-native-packager — https://github.com/sbt/sbt-native-packager/issues/1067 — hopefully I'll find enough stamina to fix eventually.

This is a blocker for v0.8, as we are currently unable to build .deb packages.

**Comment by GreyCat** [comment]
More or less closed the question for now by applying workaround suggested in https://github.com/sbt/sbt-native-packager/issues/1067#issuecomment-360738542. Would need to revisit and offer a proper patch for sbt-native-packager, but that's outside of scope of KS.

**Comment by cleary** [comment]
FYI this is on it's way to being resolved with dpkg 1.17.5ubuntu5.8

Link to source packages for testing follows:
https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627

**Comment by GreyCat** [comment]
It won't help this particular issue in any case: Bintray's problems come from their own custom implementation in Java, not from using an ancient dpkg.
