### ISSUE TITLE
Compiler produces circular imports in Python

### ISSUE THREAD

**Issue by AlexTalavari** [kaitai-io/kaitai_struct#337]
I am playing with the pcap.ksy and /network/ipv4_packet.ksy and /network/ipv6_packet.ksy reference each other which results in produced code with circular imports.

To fix it at the moment i merged both ipv4_packet.py and ipv6_packet.py under 1 file as ip_packet and the code runs.

This is both true for the code produced by the web IDE and the code provided ready to download in the gallery.

Proposed fix: merge of ipv4_packet.ksy with ipv6_packet.ksy into a new ip_packet.ksy

**Comment by GreyCat** [comment]
This actually looks like a Python's problem to me. All other languages are actually ok to deal with circular imports, see [ImportsCircularA at our CI](http://kaitai.io/ci/). Are there any better alternatives, instead of effectively punishing everyone else by disallowing circular imports? May be something could be done in a compiler to generate compliant code without circular imports exclusively for Python?

**Comment by GreyCat** [comment]
@KOLANICH So, basically, with this method you've proposed, we can replace all regular "imports" with this "guarded import", and we'll be ok?

**Comment by KOLANICH** [comment]
Don't know. The solution is just removes the exception. I don't know why a usual import raises an error, but internally it works the same way.

**Comment by GreyCat** [comment]
@AlexTalavari 
> Maybe an option to output all classes in a single .py file? that could fix circular dependencies.

That's a possibility, but, at the first glance, it would create more problems than it would solve. Right now we're close to how C or Java compilers work: you can take basically any single file or a set of files and recompile them. If we breach that contract, you lose ability to recompile things partiallly, and you basically always need to perfectly repeat the exact same command that you've used to get all set of the files in that target bundle. That looks pretty messy and error-prone.

**Comment by GreyCat** [comment]
@dgelessus has suggested that

>The circular import issue can probably be solved by using `import struct_name` instead of `from struct_name import StructName`. (This of course means that later on in the file you have to use qualified names like `struct_name.StructName` instead of just `StructName`, but since it's generated code I don't think it matters.)

Will try to check that out soon and see if it will fix things.

**Comment by GreyCat** [comment]
It really helped: https://github.com/kaitai-io/kaitai_struct_compiler/commit/c5639b74acc855e1c8077a04fdd884b3f21a4488

Thanks, @dgelessus!
