### ISSUE TITLE
Moderator discretion with removing posts

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#343]
I feel like I should explain myself, and at the same time, ask what are your guidelines and well, assumed etiquette. On Construct forum, there is noone but me to answer any questions, much less to moderate it. So if I see a post that includes long traceback (useless for CS), I just edit it out myself without asking. If I see a post that is obsolete or was just a chat, or notification of something, I just drop it without asking. In other words, I dont preserve who said what exactly, just maintain info on the topic, what is still important to whoever might read it in the future. 

I happened to kind of forget myself and deleted some one post in https://github.com/kaitai-io/kaitai_struct_formats/pull/14 . @GreyCat @koczkatamas @KOLANICH @LogicAndTrick  What do you think?

**Comment by KOLANICH** [comment]
I think that a one moderating must discuss that before taking any actions except some emergency cases. GitHub mechanism for moderation is very strange, after a post is deleted even the original author cannot see it and cannot even understand why that was deleted. Also IMHO moderation is evil.

**Comment by koczkatamas** [comment]
I was thinking about this myself. I think I will edit the top post (if I can) and put the list of relevant comment urls there or write a TL;DR if I have enough time.

Although I never tested this "method", nor have seen elsewhere.

**Comment by arekbulski** [comment]
Yeah, its true that Issues were not designed for this kind of moderation. But you have to understand, Issues were meant for Q&A (that is be relevant on the topic), not a chat. And we are so often using it for chat and notifications. 

Is editing typos acceptable? Kolanich just had "exit" instead of edit.

**Comment by KOLANICH** [comment]
Typos are acceptable, if I made a typo you can just point it to me, I'll edit it myself. But compromising integrity of the messages other than own in inacceptable in the cases except the emergent ones.

**Comment by arekbulski** [comment]
@koczkatamas You are kinda off topic :sweat_smile: on this. The one thing that this entire ruckus is about is some one-line offtopic comment that was in a PR from a year ago (January 2017). It wasnt a page long post summarizng a year-long discussion. I dont even remember what it was about, although admitedly there is no way of reverting it back to tell. 

To everyone: 
A hypotetical question. If someone posts a message in a PR before closing, its *entire* content being "looks fine", would it be acceptable to drop it at my discretion?

**Comment by koczkatamas** [comment]
Well, if you feel I answer an other question, not the one you asked, then please specify your question better.

First we talked about Issues, and I think I expressed my opinion on how various issue types should be handled IMHO, but now looks like we are talking about PRs?

I also stated my generic opinion on the topic in my previous comment: I would not edit other's posts. Especially if it's a one-liner, I don't think that bothers anyone.

**Comment by arekbulski** [comment]
Yeah okay, point taken. It seems that I was out of line, I wont do that again. Please consider the issue resolved and matter closed. :sweat:

**Comment by KOLANICH** [comment]
>A hypotetical question. If someone posts a message in a PR before closing, its entire content being "looks fine", would it be acceptable to drop it at my discretion?

IMHO it's not acceptable to do such things on own discretion. There must be a consensus in the community about every  moderators' action. Your having moderator's privileges doesn't mean that you are allowed to do ~~moderation~~censoring at own discretion.

**Comment by koczkatamas** [comment]
I would wait @GreyCat 's opinion on the matter (as for all matters) as he is not just the creator of the project, but he spends the most time on the project, he answers most of the questions, etc.

Our opinions does not / should not matter that much (at least compared to his) IMHO.

**Comment by GreyCat** [comment]
To be frank, I haven't even realized that adding simple "Write" permission on a repo automatically means that people can moderate (delete and edit) any comments in the project.

My idea of moderation is that it's only for emergencies: i.e. accidentally leaked passwords, removing hate speech, spam, unlawful content that we could be held liable for, etc.

I mostly agree with @koczkatamas that if we want to keep "short version" of something — it's usually better to *add* extra "TL;DR" explanation, than to *remove* half of a discussion, replacing it with a summary. People have actually said all these things and we've explored some other opportunities — even if we haven't agreed on them, storing discussions on unaccepted branches is still good.

> If someone posts a message in a PR before closing, its entire content being "looks fine", would it be acceptable to drop it at my discretion?

Definitely not. Someone has spent time and effort to review everything and say that it looks fine to him — and you're deleting his/her hard work. If it's one-liner, it doesn't mean that there was little work behind that one line — and you're effectively deleting all traces of that work.

**Comment by arekbulski** [comment]
I think you are missing the bigger picture:

Scope. Grey and Koczka, please remember that this topic is _only_ about posts like "thanks", not long summaries of long debates.  I would never touch those. You completely missed the point there.

Chatter. I already pointed out, and will point out once again, that in my mind Issues are meant for Q&A, rather than chat, even if its used for both. Expressing educated opinion and even just personal preference (as opposed to hard fact) is fine, I count those as more than relevant. But chatter like "thanks" and "your welcome" is not relevant, not even to the same 2 people who wrote it after a year or so, much less to everyone else. 

Comittee. If we need to create a new issue to debate in a comitee whever to remove those "thanks" and "your welcome" two posts, thats just wasting time. Even posting a third message, asking to remove the other 2, is a waste of time. On StackOverflow, comments under a submitted answer are moved out (linked) to a chat without asking. Those kinds of posts should be removed at discretion, if serving a larger good, like uncluttering long and hard-on-matter debates.

Property. I dont quite want to use this one as a justification, but let me just post it as food for thought. This is a public forum, for practical not legal purposes. I would not expect anyone to claim ownership over a "thanks" post, just like I would not expect anyone to claim ownership over a sticky note posted on a public wall. 

Misconstruding. Please note that misrepresenting someones opinion, is wrong whether you do that by editing someones post or by misquoting, or just saying what you know to not be true. This does not apply to the kind of posts that this topic is about. Despite Kolanich implications, I did not do that, not intend to, nor am talking about doing it. Also addressing GreyCat, if someone would say "looks fine" and by that meant "I carefully reviewed your PR and ran a test suite and benchmark on it, including spotchecks of X type of problems" then yeah, hard work would end up in the trash. But we have to treat what is being said by what it seems, out of sheer practicality.

**Comment by GreyCat** [comment]
I understand your concerns, but so far I think you're debating over a problem that doesn't exist, at least yet.

I understand why sites like StackOverflow tend to delete them, but personally I don't see much harm in "thanks", "you're welcome" etc, posts here. Right now, thinking about that and, or above that, "debating in a committee" is certainly wasting more of my or yours time that it would benefit the humanity for that post to be deleted and 10-20 people who would really read through it would spend 0.1s of their time scrolling through that.

I understand why it's important for sites where you get question + answer + 10000s of "thanks" from different people, and *that* really pollutes things, but that's clearly not an issue here.

This whole discussion already has eaten like 15-20 minutes of my time which I'd prefer spending on getting v0.8 out ;)

**Comment by arekbulski** [comment]
Agreed. :kissing_smiling_eyes: 

There is one related subtopic tho... 

Checkboxes. If a listed (checkable) items represent a state of the project for example, it would or might be implied that anyone can mark those as the state of the project changes. I would ask everyone to use those (and mentioning something like "feel free to update") when posting those. Its a post-facto self-reflection of a post I made here. https://github.com/kaitai-io/kaitai_struct/issues/330#issuecomment-362839461

**Comment by KOLANICH** [comment]
Again, checkboxes are good, but the bad thing about them is that changing them changes the messages, so compromises their integrity; how anyone can be sure that the one who changed a checkbox have not changed anything else? So you can use them, but please, edit only your own checkboxes, unless you are explicitly authorized to change them. May be it's better not to use checkboxes at all but to create a separate issue about each point.

**Comment by arekbulski** [comment]
Makes you think that you were serious about signing each of your posts with GPG key...

**Comment by GreyCat** [comment]
I'm kind of reluctant about checkboxes as well. It's very easy to mess up things, even by accidentally clicking (already happened to me several times, especially when using a touch screen mobile device). Given the lack of history of edits and anything, it could come as unpleasant suprise.

I guess it's ok to use them for tracking boring tedious tasks where it would save time (like these repos settings you've mentioned), but I'm just asking everyone to be careful around them and not do anything that might be ambiguous. If you change someone's checkboxes, just drop a quick line what you did and why (i.e. you've fixed some of the issues mentioned, etc).

**Comment by arekbulski** [comment]
Agreed.
