### ISSUE TITLE
Where are docs/apireference stored?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#345]
I need to edit http://doc.kaitai.io/ksy_reference.html but the https://github.com/kaitai-io/doc-kaitai-io.github.io repo seems to be a build output, not the source? @GreyCat please advise.

**Comment by koczkatamas** [comment]
https://github.com/kaitai-io/kaitai_struct_doc/blob/master/ksy_reference.adoc
