### ISSUE TITLE
kaitaistruct v0.8.0 not yet on PyPI

### ISSUE THREAD

**Issue by manuels** [kaitai-io/kaitai_struct#353]
I just notices that the latest version on PyPI is:

    pip search kaitai
    kaitaistruct (0.7)  - Kaitai Struct declarative parser generator for binary data: runtime library for Python
      INSTALLED: 0.7
      LATEST:    0.7

I guess you guys forgot to update it after the latest release ;)

**Comment by GreyCat** [comment]
Here we go, just uploaded new version: https://pypi.python.org/pypi/kaitaistruct
Thanks!

**Comment by manuels** [comment]
Damn, you're fast!
