### ISSUE TITLE
Problem reading large bit fields (IDE)

### ISSUE THREAD

**Issue by Asuranceturix** [kaitai-io/kaitai_struct#354]
Hi, I'm trying to parse a structure that contains a byte-aligned 6-byte substructure that is divided into 33-bit, 6-bit and 9-bit fields. When I try to parse it I get an error in the IDE (not with generated Python code):

Parse error: undefined
Call stack: undefined Error: readBitsInt: the maximum supported bit length is 32 (tried to read 33 bits)

**Comment by GreyCat** [comment]
I believe it's duplicate of #183? Let's continue discussion there.

**Comment by Asuranceturix** [comment]
Ok
