### ISSUE TITLE
using Kanban

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#359]
This isnt exactly a suggestion, rather sharing some experience. I added a [Kanban-style project](https://github.com/construct/construct/projects/3) to Construct (screenshot below) and have to admit, publicly, that I enjoy it. Its much easier to track the work with it, than with Issues, which I use for just work items, unline Kaitai where issues are for open and long discussions. Just something to talk about.

![zrzut ekranu z 2018-02-11 10-03-02](https://user-images.githubusercontent.com/5385838/36187139-73c8c416-1143-11e8-9f1b-12add9e578fc.png)

**Comment by KOLANICH** [comment]
>where issues are for open and long discussions

Please don't censor issues. AfaIk assigning issues to projects doesn't affect their visibility, do es it? So I guess there will be no harm from introducing it. But I have tried this kanban board in several my projects and I have not found it very useful. Projects are definitely a good feature, but I guess that if milestones were called "projects" they would have been used more extensively.

**Comment by arekbulski** [comment]
That is exactly what Projects are, a web representation of a physical board. And yes, you can have any issue assigned to more than one project and more than one milestone. The only drawback: moving between columns adds notification logs within the issue, so if you move it around too much, the thread gets polluted.
