### ISSUE TITLE
README: add installation info

### ISSUE THREAD

**Issue by tegob** [kaitai-io/kaitai_struct#36]
https://github.com/kaitai-io/kaitai_struct#downloading-and-installing seems to have download instructions but no installation instructions

**Comment by GreyCat** [comment]
Umm, these are supposed to be instructions for people who want to participate in development. Guide for "regular users" is at http://kaitai.io/#download

Do you think that it's a good idea to copy it to main repo's README as well?

**Comment by tegob** [comment]
> Do you think that it's a good idea to copy it to main repo's README as well?

Yes! It would’ve helped me, as apparently I was looking in the wrong place :)

--
Thanks for the quick response and for this wonderful project.

**Comment by GreyCat** [comment]
Ok, I'll see what I can do then :)
Thank you for trying it out ;)
