### ISSUE TITLE
Compiler version 0.8 doesn't build on Windows (10) with sbt.version = 1.1.0-RC4

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct#362]
The currently required version of `sbt` contains an [already reported bug](https://github.com/sbt/sbt/issues/3871) leading to a failed build in my Windows 10. While it has been reported for Windows 10 only, I'm pretty sure it affects all Windows because the underlying cause affects all Windows. The exact stacktrace I'm seeing [has been reported](https://github.com/sbt/sbt/issues/3871#issuecomment-363927103) already as well.

Two possible solutions, while the easiest is to simply use the following line in `build.properties` and use an older version of `sbt`:

> sbt.version = 1.0.0

This fixes the problem for me, the original old version `0.13.8` didn't work because of other build errors. The interesting question is why you used `1.1.0-RC4` at all, I don't have a non-Windows build to test if other platforms need a more current version for some reason.

If something newer than `1.0.0` is really required, things get tricky, because a snapshot release containing the fix needs to be used. Instructions can be found [here](https://github.com/sbt/sbt/issues/3871#issuecomment-357934384) and [here](https://github.com/sbt/sbt/issues/3871#issuecomment-366003491). That fixed the problem for me as well.

If you go for the snapshot release, in my opinion it would be great if you could provide the line `sbt-snapshots` of the file `repositories` in some project local configuration as well if possible. That file didn't exist in my setup by default and I needed some time to find the relevant docs to know what its minimal content needs to be.

**Comment by tschoening** [comment]
>If you go for the snapshot release, in my opinion it would be great if you could provide the line sbt-snapshots of the file repositories in some project local configuration as well if possible.

According to [some docs](https://alvinalexander.com/scala/how-configure-sbt-custom-repositories-resolvers) I've found adding the following line to `build.sbt` sounded possible, but it doesn't change anything in my test:

    resolvers += Resolver.sonatypeRepo("public")
    
    resolvers += "sbt-snapshots" at "https://dl.bintray.com/sbt/maven-snapshots"

That repo is not even mentioned as tested in the output, so I guess it's not recognized early enough or I'm doing something completely wrong.

**Comment by tschoening** [comment]
`sbt` `1.1.1` has been released already, I didn't noticed that. So switching to that version should be the best fix. I delete all local related caches, the mentioned file `repositories` and only used the following line in `build.properties` and that fixed the problem:

> sbt.version = 1.1.1

https://github.com/sbt/sbt/issues/3871#issuecomment-366052403

**Comment by GreyCat** [comment]
Cool, thanks, for the investigation! I'm not sure if it's related to particular build of Windows or what, but actually even 1.1.0-RC4 builds properly on Appveyor: https://ci.appveyor.com/project/GreyCat/kaitai-struct/build/1.0.452 — although note that it installs sbt first using `choco install` (which bootstraps 1.0.2), and then pulls 1.1.0-RC4 by the means of `build.properties`.

I've also tried to reproduce it on my local box, and it still worked — yeah, may be the problem was hidden by caches or something.

Of course, if 1.1.1 solves that, we'll upgrade to it promptly.

**Comment by tschoening** [comment]
> I've also tried to reproduce it on my local box, and it still worked[...]

Just out of interest, did you use Windows 10 as well? Maybe my assumption with older Windows was simply wrong. As this is fixed, I feel free to close this. Thanks!
