### ISSUE TITLE
Online visualizer / IDE

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#37]
The idea is to create a HTML/JS based online visualizer / IDE for parsing / visualizing binary formats on the web.

This could be extended to a fully fledged IDE where you can edit .ksy descriptors, compile them to different languages, etc.

**Comment by markbook2** [comment]
Please also think about more general case - IDE for RE. Then parser of binary formats can be its module.

Electron and TypeScript can be good choice, see [vscode](https://github.com/Microsoft/vscode), but it contains telemetry and probably other MS specific "features", which can be removed from there. Also check Electron itself for sending data to other third-parties.

Electron and [Scala.js](https://www.scala-js.org/) can be good choice too.

Another example - [LightTable](https://github.com/LightTable/LightTable)

An example of an application - [KeeWeb](https://github.com/keeweb/keeweb).

**Comment by GreyCat** [comment]
@markbook2 Ahem, isn't vscode just a fork of Atom, rebranded by Microsoft?

**Comment by LogicAndTrick** [comment]
@GreyCat No, but that's a common misconception. The only thing they share is the Electron shell.

**Comment by markbook2** [comment]
The all applications above are based on Electron, Electron is based on [brightray](https://github.com/electron/brightray), which in turn is based on [Chromium Content module](http://www.chromium.org/developers/content-module) wrapped as [libchromiumcontent](https://github.com/electron/libchromiumcontent).

**Comment by koczkatamas** [comment]
FYI: I started to create an "IDE" (more like a web-based visualizer) here: https://github.com/koczkatamas/kaitai_struct_webide

**Comment by koczkatamas** [comment]
One important note thought: please disregard any issue and bug report I create between Thursday and Sunday, because I am probably drunk as fuck. I am it's really embarrassing, but it's great effort from me to create this issue at least. I am really sorry, but that's we are us. But these are us, we have to drink to make us going, sorry for that. I am really hope you understand us, I will be myself from ~about Sunday again... maybe....

**Comment by koczkatamas** [comment]
I close this one as I think we achieved what we'd like to achieve at first.

Questions / suggestions should go https://github.com/koczkatamas/kaitai_struct_webide/issues .
