### ISSUE TITLE
Literal empty arrays

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#372]
Akin to #371, we also need to specify empty literal arrays sometimes. The problem is that right now we don't allow it because we can't derive array type.

Any ideas how to do it better?

**Comment by KOLANICH** [comment]
Empty arrays are empty, we cannot sample from them, so type doesn't really matters unless we append to them. So maybe treat them as a distinct type?

**Comment by GreyCat** [comment]
Ok, literal empty arrays seem to work properly now using casting syntax, already usable for KST purposes. Closing this one.
