### ISSUE TITLE
Handling bitwise NOT

### ISSUE THREAD

**Issue by 0xBEEEF** [kaitai-io/kaitai_struct#375]
I have a case here where I have to read an encrypted string from a file. This string is encrypted with XOR, but the key is different for each index. In C, the code for reading the string looks like this.

```
    for (unsigned char i = 0; i < length; ++i)
      string[i] ^= ~i;  // The XOR key goes down from 0xFF to 0x00. 
```

Unfortunately I didn't find an easy way to map it with the framework. Does anyone know another one to be able to map this case somehow? If possible, I would like to stay language-independent and avoid these custom classes.

**Comment by GreyCat** [comment]
Technically, you can do `process: xor([0xff, 0xfe, 0xfd, ... 0x00])`, as what you're describing is essentially a 256-byte long key.

**Comment by 0xBEEEF** [comment]
Okay, thanks for the answer. But I still have one question. Do I put the line from you now within a repeat loop, or can I use it directly for the type string? I want to get back an ASCII string in the end result. Is it better to have your own type, or should I use an instance?
