### ISSUE TITLE
What if seq has duplicated field names?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#381]
Construct export tool, in current implementation, creates a seq by renaming every unnamed field into "unnamed" which duplicates if there is more than one unnamed field. Is this a problem for Kaitai? I dont think it would be a problem for Python target, but static typed targets...

**Comment by KOLANICH** [comment]
1 the fields don't have to have id at all
2 duplicated names in seq are nkt allowed

**Comment by arekbulski** [comment]
Solution 1 solves it, thanks. Close it?

**Comment by KOLANICH** [comment]
As you like.
