### ISSUE TITLE
Webservers having working TLS having IP addresses resolved from formats.kaitai.io and other kaitai.io subdomains must be configured to use HSTS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#385]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Comment by GreyCat** [comment]
GitHub pages currently provides no means to do HSTS and supply a certificate with custom domain. The only way around it is to use CloudFlare / fly.io / similar CDN, which I'd prefer to avoid if at all possible.

I agree that current situation looks grim, but I don't see a way around it :(

**Comment by KOLANICH** [comment]
Wrote to GH support about it.

**Comment by GreyCat** [comment]
Thanks!

**Comment by KOLANICH** [comment]
Thay have said that they currently have no plans to implement it, but added `+1` into their backlog.

**Comment by GreyCat** [comment]
Thanks for the info and raising the voice! Can I also upvote it somehow?

**Comment by KOLANICH** [comment]
You can contact GH support about it.

**Comment by KOLANICH** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by GreyCat** [comment]
All kaitai.io domains powered by GH pages now have https support thanks to that GH offering. Considering this done and thus closing.
