### ISSUE TITLE
Style guide missing pad-right

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#388]
On the style guide, there is no pad-right?
http://doc.kaitai.io/ksy_style_guide.html#seq-attr

**Comment by cugu** [comment]
Duplicate of #152

**Comment by GreyCat** [comment]
Hmm, actually not exactly. This one is about "style guide", #152 is about "user guide", but I agree that both still need to be fixed...

**Comment by arekbulski** [comment]
If you would just tell me where in that list it should be, and I will add it.

**Comment by arekbulski** [comment]
I will update the docs and solve this issue.

**Comment by GreyCat** [comment]
Added `pad-right`, closing this issue.
