### ISSUE TITLE
Python runtime: stream seek

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#390]
Just leaving a note for myself to implement later. Second version uses only 1 syscall instead of 2 and also requires stream to be seekable but not tellable (if that makes a difference to anyone).
```py
self._io.seek(self._io.tell() - 1)
self._io.seek(-1, io.SEEK_CUR)
```

**Comment by GreyCat** [comment]
I don't think it would actually make much difference, at least on Linux. This is the [actual code that gets executed](https://code.woboq.org/userspace/glibc/libio/ioseekoff.c.html#31) when doing a `fseek(...)`, and it's not always leads to a `lseek` syscall, sometimes it would just shift an offset in a buffer. But you're right, if it *does* come to `lseek`, then `tell` + `seek` is actually two `lseek` calls.

**Comment by KOLANICH** [comment]
1 ```python
io.SEEK_SET is 0
io.SEEK_CUR is 1
io.SEEK_END is 2
```
2 
>A from_what value of 0 measures from the beginning of the file, 1 uses the current file position, and 2 uses the end of the file as the reference point. from_what can be omitted and defaults to 0, using the beginning of the file as the reference point.

**Comment by arekbulski** [comment]
Oops, sorry for the mistake. I fixed the top post.

**Comment by KOLANICH** [comment]
Why don't you use constants?

**Comment by arekbulski** [comment]
You are right, I edited the top post.
