### ISSUE TITLE
Encodings: black / grey / white list

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#393]
Following up https://github.com/kaitai-io/kaitai_struct/issues/391#issuecomment-376003487, the proposal is to:

- [ ] add a "white list" of encodings that are well-known, canonically named and are guaranteed to work in all languages
- [ ] add a "grey list" of encodings which are known to be aliases and non-canonical spellings; for these, ksc would map them into canonical names in all languages, and issue a warning to the user
- [ ] add a "black list" of encodings that should not be allowed; using these should break the build and clear error should be given to the user

For now we'll only do:

* `ascii`
* UTF family of encodings
* `iso-8859-xx` family of encodings, where `xx` is `[1..16]`
* `windows-12xx` family of encodings

A broader goal is #116 and there's a [relevant Google Spreadsheets table](https://docs.google.com/spreadsheets/d/1l87kGi9_U4Xrgaw2CGaTc9-_f5UEf1nf-68Dk_e1_iA/edit?usp=sharing).

**Comment by arekbulski** [comment]
What would be the status of UTF16/32? They are still not supported per #187 .

**Comment by generalmimon** [comment]
This is how we can look what unusual `encoding`s are used in the wild to get a better idea - [GitHub Search: `-org:kaitai-io extension:ksy "encoding" NOT "encoding: ascii" NOT "encoding: utf-8"`](https://github.com/search?p=7&q=-org%3Akaitai-io+extension%3Aksy+%22encoding%22+NOT+%22encoding%3A+ascii%22+NOT+%22encoding%3A+utf-8%22&type=Code)

**Comment by GreyCat** [comment]
Following @generalmimon's suggestion, here's the updated query which seem to work in 2023: https://github.com/search?q=-org%3Akaitai-io+path%3A*.ksy+%22encoding%3A%22+NOT+%22encoding%3A+ascii%22+NOT+%22encoding%3A+utf-8%22&type=code

**Comment by GreyCat** [comment]
Considering this implemented, at least it its first form. We've got a few encodings that we consider canonical, this list can be expanded further as and when necessary.
