### ISSUE TITLE
Python runtime: bytes comprehension

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#396]
I am too busy with other work so I am leaving this work item. I am implementing ProcessXor in Construct and found that this code
```py
        if PY2:
            return bytes(bytearray(v ^ key for v in bytearray(data)))
        else:
            return bytes(v ^ key for v in data)
```
could easily be
```py
            return bytes(v ^ key for v in data)
```
because bytes([1,2,3]) works on Python 2 as well.

**Comment by GreyCat** [comment]
@dgladkov did some benchmarks previously: https://github.com/kaitai-io/kaitai_struct_python_runtime/issues/8 and claimed that it was the optimal solution.

**Comment by arekbulski** [comment]
Okay, then I will withdraw this and focus on more important work.
