### ISSUE TITLE
Support "if" in "instances" with a value

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#4]
"if" is not implemented for calculated instances, but it probably should be:

http://stackoverflow.com/questions/38334665/kaitai-struct-calculated-instances-with-a-condition

**Comment by GreyCat** [comment]
[if_instances](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/if_instances.ksy) test now tests that. There are problems with C# - but that's not specific to this issue, that's about lack of distinction between "calculated" and "not (yet) calculated". Closing this one as solved.

**Comment by tempelmann** [comment]
I see that not working in 0.7 for C++. For instance:

`      - id: bar
        type: u4
        if: foo > 2
`

The test for foo is missing from the generated C++ class, so that all struct fields past this are shifted by this field unconditionally, making it simply not work right.

Shall I create a separate bug for this?
