### ISSUE TITLE
Python runtime: different methods vs single method implementation (process xor)

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#402]
When I was updating process_xor runtime, it occured to me that perhaps it would be better (idiomatic, not performance) to have a single method instead. It should be that method responsibility to detect if the key is a single byte and use an optimised code path, not the compiler. I would like @GreyCat to speak out on this issue, because when we get to implementing UTF16/32 strings, we will need some additional methods (read_bytes_term_multi and bytes_strip_right_multi) and I would like to know if that should also be preferred as different methods, or we should consolidate. 

```py
    @staticmethod
    def process_xor_one(data, key):
        if key == 0:
            return data

        if PY2:
            return bytes(bytearray(v ^ key for v in bytearray(data)))
        else:
            return bytes(v ^ key for v in data)

    @staticmethod
    def process_xor_many(data, key):
        if key == b'\x00' * len(key):
            return data

        if PY2:
            return bytes(bytearray(a ^ b for a, b in zip(bytearray(data), itertools.cycle(bytearray(key)))))
        else:
            return bytes(a ^ b for a, b in zip(data, itertools.cycle(key)))
```

**Comment by arekbulski** [comment]
I would like to point out that a tag that uses a seq field as key that happens to be bytearray of length 1 would not use the better (optimised) code since the optimisation happens (perhaps prematurly, ahem) in the compiler instead of the runtime.

**Comment by arekbulski** [comment]
Also what is supposed to happen if the key is a bytearray of length 0?

**Comment by GreyCat** [comment]
The general ideas here was to, indeed, provide better performance. Some languages (like Java) just provide 2 methods with the same name, distinguished by the argument types. Others require slightly different method names.

> Also what is supposed to happen if the key is a bytearray of length 0?

That's a good point! Let's add the test to check that and ensure it works properly in all runtimes and all combinations.

**Comment by arekbulski** [comment]
I suggest we define xoring with empty bytearray as to return unprocessed data. If you agree, I will update Python and C# runtimes accordingly, right away.

**Comment by KOLANICH** [comment]
Not sure that we should do it. Empty array kay mean "no key", so returning scrambled data as unscrambled makes no sense. I suggest to raise error.

**Comment by arekbulski** [comment]
The original topic is closed.
