### ISSUE TITLE
Python runtime: where is process zlib?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#405]
I dont see it anywhere in Python runtime. Is it not implemented?

**Comment by GreyCat** [comment]
Could you spend like 30 seconds and check it yourself? You don't even need to run anything, just clicking a few links at GH would lead you to [this line](https://github.com/kaitai-io/ci_targets/blob/master/compiled/python/zlib_with_header_78.py#L20).

**Comment by arekbulski** [comment]
Why didnt I think of doing that... second facepalm, double the shame. I appologise. :confused:
