### ISSUE TITLE
C#: automatic generation of a project file?

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#41]
While adding yet another test, I've finally got tired of adding all the required stuff manually to a C# project file, so I thought - why don't we just make some sort of `.csproj` file generator? From what I see now, it should just:

* take a template
* add `compiled/csharp/*.cs` stuff into second `Project/ItemGroup` in the following way:
```xml
    <Compile Include="..\..\..\compiled\csharp\ZlibWithHeader78.cs">
      <Link>compiled\ZlibWithHeader78.cs</Link>
    </Compile>
```
* add `tests/*.cs` to the same location in the following way:
```xml
    <Compile Include="tests\SpecZlibWithHeader78.cs" />
```
* add `src/*` to the third `Project/ItemGroup` in the following way:
```xml
    <None Include="..\..\..\src\zlib_with_header_78.bin">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Link>src\zlib_with_header_78.bin</Link>
    </None>
```

and, probably, that's all. Unless there is a simpler way to automate it, can I just hack some sort of quick script to generate this file? All our scripts so far are in either UNIX shell or Ruby — would it be ok to use it there as well?

**Comment by LogicAndTrick** [comment]
Now that partial compilation is supported by the test runner, it's probably possible to put the wildcard includes back into the project so it just includes everything in the folder. I'll give it a try.

**Comment by LogicAndTrick** [comment]
Ok that's done and it works in VS and CI. It failed on my Windows Bash shell but I assume it's something wrong with my environment because Travis isn't complaining.

**Comment by GreyCat** [comment]
Thanks! That was really fast :)
