### ISSUE TITLE
microsoft_pe.ksy - pe_signture

### ISSUE THREAD

**Issue by yuvaljacoby** [kaitai-io/kaitai_struct#417]
According to [pe documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx#signature__image_only_) at 0x3c we have a pointer to the pe header.

the .ksy file extract this field --> mz_placeholder.header_size.
so before reading the pe_signture (the ksy name for pe header) we should seek to that place.

Moreover, the mz2 field is not mandatory, there are valid pe executable with out that field.

Thanks,
y

**Comment by GreyCat** [comment]
Should be fixed with this commit: 
https://github.com/kaitai-io/kaitai_struct_formats/commit/2b34be329d2911b1b9f8c4c9166553bf3b5558f0. Please take a look.

**Comment by yuvaljacoby** [comment]
While you are there fixing stuff
In machine_type we need to add **arm64 = 43620** [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680547(v=vs.85).aspx#machine_types)

It's also possible to add alpha = 388, didn't find it in the documation only in some git projects [1](https://github.com/erocarrera/pefile/blob/master/pefile.py) [2](https://github.com/libyal/libexe/blob/master/documentation/Executable%20(EXE)%20file%20format.asciidoc)
