### ISSUE TITLE
Unified YAML parsing

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#42]
Given current situation with YAML libraries (there are no native Scala libraries, which could have compiled smoothing both to JVM and JS, and, in short notice, [natively](http://scala-native.readthedocs.io/en/latest/), and given that YAML is so weird and complex that it's infeasible to write our own YAML parsing library, I want to discuss another possible approach.

Raw SnakeYAML gives us Java `Object`, which is actually a conglomerate of `java.util.List`, `java.util.Map`, and simpler Java types (i.e. `Integer`, `Long`, `Double`, `String`). Passing objects from JavaScript gives us a ` scala.scalajs.js.Object`, which is actually also a conglomerate of simpler types, such as `js.Dictionary`, `js.Array`, etc. Note that once we've got the parsing in terms of these objects, all the "precious" information about line numbers / columns, etc, is already lost. You can't get anything from just a `java.util.List` with only objects.

What I want to propose is that we do:

1. Two relatively thin and generic layers that convert platform-specific YAML parser output (i.e. JVM or JS) into regular Scala primitives (`List`, `Map`, and primitive types). Actually, we don't really use any of the fancy YAML stuff, like custom serialization or anything, so it should be pretty simple.

2. Single manually written layer that converts data defined in terms of `List`/`Map` to our `*Spec` stuff (`ClassSpec`, `AttrSpec`, etc). Probably it should be implemented approximately the same as our current `create(...)` in companion objects work, but should just take raw `AnyRef` and cast it as it will see fit.

3. During this process, we'll push out some parsing exceptions (i.e. "certain key expected, but not found", "unknown key encountered", etc), and to make these error messages more meaningful, I propose to address them not by the line numbers, but by some sort of path inside YAML, i.e. something like `types/foo/seq/3/repeat-expr`. It is obviously worse than line numbers, but it's at least something helpful that we can do right now in our current situation with YAML parsers.

It can, in theory, allow us to solve problems like https://github.com/kaitai-io/kaitai_struct_compiler/issues/23 and https://github.com/kaitai-io/kaitai_struct_compiler/issues/22

What do you think about it?

**Comment by LogicAndTrick** [comment]
I like the idea of the extra layer of separation, and parsing errors are a good idea too. A few times I've made a typo in an instance or something and referenced a variable that doesn't exist, but I didn't get an error about it.

**Comment by GreyCat** [comment]
I've pushed everything in [unified-yaml branch](https://github.com/kaitai-io/kaitai_struct_compiler/tree/unified-yaml) - removed Jackson dependency as well, now we do just raw Snake YAML. Should work with both JVM and JS equally. Should have fixed https://github.com/kaitai-io/kaitai_struct_compiler/issues/23 and partially improved https://github.com/kaitai-io/kaitai_struct_compiler/issues/22 as well.

Please take a look and test heavily, especially the JS version.

**Comment by GreyCat** [comment]
Unified YAML parsing merged in.
