### ISSUE TITLE
--dot-net-namespace vs. --dotnet-namespace

### ISSUE THREAD

**Issue by tschoening** [kaitai-io/kaitai_struct#425]
I just tried to compile my KSY to C# and got the following error after following the docs:

	Error: Unknown option --dot-net-namespace
	kaitai-struct-compiler 0.9-SNAPSHOT
	Usage: kaitai-struct-compiler [options] <file>...

	[...]
	  --dotnet-namespace <namespace>
							   .NET Namespace (.NET only, default: Kaitai)

Looks like the user guide is wrong:

    Language-specific options:

    --dot-net-namespace <namespace> — .NET namespace (C# only, default: Kaitai)

http://doc.kaitai.io/user_guide.html#_desktop_console_version

**Comment by GreyCat** [comment]
Fixed in https://github.com/kaitai-io/kaitai_struct_doc/commit/224b52e2399b1ec7b770b7684f25d24a2ecef843, thanks!
