### ISSUE TITLE
read_u4le() does not provide values with precision

### ISSUE THREAD

**Issue by akaeme** [kaitai-io/kaitai_struct#431]
I was parsing pcap files, and due to the necessity to work with milliseconds, I needed to extract the packet's timestamp when it was captured. However, when the millisecond's values begin with zeros, the returned value omit them. For example:
1525114964.006586000: the result of pkt.ts_usec() = 6586
1525114964.014137000: the result of pkt.ts_usec() = 14137
I found that this function returns always a value with a length of 6 when there are no zeros on the left side, otherwise, it returns a 6 - number of zeros on the left.
In order to get the value with precision, I pad the value with zeros on the left:
Example in python:
str(6586).zfill(6) = 006586
str(14137).zfill(6) = 014137
I hope it helps you :)

**Comment by GreyCat** [comment]
`read_u4le` returns integer type. By definition, integer is just an integer, there's no way we can store leading zeroes in it or anything like that.

If you want to print out these values as decimal strings, there are plenty of ways to do that, but that's generally out of scope of KS. You've got one of the ways for Python. For many languages that support C-like printf templates, it's just a matter of doing something like `printf("%d.%06d", pkt.ts_sec, pkt.ts_usec)`.

Closing this one, feel free to reopen if you think that it warrants a discussion or you have any proposals / questions.
