### ISSUE TITLE
How to use KaitaiStruct to parse a very large file?

### ISSUE THREAD

**Issue by exaos** [kaitai-io/kaitai_struct#433]
I have some experiment data files which are very large (~10GB). I defined struct in kaitai struct, compiled into python code. The pc box will hang there when I tried to use it as the follow:
'''
from pixie16_bin import Pixie16Bin
data = Pixie16Bin.from_file(fn)
'''

How to use KaitaiStruct to parse very large files?

[pixie16_bin.ksy.txt](https://github.com/kaitai-io/kaitai_struct/files/1997287/pixie16_bin.ksy.txt)

**Comment by GreyCat** [comment]
From what I see in your file, your file is basically a very long list of `event_type` records. If you do `Pixie16Bin.from_file`, it loads *all* records at once into memory, representing them as array, and allows you to iterate over that array afterwards using `data.event`.

If you don't really need all records in memory at once, and you're ok with processing them one by one, for example, you can do something like that in your app code instead:

```python
from kaitaistruct import KaitaiStream
from pixie16_bin import Pixie16Bin
io = KaitaiStream(open(fn, 'rb'))
while not io.eof():
    ev = Pixie16Bin.EventType(io)
    # do something with individual event "ev"
```

**Comment by exaos** [comment]
Thanks a lot!

I tried `from_file(...)`, and the generated code works fine.

I tried the above code and encountered the following error:
```
In [4]: ev = Pixie16Bin.EventType(io)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8d3a2e3ea1c0> in <module>()
----> 1 ev = Pixie16Bin.EventType(io)

~/Laborejo/analysis/pixie-16/pixie16_bin.py in __init__(self, _io, _parent, _root)
     28             self._parent = _parent
     29             self._root = _root if _root else self
---> 30             self._read()
     31 
     32         def _read(self):

~/Laborejo/analysis/pixie-16/pixie16_bin.py in _read(self)
     33             self._raw_header = self._io.read_bytes(16)
     34             io = KaitaiStream(BytesIO(self._raw_header))
---> 35             self.header = self._root.PixieHeader(io, self, self._root)
     36             self.trace = [None] * (self.trace_len)
     37             for i in range(self.trace_len):

AttributeError: 'EventType' object has no attribute 'PixieHeader'
```

**Comment by GreyCat** [comment]
The easiest way to solve it here would be probably to just remove top-level type and move `event_type` to top-level. Then you can do just `ev = Pixie16Bin(io)` in the loop.

**Comment by exaos** [comment]
Sorry, I don't get it.

**Comment by exaos** [comment]
I know what is the problem. The correct reading should be like this:
```python
from kaitaistruct import KaitaiStream
from pixie16_bin import Pixie16Bin
io = KaitaiStream(open(fn, 'rb'))
while not io.eof():
    ev = Pixie16Bin.EventType(io, _root=Pixin16Bin)
    # do something with individual event "ev"
```
```
