### ISSUE TITLE
How do you parse bytes in Python / where is the library API at?  Not the YAML doc.

### ISSUE THREAD

**Issue by enjoysmath** [kaitai-io/kaitai_struct#437]
I want to parse EDID with KaitaiStruct because there is already an edid YAML in the format gallery.

Other than from_file() how can we parse bytes?

**Comment by GreyCat** [comment]
Please take a look at per-language pages in the gallery, for example, [this is description of parsing possibilities for C++/STL](http://formats.kaitai.io/edid/cpp_stl.html) or [parsing API for C#](http://formats.kaitai.io/edid/csharp.html), etc.
