### ISSUE TITLE
Using Compiler & Runtime with Raspberry Pi 3+

### ISSUE THREAD

**Issue by ronMilne** [kaitai-io/kaitai_struct#438]
Is there a detailed explanation available that clearly documents how one would go about getting Kaitai up and running. I have Kaitai being used on a windows platform that needs to send data to a PI. I was proposing that we define .ksy files then compile on the target platform.

**Comment by GreyCat** [comment]
I'm sorry, I don't think I quite understand you. All the documentation available so far is located at http://doc.kaitai.io/ — the user guide, per-language guides, etc.

Using compiler & runtime would be probably not that much different on Windows and on Raspberry Pi 3+ — i.e. the overall pattern is the same:

1. You make .ksy file
2. You compile .ksy to your target language
3. You use parser source file in your target language in a way you would have used it if you wrote the parser by hand.

If you have concrete question (i.e. something in particular is not clear or not working as expected, or you don't know how to proceed after doing certain steps) — please give more details about what exactly is the problem?

**Comment by ronMilne** [comment]
Ok to compile the ksy file on a pi is my problem. I'm running Raspbian with the target application being C++. The steps on the site for compiling on Debian are a little vague on how to achieve this on a PI.

**Comment by GreyCat** [comment]
If you want to *compile* a .ksy file on a PI, then you just need to proceed with "Download and install" instructions for Linux, i.e.:

```shell
# Install Java first
sudo apt-get install default-jre
# Install ksc
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 379CE192D401AB61
echo "deb https://dl.bintray.com/kaitai-io/debian jessie main" | sudo tee /etc/apt/sources.list.d/kaitai.list
sudo apt-get update
sudo apt-get install kaitai-struct-compiler
```

and then you can run ksc to compile .ksy into .cpp:

```shell
ksc your.ksy -t cpp
```

This yields .cpp and .h file. Then you (1) add these files, (2) add [these 4 files from Kaitai Struct C++ runtime](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/tree/master/kaitai) into your C++ project. For example, if you use CMake, you add these to the sources/headers list in CMakeLists.txt, if you use Makefile, you usually have a list of sources/headers file in Makefile there as well, if you use Autoconf/Automake, there is are list in AC_CONFIG_SRCDIR and AC_CONFIG_HEADERS in configure.ac, etc). After adding, you just rebuild your project, and, voila, you can use your parser.

The actual usage examples is available on every C++ page in formats gallery, for example, [this is example for EDID](http://formats.kaitai.io/edid/cpp_stl.html).

**Comment by GreyCat** [comment]
Closing this one due to inactivity. Feel free to reopen if any questions still remain.
