### ISSUE TITLE
EDID parser unable to parse extension blocks perhaps?

### ISSUE THREAD

**Issue by enjoysmath** [kaitai-io/kaitai_struct#440]
> OK ddc:read A 0
> 
> * ddc:read A 0 0x00 00:ff:ff:ff:ff:ff:ff:00:41:0c:01:00:01:01:01:01:01:10:01:03:80:40:24:78:0a:e6:92:a3:54:4a:99:26:0f:4a:4c:21:08:00:01:01:01:01:01:01:01:01:01:01:01:01:01:01:01:01:01:1d:80:d0:72:1c:16:20:10:2c:25:80:80:68:21:00:00:9e:64:19:00:40:41:00:26:30:18:88:36:00:90:2c:11:00:00:18:00:00:00:fc:00:50:68:69:6c:69:70:73:20:46:54:56:0a:20:00:00:00:fd:00:30:3e:0f:32:09:00:0a:20:20:20:20:20:20:01:8b
> 
> * ddc:read A 0 0x80 02:03:24:f0:4b:01:03:04:05:06:07:12:13:14:15:16:29:09:1f:07:15:07:50:19:07:86:83:01:00:00:65:03:0c:00:10:00:01:1d:80:18:71:1c:16:20:58:2c:25:00:80:68:21:00:00:9e:01:1d:00:bc:52:d0:1e:20:b8:28:55:40:80:68:21:00:00:1e:01:1d:00:72:51:d0:1e:20:6e:28:55:00:80:68:21:00:00:1e:8c:0a:d0:90:20:40:31:20:0c:40:55:00:80:68:21:00:00:18:8c:0a:d0:8a:20:e0:2d:10:10:3e:36:00:80:68:21:00:00:18:00:d1

That's what I'm trying to parse.  I've broken it into two Edid blocks using regexes and Kaitai Struct obviously doesn't like the second one since it doesn't start with the magic number.  However the first block byte 126 is 1 so I guess the second block is an extension block.  Any idea how to get the data sheet on that so that I can update the EDID definition?

**Comment by GreyCat** [comment]
Not really. May be [wikipedia](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#EIA/CEA-861_extension_block) might help?

**Comment by GreyCat** [comment]
Closing this one due to inactivity. Feel free to reopen if any questions still remain.
