### ISSUE TITLE
Migrate from ₲itHub

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#447]

**Comment by GreyCat** [comment]
No comments, no explanations, no rationale => closing as invalid.

**Comment by KOLANICH** [comment]
>closing as invalid

Completely OK.

**Comment by KOLANICH** [comment]
https://github.blog/2022-05-04-software-security-starts-with-the-developer-securing-developer-accounts-with-2fa/

**Comment by KOLANICH** [comment]
Today I got the notification:

> GitHub users are now required to enable two-factor authentication as an additional security measure. Your activity on GitHub includes you in this requirement. You will need to enable two-factor authentication on your account before October 06, 2023, or be restricted from account actions. 

If I have to migrate (I have no plans of enabling 2FA, it doesn't benefit me and benefits only M$, and M$ has decided it is OK to force users to do what they want) from GitHub, my KSF repo will likely be here: https://codeberg.org/KOLANICH-specs/kaitai_struct_formats .
