### ISSUE TITLE
formats.kaitai.io certificate has expired

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#455]
>formats.kaitai.io uses an invalid security certificate. The certificate expired on June 7, 2018, 6:41 PM.

**Comment by GreyCat** [comment]
I've tried to reset the certificate by removing the https support and re-adding it, as suggested in https://github.community/t5/GitHub-Pages/How-to-enable-https-support-on-custom-domains/td-p/6894

It looks like it's ok now?

**Comment by KOLANICH** [comment]
It does.
