### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by unxed** [kaitai-io/kaitai_struct#46]
Is it possible to add Rust language support to kaitai?
Thanks.

**Comment by GreyCat** [comment]
Take a look at #22, please :)

If you're willing to help - take a look at [this wiki page](https://github.com/kaitai-io/kaitai_struct/wiki/Adding-support-for-new-target-language) - it's possible to aid adding language support even if you don't know anything about Scala and/or compiler development.

**Comment by unxed** [comment]
thanks, will look there, so closing this as duplicate.

**Comment by GreyCat** [comment]
Feel free to reopen #22 then :)
