### ISSUE TITLE
A  script setting up KSC in CI

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#462]
```bash
#!/usr/bin/env bash
echo "TRAVIS is $TRAVIS"
if [ "$TRAVIS" = "true" ]; then
  SUDO="sudo";
else
  SUDO="";
fi;
echo "SUDO is $SUDO";
$SUDO apt-get update

if ! $($SUDO apt-get -y install gnupg-curl); then
  $SUDO apt-get -y install gnupg1-curl
fi;
$SUDO apt-get install -y apt-transport-https

echo "deb https://dl.bintray.com/kaitai-io/debian_unstable jessie main" | $SUDO tee /etc/apt/sources.list.d/kaitai.list
$SUDO apt-key adv --keyserver hkps://keyserver.ubuntu.com --recv 8756C4F765C9AC3CB6B85D62379CE192D401AB61
$SUDO apt-get update
$SUDO apt-get install kaitai-struct-compiler
export KAITAI_STRUCT_ROOT="/usr/share/kaitai-struct-compiler"
echo "KAITAI_STRUCT_ROOT=$KAITAI_STRUCT_ROOT" | $SUDO tee -a /etc/environment

if ! $(java -version); then
  $SUDO apt-get install -y default-jre-headless;
fi;

#git clone --depth=1 https://github.com/kaitai-io/kaitai_struct_formats.git "$KAITAI_STRUCT_ROOT/formats"
ksc --help
```

**Comment by GreyCat** [comment]
Um, what is it, and why do you suggest that?

**Comment by KOLANICH** [comment]
I already use it for building my packages wheels.

**Comment by KOLANICH** [comment]
>what is it

it `installs` the latest It is bleeding edge non-release version of KSC and sets the env varible for using with kaitaiStructCompile.

>why do you suggest that?

I guess it may be useful for someone. I personally use it for building wheels of my packages in GitLab CI.

**Comment by KOLANICH** [comment]
>Um, your target is clearly Ubuntu Trusy. 

Not quite. Trusty is the latest ubuntu on travis. On gitlab docker images are used and python:latest image is based on debian stretch. (pypy image is based on something ancient which doesn't even have msiutils)

>Why don't you just use unstable .deb build ­— https://bintray.com/kaitai-io/debian_unstable/kaitai-struct-compiler?

For now kautaiStructCompile assumes the folder structure where `bin` is a sibling of `formats` and `lib` and uses `KAITAI_STRUCT_ROOT` for all the paths. I will have to redo it somewhen, for example by using 3 env variables, and/or some autodiscovery code, but now I had no time for it, for now it seems for me to be simplier is to just unpack a windows build in some accessible folder and use it.

**Comment by KOLANICH** [comment]
Done

**Comment by KOLANICH** [comment]
Upgraded the script.

**Comment by KOLANICH** [comment]
@GreyCat,
>The repository 'https://dl.bintray.com/kaitai-io/debian_unstable jessie Release' is not signed.

**Comment by GreyCat** [comment]
Thanks, fixed!

**Comment by KOLANICH** [comment]
The repo is still without a signature (I don't see `Release.gpg` in `https://dl.bintray.com/kaitai-io/debian_unstable/dists/jessie/`).

**Comment by GreyCat** [comment]
Probably it will be generated after an update. I'll trigger one now.

**Comment by KOLANICH** [comment]
Appeared, works, thank you.

**Comment by KOLANICH** [comment]
Should we put this script to some repo?

**Comment by GreyCat** [comment]
I don't see much value in it. I mean, this is virtually the same download instructions from http://kaitai.io/#download — plus a few extra things related to Travis (which I'm not even sure that are required — for example, I'm sure that manual Java installation should be unnecessary with modern ksc packages).

For example, we have similar piece in formats repo: https://github.com/kaitai-io/kaitai_struct_formats/blob/master/.circleci/config.yml#L15-L26

**Comment by KOLANICH** [comment]
>I'm sure that manual Java installation should be unnecessary with modern ksc packages

I'm also sure that it should be unnecessary, but ... installing ksc package doesn't trigger installation of java, if it is not installed.  It may be intentional though.
