### ISSUE TITLE
Awesome Kaitai List

### ISSUE THREAD

**Issue by cugu** [kaitai-io/kaitai_struct#470]
I created an awesome kaitai list to create an overview of kaitai related projects

List: https://gist.github.com/cugu/ff0010c84c80cae1027e78fbefcc38c6

I would like to include that into the kaitai project. But where does it fit most? In the main repo? In the docs?

**Comment by koczkatamas** [comment]
For the WebIDE here is some "documentation": https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features , it uses some image files from the https://github.com/kaitai-io/kaitai_struct_webide_docs repo.

https://github.com/kaitai-io/webide-usercontent.kaitai.io is used for sandboxing purpose in the V2 WebIDE. It is a prevention against that somebody creates a malicious .ksy which causes XSS and steals your WebIDE data (eg. your files). Currently it is less severe but in V2 I planned Github integration, so it could steal your Github token too which would be a more severe security vulnerability. (Related: https://github.com/kaitai-io/kaitai_struct/issues/170)

**Comment by cugu** [comment]
I added the infos to the list, thanks!

**Comment by KOLANICH** [comment]
In my repo you can see some libs wrapping some formats parsers. And also an unfinished converter, but it is more closed to finished in my private branch not yet released.

**Comment by GreyCat** [comment]
@cugu Thanks a lot, this looks like a cool idea ;)

I'll try to review the contents in more detail a little bit later.

For the location, I see several choices:

* Main repo location => probably should migrate to full-fledged repository, as this is what people usually expect encountering awesome lists on Reddit, etc. It's relatively hard to do proper PRs using gists, which means that uncontrolled forks would commence, and it would be real pain in the ass to establish proper "central" version then.
* If you want to, we can migrate (or create that) as repo under kaitai-io organization. Probably creating that would be an easier way. Tell me if you'd want to proceed with that, and how we should name the repo.
* "Advertisting" the list is probably best done in the docs, as that's where people would likely want to find that, i.e. people are not usually interested in all these advanced details when they have no idea what Kaitai Struct is.
