### ISSUE TITLE
MachO format misuses requirement(s)/entitlements

### ISSUE THREAD

**Issue by strazzere** [kaitai-io/kaitai_struct#472]
In this blob, `entitlements` should actually be `requirements`;
https://github.com/kaitai-io/kaitai_struct_formats/blob/58f01e59c34d9a5c62afb39790858b7fa7e7db0b/executable/mach_o.ksy#L1212-L1236

In this blob, `entitlements` should then become `requirements`;
https://github.com/kaitai-io/kaitai_struct_formats/blob/58f01e59c34d9a5c62afb39790858b7fa7e7db0b/executable/mach_o.ksy#L966-L967

There seems to just be some transposing of words. In a macho structure you should have one "requirements" blob which references out to multiple requirement objects. There should also only be one entitlement blob, which is completely contained.

**Comment by koczkatamas** [comment]
I did not check what's the correct terminology, I don't really know, I just copy-pasted the current one from some documentation (probably not an official one), so I trust @strazzere 's decision on changing these names.

**Comment by GreyCat** [comment]
Done: https://github.com/kaitai-io/kaitai_struct_formats/commit/5f268d0367f9109e3e37cd104df44ebb552bc149

Please reopen if there are any concerns stil left it. Thanks!

**Comment by strazzere** [comment]
👍 LGTM, thanks! I never got back around to submitting a PR.
