### ISSUE TITLE
'kaitai-struct-compiler-0.8 -t python --opaque-types true' generate only one type import

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#480]
Moving from https://github.com/kaitai-io/kaitai_struct_compiler/issues/145, originally reported by @Oleh-Kravchenko:

> test.ksy have 3 opaque types, but generated test.py has import only for first type.
> 
> # Steps to reproduce
> 1. ``$ cat test.ksy``
> ```
> meta:
>   id: test
>   file-extension: test
>   endian: le
>   ks-opaque-types: true
> seq:
>   - id: t1
>     type: test1
>   - id: t2
>     type: test2
>   - id: t3
>     type: test3
> ```
> 2. ``$ ./kaitai-struct-compiler-0.8/bin/kaitai-struct-compiler -t python test.ksy``
> 3. ``$ cat test.py``
> ```
> # This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild
> 
> from pkg_resources import parse_version
> from kaitaistruct import __version__ as ks_version, KaitaiStruct, KaitaiStream, BytesIO
> 
> 
> if parse_version(ks_version) < parse_version('0.7'):
>     raise Exception("Incompatible Kaitai Struct Python API: 0.7 or later is required, but you have %s" % (ks_version))
> 
> from test1 import Test1
> class Test(KaitaiStruct):
>     def __init__(self, _io, _parent=None, _root=None):
>         self._io = _io
>         self._parent = _parent
>         self._root = _root if _root else self
>         self._read()
> 
>     def _read(self):
>         self.t1 = Test1(self._io)
>         self.t2 = Test2(self._io)
>         self.t3 = Test3(self._io)
> ```

**Comment by GreyCat** [comment]
This is indeed a strange behavior. Should be easy to fix, I'll try to take a look soon.

**Comment by generalmimon** [comment]
This is already fixed in the current compiler, so closing.

Test format:

```yaml
meta:
  id: opaque_external_type_multi
  ks-opaque-types: true
seq:
  - id: t1
    type: test1
  - id: t2
    type: test2
  - id: t3
    type: test3
```

Generated code:

```python
# This is a generated file! Please edit source .ksy file and use kaitai-struct-compiler to rebuild

from pkg_resources import parse_version
import kaitaistruct
from kaitaistruct import KaitaiStruct, KaitaiStream, BytesIO


if parse_version(kaitaistruct.__version__) < parse_version('0.9'):
    raise Exception("Incompatible Kaitai Struct Python API: 0.9 or later is required, but you have %s" % (kaitaistruct.__version__))

import test1
import test2
import test3
class OpaqueExternalTypeMulti(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        self._read()

    def _read(self):
        self.t1 = test1.Test1(self._io)
        self.t2 = test2.Test2(self._io)
        self.t3 = test3.Test3(self._io)



```
