### ISSUE TITLE
KSC Not Working With Java 10 JRE

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#483]
Original issue by @Saedeas at https://github.com/kaitai-io/kaitai_struct_compiler/issues/148:

> I believe this is actually an SBT error (see https://github.com/sbt/sbt-native-packager/issues/1145), but KSC should probably be changed to use the latest version of SBT that fixes this.
>
> The error is this message when I try to run KSC:
> 
> "The java installation you have is not up to date
> requires at least version 1.6+, you have
> version 10.0.2"
>
> Changing to the Java 8 JRE immediately fixes this.
> 
> Supposedly sbt-native-packager:1.3.3 and up has a fix for this issue (similar issue fixed in this repo by updating the version number https://github.com/mgifos/quick-plan/issues/27), so I suspect the fix is just changing line 3 in plugins.sbt from:
>
> addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.2")
> 
> to
> 
> addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.3")
>
> and confirming all the tests pass.

**Comment by GreyCat** [comment]
@Saedeas, I believe we've addressed this issue several months ago. I'm using Java 10 myself, and don't see any problems. Please confirm if you're having issues with latest unstable build or with stable release 0.8?

**Comment by Saedeas** [comment]
It's stable release 0.8 that I see the issue in. I can pull down the latest branch and see if the issue is fixed.  I'll get back to you.

**Comment by GreyCat** [comment]
Thanks! You can actually just install latest unstable builds:

* For Linux: https://bintray.com/kaitai-io/debian_unstable/kaitai-struct-compiler
* For Windows: https://ci.appveyor.com/project/GreyCat/kaitai-struct/build/artifacts

**Comment by Saedeas** [comment]
Huh, I'm still actually able to reproduce the error.

Version information for everything:

Downloaded this new KSC:
`kaitai-struct-compiler 0.9-SNAPSHOT347077819`

Ran this version of ksc successfully on this java version:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```


Switched to this version of java:
```
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)
```

Now any ksc command causes this error:
```

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

Please go to http://www.java.com/getjava/ and download

a valid Java Runtime and install before running .
```

**Comment by GreyCat** [comment]
Actually, my bad. The problem indeed still persists. And it looks like updating sbt-native-packager to 1.3.3 does not solve it.

**Comment by Saedeas** [comment]
Hmm one of the devs actually says 1.3.6 of sbt here: https://github.com/mgifos/quick-plan/issues/27

Maybe try that version instead?  If that doesn't fix it, it's probably a bug somewhere else.

**Comment by FilipDominec** [comment]
Bitten by this bug, too, on Ubuntu 18.04. A workaround for me is to use 

    kaitai-struct-compiler -no-version-check ...

**Comment by GreyCat** [comment]
@FilipDominec Please check if unstable build works for you?
https://bintray.com/kaitai-io/debian_unstable/kaitai-struct-compiler

**Comment by FilipDominec** [comment]
@GreyCat Yes, apparently it generates the parser without ``` -no-version-check``` and without complaints.

**Comment by GreyCat** [comment]
Good, then we consider this fixed and closed.

**Comment by glass-ships** [comment]
Hi, sorry to poke a closed issue, but I've encountered a similar issue and was wondering if Java is a hard dependency for kaitai? I've passed the no version check option but my KSC command won't run, even though cpp is the target language: 

```bash
[/home/josh/dev/dataReaderWriter/kaitai/simple_kaitai_example  (develop)]
><josh@detlap1> kaitai-struct-compiler -t cpp_stl --no-version-check ksy/animal.ksy                                                                                              (base)

No java installations was detected.
Please go to http://www.java.com/getjava/ and download
```

**Comment by KOLANICH** [comment]
Any modern JVM impl should work. GraalVM works fine.

**Comment by dgelessus** [comment]
@glass-ships kaitai-struct-compiler is written in Scala, which runs on the JVM, so you need to have a Java runtime installed to run the compiler. The taget language doesn't matter here, it's the compiler itself that needs a Java runtime.

The link in the error message isn't really useful on Linux by the way - you should use your distro's package manager to install a JRE, rather than downloading it from java.com. (Also, as of recently the Oracle JREs/JDKs from java.com have license restrictions regarding commercial usage. In practice these restrictions might not affect you, but to be safe I would avoid using Oracle's JRE. Your package manager will usually provide an OpenJDK-based JRE, which has no commercial use restrictions other than the regular GPL.)

**Comment by glass-ships** [comment]
Excellent, thank you both for the responses! I'll install a JVM and try again :)

**Comment by GreyCat** [comment]
> kaitai-struct-compiler is written in Scala, which runs on the JVM, so you need to have a Java runtime installed to run the compiler.

Technically, that's not really true. Scala works perfectly fine in JS environment as well, so this is that allows us to use ksc in WebIDE in a browser.

In theory, it's also possible to run ksc using node.js environment — however, we current lack proper command-line UI for that.

**Comment by glass-ships** [comment]
Thanks again, hope the holidays are going well!

So I've noticed that oracle JDK 9 is end of life, and 11+ requires an oracle account, but I'm having trouble finding instructions on installing another JVM - is GraalVM the recommended alternataive?

**Comment by GreyCat** [comment]
There's always free alternatives of OpenJDK-based JRE builds. We don't really test GraalVM (for example, in CI), although, as far as I remember, @KOLANICH experimented with it a little.

**Comment by glass-ships** [comment]
Gotcha that seems reasonable. 

So I've installed `openjdk-14-jre` and tried again, but I've managed to run into the same issue that's supposed to have been resolved:

```bash
[/home/josh/dev/dataReaderWriter/kaitai/simple_kaitai_example  (develop)]
><josh@detlap1> kaitai-struct-compiler -t cpp_stl --no-version-check ksy/animal.ksy                                                                                              (base)

The java installation you have is not up to date
requires at least version 1.6+, you have
version 14-ea
```
Can I ask what version has been confirmed to work, or if I've perhaps missed something along the way?

**Comment by GreyCat** [comment]
@glass-ships Which version of ksc you're using?

**Comment by glass-ships** [comment]
Excellent question; `kaitai-struct-compiler --version` returns the same error - is there another way to check?

**Comment by GreyCat** [comment]
You can try this workaround: https://github.com/kaitai-io/kaitai_struct/issues/483#issuecomment-435620063

**Comment by glass-ships** [comment]
Thanks GreyCat! Unfortunately, while the `--no-version-check` flag has worked around this in the past, the error is persisting. 

Is it possible that installing `openjdk-14-jre` didn't install some things correctly? (eg. does KSC require java 8 underneath, which maybe missing?)

**Comment by GreyCat** [comment]
Are you sure that you're using `-no-version-check`, and *not* the version with two dashes that you've specified in your post now?

**Comment by glass-ships** [comment]
Indeed, I've been copy-pasting directly from my terminal into the comment window. 

![image](https://user-images.githubusercontent.com/26975530/71495057-014f1c80-2809-11ea-9b21-d077e20c8270.png)

**Comment by dgelessus** [comment]
@glass-ships The option has to be written with a single dash (`-no-version-check`). If you use double dashes (`--no-version-check`) it won't be recognized.

Java 14 is not yet released - the version you've installed is a pre-release build and is likely to cause problems. As an end user it's best to stick with stable release versions of Java. Currently Java 13 is the latest release; if your package manager doesn't have that, you should use Java 11 or Java 8 instead (both are long-term support versions, so they are still updated even though they are no longer the newest version).

**Comment by glass-ships** [comment]
Aha, that does indeed check out! Thanks @dgelessus it seems to be working as expected now!! 

`openjdk-13-jre` (stable release) + `-no-version-check` (single dash) was the strat. 

My gratitude again for everyone's assistance!

**Comment by dgelessus** [comment]
OK, it seems that Ubuntu 19.10 (eoan) has OpenJDK 14 snapshot builds in its normal package repositories, which is a terrible idea IMHO (the package metadata doesn't mention at all that this is a pre-release version).

Interestingly, I can't reproduce the version check problem - even if I have `openjdk-14-jre` installed and force `ksc` to use it (`ksc -java-home /usr/lib/jvm/java-14-openjdk-amd64`), I don't get a Java version error.

@glass-ships If you're using Java 13, there should be no need for `-no-version-check`. If you still get a version error when using Java 13, that's definitely a bug with the launch script.

**Comment by glass-ships** [comment]
Oh that is interesting! I wonder if you might have separate installation of java 8 that it's silently referencing (vs. what gets packaged in openjdk). 

I tried omitting the `-no-version-check` flag with Java 13 installed and it still throws the error... Let me know if I can be of any use in debugging this!

**Comment by dgelessus** [comment]
@GreyCat I'm wondering if the Java version check in the launch script is useful at all. It uses Java 1.6 as the minimum version to check against, which is kind of pointless - the chances of finding a modern system with Java 1.5 or older are basically zero. Removing the Java version check would eliminate all false positives like this, with basically no negative effects.

@glass-ships Can you run `ksc -no-version-check --version` and post your ksc version number? Most likely your ksc installation just has an older launch script than mine, so it doesn't handle modern Java version numbers correctly.

**Comment by glass-ships** [comment]
sure thing! 
```bash
> kaitai-struct-compiler -no-version-check --version                                                                                                               (base)
kaitai-struct-compiler 0.8
```

**Comment by GreyCat** [comment]
> @GreyCat I'm wondering if the Java version check in the launch script is useful at all. It uses Java 1.6 as the minimum version to check against, which is kind of pointless - the chances of finding a modern system with Java 1.5 or older are basically zero. Removing the Java version check would eliminate all false positives like this, with basically no negative effects.

We actually don't supply this script, it's generated by sbt. I have no strong feelings for or against the check — it is kind of useful, but it was poorly implemented. Now everything should be fine.

What we really need to do is we need to get 0.9+ released, so people would not hit the same set of bugs that were discovered in 0.8 and fixed already...

```
> kaitai-struct-compiler -no-version-check --version
kaitai-struct-compiler 0.8
```

Ok, so it's nothing new: ksc 0.8 is known to be affected, if you'll upgrade to ksc 0.9+ unstable it should be gone.
