### ISSUE TITLE
KSY reference missing Bit-sized integers

### ISSUE THREAD

**Issue by brunchboy** [kaitai-io/kaitai_struct#495]
The User Guide has a Section 4.13 discussing Bit-sized integers, specified using, for example, `b1`, but this is not mentioned at all in the KSY reference.

**Comment by GreyCat** [comment]
KSY reference is, unfortunately, horribly out of date in many respects, and generally warrants a major overhaul — like rewriting it totally in some machine-readable form, such as YAML and/or JSON schema #47.

I'll try to update it at least in respect of mentioning `bX`.

**Comment by brunchboy** [comment]
Oops, thanks! 👍

**Comment by GreyCat** [comment]
Ok, here we go: http://doc.kaitai.io/ksy_reference.html#_bit_size_integers
