### ISSUE TITLE
suggesion -> suggestion

### ISSUE THREAD

**Issue by volo-zyko** [kaitai-io/kaitai_struct#498]
https://github.com/kaitai-io/kaitai_struct_compiler/blob/25fb1eee61d07bdc8b199445776836ce9a6606ef/shared/src/main/scala/io/kaitai/struct/format/YAMLParseException.scala#L44

**Comment by GreyCat** [comment]
Fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/cc373b2283e65810a315ec7488a6f288bb002f6e — thanks!
