### ISSUE TITLE
error on  compile swf.ksy, target is construct when has 'process'

### ISSUE THREAD

**Issue by zhao07** [kaitai-io/kaitai_struct#506]
when I compile the swf.ksy to construct,  I found it can't compile the ‘process’ into correct state, it says '???'
How to fix it?

**Comment by GreyCat** [comment]
Unfortunately, Construct author seem to have abandoned the project, and, facing that, it's unlikely that we'll ever complete Construct target for production purposes. If you feel like picking it up, you're most welcome to contribute implementation (telling me how it should look like would work too) ;)

**Comment by GreyCat** [comment]
The answer is given, closing this one. Please feel free to reopen if something's still not clear.
