### ISSUE TITLE
How to get the every pixel of pcx image ?

### ISSUE THREAD

**Issue by toplinuxsir** [kaitai-io/kaitai_struct#515]
How to iterate over every pixel of pcx image ?

Thanks !

**Comment by GreyCat** [comment]
Unfortunately, that's kind of outside of scope for Kaitai Struct. Getting pixel data for various formats typically requires uncompression of raw pixel data, and, while technically it might be possible to do so staying in Kaitai Struct, it's not really useful for practical purposes.

To achieve compression/uncompression that, we typically use `process: ...` routines — the catch is that you would need to (1) implement these algorithms in every supported language, (2) it's still "byte stream in = byte stream out", there is no universal way to address individual pixels afterwards.

(1) is now being sort of addressed in form of https://github.com/kaitai-io/kaitai_compress project — though note that PCX format exactly employs several (totally not complex, but still) compression schemes, and that project does not implement any of them at the moment.

(2) is being discussed around #188.

**Comment by GreyCat** [comment]
No discussion ensuing for 2 weeks, some answers and pointers were given, closing. Feel free to reopen if anything comes up again.
