### ISSUE TITLE
Incorrect example in GPT documentation

### ISSUE THREAD

**Issue by afrocheese** [kaitai-io/kaitai_struct#517]
https://formats.kaitai.io/gpt_partition_table/python.html

Contains the following sample code:

`data.sectorSize # => get sector size`

while the correct code should be

`data.sector_size # => get sector size`

**Comment by GreyCat** [comment]
Good catch, thanks!

**Comment by GreyCat** [comment]
Should be fixed now, will roll out in a few minutes. Thanks for attention to details again!
