### ISSUE TITLE
Make seq attribute IDs optional

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#52]
Yet another idea that might make reverse engineering jobs a little bit easier. In many cases, when you explore some format, you just don't know anything about certain values (at least yet), so you end up giving them some stupid names like `unknown`, `unknown2`, `junk`, `magic`, `something`, etc. Why not automate that? I.e.:

```yaml
seq:
  - type: u4
  - type: u1
  - size: 10
```

which would result in something like:

```java
this._unnamed0 = _io.readU4le();
this._unnamed1 = _io.readU1();
this._unnamed2 = _io.readBytes(10);
```

The names `_unnamedXXX` are assigned automatically during parsing. They are not supposed to be referenced anywhere and are there just for the sake of storing the data somewhere and displaying stuff in visualizers, until a reverse engineer can come up with a better name.

If anyone can think of a better name for `_unnamed` - feel free to suggest ;)

**Comment by hilts-vaughan** [comment]
`unknown` seems suitable.

**Comment by GreyCat** [comment]
Just implemented this feature. The basic "template" word for unnamed attributes so far is stored at https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/format/Identifier.scala#L20 and, as of now, is "unnamed" (but it's easy to fix that to whatever we want, if there's a consensus). In the majority of target languages, we're getting names like `_unnamedXXX`, where XXX is an index in the sequence (you obviously can't have unnamed instance attribute).

The only exception is C#, for which I've chosen to generate `Unnamed_XXX`, which should never clash with regularly generated stuff due to that special underscore in the middle. @LogicAndTrick, do you approve?

As for names, I don't really like "unknown", because, well, it's not really only for *unknown* fields, but generally for skipping some junk left from dumping raw C in-memory structures (i.e. alignment, etc), for "reserved" bytes, stuff like that. They are actually *known*, but just not worth to be named.

Anyone else interested in alternative names for "unnamed"? If the majority of people likes "unknown", it's fine by me. I don't like "unnamed" too much either, particularly because of the ugly visual clutter "unn*m" combination of letter creates. @koczkatamas? @markbook2? @mnakamura1337?

**Comment by markbook2** [comment]
I am fine with `unknown`, other possible alternatives:
* `noname1`, `noname2`, etc (or no_name1, no_name2, etc)
* or `random1`, `random2`, etc
* or `noid1`, `noid2`, etc (or no_id1, no_id2, etc)

**Comment by LogicAndTrick** [comment]
C# naming is okay for me. I'd almost go as far as to suggest that these fields should be dropped entirely after read rather than putting them into an `unknown` variable, but it doesn't really bother me either way. If the fields are unknown then you probably don't know the type anyway.

```yaml
seq:
  - id: something_useful
    type: u4
  - size: 20 # I will never care about this
```

```csharp
class Thing
{
    public uint SomethingUseful { get; set; }
    // Unknown field is not needed

    _parse(/* */) {
       SomethingUseful = stream.ReadU4();
       /* var unknown_1 = */ stream.ReadBytes(20);
    }
}
```

**Comment by GreyCat** [comment]
@LogicAndTrick Saving them (and even interpreting them as some proposed type) actually serves a very important function: you can view them in the visualizer. May be at first they won't make any sense (beyond seeing that it's a 4-byte long integer, for example), but at some moment later during reversing you might understand what it is - and, voila, all you have is to slap a name on it.

**Comment by LogicAndTrick** [comment]
Good point, perhaps they could be debug-only variables?

**Comment by GreyCat** [comment]
Um, maybe ;) Technically, you can even group them together and try to use some sort of `stream.Skip(xxx)` to avoid useless interpreting.

**Comment by mnakamura1337** [comment]
Thanks! Works like a charm. I have no opinion on particular naming, everything's fine by me. Another option is to just hide these generated names display in ksv - i.e. something like:

```
[-] foo = 123
[-] 456
[-] bar = 789
```

... and nobody would know whatever's there under the hood.
