### ISSUE TITLE
Unexpected FieldTypeEnum while parsing specific jpegs

### ISSUE THREAD

**Issue by rjt-gupta** [kaitai-io/kaitai_struct#523]
Hi! While parsing this [JPEG](https://img.lemde.fr/2018/10/09/0/56/4770/3180/184/122/60/0/2616eb7_ZEmpnu_LH1c1xeTNOJ5uM5uh.jpg) with mitmproxy.

Traceback I got:
`File "mitmproxy/contentviews/__init__.py", line 130, in get_content_view ERROR 
  File "mitmproxy/contentviews/auto.py", line 17, in __call__	ERROR 
  File "mitmproxy/contentviews/image/view.py", line 36, in __call__	ERROR			
  File "mitmproxy/contentviews/image/image_parser.py", line 78, in parse_jpeg	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 572, in ifd0	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 31, in __init__	ERROR			
  File "mitmproxy/contrib/kaitaistruct/exif_be.py", line 522, in __init__	ERROR			
  File "enum.py", line 291, in __call__	ERROR			
  File "enum.py", line 533, in __new__	ERROR			
  File "enum.py", line 546, in _missing_	ERROR
ValueError: 9 is not a valid FieldTypeEnum	ERROR`

I think the main issue lies [here](https://github.com/kaitai-io/kaitai_struct_formats/blob/8ab8aa21bacfba94e900d7f05f2e902fef6e95ab/image/exif_be.ksy#L54). An unexpected FieldTypeEnum 9 is generated and throws error when `field_type` gets updated.

Would be glad to make changes to fix this.

**Comment by GreyCat** [comment]
The core problem lies in a fact that Python enum implementation throws an exception on encountering of value not specified in enum. Majority of other languages just treat it as `null`, or `undefined`, or just keep a numeric value. To some extent, it's being mentioned in #300, but there is no Python-specifid bug. Let us consider this one to be like that.

There are 2 ways to solve that specific problem you're mentioning:

* Implement workaround for Python (probably add it to Python KS runtime + adjusting ksc output)
* Fix `exif_be` to actually include value for FieldTypeEnum 9.

**Comment by rjt-gupta** [comment]
Hi! Thanks for looking into this.
I think the second way would be the best solution but not sure what would be the value for FieldTypeEnum 9 that has to be added in exif_be.
What do you think?

**Comment by KOLANICH** [comment]
>Implement workaround for Python (probably add it to Python KS runtime + adjusting ksc output)

IMHO just a function returning either an `IntEnum` or just an integer is needed. And this behavior should be disableable. For example when debugging specs (usually I create a python script trying to parse all the files in a dir) a missing enum value means that I need something to be added.

**Comment by GreyCat** [comment]
JFYI, a similar thing already exists in Ruby runtime: https://github.com/kaitai-io/kaitai_struct_ruby_runtime/blob/master/lib/kaitai/struct/struct.rb#L478-L483

We just need similar one for Python.

**Comment by GreyCat** [comment]
Python-related problem fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/50394015ab013422c83298db118a6c06298dd261

New test is called "enum_invalid": http://kaitai.io/ci/ci.html

Eventually to be implemented for all languages.

**Comment by GreyCat** [comment]
Test passes for all languages. Please reopen if any problems still remain.
