### ISSUE TITLE
`contents`  broken for Go in latest released ksc v0.8

### ISSUE THREAD

**Issue by lannybroo** [kaitai-io/kaitai_struct#528]
Trying to compile a `.ksy` that has a fixed `contents` field using `ksc --target all` or `ksc --target go` fails due to some issue with the go compiler.

Example `broken_go.ksy`:

    meta:
      id: broken_go
    seq:
      - id: magic
        contents: [0x44, 0x42, 0x2F]

Compiler output:

    > ksc --version
    kaitai-struct-compiler 0.8
    > ksc --target go broken_go.ksy --verbose file
    parsing broken_go.ksy...
    reading broken_go.ksy...
    ... compiling it for go... 
    List(ArraySeq(IntNum(68), IntNum(66), IntNum(32))) (of class io.kaitai.struct.exprlang.Ast$expr$List)

**Comment by KOLANICH** [comment]
>kaitai-struct-compiler 0.8

Have you tried the unstable compiler?

**Comment by GreyCat** [comment]
golang support is still in relatively stages, even as of now in unstable version. [Latest CI report](http://kaitai.io/ci/) shows that it passes only 41% of tests, which is actually pretty bad, although your particular use case now passes (see `FixedContents` test).

Unfortunately, there's been pretty quiet in golang compiler's land lately: last few updates to #146 were done by me, and I'm probably the person least interested in golang, as I don't use it in my everyday's life, I don't have any experience with it, etc. @lannybroo, if you feeling like you could contribute something to golang support, you'd be most welcome.

**Comment by lannybroo** [comment]
Thanks for the link to the CI report -- I had not realized that go is essentially not ready yet. I'd love to contribute but also don't have a good background in go (more interest in Construct, however). Perhaps the right approach for golang is to not include go in the `ksc --all` command until it passes more useful percentage of the tests?

**Comment by GreyCat** [comment]
There is no `ksc --all` command. There is `ksc -t all`, which is 99.9% of time used for exactly for the purpose of these CI test runs — if we'll omit `go` from there, how would we test it?

Also, note that, unfortunately, @arekbulski stopped working on Construct: https://github.com/kaitai-io/kaitai_struct/issues/377#issuecomment-412343302, so most likely Construct target will be phased out in some time :(

**Comment by lannybroo** [comment]
Ah, I interpreted `ksc --target all` as the library's typical way of emitting trusted parsers for all of the supported languages once I have tested my `.ksy` in the language I happen to be developing with. As an end user of the library, I did not have the CI test run in mind.

**Comment by lannybroo** [comment]
Closing this issue. I don't know that there are actual actions to take (other than perhaps not including unsupported/incomplete languages when someone runs `ksc --target all`).

**Comment by GreyCat** [comment]
KS is still an project under development, and there's no clear distinction between "unsupported/incomplete" vs "supported/complete". We can probably mark up some languages as "officially good" if they pass 100% of the tests, but then probably only Java & Ruby will be passing up to that mark — all other languages will have some percentages lower than that. This might seem terrible, but in reality if test pass rate is 85-90%, it will be still useful for some (or even many) people. Even at 41%, I know that some people have reported some success with go target.
