### ISSUE TITLE
Which of the following parsing algorithms kaitai implement?

### ISSUE THREAD

**Issue by tinrodriguez8** [kaitai-io/kaitai_struct#529]
I couldn't find what are the algorithms implemented in kaitai.

Are LALR, LL or LR implemented in kaitai or is a different algorithm?

**Comment by KOLANICH** [comment]
None of them. There are no shifts and reduces in KS.

**Comment by GreyCat** [comment]
As @KOLANICH has noted, Kaitai Struct has nothing to do with traditional parsing theory/algorithms: it does not really has a concept of state beyond the position in the file and execution pointer in generated code, it does not really do any rollbacks and re-parsing, etc.

Closing now, as the answer was given. Please feel free to reopen if you have any additional questions.

**Comment by dgutson** [comment]
Is there any documentation on the parsing algorithm, such as an internals doc?
