### ISSUE TITLE
Problem parsing a buffer containing data from JPEG image

### ISSUE THREAD

**Issue by maurisanfilippo** [kaitai-io/kaitai_struct#532]
Sorry if this is not the right place to ask this, but I did not find how to create issues on the https://github.com/kaitai-io/kaitai_struct_formats repo

The thing is that I think that probably the JPEG parser present on the gallery is not working well.
I need to parse a buffer which is contained inside another buffer with any kind of content, i.e., the JPEG file is embedded, and I have to be able to find where it starts and ends. It is important to note that I have the same problem even with pure jpeg files. Btw, I'm working in python

For this task, the flow is more or less the following:

- find JPEG signature in the bigger buffer
- if signature found, try to parse content of the buffer with the jpeg module

so far, so good.

Looking at the segments read by the module, I realized that the last segment is not the EOI segment (End of Image), but the SOS segment (Start of Scan).
So, in one hand, the parser doesn't recognize where the image ends, and in the other hand, all the bytes from the buffer are consumed and loaded into the image_data attribute of the segment object.

Any idea why is this happening? Or am I misunderstanding something? I think it probably has to do with the declaration of this format, but I'm not sure.

I could do this with GIF and PNG images by reading the rest of the bytes from the buffer (lets say the "rest"), and getting a sub-buffer from the signature until the position where the "rest" starts. But as I said before, the JPEG parser consumes all the bytes, so there are no more bytes to read after parsing the buffer.

**Comment by GreyCat** [comment]
As far as I remember, jpeg.ksy on encountering SOS marker believes that everything that lies beyond that marker until the end of stream is the image data. It works ok for most use cases, but probably not yours.

Unfortunately, I'm not aware of simple way to learn of image data size without fully decoding JPEG blocks stream. This [SO question](https://stackoverflow.com/questions/26715684/parsing-jpeg-sos-marker) has some answers with suggestions, but these are also not 100% fool-proof, and it's not very easy to implement these in KS.

#530 might be actually slightly relevant, but, again, not implemented at this time.

For practical purposes, you might be interested in [removing these lines](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/image/jpeg.ksy#L38-L40) and implementing one the skipping / parsing algorithms in your application.

**Comment by GreyCat** [comment]
BTW, there is https://github.com/kaitai-io/kaitai_struct/issues/158, which discussed exactly this issue with JPEGs. I'm suggesting to close this one and continue the discussion there.
