### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by heinrich5991** [kaitai-io/kaitai_struct#541]
Are you aware of projects tackling a similar problem?

Reading your [FAQ](http://doc.kaitai.io/faq.html), I can only find language-specific competitors for declaratively parsing binary formats. Is that correct? :)

**Comment by GreyCat** [comment]
[Awesome Kaitai](https://github.com/kaitai-io/awesome-kaitai) lists certain similar projects.

**Comment by GreyCat** [comment]
Some answer is provided, no discussion ensued so far. Please feel free to reopen if you'd want to continue discussion.

**Comment by heinrich5991** [comment]
Thanks for the answer. :)

No follow-up questions so far.
