### ISSUE TITLE
Deconstruct old CI pipeline

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#550]
Moving forward to [our new shiny CI](https://ci.kaitai.io/), we don't really need [our old monolithic sequential pipeline](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/ci-all).

It already gives wrong impressions that we're relying on it, and it already slows down new pipeline doing lots of stuff in vain.

The plan:

- [x] Remove per-language support from [main project's .travis.yml](https://github.com/kaitai-io/kaitai_struct/blob/master/.travis.yml)
- [x] Remove [ci-all](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/ci-all)-related machinery from tests repo
- [x] Remove [aggregated HTML page renderer](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/aggregate/aggregate)
- [ ] Update developer docs to show overall scheme of new CI

Cc @13rac1

**Comment by GreyCat** [comment]
High-level overview documentation delivered: http://doc.kaitai.io/ci.html

Hopefully one day I'll get to write it in more detail.

**Comment by KOLANICH** [comment]
Why there is no `formats.kaitai.io` in the graph?

**Comment by GreyCat** [comment]
> Why there is no `formats.kaitai.io` in the graph?

It's a separate pipeline, not really related to the main one: http://doc.kaitai.io/ci.html#_formats_gallery

From the beginning, I thought it would be a good idea to depict whole set of repos and jobs, but after some tries, I found out that it quickly becomes a very dense chart which will be super scary and not very useful for demonstration purposes. So, I've deliberately simplified it as much as I could and dropped all aux pipelines from "overview".

> It also may make sense to paint websites rectangles into another color, for example pink.

Good idea.
