### ISSUE TITLE
Make "import-path" more compatible regarding "File.pathSeparator".

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct#557]
The script `build-formats` of the tests-repo contains the following line:

> -I "$FORMATS_REPO_DIR:$FORMATS_KSY_DIR/ks_path" \

Notice the usage of `:` as path separator, as it is standard on Unix-like systems. I'm using Windows with Git Bash to run the tests and that works, except for things relying on `import-path`. The problem is that Java gets started in the end and uses `;` as `File.pathSeparator`, because the currently running OS still is Windows. As a result, everything forwarded using the line above is assumed to be one path and breaks path handling of Java and the compiler can't find imported types and such.

> 18:57:07,9853337	java.exe	16768	CreateFile	C:\C\Program Files (x86)\kaitai_struct\formats:formats\ks_path\for_abs_imports\imported_and_abs.ksy	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

Changing the line to use `;` instead and everything seems to work as expected. Therefore I suggest making the following code of the compiler a bit more compatible with environments like mine, so that not all callers need to keep this in mind and deal with such differences. Else I would ask you how to handle this in the tests-repo as well... ;-)

      val importPathExample = List("<directory>", "<directory>", "...").mkString(File.pathSeparator)
      opt[String]('I', "import-path") valueName(importPathExample) action { (x, c) =>
        c.copy(importPaths = c.importPaths ++ x.split(File.pathSeparatorChar))
      } text(".ksy library search path(s) for imports (see also KSPATH env variable)")

I see two options: Add support for providing `import-path` more than once, which in my opinion would be the best thing to do. OTOH, checking if `:` is used and splitting on that or splitting on `File.pathSeparatorChar` as is. While `:` on Windows is allowed for Alternate Data Streams in general, using it that way in this concrete context doesn't make any sense, so should be safe to assume it's the separator char.

Any opinions?

**Comment by GreyCat** [comment]
Tottaly ok with implementing multiple `--import-path` as proper cross-platform solution. Your solution seems to be merged in, I'll run the CI pipeline to check that everything's fine.
