### ISSUE TITLE
KaitaiStream is abstract?

### ISSUE THREAD

**Issue by cgivre** [kaitai-io/kaitai_struct#565]
I've been trying out Kaitai Structs and it looks very impressive.  However, I'm getting an error:

I copied the code directly from your site:
```
DnsPacket data = new DnsPacket(new KaitaiStream(dns_bytes));
```
However, when I try to build this, I get the following error:

```
java:[53,77] error: KaitaiStream is abstract; cannot be instantiated
```
I'm not a great Java developer, but it seems like this should work.  Any suggestions?
I am using Kaitai version 0.8.

**Comment by GreyCat** [comment]
Hmm, good catch, thanks for reporting it. Actually, code samples on https://formats.kaitai.io for Java seem to be outdated. Currently there are two implementations of KaitaiStream. You can try

```java
DnsPacket data = new DnsPacket(new ByteBufferKaitaiStream(dns_bytes));
```

**Comment by cgivre** [comment]
Thanks for the help! Just another suggestion, as a n00b Java person, it would be really helpful as well if you included the imports for a maven or gradle project.  It took me quite a while to figure out what exactly had to be included as a dependency.

**Comment by GreyCat** [comment]
> it would be really helpful as well if you included the imports for a maven or gradle project. 

Does http://doc.kaitai.io/lang_java.html#_installation answer that question?

**Comment by cgivre** [comment]
Yes it does.  Thanks!  Should I close this ticket?

**Comment by GreyCat** [comment]
I'll fix the formats intro generation and will close it.

**Comment by GreyCat** [comment]
Actually, that second question raises a more complex concern: looks like it's not obvious that runtime should be installed before using this format, and people tends to miss runtime installation docs. I wonder what would be the best way to expose it, without adding too much scary boilerplate in these format usage intros...

**Comment by GreyCat** [comment]
Forked that "more complex concern" in separate issue #571. This one is resolved.
