### ISSUE TITLE
the same type in several ksy files

### ISSUE THREAD

**Issue by swex** [kaitai-io/kaitai_struct#57]
Sorry if I missed but I can't find any information about sharing types information between different files. Is possible is there any examples?

**Comment by GreyCat** [comment]
To some extent, yes. Basically, you just have N several .ksy files, you can compile them separately (or all together — that's all the same, compiler will treat each one as independent file). You can see the example of such practice with a chain of [networking formats](https://github.com/kaitai-io/kaitai_struct_formats/tree/master/network). `pcap` → `ethernet_frame` → `ipv4_packet` → ..., etc.

If compiler encounters a type with unknown name, it will treat it as "opaque" type, probably specified in some other ksy file at the top level.

**Comment by GreyCat** [comment]
Closing this question. Feel free to reopen if you need more info.
