### ISSUE TITLE
application field accepts string list

### ISSUE THREAD

**Issue by flanfly** [kaitai-io/kaitai_struct#570]
Hi.
According to the [reference](https://doc.kaitai.io/ksy_reference.html#meta) the `application` field of `meta` is a single (optional) string, but some ksy files (i.e. `fasttracker_xm_module.ksy`) specify a sequence of strings.

Does it make sense to send a PR to doc-kaitai-io.github.io correcting this to something like this:
> - Contents: a string or an array of strings
> 
> - Purpose: free-form text strings that describe applications that are associated with this particular format, if it’s a format used by some applications
> 
> - Influences: nothing
> 
> - Mandatory: no

**Comment by GreyCat** [comment]
Cc @dar2355 

@flanfly: Thanks for reporting it!

We'll be likely retiring text reference soon in favor of formal [ksy schema](https://github.com/kaitai-io/ksy_schema).

Current modus operandi of "application" is indeed allowing both a single string and/or a list of strings. https://github.com/kaitai-io/ksy_schema/blob/master/ksy_schema.json#L48-L56 actually shows that.

**Comment by generalmimon** [comment]
> We'll be likely retiring text reference soon in favor of formal [ksy schema](https://github.com/kaitai-io/ksy_schema).

We've already done that by now (see https://github.com/kaitai-io/kaitai_struct_doc/pull/42). The replacement for the KSY reference is https://doc.kaitai.io/ksy_diagram.html, which is directly backed by https://github.com/kaitai-io/ksy_schema. As @GreyCat mentioned, `meta/application` is described correctly [in `ksy_schema.json`](https://github.com/kaitai-io/ksy_schema/blob/a43a946159415dfa9b4f9306e174606b61c963cf/ksy_schema.json#L104-L112), so there's nothing more to do in this issue.
