### ISSUE TITLE
Instances generating invalid Java code

### ISSUE THREAD

**Issue by antiquechrono** [kaitai-io/kaitai_struct#574]
The following ksy file generates invalid Java code.
[test.txt](https://github.com/kaitai-io/kaitai_struct/files/3132282/test.txt)

This code is outside the for loop that gets generated so it doesn't compile as the i variable hasn't been defined yet.

 this._io.seek(fileOffsets().get((int) i));

Compiler version is 0.8

**Comment by GreyCat** [comment]
Might be related: https://github.com/kaitai-io/kaitai_struct/issues/281
Likely a duplicate: https://github.com/kaitai-io/kaitai_struct/issues/436

**Comment by antiquechrono** [comment]
Yeah it looks like this is a duplicate of #436 , I even did this because the docs show it as a valid ksy.

**Comment by GreyCat** [comment]
Thanks for confirming! Let's continue the discussion in #436 then :)
