### ISSUE TITLE
Adding support for awkward-array library, best approach?

### ISSUE THREAD

**Issue by GabriellaNicoleRamirez** [kaitai-io/kaitai_struct#589]
Good afternoon everyone,

I am trying to see if I can add support for Python's awkward array library, and I was wondering if you have any pointers for when it comes to implementing it? The main reason I am seeking to implement this is because the project I am working on handles hundreds of thousands of data points and parsing through an array can only go so fast. In addition to this, other parts of my data can be implemented in a jagged array, something that awkward array can handle.

At the moment, I am unsure if I should seek to add to the Python support and add awkward-array as a dependency or if I should (or even could) implement it as a separate language.

Any help would be greatly appreciated, thanks!

**Comment by GabriellaNicoleRamirez** [comment]
Thanks for getting back to me.

I don't necessarily want to replace standard python arrays, rather, I intend to add support for the `awkward array` library.

The data I'm working with can have holes in it and we want to be able to--instead of manually formatting a standard python array--automatically be able to define the size of an array when the data is not in a fixed format. That is, if we are missing some entries. From my understanding, awkward array supports such data sets.

Either way, my project manager thinks awkward array will be a good fit for our data and she wants me to see if I can implement support for it. I can look into implementing it as a separate language, similar to the `construct` library, as @KOLANICH suggested.

**Comment by GreyCat** [comment]
> The data I'm working with can have holes in it and we want to be able to--instead of manually formatting a standard python array--automatically be able to define the size of an array when the data is not in a fixed format. That is, if we are missing some entries.

Um, this does not make it much clearer, honestly. Can you explain, what exactly does it mean:

> The data I'm working with

By "the data" do you mean binary representation in stream, or representation in memory?

> That is, if we are missing some entries.

Ok, if you mean "representation in stream", then can you provide an example of hex dump that illustrates "missing entries", as I can't imagine one? If you mean "representation in memory", ok, this kind of makes sense, but I still can't imagine how data in stream will look like — i.e. it would be some kind of special serialization format that skips missing entries, or something like that?

> The type of data structure we're dealing with when using standard python arrays can be found in the second cell of this jupyter notebook.

@GabriellaNicoleRamirez, you assume that I (or somebody around Kaitai team) is familiar with certain things, but at least for me — I'm totally ignorant about it:

* I have pretty vague idea of what "jupyter notebook" is,
* What is a "second cell" in it.

Later you show some Python code, which uses `numpy.array`, which I also only have pretty vague general idea about.

Further below, you use `awkward.Table.fromrec` and `awkward.JaggedArray.fromcounts` — again, I have no idea what it does and given almost non-existent documentation of these, I'm not very much inclined to dig deeper just to understand what is going on.

**Comment by GabriellaNicoleRamirez** [comment]
Sorry about that, I'm fairly new to the project and I'm trying to figure it out myself.

Yes, it is binary data and I'll post an example of it.

Sorry for the confusion, I'll regroup with my project manager and see if I can get a clearer understanding, then get back to you.

**Comment by pibion** [comment]
What we're interested in doing is essentially adding a new language support to Kaitai.  The existing python compiler represents data as python objects, and analyzing > 1 GB data sets goes a bit slowly with that data structure.

We'd like to make a Kaitai compiler that instead targets the awkward-array data structure (https://github.com/scikit-hep/awkward-array/blob/master/README.rst, as @GreyCat pointed out).  This data structure is nice for the kind of data we usually look at, which is array-like but often has variable-length arrays.

(I think the variable length of the arrays is what @GabriellaNicoleRamirez refers to as missing entries.)

Right now awkward-array reads in a fixed set of file formats, but we're hoping that making a Kaitai compiler will let anyone in the nuclear physics/custom binary science data make use of awkward-array's nice query times.

We've started by looking at the documentation for adding a new language, and we wanted to reach out and check that that's the sensible documentation to start with.  I'm also wondering if any of our work could be of use to the project - like filling in some of the "add a new language" TODOs.

Apologies in advance if the GitHub issues isn't the right channel for this discussion!

**Comment by GabriellaNicoleRamirez** [comment]
Thanks @pibion for explaining a bit more. Since this really isn't an issue--more like an announcement of adding support--I'll go ahead and close this issue and utilize the existing documentation for adding support for a new language.

If any issues come up, I'll be sure to open a new thread and get feedback.

Thanks!
