### ISSUE TITLE
ksc: Python zlib decompression failure on certain files

### ISSUE THREAD

**Issue by doesthisusername** [kaitai-io/kaitai_struct#594]
Hi, hopefully this is the right place to post this issue.

It seems that some files will trigger a `zlib.error: Error -5 while decompressing data: incomplete or truncated stream` error at runtime, when using `zlib.decompress(data)` by itself.

I first found this when attempting to decompress a 3 MB (6 MB decompressed) file outside of Kaitai. It then appears that other people have had the same issue: [SO](https://stackoverflow.com/questions/32367005/zlib-error-error-5-while-decompressing-data-incomplete-or-truncated-stream-in)

I fixed it by using this instead:
```python
zobj = zlib.decompressobj()
dec_data = zobj.decompress(data)
dec_data += zobj.flush()
```

Then, I attempted to write a `.ksy` file for the format, and after compiling, it triggered the exact same error.
Inspecting the generated code: `self._raw_dec_toc = zlib.decompress(self._raw__raw_dec_toc)`
(also not sure where the extra \_raw\_ came from, maybe the way I wrote the format is wonky)

When I manually changed the generated code to follow my above fix, it worked properly.

Note that, I do not know if this is the "proper" fix, nor do I know what causes specific files to fail the regular `zlib.decompress()` like this. I also tried a 1 GB file, which worked fine.

My zlib version is 1.2.11.

Thanks.

**Comment by KOLANICH** [comment]
Please keep in mind that `kaitaistruct.compress` is not very stable. I have a better design in mind, allowing to pass args influencing compression and decompression, but haven't managed to find time to finish improvement of it yet.

**Comment by GreyCat** [comment]
@doesthisusername Can you provide an example of file that fails decompression with current Python implementation? This way we can probably add a test and see if other implementation are affected as well.

@KOLANICH If you mean [this kaitai_compress](https://github.com/kaitai-io/kaitai_compress), then I don't think that the issue that @doesthisusername has reported has anything to do with it (although it *is* probably quicker to fix it there ;))

**Comment by doesthisusername** [comment]
@GreyCat It would seem that the cause (in this case) is the lack of an ending Adler-32 checksum in the file.
If I recompress the file after decompressing it with my "solution", a single byte partway through the file has changed (likely a stream marker of some sort), as well as the trailer changing from `00 00 00 FF FF` to `C8 3B 26 73`.
This is basically the exact same thing as is happening [here](https://stackoverflow.com/questions/1372659/zlib-decompression-failing).

So it would seem that this is indeed an invalid zlib stream. Sadly I can't control my input file (to fix it permanently on my end), nor do I think I can share it here. I can try to create an example if needed, though.

**Comment by GreyCat** [comment]
Then probably implementing a custom compressor would be the way to go here. [kaitai_compress](https://github.com/kaitai-io/kaitai_compress) project actually aims to collect popular compression algorithm bindings as .

What I can propose is to add "raw zlib" (or "raw deflate"), i.e. without a header & footer and call it from there.

For reference, current Python implementations look like these: https://github.com/kaitai-io/kaitai_compress/blob/master/python/kaitai/compress/zlib.py

**Comment by doesthisusername** [comment]
I'll have a look at that, thanks! That does seem to be the best option.
Feel free to close if you want (not sure how this stuff works).
