### ISSUE TITLE
Partial compilation for C#

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#6]
Normal CIs work assuming that at the very least, the project is compiling: normally, no one commits stupid syntax errors.

However, it's not exactly the case with Kaitai Struct tests: it's normal course of development to have some generated sources, and only *some* of them would compile correctly. And even only *some* of the sources compile, it's still worthwhile to try testing them. There are high chance that the rest would pass.

I've implemented this thing I call "partial compilation" for Java - see [run-java](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/run-java). The general idea is very crude, but it works: first it tries to compile all the sources together, if it fails, it tries to compile files one-by-one.

It's worth to implement the similar build scheme for any compilable language (i.e. C#, C++, Java). The general overview is as follows:

1. `run-$LANG` compiles language runtime; if this fails, the rest is abandoned, it's a fatal error
2. `run-$LANG` tries to compile format classes generated by KS compiler; it requires only the source of the class itself + runtime (which is already compiled at step 1); if anything fails, it's not a fatal error and we proceed, trying to keep as many format classes compiled as possible;
3. `run-$LANG` tries to compile test specs; there is 1 test spec file per 1 test; if anything fails, we just abandon failed file and try to continue with the rest
4. `run-$LANG` runs tests (obviously, only those that compiled successfully)
5. `aggregate/aggregate` later parses results of steps 1-4 and outputs distinct statuses like "spec build failed" and "format build failed", to give an idea of what's broken

For steps 2 and 3 we keep a list of files failed to build in `test_out/$LANG/build.fails` and detailed compilation error logs in `test_out/$LANG/compile_log/$FILE.log` - these are used for aggregation and display of errors at http://kaitai.io/ci/

Is it possible somehow to do that for C#?

**Comment by LogicAndTrick** [comment]
.NET needs a project file to build, which adds an extra layer of complexity when doing dynamic stuff like this. It should be possible in some form.

Right now I can think of a few options:

- Create a project for each test case and build each test case as a separate project
    - Projects are plain XML so they could be auto-generated by the test runner
    - Easiest to understand, but messy
- Use .NET Core instead of Mono and use the [roslyn](https://github.com/dotnet/roslyn) compilers to check each file compiles - it it doesn't, remove it from the test build
    - .NET Core is very young technology - 1.0 released only a few weeks ago
    - However .NET Core is the future of cross-platform .NET, so it's a good option to consider switching to
- Dynamically load the classes and use the Roslyn compiler service to compile each test case
    - Not viable right now as the Roslyn scripting library only runs on .NET full (Windows only)
    - Could potentially be possible if the Roslyn scripting API becomes available on .NET Core

**Comment by GreyCat** [comment]
Is possible to somehow compile & run files manually, one by one? I see that mono includes `mcs` - a one-shot compiler. What is .NET equivalent of Java's `.class` (compiled bytecode for a class)? Is it possible to compile .cs into separate bytecode files and then run whatever's compiled there?

**Comment by LogicAndTrick** [comment]
There's no intermediate class format, it would go straight to an executable. It is possible to compile each test case to a separate DLL to achieve a similar result, though. Ideally I'd like a solution that would work with all .NET platforms (specifically .NET Core), but I will check out Mono's `mcs` if the other options don't work out.

**Comment by GreyCat** [comment]
Ok, thanks. Anyway, it's not a top priority task, so if probably it's better to spend time on porting more tests to C# and fixing the ksy-to-cs compiler. Current single project model still works, but you need to add tests manually one-by-one, as they become available.
