### ISSUE TITLE
wav decoding failed using example .ksy file

### ISSUE THREAD

**Issue by axet** [kaitai-io/kaitai_struct#604]
When I load file using 'media/wav.ksy' files I got following error:

Parse error: undefined
Call stack: undefined KaitaiEOFError: requested 243712 bytes, but only 243711 bytes available

**Comment by GreyCat** [comment]
1. Are you sure that the file you're trying to load is not corrupted?
2. If you are, and you can share that file, please share it, so we can take a look.

**Comment by axet** [comment]
1. It is almost ok, file produced by android LineageOS recorder app (it may be not 100% fit to standard)
2. https://drive.google.com/open?id=1w581FwDrG3eFHQRNnalbs1he-gNaqBMR

I report this, because error very user unfriendly.

**Comment by generalmimon** [comment]
Fixed in https://github.com/kaitai-io/kaitai_struct_formats/commit/002a5e55f1769c225a3d4304fbf8c30db7d34776
