### ISSUE TITLE
Is there a way to define throw/raise exception in ksy? 

### ISSUE THREAD

**Issue by jaroslaw-wieczorek** [kaitai-io/kaitai_struct#607]
Hi, 
I create dnp3 protocol parser and I need throw or raise defined exception like e.g. 'This object is not supported' when I get objecet id, that is not implemented yet.

Is it possible to define exceptions in ksy?

**Comment by dgelessus** [comment]
You could define an `enum` for your object ID and list all IDs that you currently support. Then when the parser encounters an unknown ID, it will automatically throw an exception.

There is also another issue (#435) that suggests a validation mechanism to throw exceptions when a field doesn't match certain conditions. This has been partially implemented, but I think at the moment it doesn't help with your use case.

**Comment by jaroslaw-wieczorek** [comment]
Okey, thanks for response :)
