### ISSUE TITLE
[Q] switch-on a binary string

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#614]
How to `switch-on` a binary (without any encoding) string?

**Comment by GreyCat** [comment]
There is no magic in switching, but you need to know to specify byte array literals. Something like this should work:

```
type:
  switch-on: foo
  cases:
    '[0, 0, 1, 2]': case_1
    '[0xff, 0xff, 7, 8]': case_2
```

**Comment by KOLANICH** [comment]
Thanks. Though I have already forgotten for which spec I needed it.

**Comment by generalmimon** [comment]
Closing as resolved.
