### ISSUE TITLE
How to identify a values original ksy type (e.g. u2) after parsing?

### ISSUE THREAD

**Issue by karlpeterhugo** [kaitai-io/kaitai_struct#615]
I would like to parse binaries and write the decoded data structured form and annotate the exact original type of a variable, such as `name="foo", value="42", type="u2"`.

E.g. when using generated python code, the parsed `foo` would be of type integer.
How to access the information about its original type as a 16 bit unsigned int?

Extended scope of question: 
* How do visualizers, such as ksy, which annotate the byte position of each value in the hex-dump, extract this size and position information of values?
* Do they implement an complete parser for ksy language itself or is there some basis libraries to reuse?

Thank you

**Comment by KOLANICH** [comment]
0. AFIK integer type cannot be detected at least for python and JS.
1. You can detect it size and position using `_debug`. You neec to call KSC with `--read-pos`.
2. IDK. KS is just YAML with some additional rules. It is possible to both parse it oneself and to reuse the internal repr by KSC.

**Comment by karlpeterhugo** [comment]
Thank you!

**Comment by GreyCat** [comment]
@KOLANICH's answer is correct, just wanted to add some more clarity.

> How to access the information about its original type as a 16 bit unsigned int?
> How do visualizers, such as ksy, which annotate the byte position of each value in the hex-dump, extract this size and position information of values?

It is impossible to access type information right now, and none of existing vis tools uses that. All existing vis tools use `ksc --debug` compiling mode, which enables recording of positions of objects in the stream in `_debug` array (or equivalent of thereof), and enables more forgiving error handling.

If you really need that, I don't see why we can't add that to `_debug` info too, but please elaborate more why would you need that in your scenario?

> Do they implement an complete parser for ksy language itself or is there some basis libraries to reuse?

All vis tools just run ksc with debug mode on, and use its result in its code.

**Comment by GreyCat** [comment]
Looks like the answer was given, closing this one. Feel free to reopen if anything else still persists.

**Comment by KOLANICH** [comment]
Related: #898
