### ISSUE TITLE
Delete .ksy repositories

### ISSUE THREAD

**Issue by cugu** [kaitai-io/kaitai_struct#622]
Can the .ksy repositories be deleted?

- [edid.ksy](https://github.com/kaitai-io/edid.ksy)
- [windows_resource_file.ksy](https://github.com/kaitai-io/windows_resource_file.ksy)
- [dicom.ksy](https://github.com/kaitai-io/dicom.ksy)
- [java_bytecode.ksy](https://github.com/kaitai-io/java_bytecode.ksy)

The first three repositories are part of [kaitai_struct_formats](https://github.com/kaitai-io/kaitai_struct_formats). java_bytecode.ksy could be included there as well.

**Comment by GreyCat** [comment]
No, these repositories are part of ["big formats" model](https://github.com/kaitai-io/kaitai_struct/issues/165) repos. Current idea is that they are being developed in these .ksy repos and being mirrored to [kaitai_struct_formats](https://github.com/kaitai-io/kaitai_struct_formats) from time to time.

**Comment by dgelessus** [comment]
> Current idea is that they are being developed in these .ksy repos and being mirrored to kaitai_struct_formats from time to time.

I don't think this is documented anywhere (or if it is, it's not very obvious IMHO). Maybe this should be pointed out in the KSF repo somewhere? Or alternatively, would it be a good idea to use Git submodules to pull in the "big formats" repos into KSF? I think that would be clearer than manually copying specs from the separate repos into KSF.

**Comment by GreyCat** [comment]
I agree, it's not documented, while it should be. OTOH, whole formats repo is not very well documented, frankly.

Originally, the idea was to connect them using `meta/xref` links to point to one "canonical" repo for every such instance. This way, some formats in formats repo can be picked as "featured" or something like that, provided that there's a good backing repository with solid set of tests behind it, etc.

Using git submodules is also a pretty interesting idea. Essentially, it's the same thing, but built using existing git technologies, not reinventing the wheel. If everyone's ok with that, I'll proceed with modifying it like that.

**Comment by KOLANICH** [comment]
Submodules are OK if a format is big enough to occupy a whole dir, like the one used in xgboost. But IMHO if a format is a single file, it should be in ksf.

**Comment by cugu** [comment]
I like the submodules idea as well. I'll adjust the issue.

**Comment by cugu** [comment]
See #623
