### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#63]
I think that we should supply binary packages. This can be done using Travis CI.
1 Build binary packages in Travis CI. They are built anyway, all what you need is to package build results into packages.
2 Upload them into repos' [Releases](https://github.com/kaitai-io/kaitai_struct/releases) and anywhere else using [the Travis feature to supply private data in encrypted form](https://docs.travis-ci.com/user/encrypting-files/).

**Comment by GreyCat** [comment]
Um, we already have binaries published for releases at BinTray (see downloads links from our website), and we publish all unstable .msi builds as AppVeyor artifacts. The only thing I can think of is publishing unstable .zip / .deb artifacts — you mean that?

**Comment by KOLANICH** [comment]
>and we publish all unstable .msi builds as AppVeyor artifacts.
It's nice! I guess linux users can just unpack an msi to get a jar file. It even may be better to just supply a jar file since it doesn't require installation.

Please add [the link](https://ci.appveyor.com/project/GreyCat/kaitai-struct/build/artifacts to download section of the website.

**Comment by GreyCat** [comment]
> It's nice! I guess linux users can just unpack the msi to get the jar file.

So far, none of the Linux users complained — I guess `git clone` + `sbt stage` is something that average Linux user can do. But point taken, there are plans to publish .zip + .deb artifacts as well that I'll publish soon in #62.

> It even may be better to just supply a jar file since it doesn't require installation.

We don't build fat jars, and kaitai_struct.jar alone is not enough to work properly on an average system.

> Please add the link to the download section of the website.

Um, what exactly is missing?

![download_msi](https://cloud.githubusercontent.com/assets/157154/21076113/5a2efb36-bf34-11e6-99d9-3d7460ae7f4c.png)

**Comment by KOLANICH** [comment]
>Um, what exactly is missing?

Links in Universal .zip and Linux .dev sections are missing.

**Comment by KOLANICH** [comment]
@GreyCat, how ahout fixing build of nightly packages on bintray?

**Comment by GreyCat** [comment]
Since ~2018-02-28 (as seen in [commits like these](https://github.com/kaitai-io/kaitai_struct/commit/86726216a68131cc96cb26daaa2cd48d0a2c9027#diff-354f30a63fb0907d4ad57269548329e3)), we're publishing unstable Debian packages to https://bintray.com/kaitai-io/debian_unstable repo. I guess all that's left is adding relevant link to website.

**Comment by GreyCat** [comment]
Finally, seems to be done.
