### ISSUE TITLE
No doc element supported in meta?

### ISSUE THREAD

**Issue by larsks** [kaitai-io/kaitai_struct#630]
I figured the `meta` element would be a good place to include module-level documentation, but it turns out that the `doc` key isn't supported in `meta`:

```
/meta/doc: unknown key found, expected: application, encoding, endian, file-extension, id, imports, ks-debug, ks-opaque-types, ks-version, license, title, xref
```

This seems like it would be a useful spot for documentation since it is typically at the top of the `.ksy` file (and presumably the same docs could be emitted in a similar location in the generated code).

**Comment by GreyCat** [comment]
Just top level /doc and /doc-ref would work :)
