### ISSUE TITLE
Parseing pcap file which has tcp/IP flow info using java

### ISSUE THREAD

**Issue by avi-techno** [kaitai-io/kaitai_struct#634]
Sir I am new to Kaitai, I want to parse **pcap** file which has tcp/IP flow info, I am using java for programming . I have seen your video in Youtube regarding media parsing, kindly let me know how to parse pcap file

_Originally posted by @avi-techno in https://github.com/kaitai-io/kaitai_struct_formats/issues/147#issuecomment-542146699_

**Comment by GreyCat** [comment]
There is an example at http://formats.kaitai.io/pcap/java.html — if you run into any specific problems, please elaborate what is your goal, what have you tried already and why do you think it's not working.

**Comment by avi-techno** [comment]
> There is an example at http://formats.kaitai.io/pcap/java.html — if you run into any specific problems, please elaborate what is your goal, what have you tried already and why do you think it's not working.

Sir  , I am using this code in java to extract pcap file kept in my e drive. How could I implemet this in Kaitai .. the code is :
package jnt; 

import java.io.File; 
import org.jnetpcap.Pcap; 
import org.jnetpcap.packet.JPacket; 
import org.jnetpcap.packet.JPacketHandler; 

public class PacketCounters { 

	
	static String folderpath 
		= "E:\\pcap"; 

	static double count = 0; 
	static double globalcount = 0; 

		public static void main(String[] args) 
	{ 

				File file = new File(folderpath); 

		
		File[] files = file.listFiles(); 

		
		for (File f : files) { 

			
			String FILENAME 
				= folderpath + f.getName(); 

						StringBuilder errbuf = new StringBuilder(); 

			 
			Pcap pcap = Pcap.openOffline(FILENAME, errbuf); 

			
			pcap.loop(-1, new JPacketHandler() 
			{ 
				 public void nextPacket(JPacket packet, StringBuilder errbuf) 
				{ 
					count++; 
				} 
			}, errbuf); 

			System.out.println("File : " + f.getName() 
							+ " Number of Packets : "
							+ count); 

			globalcount = globalcount + count; 

			count = 0; 
		} 

		System.out.println("Total Packets in folder : "
						+ globalcount); 
	} 
}

**Comment by GreyCat** [comment]
@avi-techno, this is a free/open source project that I do in my spare time, and I don't have the capacity to rewrite a sizeable chunk of code written using some sort of library which I've never had the experience with. You're welcome to ask specific questions about KS, but please don't expect people to do work for you for free, especially when you haven't even bothered to try basic examples.
