### ISSUE TITLE
Not valid PHP namespaces

### ISSUE THREAD

**Issue by Ralle** [kaitai-io/kaitai_struct#637]
I am getting a lot of errors from the PHP generated by kaitai.

```
Fatal error: Uncaught Error: Undefined constant 'FunctionInfo' in /Users/ralle/Code/Warcraft3Parsers/dist/FunctionInfo.php:5258
```
On that line is this:
```
namespace \FunctionInfo;
```

The first bug here is that the `namespace` construct always comes with an absolute namespace, so the \ does not make sense.

When removing the \ you get this:

```
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /Users/ralle/Code/Warcraft3Parsers/dist/FunctionInfo.php on line 5258
```

In PHP you want the namespace before everything else. Moving the `namespace` to the first line fixes it.

The only problem now is that the main object, `FunctionInfo` is now in the `FunctionInfo` namespace. So the fix here is to change all references to it (inside the same file to just `FunctionInfo` instead of `\FunctionInfo`.

But in other files that refer to `FunctionInfo`, we want them to either have this in the top just after the namespace:
```
use FunctionInfo\FunctionInfo;
```
or refer to it as \FunctionInfo\FunctionInfo unless they have the same namespace.

**Comment by GreyCat** [comment]
I don't have much experience with PHP — cc @markbook2 — any chance you could take a look at this one?

Otherwise, @Ralle, can I ask you to add contribute some test into [our test repo](https://github.com/kaitai-io/kaitai_struct_tests) that clearly demonstrates the problem, or explain how to reproduce it?

**Comment by Ralle** [comment]
First of all, on this line:


https://github.com/kaitai-io/kaitai_struct_compiler/blob/407389a870d17b8638615c568118bc28f8f227b8/shared/src/main/scala/io/kaitai/struct/languages/PHPCompiler.scala#L46


You need to check if `config.phpNamespace` was actually set to anything, otherwise it will result in a `namespace \SomeNameSpace` which is invalid. Namespaces in `namespace` blocks are always absolute so they don't start with a slash.

As you cannot change namespace during a file, I think you have to make it so if `nsPart` is nonEmpty, it will simply not output a namespace.

You can reproduce it by putting a type in`types:`. This type will have its own namespace block above its definition which is invalid PHP. It has to be at the start of the file and nowhere else.

**Comment by markbook2** [comment]
@Ralle Please provide the expected PHP code and fragment of the generated invalid PHP code. Thanks.

**Comment by andrewDyakin** [comment]
namespace \DosMz;

should be

namespace DosMz;

**Comment by markbook2** [comment]
@GreyCat 
If the generated .php files have the `\` at the begging of the namespace name, then it should be fixed, i.e. the following:
```php
namespace \Foo\Bar\Baz;
```
should be replaced with:
```php
namespace Foo\Bar\Baz;
```
It should be done only for the namespace definition.

**Comment by generalmimon** [comment]
> As you **cannot change namespace during a file**

> This type will have its own namespace block above its definition which is invalid PHP. It has to be **at the start of the file and nowhere else**.

This is not true. Just open generated code of any passing PHP test with some subtypes (e.g. [NestedTypes](https://github.com/kaitai-io/ci_targets/blob/eb0a5c684162c148a716f84a9a33cd715374bc05/compiled/php/NestedTypes.php)). It's absolutely possible to [define multiple namespaces in the same PHP file](https://www.php.net/manual/en/language.namespaces.definitionmultiple.php), although it's illegal to mix namespaced code and non-namespaced when using "semicolon syntax".

Actually, if you compile the NestedTypes format with no specified PHP namespace, it produces a code with this structure:

```php
class NestedTypes {}
namespace NestedTypes {
  class SubtypeA {}
  class SubtypeB {}
}
namespace NestedTypes\SubtypeA {
  class SubtypeC {}
}
```

The `NestedTypes` class is global, but all subtypes are in some namespace. The [PHP documentation says](https://www.php.net/manual/en/language.namespaces.definitionmultiple.php): "To combine global non-namespaced code with namespaced code, only bracketed syntax is supported." So the current codegen is incorrect, it is invalid to define `NestedTypes` class without any previous namespace definition.

So I had to convert all namespace definitions to bracketed to make this work. I ran all tests locally for PHP, only had to fix enums declaration, but I think everything seems fine. Could you have a look, @GreyCat?

**Comment by andrewDyakin** [comment]
https://www.php.net/manual/en/language.namespaces.definitionmultiple.php
sintax without brackets is not wrong, it's not recommended
