### ISSUE TITLE
Switch fall-through

### ISSUE THREAD

**Issue by Ralle** [kaitai-io/kaitai_struct#638]
When I use switch statements, I kind of want to express that only the options in the switch are allowed. In case of anything else, I want kaitat to throw an exception.
This could be expressed this way:
`_: error`

**Comment by KOLANICH** [comment]
#435 #81

**Comment by Ralle** [comment]
I did my searching but your issues just let me find an exact match: #208

**Comment by GreyCat** [comment]
@Ralle Thanks for sorting this one, I'll mark this one as duplicate of #208.
