### ISSUE TITLE
Multiple type declarations behaviour

### ISSUE THREAD

**Issue by DCxDemo** [kaitai-io/kaitai_struct#641]
Yesterday I found out I had this silly typo in ksy: I declared 2 different types for the same field. vec2f here is basically 3 floats.
```
type: vec3f
type: f4
```
So what happened here is that web-ide used 1st declaration and parsed the whole file correctly (both stable and devel), but C# converted class used second declaration and ruined the whole thing. I tried both stable and latest build from appveyor (labeled c# fixes).

It would be nice to:
1. have consistent behavior between compiler and web-ide
2. maybe have a warning of multiple "type" declarations in case this is not the intended behaviour.

**Comment by GreyCat** [comment]
The problem with this is that part is entirely defined by YAML parser — we don't have much control over that. For some reasons, most YAML parsers treat duplicate keys in a map as normal, picking one of them (i.e. either the first or the last value, based on how the parser is coded). On top of that, we use two different YAML parsers — SnakeYAML for JVM build and YamlJS for JS build, and that can give some inconsistent results too.

There's already https://github.com/kaitai-io/kaitai_struct/issues/229 to use better, pure Scala YAML parser (may be creating our own) that will work for all Scala targets, but at the moment, this is the best thing we can do.

**Comment by GreyCat** [comment]
Actually, I went ahead and checked if we can do duplicate keys check at least in some situations, i.e. in SnakeYAML/JVM. It turns out that with recent SnakeYAML versions, we can! So I've added [relevant code and a test](https://github.com/kaitai-io/kaitai_struct_compiler/commit/407389a870d17b8638615c568118bc28f8f227b8). Please take a look at newest unstable build?

**Comment by DCxDemo** [comment]
Yeah, I'm getting "found duplicate key type" now.

**Comment by GreyCat** [comment]
Ok, considering this one fixed then, to the extent it is possible now. JS one is a different thing, though :(
