### ISSUE TITLE
C# tests compilation is failing

### ISSUE THREAD

**Issue by pluskal** [kaitai-io/kaitai_struct#644]
Altho C# [Kaitai Struct CI results page](https://ci.kaitai.io/) is green, C# tests cannot be compiled.

[mono5.18.0](https://github.com/kaitai-io/ci_artifacts/tree/csharp/mono5.18.0/test_out/csharp) build1-4 fails.

[net45_windows](https://github.com/kaitai-io/ci_artifacts/tree/csharp/net45_windows/test_out/csharp) is outdated and buid1-2 also fails.

I tried to build it locally as well but with the same failing result.

**Comment by GreyCat** [comment]
The fact that *some* formats fail to build is totally ok, this is exactly why we have partial builder in place.

I don't see mono build failing: [the job](https://travis-ci.org/kaitai-io/ci_targets/jobs/609843319) says it's ok, delivering these results:

```
SUMMARY: {"kst"=>131, "passed"=>152, "failed"=>1, "spec_build_failed"=>6, "format_build_failed"=>3}
```

and these seem to be reflected properly in [relevant ci_artifacts branch](https://github.com/kaitai-io/ci_artifacts/tree/csharp/mono5.18.0/test_out/csharp).

Situation with [net45_windows build job](https://ci.appveyor.com/project/GreyCat/ci-targets/build/job/b3rp8fmsx610qsji) seems to be worse, as it genuinely fails fully, and partial builder is not doing a very good job at picking up why and resolving this situation:

```
#### CSharpBuilder: process_status: #<Process::Status: pid 2760 exit 1>
#### CSharpBuilder: build attempt 2: elapsed: 5s
#### CSharpBuilder: build failed
#### CSharpBuilder: errors detected in bogus files:
#### CSharpBuilder: - "tests\\SpecEofExceptionBytes.cs"
#### CSharpBuilder: - "tests\\SpecEofExceptionU4.cs"
#### CSharpBuilder: - "tests\\SpecEosExceptionBytes.cs"
#### CSharpBuilder: - "tests\\SpecEosExceptionU4.cs"
#### CSharpBuilder: - "tests\\SpecExprCalcArrayOps.cs"
#### CSharpBuilder: unable to recover, bailing out :(
```

This generally needs to be addressed, we want our build system to be as resilient to temporary codegen problems as possible. And, what's even worse, we'd likely want to reflect that in CI dashboard, and not just hide that fact in job logs.

**Comment by pluskal** [comment]
I see, that is nice functionality.

I can help to address issues, to describe what is wrong with the compilation, but I am afraid that I will not be able to submit PR. Can we coop on this?

**Comment by GreyCat** [comment]
I've fixed Windows/Appveyor compilation, now it suceeds.
