### ISSUE TITLE
Go: support for .to_s function to convert integer to string

### ISSUE THREAD

**Issue by toog** [kaitai-io/kaitai_struct#657]
using example from bcd.ksy (renamed to join it in this issue)

[bcd.ksy.txt](https://github.com/kaitai-io/kaitai_struct_go_runtime/files/3975753/bcd.ksy.txt)

produce good code in ruby but in GO can't have result, only error message : "an implementation is missing"

**Comment by GreyCat** [comment]
Current golang support status can be observed here: https://ci.kaitai.io/
As you can see, it's nowhere close to 100%.

Please consider contributing fixes to make it better supported ;)

**Comment by s00500** [comment]
Hooking into this question, I have a larger file I am trying to compile to go, is there any way to have a more specific error on what feature is missing ?

File: https://github.com/Deep-Symmetry/crate-digger/blob/main/src/main/kaitai/rekordbox_anlz.ksy

**Comment by generalmimon** [comment]
@s00500:

> Hooking into this question, I have a larger file I am trying to compile to go, is there any way to have a more specific error on what feature is missing ?

Try the `--ksc-exceptions` CLI option - it will give you a stack trace:

```console
$ kaitai-struct-compiler --help
...
  --ksc-exceptions         ksc throws exceptions instead of human-readable error messages
```

**Comment by generalmimon** [comment]
@s00500 The problematic part is here - [`rekordbox_anlz.ksy:424-430`](https://github.com/Deep-Symmetry/crate-digger/blob/145b8b93d2c16743d3ef7e0347e52b62bab83af0/src/main/kaitai/rekordbox_anlz.ksy#L424-L430):

```ksy
      mask:
        value: |
          [
            (0xCB+c).as<s1>, (0xE1+c).as<s1>, (0xEE+c).as<s1>, (0xFA+c).as<s1>, (0xE5+c).as<s1>, (0xEE+c).as<s1>, (0xAD+c).as<s1>, (0xEE+c).as<s1>,
            (0xE9+c).as<s1>, (0xD2+c).as<s1>, (0xE9+c).as<s1>, (0xEB+c).as<s1>, (0xE1+c).as<s1>, (0xE9+c).as<s1>, (0xF3+c).as<s1>, (0xE8+c).as<s1>,
            (0xE9+c).as<s1>, (0xF4+c).as<s1>, (0xE1+c).as<s1>
          ].as<bytes>
```

Type casting (`.as<>`) is not yet implemented for Go, see https://github.com/kaitai-io/kaitai_struct/issues/931.

**Comment by s00500** [comment]
Hey @generalmimon 
Thanks a lot, that was very helpful!

Do you have any pointers to what would need to be done to add this feature?  Should I start looking into the compiler or the runtime part or is there any other tipps to where to start contributions?

Greetings

**Comment by generalmimon** [comment]
> using example from bcd.ksy (renamed to join it in this issue)
> 
> [bcd.ksy.txt](https://github.com/kaitai-io/kaitai_struct_go_runtime/files/3975753/bcd.ksy.txt)

In fact, this is [`bcd_user_type_le.ksy`](https://github.com/kaitai-io/kaitai_struct_tests/blob/c5f366f4ce108650d585f9218deb9de345c44e7f/formats/bcd_user_type_le.ksy) used in our test suite with results at https://ci.kaitai.io/. As you can see, the `BcdUserTypeLe` test now passes for all target languages except Construct (and actually fails in Construct due to issues with features other than this one), so this issue is resolved.

**Comment by s00500** [comment]
Is there a new release for the compiler planned in the near future ?
