### ISSUE TITLE
Outdated documentation for base type for enum

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#673]
Last paragraph in https://doc.kaitai.io/user_guide.html#enums states:

> We add enum: …​ parameter to every attribute that’s going to be represented by that enum, instead of just being a raw integer. **Note that such attributes must have some sort of integer type in the first place (i.e. type: u\* or type: s\*).**

Emphasized is not true. Enums can also be based on strings

**Comment by GreyCat** [comment]
Can you elaborate more? To my knowledge, enums in KS are always integers.

**Comment by KOLANICH** [comment]
#434

**Comment by Mingun** [comment]
Ah, I confused them with `cases` in `switch-on`, where strings is acceptable
