### ISSUE TITLE
no python pre-built SNAPSHOT available

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#692]
In order to test if an issue was fixed in master:
- I installed the 0.9-SNAPSHOT from https://dl.bintray.com/kaitai-io/debian_unstable/ as described on http://kaitai.io/#download
- I ran `pip3 install kaitaistruct`, but only stable releases are posted (link: [PyPi kaitaistruct history](https://pypi.org/project/kaitaistruct/#history)) so 0.8 is the latest Python API

Of course, the two are not compatible which causes an exception:
```
Exception: Incompatible Kaitai Struct Python API: 0.9 or later is required, but you have 0.8
```
As a developer, if I choose to use 0.9-SNAPSHOT when testing, instead of building from source, then it would be nice to have corresponding SNAPSHOT for the other items like Python API.

**Comment by KOLANICH** [comment]
0. package name is `kaitaistruct`, not `kaitai-struct`.
1. Install python runtime directly from git: `pip3 install --upgrade -pre git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git`. If you wanna specify it as a dependency, use `kaitaistruct @ git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git`.

**Comment by GreyCat** [comment]
@KOLANICH Thanks for sharing this trick, it's super helpful! I'll try to add it to https://github.com/kaitai-io/kaitai_struct_doc/blob/master/lang_python.adoc

**Comment by GreyCat** [comment]
Here we go: http://doc.kaitai.io/lang_python.html#add-runtime-snapshot

**Comment by KOLANICH** [comment]
>If your project is using requirements.txt to manage your dependencies

`requirements.txt` suouldn;t be used for that, instead it should be package metadata.

**Comment by GreyCat** [comment]
My practical Python-fu is very limited, so these things are bound to happen :( @KOLANICH any chance I can ask you to submit an edit to this doc so it will be correct?

**Comment by KOLANICH** [comment]
https://github.com/kaitai-io/kaitai_struct_doc/pull/32

**Comment by GreyCat** [comment]
Thanks! Please take a look at few comments there?
