### ISSUE TITLE
KSY (YAML) parser support for JSON

### ISSUE THREAD

**Issue by gnbl** [kaitai-io/kaitai_struct#693]
From http://doc.kaitai.io/ksy_reference.html#ksy-file

> KSY files
> 
> Kaitai Struct data structure (format) descriptions (KSY files) are simple YAML files and are usually saved using .ksy extension to differentiate them from the rest of .yaml files.
> 
> Every .ksy file MUST be a valid YAML file, and is expected to be parsed with generic YAML parsing libraries. Inside, every file MUST provide a map of strings (keys) to some values. Each file is essentially a single User-defined type spec.
> 

Relation to JSON

- https://en.wikipedia.org/wiki/JSON#YAML
- https://yaml.org/spec/1.2/spec.html#id2759572
- https://www.json.org/json-en.html

But currently JSON is not supported as input:

https://ide.kaitai.io/
> Kaitai WebIDE version: 0.1-SNAPSHOT-b2479d8 (2018-03-22 10:43:49, license)
> Kaitai compiler version: 0.8-SNAPSHOT337369088 (2018-02-05 01:36:23.722)
> 

This input

```
{
  "doc": "json test",
  "meta": {
    "id": "test",
    "endian": "le"
  },
  "seq": [
    {
      "id": "version",
      "contents": [
        1,
        255,
        255,
        255
      ],
      "doc": "4 - structure version"
    }
  ]
}
```

causes this error

```
Parse error (Error): Unexpected characters (
  },
  "seq": [
    {
      "id": "version",
      "contents": [
        1,
        255,
        255,
        255
      ],
      "doc": "4 - structure version"
    }
  ]
}).
Call stack:  <ParseException> Unexpected characters (
  },
  "seq": [
    {
      "id": "version",
      "contents": [
        1,
        255,
        255,
        255
      ],
      "doc": "4 - structure version"
    }
  ]
}). (line 1: '{')
```

**Comment by GreyCat** [comment]
Can I ask you to check that with Java-based ksc and newer IDE at https://ide.kaitai.io/devel ?

**Comment by gnbl** [comment]
Sure!
Same error:

```
Parse error (Error): Unexpected characters (
  },
  "seq": [
    {
      "id": "version",
      "contents": [
        1,
        255,
        255,
        255
      ],
      "doc": "4 - structure version"
    }
  ]
}).
Call stack:  <ParseException> Unexpected characters (
  },
  "seq": [
    {
      "id": "version",
      "contents": [
        1,
        255,
        255,
        255
      ],
      "doc": "4 - structure version"
    }
  ]
}). (line 1: '{')
```


> Kaitai WebIDE version: 0.1-SNAPSHOT-de5791e (2020-01-19 01:09:40, license)
> Kaitai compiler version: 0.9-SNAPSHOT20200122.115442.05b537e9 (2020-01-22T11:54:42+00:00)
>

**Comment by GreyCat** [comment]
It's likely the problem with YAML parser that we use in JavaScript in IDE. Most likely the proper solution is #229.

**Comment by gnbl** [comment]
According to #229 js-yaml is used in WebIDE.

https://github.com/kaitai-io/kaitai_struct_webide/blob/master/lib/yaml.js does not have a any comments.


JS-YAML does parse JSON (live test with data from earlier post):

http://nodeca.github.io/js-yaml/#yaml=eyAgImRvYyI6ICJqc29uIHRlc3QiLAogICJtZXRhIjogewogICAgImlkIjogInRlc3QiLAogICAgImVuZGlhbiI6ICJsZSIKICB9LAogICJzZXEiOiBbCiAgICB7CiAgICAgICJpZCI6ICJ2ZXJzaW9uIiwKICAgICAgImNvbnRlbnRzIjogWzEsMjU1LDI1NSwyNTVdLAogICAgICAiZG9jIjogIjQgLSBzdHJ1Y3R1cmUgdmVyc2lvbiIKICAgIH0KICBdCn0=

**Comment by cherue** [comment]
WebIDE (v1) uses [yaml.js](https://github.com/jeremyfa/yaml.js) from npm.

WebIDE (v2) uses a customized version of yaml.js that saves the position of nodes. This patched version is the `lib/yaml.js` file.

Note that both https://ide.kaitai.io and https://ide.kaitai.io/devel use v1. v2 is an abandoned effort to rewrite the WebIDE with new features such as auto-complete (that's what the node positions are for).
