### ISSUE TITLE
CI: Add newer Java versions

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#697]
Currently the CI tests the Java target using OpenJDK 7 and Oracle JDK 8. Although Java 8 is still widely used, the most recent version is Java 13, and the newest LTS version is Java 11. (What exactly "LTS" means depends on your JDK vendor, but everyone agrees *which* versions are LTS.)

I think it would be a good idea to add Java 11 to the CI matrix. The next LTS version will be Java 14; maybe until then Java 13 should be added to the matrix? Or we could decide to only test on LTS versions in the interest of updating the CI configuration less often, but that may not be a good idea, because testing on new non-LTS versions is a good way to find issues that may affect us in future LTS versions. In any case, testing on old *non*-LTS versions (Java 9, 10, 12) is probably not worth it.

The difference between Oracle JDK and OpenJDK is *very* unlikely to matter to KS - as far as I know, that mostly affects things outside the core language, like JavaFX, database support, web start, browser integration, etc. Also, recent versions of Oracle JDK have much more restrictive license terms than before, so in that respect it's safest to just use OpenJDK.

**Comment by GreyCat** [comment]
Makes sense. Let's have 7+8+11, and then we'll be reviewing it, say, once per year?

**Comment by KOLANICH** [comment]
Not once per year. IMHO we should just replace OpenJDK with GraalVM (works pretty fine for a long time, the benefits are native integration with python using graalpython, but integration with cpython using JPype works well too), I have a script building its deb packages in GitLab CI from official releases, but this script has recently got broken (in fact they have only changed the location of the repo, I can fix it, but it makes no sense to do it without reworking) and also I plan to rework it a lot (I have created a wholr framework for building packages, but that script uses an old predecessor of that framework, currently I have no time to port it, but when I fix it, I gonna notify you, so you can use the deb packages).

**Comment by dgelessus** [comment]
> IMHO we should just replace OpenJDK with GraalVM

The vast majority of users use OpenJDK though (or Oracle JDK, which is based on the same code), so dropping OpenJDK from the CI matrix is not an option. I don't know if testing on alternative JVM versions *in addition* to OpenJDK would be worth the effort.

**Comment by GreyCat** [comment]
Done. All Java builds exhibit the same behavior, as expected:

Test \ Target | java openjdk11 | java openjdk7 | java oraclejdk8
-- | -- | -- | --
Rating | 97.3% | 97.3% | 97.3%

Considering this done. GraalVM-related stuff should be discussed as a big distinct project.
