### ISSUE TITLE
Floating point data types

### ISSUE THREAD

**Issue by LogicAndTrick** [kaitai-io/kaitai_struct#7]
This is a proposal to add [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point) floating points data types to the list of supported primitive types. The single and double precision types being the key types as the other types in the specification are rare.

Suggested specification pattern: `(f)(4|8)(le|be)`
- First group - always `f` - Indicates floating point
- Second group - `4` or `8` - The length of the type in bytes, 4 being single precision (float) and 8 being double precision (double)
- Third group - `le` or `be` - The endianness of the stored value (optional)

Examples: `f4`, `f4be`, `f8le`

Suggested stream API methods:
-  `read_f4le`
-  `read_f4be`
-  `read_f8le`
-  `read_f8be`

Required changes (I'm mostly guessing here):
- Compiler core: Add type handling for floating points
- Language compilers: Add native type mappings for new types
- Language Runtimes: Add new API methods
- Documentation: Update the API docs and the page listing primitive types
- Tests: Add/modify test cases to add floating point values

I've only ever encountered a half-precision floating point value once, and I'm not sure I ever will again. It's probably not worth adding any FP formats outside of the standard single and double.

**Comment by GreyCat** [comment]
Makes perfect sense :)

It shouldn't be hard to add, it's just I've encountered floating point number in binary packed structures only once or twice and it was really long ago. And, to be honest, I had to idea that there are big-endian and little-endian floats out there too.

As for the required changes, you're absolutely right too. I'd start with the tests, though :)

**Comment by LogicAndTrick** [comment]
Cool. I can give the implementation a shot if you like. I would log a PR rather than committing directly though, as Scala is still very new to me.

I've dealt with a lot of game formats (maps, models, etc) and they're loaded with floating points. I added the endianness in there because the IEEE spec doesn't specify one - it's based on the system architecture that it's running on.

**Comment by GreyCat** [comment]
Sure, feel free to :) Just try to keep PRs small and distinct - I mean, it's easier to review and accept/comment small PRs, than to review large PR with multiple commits / files changes.

Actually, I'd propose that we all do PRs if we're doing something that we're not yet sure enough about, like some new major feature or something like that.

**Comment by LogicAndTrick** [comment]
Yeah, good idea. It's a good way to keep track of what's changing, as things can sometimes get lost in the commit log.

**Comment by GreyCat** [comment]
The last problem for Java is fixed, so I guess we can consider it done.

**Comment by LogicAndTrick** [comment]
Nice, thanks!
