### ISSUE TITLE
enum capitalization in cpp_stl generates non-utf8 characters

### ISSUE THREAD

**Issue by lvntbkdmr** [kaitai-io/kaitai_struct#708]
I try to generate **cpp_stl** files from **zip.ksy** that is already available by running;

`kaitai-struct-compiler.bat --target=cpp_stl zip.ksy`

Generated zip.h contains enums like this:
```
    enum compression_t {
        COMPRESSİON_NONE = 0,
        COMPRESSİON_SHRUNK = 1,
        COMPRESSİON_REDUCED_1 = 2,
        COMPRESSİON_REDUCED_2 = 3,
        COMPRESSİON_REDUCED_3 = 4,
        COMPRESSİON_REDUCED_4 = 5,
        COMPRESSİON_İMPLODED = 6,
        COMPRESSİON_DEFLATED = 8,
        COMPRESSİON_ENHANCED_DEFLATED = 9,
        COMPRESSİON_PKWARE_DCL_İMPLODED = 10,
        COMPRESSİON_BZİP2 = 12,
        COMPRESSİON_LZMA = 14,
        COMPRESSİON_İBM_TERSE = 18,
        COMPRESSİON_İBM_LZ77_Z = 19,
        COMPRESSİON_PPMD = 98
    };

    enum extra_codes_t {
        EXTRA_CODES_ZİP64 = 1,
        EXTRA_CODES_AV_İNFO = 7,
        EXTRA_CODES_OS2 = 9,
        EXTRA_CODES_NTFS = 10,
        EXTRA_CODES_OPENVMS = 12,
        EXTRA_CODES_PKWARE_UNİX = 13,
        EXTRA_CODES_FİLE_STREAM_AND_FORK_DESCRİPTORS = 14,
        EXTRA_CODES_PATCH_DESCRİPTOR = 15,
        EXTRA_CODES_PKCS7 = 20,
        EXTRA_CODES_X509_CERT_İD_AND_SİGNATURE_FOR_FİLE = 21,
        EXTRA_CODES_X509_CERT_İD_FOR_CENTRAL_DİR = 22,
        EXTRA_CODES_STRONG_ENCRYPTİON_HEADER = 23,
        EXTRA_CODES_RECORD_MANAGEMENT_CONTROLS = 24,
        EXTRA_CODES_PKCS7_ENC_RECİP_CERT_LİST = 25,
        EXTRA_CODES_İBM_S390_UNCOMP = 101,
        EXTRA_CODES_İBM_S390_COMP = 102,
        EXTRA_CODES_POSZİP_4690 = 18064,
        EXTRA_CODES_EXTENDED_TİMESTAMP = 21589,
        EXTRA_CODES_İNFOZİP_UNİX = 30805,
        EXTRA_CODES_İNFOZİP_UNİX_VAR_SİZE = 30837
    };
```

As you can see, capitalizing small "i" results in capital İ which is available in my native language (Turkish). However, as you can imagine, it does not compile.. It gives me 

```
In file included from src\zip.cpp:3:
include/zip.h:31:17: error: stray '\335' in program
         COMPRESSİON_NONE = 0,
```

There are also macro issues such as

```
#ifndef ZİP_H_
#define ZİP_H_
```

**Comment by GreyCat** [comment]
Great catch, thanks! Looks like we need to test capitalization to be locale-independent.

**Comment by generalmimon** [comment]
Relying on `toUpperCase(java.Locale.ROOT)` apparently [doesn't work for JavaScript](https://travis-ci.org/kaitai-io/kaitai_struct/builds/657500243#L1015). As suggested [in this issue](https://github.com/scala-js/scala-js/issues/1773#issuecomment-277950805), we'll probably need to use https://github.com/cquiroz/scala-java-locales.

**Comment by GreyCat** [comment]
I've started [this thread on SO](https://stackoverflow.com/questions/60486347/), but so far the proposed simple solution doesn't quite work for me :( Will try to get to it more...

**Comment by GreyCat** [comment]
Confirming that it works! Thanks, @generalmimon, I've played with it a lot but for some reason that solution at SO never worked for me — but you've demonstrated that it clearly works!
