### ISSUE TITLE
Runtime API version check in generated code

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#72]
KS compiler of a given version targets certain version of runtime API. As we're still adding major features, this API is bound to change.

It might be a good idea to add some sanity checks in the beginning of generated code (preferably, compile- or import-time checks, if a language allows them), that will get the API version of just imported KS runtime KS, and check if it's compatible with what we had in mind when compiled.

**Comment by GreyCat** [comment]
Wow, my bad. I've recreated exactly same issue — #110 — a month later — and started to work there. Closing this one then, as that one has more info there already.

**Comment by generalmimon** [comment]
Duplicate of #110
