### ISSUE TITLE
Use Environment Variable in Conditionals

### ISSUE THREAD

**Issue by crbreingan** [kaitai-io/kaitai_struct#720]
I have a message that has multiple versions with different data and lengths between versions. Unfortunately, there is no indication in the message which version it is, they have the same header sequence. But, as a user, I will always know what version of data I am processing. So, it would be awesome if I could have the user specify the version in the environment (like in a docker run command) and have the Kaitai switch between versions. 

From reading through the docs, I think I could use an Opaque type that just doesn't process any bytes off of the stream to do this. But that seems a little convoluted. It would be must nicer if I could just have a switch-on: env.MSG_VERSION

**Comment by Mingun** [comment]
You can have parameters at top-level of grammar. See `params` key
