### ISSUE TITLE
Tests for `--debug`

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#73]
We have quite a few code that gets generated using `--debug` - and it's mostly untested. I propose to create some special tests for that.

The basic idea is to include some special field into file (for example, we could use `-compiler-debug: true` or something like that) that will enforce compiling with `--debug` option turned on (even if it's not on the command line), and then write some tests for the output.

**Comment by GreyCat** [comment]
I've added simple [debug_0](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/debug_0.ksy) test — it just tests simple 1-byte integer in a seq + fixed amount of repetitions array in a seq. I ended up adding `ks-debug: true` option in `meta`, in spirit of `ks-version`.

@koczkatamas Please add tests to whatever functionality you have in mind for `--debug` mode for JavaScript, i.e. "instances", "enums", etc, etc.

**Comment by koczkatamas** [comment]
Added tests here: https://github.com/kaitai-io/kaitai_struct_tests/pull/25

**Comment by GreyCat** [comment]
I guess, we have some test coverage, so closing this one for now.
