### ISSUE TITLE
KSYs using .as<> in format gallery are incorrectly interpreted as HTML

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#733]
All formats using the casting `.as<...>` have rendered incorrectly in https://formats.kaitai.io/, because the pointy brackets are interpreted by the browser as HTML tags (the KSY contents are inlined unescaped). Although the browsers can handle it, the part between the brackets is not visible on the page (it behaves like HTML tag), so copy-pasting the KSY code from the browser doesn't compile with the KSC. The generated target language source codes apparently don't have this issue.

Example: [java_class](http://formats.kaitai.io/java_class/index.html) (you can see that only `.as` is present in the page). Here is how the HTML source code looks like:

![formats-kaitai-io-typecasting-html-injection](https://user-images.githubusercontent.com/47499687/79795787-c2fbe100-8354-11ea-92e0-00762b3c6a6f.gif)

**Comment by GreyCat** [comment]
Great catch, thanks, @generalmimon!
