### ISSUE TITLE
Add link to xref.html in the format gallery 

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#739]
While digging in the generating code for the [format gallery](https://formats.kaitai.io/), I noticed that every time it generates page https://formats.kaitai.io/xref.html, which is quite a neat summary of all formats included with their licenses and cross-references. It's a pity that there isn't any link leading to it, so nobody can actually get there. So I think it makes sense to add one. Probably on the [format gallery homepage](https://formats.kaitai.io/).

**Comment by GreyCat** [comment]
I've created xref.html for my own reference to understand how good/bad the situation with different xrefs/titles/docs/licenses in the repo is. But if you see any value in making it public — sure, let's add the link.
