### ISSUE TITLE
Decide on target C# version

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#74]
Currently the C# runtime uses C# 6 features [1], like:

- Interpolated strings 
  - `throw new Exception($"Expected bytes: {Convert.ToBase64String(expected)}, Instead got: {Convert.ToBase64String(bytes)}");`
- Expression-bodied function members
  - `public bool IsEof => BaseStream.Position >= BaseStream.Length; `

While the compiler generated code uses ~C# 2 features.

So we either target an older C# version in the runtime (it can be fixed easily) or generate more modern C# code by the compiler [2].

Even if we target ~C# 2 it would be good if the target version would be a compiler flag, so the user could choose between backward compatibility or more modern code based on his/her needs.

[1] https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6
[2] https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#getter-only-auto-properties

**Comment by GreyCat** [comment]
Well, given that we can only have one C# runtime (or, in worst case scenario, several: if they are *that* different and warrant to be distinct, but definitely not dozens), I guess we have to keep C# runtime requirements as low as practically possible.

As for generated code, we can have compiler flag to choose target version. In fact, same holds true for many other languages (C++ versions differ *a lot*, PHP 7.1 might finally have use for proper type system, and even in Java we can use a few better methods if we were sure that we have Java 8), etc.

Does it make sense?

Cc @LogicAndTrick ?

**Comment by LogicAndTrick** [comment]
Yeah, to be honest there's no reason not to use the older, backwards compatible syntax in the runtime, and there's no reason to generate two different code styles either. I just wanted to use the fancy new features when I was writing the runtime :)

My vote is to just change the new syntax in the runtime to just use the older style code, and leave it at that.
