### ISSUE TITLE
C#: Using unsigned long (ulong) for sizes smaller than byte

### ISSUE THREAD

**Issue by alloncm** [kaitai-io/kaitai_struct#742]
Hi I have noticed that the compiler for C# (not sure about other languages) the compiler will use ulong (unsigned long) for types smaller than byte.
Is there any reason for that?

**Comment by GreyCat** [comment]
No particular reason — it's been done mostly for simplicity and avoiding potential typecasting pitfalls.

Technically, it's problem to cast that to unsigned 1-, 2- and 4-byte integers where relevant, but I'm not sure if there would be any benefits?

**Comment by alloncm** [comment]
Could you please explain on what kind of pitfalls are you talking about, if you know the value could hold a maximum value of 6 bit what is the problem storing it in a 8 bit type?
Or maybe it is some compiler internal pitfalls you are trying to avoid?
