### ISSUE TITLE
Kismet stopped using KS due to C++ memory leaks

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#747]
See https://github.com/kismetwireless/kismet/commit/a42a7125ac1c883e8d3415f3f535256ea037d1a1

This is quite an unpleasant matter, that the project had to disable Kaitai Struct due to memory leaks. I don't know if the guilty issue is covered in https://github.com/kaitai-io/kaitai_struct/issues/214 and https://github.com/kaitai-io/kaitai_struct/issues/494 or not, but it would be nice to fix it so that they can use Kaitai Struct again. I have no idea how difficult it would be to fix. It's also possible that it's been already fixed in the current compiler (they reported the issue and stopped using KS 2 years ago).

**Comment by GreyCat** [comment]
The original idea of v0.9 milestone was exactly to solve C++ problems which got highlighted by Kismet usage (and subsequent decline of the it, as you've referenced).

Unfortunately, nowadays we're terribly behind the original schedule and intent. Still, I think that we should release 0.9 is a way that it will be at least not worse than 0.8 in relation to C++.

**Comment by generalmimon** [comment]
AFAIK, all known C++ memory leaks were fixed in 0.9. Shortly after releasing 0.9 (2 years ago), I sent an e-mail to @dragorn that I believe the issues they had trouble with ([**kismet** / kaitai_definitions_disabled/README](https://github.com/kismetwireless/kismet/blob/24326078ec77de482f5dbd7af502afcf2a2440c9/kaitai_definitions_disabled/README)) were solved, and he got back to me saying that he'll check it out.

Kismet devs disabled KS generation in 2018, so they have been doing well with manually written parsers for a while and have certainly found their ways. That's completely OK. It's nice to see that they are at least using the standalone [KS C++/STL runtime library](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime).
