### ISSUE TITLE
ide.kaitai.io

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#75]
Probably it's time to finish our discussions and get things done with long-proposed ide.kaitai.io.

Things that I remember that we somewhat discussed and that are probably worth doing:

- [x] Transfer https://github.com/koczkatamas/kaitai_struct_webide to team account (i.e. https://github.com/kaitai-io/kaitai_struct_webide)
- [x] Register ide.kaitai.io, point it at GH pages
- [x] Create a ide.kaitai.io repository that will host pre-built versions of HTML + JS + etc
- [x] Discuss and implement auto-building process for kaitai_struct_webide -> ide.kaitai.io repo (Travis, probably?)

Somewhat related: #62

**Comment by GreyCat** [comment]
Ok, a little for the history based on our chat discussions:

* We've decided that we need two different IDE sites: one stable (ide.kaitai.io), one unstable (ide-devel.kaitai.io)
* We had some pretty strong argument on how these sites should be served; @koczkatamas insisted that https is a must, so we've transferred kaitai.io domain DNS to Cloudflare, and enabled proxying (with https support) for these two sites.
* We've created two repositories:
  * [ide-kaitai-io.github.io](https://github.com/kaitai-io/ide-kaitai-io.github.io) - for stable GH pages exposure
  * [ide-devel-kaitai-io.github.io](https://github.com/kaitai-io/ide-devel-kaitai-io.github.io) - for unstable builds
* We've added some building infrastructure into [kaitai_struct_webide](https://github.com/kaitai-io/kaitai_struct_webide) repo (namely: `build` script and `.travis.yml`)

Unstable builds now work, kind of. Stable are to be implemented and tested.

**Comment by KOLANICH** [comment]
14 марта 2017 г. 5:58:32 GMT+03:00, Mikhail Yakshin <notifications@github.com> пишет:
>Ok, a little for the history based on our chat discussions:
>
>* We've decided that we need two different IDE sites: one stable
>(ide.kaitai.io), one unstable (ide-devel.kaitai.io)
>* We had some pretty strong argument on how these sites should be
>served; @koczkatamas insisted that https is a must, so we've
>transferred kaitai.io domain DNS to Cloudflare, and enabled proxying
>(with https support) for these two sites.
>* We've created two repositories:
>*
>[ide-kaitai-io.github.io](https://github.com/kaitai-io/ide-kaitai-io.github.io)
>- for stable GH pages exposure
>*
>[ide-devel-kaitai-io.github.io](https://github.com/kaitai-io/ide-devel-kaitai-io.github.io)
>- for unstable builds
>* We've added some building infrastructure into
>[kaitai_struct_webide](https://github.com/kaitai-io/kaitai_struct_webide)
>repo (namely: `build` script and `.travis.yml`)
>
>Unstable builds now work, kind of. Stable are to be implemented and
>tested.

>https is a must

It surely is, but using cloudflare adds one more trusted party. I see no reason not to use .github.io subdomain, it has https, any github-based website has https. The url will not look that nice, but not using cloudflare imho worths it.

**Comment by GreyCat** [comment]
IDE deployment seems to be working now, closing.
