### ISSUE TITLE
"ensureFixedContents" vs. "ValidationNotEqualError" because of different exceptions.

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct#750]
For unrelated reasons I've recently upgraded KS compiler+runtime and my formerly working parser is failing now at various places. One of the reasons is that the generated code for `contents` has changed. The following KSY:

    # par_oms_dll_command:
    seq:
      - id:       check_value
        contents: [0x44]

Resulted in the following Java in the past:

    this.checkValue = this._io.ensureFixedContents(new byte[] { 68 });

But is now resulting in the following:

            this.checkValue = this._io.readBytes(1);
            if (!(Arrays.equals(checkValue(), new byte[] { 68 }))) {
                throw new KaitaiStream.ValidationNotEqualError(new byte[] { 68 }, checkValue(), _io(), "/seq/0");
            }

While I don't care for how things are checked in the end, I DO care about the exceptions thrown. That has been `UnexpectedDataError` in the past instead of the new one and I have code relying on that. When that exception is thrown, I need to do different things in Java and that fails now of course. I would have preferred that this kind of change would trigger a compile time error instead of on runtime.

While `ensureFixedContents` is still available in the compiler, is it used at all anymore? If not, an easy way to prevent problems like mine would have been to remove `UnexpectedDataError` and the calling method at all. Remember that my use of `contents` has been rewritten to the new validations already, so I don't see how one could trigger the old behaviour at all anymore.

**Comment by GreyCat** [comment]
Apologies for late reply again.

`ensureFixedContents` is not used anymore and it will be kept in the runtime libraries for some time (likely until KS 1.0) for keeping some degree of compatbility with older generated code.

The whole exception systems gets revamped — which is a good thing. Unfortunately, I don't see any good solutions on how to avoid breaking API with this change.

> I would have preferred that this kind of change would trigger a compile time error instead of on runtime.

Can you suggest any kind of changes we can do for that? I'm only aware of Java checked exceptions mechanism, which is generally frowned upon and just about everyone nowadays tends to use `RuntimeException`-derived exceptions.

**Comment by ams-tschoening** [comment]
> ensureFixedContents is not used anymore and it will be kept in the runtime libraries for some time (likely until KS 1.0) for keeping some degree of compatbility with older generated code.

Which makes sense of course, but my use case was generating new code and in that case keeping `ensureFixedContents` and `UnexpectedDataError` in the runtime looked like things were backwards compatible, while they actually were not.

> Can you suggest any kind of changes we can do for that?[...]

Keeping RuntimeExceptions makes sense in general, I really meant removing/renaming the exception `UnexpectedDataError` I relied on. This would have triggered compile time errors for me, but of course wouldn't be backwards compatible in case one updates the runtime only without generating new code.

OTOH, in this special case, I would have argued that most likely not too many users rely on that exception like I do. And if they do, they most likely run into the same problem like I did.

**Comment by ams-tschoening** [comment]
Maybe it's enough already to mark `ensureFixedContents` and `UnexpectedDataError` as `@deprecated`, creating a warning that I might have stumbled upon as well:

![Screenshot](https://user-images.githubusercontent.com/6223655/83349804-d7f66780-a337-11ea-8e8e-a4ca19dce2d1.png)

**Comment by ams-tschoening** [comment]
Closing here for now because a [deprecation-warning has been merged](https://github.com/kaitai-io/kaitai_struct_java_runtime/pull/33). This might be enough already to make users aware of the problem.
