### ISSUE TITLE
Unstable Debian repository doesn't install latest snapshot

### ISSUE THREAD

**Issue by woodruffw** [kaitai-io/kaitai_struct#760]
First of all, thanks a ton for Kaitai Struct!

It looks like the unstable Debian repository isn't installing the latest available snapshot by default.

Using the following steps:

```bash
apt-key adv --keyserver keyserver.ubuntu.com --recv 379CE192D401AB61 && \
    echo "deb https://dl.bintray.com/kaitai-io/debian_unstable jessie main" \
        | tee /etc/apt/sources.list.d/kaitai.list && \
    apt-get update && \
    apt-get install -y kaitai-struct-compiler
```

And running the following:

```bash
$ kaitai-struct-compiler --version
```

I get `0.9-SNAPSHOT522603588` instead of `0.9-SNAPSHOT20200607.053216.a0d7f531`, which is what I expect.

I'm currently attempting to install the latter explicitly via `apt-get install -y kaitai-struct-compiler=0.9-SNAPSHOT20200607.053216.a0d7f531`; will report on the effects.

**Comment by KOLANICH** [comment]
<details>
<summary>some offtop</summary>

>--recv 379CE192D401AB61

You should use a full fingerprint, not a truncated one. And a repo should be bound to key file
</details>

**Comment by generalmimon** [comment]
Bintray is (unfortunately) no longer active, so this issue has become pointless.
