### ISSUE TITLE
Exception support for EOFError to access the valid parsed contents

### ISSUE THREAD

**Issue by vrpcse** [kaitai-io/kaitai_struct#761]
I am currently parsing pcap dumps with pcap.ksy input. if dump is partial (the last packet isn't fully captured), i want to still have the correctly parsed packets. 
Currently the parsing is aborted with an exception EOFError.

if pcap.py is having an exception handling in _read(), i can still access the correctly parsed packets. i checked the user guide and couldn't find a way to mention it in ksy file.

Example (proposal) ksy file to handle this exception:

seq:
  - id: hdr
    type: header
  - id: packets
    type: packet
    repeat: eos
    _except: eoferror
    except-print: incomplete packet_

Generated code can be,

    def _read(self):
        self.hdr = self._root.Header(self._io, self, self._root)
        try:
            self.packets = []
            i = 0
            while not self._io.is_eof():
                self.packets.append(self._root.Packet(self._io, self, self._root))
                i += 1
        except EOFError:
             print("incomplete packet")

It is just an proposal and can be improved if looks good.

**Comment by vrpcse** [comment]
Did anybody look into this?

**Comment by webbnh** [comment]
@vrpcse, I think the maintainers are pretty busy (working on KS as well as working on other stuff), so it might take more than just a few days for them to comment on an enhancement request.

The other problem is that this request is sort of a tip-of-the-iceberg thing:  you've come up with a point solution for a very specific and rather simple case; however, if something like what you propose were added to KS, it would need to be applicable to and work in a variety of cases.

For instance, should it apply to other `repeat` attibutes (e.g., ones in the middle of a `type`)?  Should it apply to non-repeated fields?  How does it apply if the containing type is nested inside another type?  Should it be an attribute of a particular field, or is this an idea which should be applied to an entire type, an entire file, or globally?

In my own case, I use KS to describe my input format, but I don't try to parse the entire thing in one operation.  This is for a variety of reasons, but one of them is so that I can handle incomplete type instances.

So, rather than hoping that KS can cover your situation, you might want to try using KS differently:  instead of counting on KS to perform the iteration, do it yourself (using KS to read each packet), and then you can handle the failures in any way that you think is appropriate.

**Comment by vrpcse** [comment]
@webbnh - thank you for your detailed feedback. May be, I dived deep into my problem to express a feature-update :-).
When I have a dump and parsing throws me an exception 'EOFError', I am still losing the valid parsed contents that I wanted to overcome.

_So, rather than hoping that KS can cover your situation, you might want to try using KS differently: instead of counting on KS to perform the iteration, do it yourself (using KS to read each packet), and then you can handle the failures in any way that you think is appropriate._

I couldn't follow you. I use the pcap.ksy from kaitai-struct collections and feed the pcap dump directly.
Could you please explain how do i do the error handling of partial packet in the pcap dump?

Sorry if I am deviating from the original topic to get help.

**Comment by KOLANICH** [comment]
I deal to such problems the following way:
1. I transpile to the language I use
2. I manually modify the parser the way I need
3. I generate a patch file

That patch file can be applied automatically.

**Comment by vrpcse** [comment]
@webbnh 
I did the following and requesting your feedback.
I changed 'seq' into 'instances' in pcap.ksy and did an exception handling in my wrapper code.
```
f = Pcap.from_file('test.pcap')
hdr = f.hdr

try:
    packets = f.packets
except EOFError:
    print("[WARN] Dump has partial packets. Proceeding with available valid packets")

for packets in f.packets # here parsed valid packets are available
....
```

**Comment by webbnh** [comment]
What we did was instantiate a `kstream` and then instantiate objects of each type from it.  So, in your example, you would instantiate a `header` and then loop instantiating `packet`'s until you hit the end.

I expect that the end result is pretty much the same as what you have now.  (It's possible that using KS `instance`'s is more elegant, but I don't think that they were as capable as they are now when I was writing my code.)

**Comment by vrpcse** [comment]
The query I raised as an issue can be handled in the wrapper code which uses kaitai generated classes as explained above.

I am new to GitHub as well. So this query can be closed. I am not sure that I could just close without setting any labels or other parameters.

Thank you for having your time and for your valuable feedback.

**Comment by generalmimon** [comment]
@webbnh 
> What we did was instantiate a `kstream` and then instantiate objects of each type from it. So, in your example, you would instantiate a `header` and then loop instantiating `packet`'s until you hit the end.

I don't think it's necessary in this case. Note that if you compile the KSY spec with the `--no-auto-read` command-line option, you can easily wrap the `_read()` call in a `try..except` block. After doing so, when you catch an exception there, you can still work with the partial struct filled with data that has been parsed before the exception occurred.

A simple example:

```python
# hello_world.py
class HelloWorld(KaitaiStruct):
    def __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self
        # self._read() # important: make sure this line is gone; if not, make sure to specify the --no-auto-read switch to the kaitai-struct-compiler

    def _read(self):
        self.one = self._io.read_u1()
        raise ValueError('unexpected foo')
        self.two = self._io.read_u1() # never executed
```

```python
# test.py
from hello_world import HelloWorld

hw = HelloWorld.from_file('file.bin')
try:
    hw._read()
except ValueError as err:
    print("raised exception: {}".format(err))
    print("one = {}".format(hw.one))
```

Of course, you have no idea where the parsing stopped without querying `hasattr(hw, 'one')`, `hasattr(hw, 'two')` etc. The suggestion by @webbnh seems to have more control, so feel free to use it, I wanted to just point out that this is also possible. You don't need to change either the original KSY spec or the generated code this way.

**Comment by webbnh** [comment]
@generalmimon, yours is a good suggestion, as well.  However, one of the nice features of my approach (and the `instance` approach that @vrpcse hit upon might be handled similarly) is that it does not necessarily have to read all of the input into memory at once.

In many cases, on modern machines, this isn't an issue, but for very large inputs (or very restricted processing environments), it's handy to be able to process the input as a stream and deal with one packet at a time.

**Comment by GreyCat** [comment]
Closing, as per @vrpcse comment above.
