### ISSUE TITLE
Using Kaitai with a string in python

### ISSUE THREAD

**Issue by StelluR** [kaitai-io/kaitai_struct#767]
I'm trying to use the library to decode a string's binary components. I don't need a separate file to hold the string. Is it possible for me to just say:

exampleString  = "thisIsAString"

and then use kaitai on the variable exampleString? I don't want to use a separate file to store the string -- a little unnecessary for me. If this is possible, how do I call kaitaistruct methods on the variable exampleString? Whenever I try to do so, I'm getting errors because it's a primative string type not the object that my KSY file generated. How can I instantiate an object using the python generated source file from my KSY in python?

**Comment by vrpcse** [comment]
Did you try with from_bytes() method?

**Comment by StelluR** [comment]
Can you expand on what you mean/give an example? I'm not sure I totally understand.

**Comment by KOLANICH** [comment]
`YourSpecClass.from_bytes(yourStr.encode("encoding of your string"))`

**Comment by StelluR** [comment]
Example of what I'm doing:

I've created a KSY file and from that I've generated a source file called exampleString. 

I need to instantiate the kaitai exampleString object so that I can parse it.
I have a string variable: kaitaiTestString = "thisIsATestString"
here's what I've tried: exampleString.from_bytes(kaitaiTestString.encode("UTF-8"))
No matter what I do, I'm getting an error that the module doesn't have the attribute from_bytes or from_file if I try to import it from a file

**Comment by vrpcse** [comment]
If I understand your question, you want to parse the string using Kaitai struct instead of putting that in a file and parsing that file.

```
seq:
  - id: var1
    size: 2
  - id: var2
    size: 6

# Your code can be,
t = "mystring"
ko = kaitaistruct.from_bytes(t.encode('utf-8')
print(ko.var1, ko.var2)
```

**Comment by StelluR** [comment]
Yes, vrpcse, your understanding of my question is correct. I'm getting the error that <your_class> doesn't have the attribute from_bytes when I'm trying to instantiate it.

**Comment by generalmimon** [comment]
@StelluR Can you show your code and the error? The `from_bytes` method is present since the stable version 0.8 (https://github.com/kaitai-io/kaitai_struct_python_runtime/commit/a71013c902dfdb52d0778305fd591df5ddfae636), so if you're not using an older version, `<your_class>.from_bytes()` should work. For example, if your .ksy top-level id is [`utf8_string`](http://formats.kaitai.io/utf8_string/python.html), then the class is named `Utf8String` and so you should be able to do `Utf8String.from_bytes(b"foobar")`.

**Comment by vrpcse** [comment]
Yes correct. Try checking whether you are mentioning utf8_string (generated python file name) or Utf8String (generated class name)

**Comment by generalmimon** [comment]
> Try checking whether you are mentioning utf8_string (generated python file name) or Utf8String (generated class name)

Yeah, it shouldn't be ~`<your_class>`~, but **`<YourClass>`** for clarity. I'll update the above comments so it's not misleading.

**Comment by vrpcse** [comment]
:-) it tells that class name to be put. yeah as you said, can make confusions.

**Comment by StelluR** [comment]
Thank you for the awesome replies, everything works now :)
