### ISSUE TITLE
Escape characters in strings

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#77]
Currently, some escape sequences (i.e. `\n`, `\0`, etc) get parsed in strings in expression language, but none of them get proper output back - i.e. we get literally newlines and zero bytes. We need:

1. Clearly outline what we support and what we don't
2. Create a few tests for these
3. Implement them carefully in all languages

**Comment by GreyCat** [comment]
Done initial work on parsing escaped character literals. Now we have:

* single-quoted literals take literally whatever goes into them (except for single quotes, obviously)
* double-quoted literals handle escape sequences:
  * `\n`, `\r` and such characters — full list is in [QUOTED_CC](https://github.com/kaitai-io/kaitai_struct_compiler/blob/master/shared/src/main/scala/io/kaitai/struct/exprlang/Lexical.scala#L46-L58)
  * octal escapes (i.e. `\0` = zero character, `\33` = escape character, `\123`= `S`, etc)
  * hex unicode escapes (i.e. `\u263b` = `☻`)

This more or less matches how most languages interprete them (Shell script, Ruby, PHP, Perl), and feature set is more or less corresponds to whatever many languages offer. I'm kind of doubting whether or not we should include support for stuff like `\x1b`, given existing `\uXXXX` syntax totally supersedes that.

Next points:

* understanding how this copes with YAML and probable another layer of interpreting these chars in YAML string literals
* translating this properly into various target languages.

**Comment by GreyCat** [comment]
Ok, some progress on the "next points".

## YAML

There are 3 basic ways to use strings in YAML

* `foo`
* `"foo"'
* `'foo'`

There is internal YAML conversion for quoted characters (i.e. `\n`, `\r`, etc), but it only works in double-quoted strings. So, generally, as long as one uses string literal inside an expression (i.e. `a == "foo"`), or in single-quoted string (i.e. `'"foo"'`), it's safe and would do the trick.

## Translators

Basic implementation is in BaseTranslators, it's somewhat complex, but pretty modular, so one can customize it with easy overrides without the need to rewrite everything if language's list of quoted characters differs a bit from default one.

Done a [str_literals](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/str_literals.ksy) test, spec is ported to some languages. I might use some help with Perl, Python, JS, etc. @sergeyzelenyuk, @markbook2, @koczkatamas?

**Comment by markbook2** [comment]
@GreyCat PHP has the `{` and `}` for unicode:
```scala
  def strLiteralUnicode(code: Char): String =
    "\\u{%04x}".format(code.toInt)
```
For tests we could use something like that:
```php
$this->assertSame("\u{0}\u{1}\u{2}\u{7}\u{8}\u{a}\u{d}\u{9}\u{b}\u{c}\u{1b}\u{3d}\u{7}\u{a}\u{24}\u{263b}", $r->complexStr());
```
or use own implementation to converting a string to an array of decimals. Here is an example of converting 
```sh
>>> IntlChar::ord(mb_substr('abc', 0, 1, 'UTF-8'));
=> 97
>>> IntlChar::ord(mb_substr('abc', 1, 1, 'UTF-8'));
=> 98
>>> IntlChar::ord(mb_substr('abc', 2, 1, 'UTF-8'));
=> 99
```

**Comment by GreyCat** [comment]
@markbook2 Thanks!

The majority of the task is done. We've got 2 .ksy tests + assortment of ExpressionsSpec and TranslatorSpec tests. The only remaining 2 tests are Perl. I'll try to take on them soon.

**Comment by GreyCat** [comment]
Perl tests are there. I consider this task done.
