### ISSUE TITLE
How to clean up an array of IO stream pointers in C++11

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#774]
The test [`repeat_until_sized`](https://github.com/kaitai-io/kaitai_struct_tests/blob/1d6a6b1369f170ce71d5e3c9a3e401c3682eac3b/formats/repeat_until_sized.ksy#L1) currently leaks memory in C++11. Here's the generated code (I threw away the irrelevant parts, see [`repeat_until_sized.cpp:15-35`](https://github.com/kaitai-io/ci_targets/blob/afe8554a32cb0bac8786cf8b598be457298c8fdb/compiled/cpp_stl_11/repeat_until_sized.cpp#L15-L35) for the full version):

```cpp
void repeat_until_sized_t::_read() {
    m__io__raw_records = std::unique_ptr<std::vector<kaitai::kstream*>>(new std::vector<kaitai::kstream*>());
    m_records = std::unique_ptr<std::vector<std::unique_ptr<record_t>>>(new std::vector<std::unique_ptr<record_t>>());
    {
        record_t* _;
        do {
            kaitai::kstream* io__raw_records = new kaitai::kstream(_buf); // this line is reported by Valgrind to leak memory
            m__io__raw_records->push_back(io__raw_records);
            _ = new record_t(io__raw_records, this, m__root);
            m_records->push_back(std::move(std::unique_ptr<record_t>(_)));
        } while (!(_->marker() == 170));
    }
}

repeat_until_sized_t::~repeat_until_sized_t() {
}
```

I think that the `kaitai::kstream*` pointers stored in `m__io__raw_records` variable are supposed to be cleaned up in the destructor. This is done in [C++98 codegen](https://github.com/kaitai-io/ci_targets/blob/afe8554a32cb0bac8786cf8b598be457298c8fdb/compiled/cpp_stl_98/repeat_until_sized.cpp#L36-L39), because it uses only raw pointers. The `m__io__raw_records` variable is a `std::unique_ptr`, but as I understand, this will ensure only the cleanup of the underlying array (`std::vector`) itself when it goes out of scope, but the individual `kaitai::kstream*` items still have to be handled manually?

What if the destructor would look like this:

```cpp
repeat_until_sized_t::~repeat_until_sized_t() {
    for (std::vector<kaitai::kstream*>::iterator it = m__io__raw_records->begin(); it != m__io__raw_records->end(); ++it) {
        delete *it;
    }
}
```

Would it solve the problem? Is there a way to do it better?

**Comment by webbnh** [comment]
It looks to me like you have an array of streams (`m__io__raw_records`) and an array of records (`m_records`), each of which is a `std::vector`, but one contains raw pointers and one contains `std::unique_ptr`'s...and it's the things pointed to by the raw pointers which aren't being destructed.

So, either the raw-pointer-pointed-to values need to be deallocated, or they need to be wrapped in smart pointers...I would think.

**Comment by generalmimon** [comment]
@webbnh 
> So, either the raw-pointer-pointed-to values need to be deallocated, or they need to be wrapped in smart pointers

**Comment by generalmimon** [comment]
@webbnh 
> So, either the raw-pointer-pointed-to values need to be deallocated, or they need to be wrapped in smart pointers

It would be nice to use smart pointers if possible. Is it OK to use `std::unique_ptr` for individual `io__raw_records` similarly as in the case of `m_records`? When the `repeat_until_sized_t` is destructed, the `m__io__raw_records` items of type `std::unique_ptr<kaitai::stream>` should be then deallocated automatically (at least I think). Will it work? I'd write it like this:

```cpp
void repeat_until_sized_t::_read() {
    m__io__raw_records = std::unique_ptr<std::vector<std::unique_ptr<kaitai::kstream>>>(new std::vector<std::unique_ptr<kaitai::kstream>>());
    m_records = std::unique_ptr<std::vector<std::unique_ptr<record_t>>>(new std::vector<std::unique_ptr<record_t>>());
    {
        record_t* _;
        do {
            std::unique_ptr<kaitai::kstream> io__raw_records(new kaitai::kstream(_buf));
            kaitai::stream* io__raw_records_rawptr = io__raw_records.get();
            m__io__raw_records->push_back(std::move(io__raw_records));

            _ = new record_t(io__raw_records_rawptr, this, m__root);
            m_records->push_back(std::move(std::unique_ptr<record_t>(_)));
        } while (!(_->marker() == 170));
    }
}

repeat_until_sized_t::~repeat_until_sized_t() {
}
```

Cc @ams-tschoening, @JaapAap, @mosolovsa

**Comment by ams-tschoening** [comment]
Does `record_t` destroy the given stream-pointer in its own DTOR? I guess not and then your suggestion seems safe to me and is in line with official examples:

> void sink(unique_ptr<widget>); // takes ownership of the widget
> void uses(widget*);            // just uses the widget

http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-uniqueptrparam

`uses` corresponds to `new record_t(io__raw_records_rawptr, this, m__root);`.

**Comment by webbnh** [comment]
The fact that your suggested code pulls the raw pointer out of the `unique_ptr` and passes it to the `record_t()` c'tor is a bit...disturbing.  So long as the `record_t()` c'tor doesn't store it, it's OK, but it's not exactly "robust" code.

Also, if we're targeting C++11 here, I think there are nicer idioms for dealing with smart pointers.  E.g., consider using [`emplace_back()`](https://en.cppreference.com/w/cpp/container/vector/emplace_back) instead of invoking the c'tor and passing the result to `push_back()`.  Unfortunately, [`make_unique()`](https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique) doesn't show up until C++14, but [`make_shared()`](https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared) is available in C++11, and you might want to consider using that at least for `io__raw_records()`.

**Comment by generalmimon** [comment]
@webbnh Thank you very much for your great suggestions and support. We have now this kind of memory leak eliminated thanks to you. Here are the final changes introduced to the generated code: https://github.com/kaitai-io/ci_targets/commit/839a7a3c02963cb459a392e276cc214a3b011ee8

I used `emplace_back()` as you suggested and it works great!

**Comment by webbnh** [comment]
@generalmimon, you are very welcome.  I'm glad that you were able to hammer out a workable solution.

KS has been very useful to us, so I am pleased to be able to "give back".
