### ISSUE TITLE
formats.kaitai.io: support tags

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#779]
In #572 we've added support for `meta/tags`, which allows more flexible navigation for formats repo. In #728, we were talking about adding documentation for that.

Now it's time to add that extra navigational support into where it will be most visible and useful — https://formats.kaitai.io.

The proposed design is very straightforward: instead of appearing only in one category, a file will appear in multiple categories — primary, as per directory structure, and secondaries, as per `meta/tags` contents.

**Comment by generalmimon** [comment]
> The proposed design is very straightforward: instead of appearing only in one category, a file will appear in multiple categories — primary, as per directory structure, and secondaries, as per `meta/tags` contents.

I believe this was exactly implemented in https://github.com/kaitai-io/kaitai_struct_formats/commit/13927c6daa5a3baf9771ce0910a04c2a2db21609 and has been already working for a while now, so I'm closing the issue.
