### ISSUE TITLE
Absolute import don't work in C++

### ISSUE THREAD

**Issue by kjczarne** [kaitai-io/kaitai_struct#794]
Hi, I've been trying to compile to cpp_stl and I've encountered something weird. I am not entirely sure if I am doing something wrong or whether this is a bug, so please excuse me if this seems like a newbie question ;)

I get warnings from IntelliSense that the `#include "/network/ipv4_packet.h"` and `#include "/network/ipv6_packet.h"` cannot be found:

```cpp
#include "kaitai/kaitaistruct.h"
#include <stdint.h>
#include <memory>
#include "/network/ipv4_packet.h"  // <-- no folder "network"
#include "/network/ipv6_packet.h"
```

The compiler dumps all files into a common folder without creating a `network` subfolder. Compiler command used was:
` ksc C:\Users\kczarnecki\Desktop\kissy\kissy\src\formats\network\pcap.ksy -t cpp_stl --cpp-namespace kaitai --cpp-standard 11`

Interestingly when I manually patch every `#include` directive to use header files from the same folder and compile the following code:

```cpp
#include <fstream>
#include <chrono>
#include <iostream>
#include "kaitaistream.h"
#include "pcap.h"

std::chrono::microseconds timing(std::string path){
    auto start = std::chrono::high_resolution_clock::now();

    std::ifstream is(path, std::ifstream::binary);
    kaitai::kstream ks(&is);
    kaitai::pcap_t data(&ks);

    auto stop = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start); 
    return duration;
}

int main(int argc, char *argv[]){
    for (int i = 0; i<argc; i++){
        std::cout << timing(argv[i]).count() << std::endl;
    }
}
```
I get a validation error, stemming from a seemingly incorrect magic number:
```
terminate called after throwing an instance of 'kaitai::validation_not_equal_error<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  /types/header/seq/0: at pos : validation failed:not equal
Aborted (core dumped)
```

I've set the KS_STR_ENCODING_NONE.

Parsing the very same PCAP with a Python build works perfectly. I'm using a kaitai struct compiler on Windows (commit 031c074b) and the freshest cpp runtime library version.

**Comment by generalmimon** [comment]
@kjczarne Thanks for reporting the bug! I found out that it has been demonstrated by test `ImportsAbs` (see [`imports_abs.h:8`](https://github.com/kaitai-io/ci_targets/blob/7bb24c298a9f14692cb9c6816a9e0a1c9c327469/compiled/cpp_stl_11/imports_abs.h#L8) before introducing the fix). The bug caused that the `ImportsAbs` test was failing for all C++ targets in the [CI dashboard](https://ci.kaitai.io/). 

I fixed it in commits https://github.com/kaitai-io/kaitai_struct_compiler/compare/07d71cce710eb253011f1bcd5775a0a90bef8136...f725faf548f42d7a7eb95f4808a6459f51284899 and the `ImportsAbs` test is passing for C++ in the dashboard, so I'm closing this issue.

**Comment by kjczarne** [comment]
Awesome, thank you! 😊
