### ISSUE TITLE
BitsType and BitsType1 inconsistent behavior

### ISSUE THREAD

**Issue by glass-ships** [kaitai-io/kaitai_struct#796]
I've returned to working on adding the Awkward target language and am attempting to get things compiling, but there appear to be some changes in the required arguments for BitsType and BitsType1.
When I attempt to compile with `sbt`, it returns: 
```
[error] /home/josh/dev/awkward-kaitai/kaitai_struct_compiler/shared/src/main/scala/io/kaitai/struct/languages/AwkwardCompiler.scala:54:12: pattern type is incompatible with expected type;
[error]  found   : io.kaitai.struct.datatype.DataType.BitsType1.type
[error]  required: io.kaitai.struct.datatype.DataType
[error] Note: if you intended to match against the class, try `case BitsType1(_)`
[error]       case BitsType1 =>
[error]            ^
[error] /home/josh/dev/awkward-kaitai/kaitai_struct_compiler/shared/src/main/scala/io/kaitai/struct/languages/AwkwardCompiler.scala:56:20: wrong number of arguments for pattern io.kaitai.struct.datatype.DataType.BitsType(width: Int,bitEndian: io.kaitai.struct.datatype.BitEndianness)
[error]       case BitsType(width: Int) =>
[error]                    ^
```

However, comparing AwkwardCompiler with CppCompiler and NimCompiler, I cannot see how my calls differ and why they're causing issues with Awkward but not Nim or anything else... 

![image](https://user-images.githubusercontent.com/26975530/89691193-91883080-d8c5-11ea-83e3-a7bd64314725.png)

Any input/help getting this to compile would be greatly appreciated!

**Comment by glass-ships** [comment]
To add, I only tried `case BitsType1 =>` at first, and at the error's suggestion added `(_)` which removes the first error. 

`BitsType(width: Int)` is however consistent with Nim and Cpp Compilers

**Comment by generalmimon** [comment]
@glass-ships `BitsType1` and `BitsType` are defined like this [in `DataType.scala`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/07d71cce710eb253011f1bcd5775a0a90bef8136/shared/src/main/scala/io/kaitai/struct/datatype/DataType.scala#L49-L50):

```scala
  case class BitsType1(bitEndian: BitEndianness) extends BooleanType
  case class BitsType(width: Int, bitEndian: BitEndianness) extends IntType 
```

This means that you have to match these case classes like this:

```scala
dataType match {
  case BitsType1(_) => ...
  case BitsType(width, _) => ...
}
```

Or alternatively like this:

```scala
dataType match {
  case bt1: BitsType1 => ...
  case bt: BitsType => ... // `bt.width` can be accessed here
}
```

See [Pattern matching](https://docs.scala-lang.org/tour/pattern-matching.html) in the Scala docs for more info.

If you wonder what the `BitEndianness` is, see https://github.com/kaitai-io/kaitai_struct/issues/155#issuecomment-613733627. This new feature requires every bit-integer type to keep track of its endianness, as you can now specify `type`s like `b1le`, `b27be` etc.

**Comment by generalmimon** [comment]
> `BitsType(width: Int)` is however consistent with Nim and Cpp Compilers

The current [`master` branch](https://github.com/kaitai-io/kaitai_struct_compiler/tree/07d71cce710eb253011f1bcd5775a0a90bef8136) of the compiler is compiling normally, so it isn't possible that there is anything like `case BitsType(width) => ...` anywhere without specifying the second parameter like `BitsType(width, _)` (the `sbt` would report any such places with the error `wrong number of arguments for pattern ...`, as you posted).

If you're working on a separate branch for adding the awkward C++ support, have you merged `master` to your branch or rebased the branch onto `master`? If some merge conflicts showed up, how did you resolve them?

**Comment by glass-ships** [comment]
Thanks, @generalmimon ! 

It looks like there was indeed an issue merging the upstream changes, but I do see the correct calls to BitsType now! 

I have now cleared any errors due to changes, but run into the same issue I had before: 
```
[error] /home/josh/dev/awkward-kaitai/kscnew/shared/src/main/scala/io/kaitai/struct/languages/AwkwardCompiler.scala:206:8: object creation impossible, since method getCompiler in trait LanguageCompilerStatic of type (tp: io.kaitai.struct.ClassTypeProvider, config: io.kaitai.struct.RuntimeConfig)io.kaitai.struct.languages.components.LanguageCompiler is not defined
[error] object AwkwardCompiler extends LanguageCompilerStatic {
[error]        ^
[error] /home/josh/dev/awkward-kaitai/kscnew/shared/src/main/scala/io/kaitai/struct/languages/AwkwardCompiler.scala:208:16: method getCompiler overrides nothing.
[error] Note: the super classes of object AwkwardCompiler contain the following, non final members named getCompiler:
[error] def getCompiler(tp: io.kaitai.struct.ClassTypeProvider,config: io.kaitai.struct.RuntimeConfig): io.kaitai.struct.languages.components.LanguageCompiler
[error]   override def getCompiler(
[error]                ^
```

Perhaps it would be best to open a separate question issue for this?
