### ISSUE TITLE
Add const to kstream constructor parameter definition?

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#806]
It would be handy if the parameter for the [`kstream::kstream(std::string& data)`](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/7e420f9337eb31622bf289259424ca2d4f1dd5c4/kaitai/kaitaistream.cpp#L34]) were declared to be `const`.  The parameter is used in the initialization of [`std::istringstream m_io_str`](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/7e420f9337eb31622bf289259424ca2d4f1dd5c4/kaitai/kaitaistream.h#L254) whose constructor [takes a `const`](https://en.cppreference.com/w/cpp/io/basic_istringstream/basic_istringstream) (see the third overload):  
```cpp
explicit basic_istringstream( const std::basic_string<CharT,Traits,Allocator>& str,
                              std::ios_base::openmode mode = std::ios_base::in );
```

My KSY looks like this:
```yaml
...
      - id: payload_bytes
        size: payload_size
...
```
And when I want to parse the payload, I want to write my code like this:
```cpp
    kaitai::kstream ks(recordPtr->payload_bytes());
```
but it won't compile because `payload_bytes()` is defined like this:
```cpp
        std::string payload_bytes() const { return m_payload_bytes; }
```
(note the `const`).

I think the `const` in the definition of `payload_bytes()` is generally appropriate; and, I see no reason why `kaitai::kstream` shouldn't be declared compatibly.

Thanks!

**Comment by generalmimon** [comment]
Can't this be a breaking change in some cases? I have no idea how the `const`/non-`const` conversions work in C++, so I'm asking if any existing code instantiating the current `kaitai::kstream` class with the non-`const` parameter won't break when declaring the `std::string& data` parameter `const`.

**Comment by webbnh** [comment]
This change to the definition of the parameter affects only the accesses to the parameter made inside the function (adding `const` makes the access more restrictive, but it's compatible with the existing use).  This change would have no effect on calling code:  the previous contract was, "please give me a `string`"; with this change, it now says, "thanks for the `string`, I promise not to modify it" -- so, there's no change on the caller's side.

**Comment by webbnh** [comment]
For what it's worth, it's not a "conversion":  the presence of the `const` specifier limits accesses to the `string` object to only member functions with the `const` attribute.  These functions can also be applied to instances which don't have the `const` attribute, so adding the `const` attribute to the instance doesn't change the ability to invoke these methods.

The function in question actually receives a reference to the `string`.  My proposal is to add `const` to the reference -- this doesn't change the thing being referred to -- it only changes how it may be accessed by the calling code.

**Comment by generalmimon** [comment]
@webbnh Can you prepare a PR for that?

**Comment by webbnh** [comment]
Sure...but, I'm not in a position to build or test anything, unfortunately.  (I hacked the change into my 0.8 installation, and it seemed to work as hoped, but that's all that I can offer.)

And, since the change is just adding six characters to a file, I'm not sure that it won't be more effort for you to pull my change than it would be to type it in yourself.  :-)

But, yes, if you really want me to, I'll proceed...let me know.
