### ISSUE TITLE
Compiler complains that Java 11 is too old :/

### ISSUE THREAD

**Issue by abitrolly** [kaitai-io/kaitai_struct#813]
I downloaded JRE OpenJDK11U-jre_x64_linux_hotspot_11.0.8_10.tar.gz from https://adoptopenjdk.net/index.html and compiler 0.8 doesn't work with it.

```
✗ JAVA_HOME=kaitai-struct-compiler/jre kaitai-struct-compiler/bin/kaitai-struct-compiler

The java installation you have is not up to date
requires at least version 1.6+, you have
version 11.0.8

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

**Comment by KOLANICH** [comment]
>Compiler

Please call Katai Struct Compiler as `KSC`.

You can try to modify the shell script launching KSC.

**Comment by abitrolly** [comment]
Downloaded [Universal .zip](https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip) from https://kaitai.io/#download

**Comment by abitrolly** [comment]
@KOLANICH there is no `ksc` in this distribution.

**Comment by GreyCat** [comment]
Duplicate of #483. Already fixed in modern versions, can be worked around with `-no-version-check` with existing releases.

**Comment by abitrolly** [comment]
@GreyCat thanks. Missed that ticket.
