### ISSUE TITLE
Upper limit of a string

### ISSUE THREAD

**Issue by computerquip** [kaitai-io/kaitai_struct#817]
Sorry if this is answered somewhere in the docs, I can't seem to find anything that matches the exact thing I'm looking for.
I have a value that is a NULL-terminated string but can be no longer than 256 bytes (with NULL terminator included). I tried doing:
```ksy
      - id: name
        type: strz
        size: 256
        encoding: ASCII
```
but this seems to imply that the string *is* 256 bytes, not that the maximum is 256 bytes. This doesn't work for me since the field size depends on where the null-terminator is or if it reaches 256 bytes.
Is there anything that can describe what I'm wanting?

EDIT: It would also work if there was maybe an error that occurred if the null-terminator was past the 256-byte mark.

**Comment by generalmimon** [comment]
Although I personally wouldn't make these hard restrictions even if the spec does explicitly say it _(I'd rather stick to ["be liberal in what you accept from others"](https://en.wikipedia.org/wiki/Robustness_principle); e.g. if I'm parsing a file with a 260-byte name, I would try to parse it anyway, regardless of whether it strictly conforms to the spec or not)_, sure, it's possible.

You can enforce the 256-byte limit using the `valid/expr` key (https://github.com/kaitai-io/kaitai_struct/issues/435#issue-323332353).

Note that the `valid` key is **not available** in the stable 0.8 version, you need to fetch the latest development 0.9 _(use the unstable KSC from https://kaitai.io/#download or the [devel Web IDE](https://ide.kaitai.io/devel/) for compiling, and then link the `master` version of runtime for the language you want)_. 

I see two options how to use it in your situation:

1. Add a subtype with a string stretching to EOS and wrap this type to a null-terminated substream. The byte size of a substream can be accessed by [`_io.size`](https://doc.kaitai.io/user_guide.html#_streams):

   ```ksy
   seq:
     - id: wrapped_name
       type: str_eos
       terminator: 0
   types:
     str_eos:
       seq:
         - size: 0
           valid: # when this is `false`, a ValidationExprError is thrown
             expr: _io.size <= 256
         - id: s
           type: str
           encoding: ASCII
           size-eos: true
   ```

2. First read a zero-terminated byte array, check its size (again with `valid/expr`, using the attribute [`bytes.length`](https://doc.kaitai.io/user_guide.html#_byte_arrays)) and then reinterpret the byte array as string using the [`bytes.to_s(encoding)`](http://doc.kaitai.io/user_guide.html#_byte_arrays) method:

   ```ksy
   seq:
     - id: name_raw
       terminator: 0
       # no `type: ` = byte array in KS
       valid:
         expr: _.length <= 256
   instances:
     name:
       value: name_raw.to_s("ASCII")
   ```

Nice thing is that neither of these approaches bother to parse the actual string from raw bytes if the `<= 256` check fails.

BTW, any chance you're describing the SoundFont 2.04 format? If so, I have almost finished a KSY spec for this format (https://github.com/kaitai-io/kaitai_struct_formats/pull/293). If you're interested, let me know.

**Comment by computerquip** [comment]
No, I was making a parser for Microsoft CAB files, mostly for a way to figure out what Kaitai can do and is all about.

I think I will go with the simpler solution you suggested where I just allow any length of string since even though the spec says a specific size, I don't see any reason to limit to that length (outside of buffer optimization purposes maybe).

I put a link to the the ksy below if you want to look at it. For now I'll close the issue. Thanks for the help.

https://hastebin.com/ubazalidim.less

**Comment by KOLANICH** [comment]
A parser for a CAB? We are waiting for it for a long time.  Please register yourself in https://github.com/kaitai-io/kaitai_struct_formats and note that we have some drafts for CDF in the repo. Also please note https://github.com/kaitai-io/kaitai_compress , you will surely need it, since CAB uses custom compression algo.
