### ISSUE TITLE
Make the ./publish script reusable instead of "vendoring" it everywhere

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#819]
Right now, we have the `./publish` shell script **vendored** (i.e. copied) in every repo that needs to publish build results to some other repository _(on behalf of @kaitai-bot)_.

In fact, it seems that there are three versions of the script - I call them version **1**, **1.1** and **2**. 

Version **1.1** has one extra feature above **1**:
 - it proactively adds the GitHub RSA public key _(hardcoded in the script)_ to `~/.ssh/known_hosts` if it's not there

Version **2** has two extra features above **1.1**:
 - supports specifying non-default Git branch via `GH_REPO_BRANCH` bash variable _(used only in **ci_targets** repo though; in **kaitai_ci_ui** repo, there is just boring `GH_REPO_BRANCH=master`)_
 - if `rsync` is not found on `PATH`, it tries `/c/cygwin64/bin/rsync.exe`

Version **1**:

 - [**kaitai_struct_tests** / publish-targets](https://github.com/kaitai-io/kaitai_struct_tests/blob/3cb98ecd6d7793ce412d53b210bc6f4b595ed544/publish-targets)
 - [**kaitai_struct_webide** / publish](https://github.com/kaitai-io/kaitai_struct_webide/blob/7950b8df56dd36acaf56333add2aab270f439a37/publish)
 - [**kaitai_struct_doc** / publish](https://github.com/kaitai-io/kaitai_struct_doc/blob/e03f0b04de740015facf5acbcf6737ca54036161/publish)

Version **1.1**:

 - [**kaitai_struct_formats** / .github/publish](https://github.com/kaitai-io/kaitai_struct_formats/blob/53a38bd530bcb41d4eded7983cda61238046844b/.github/publish)

Version **2**:

 - [**kaitai_ci_ui** / publish](https://github.com/kaitai-io/kaitai_ci_ui/blob/51a7d6f5a10d4d69e2dc1f0aaa6c51310b8659bc/publish)
 - [**ci_targets** / publish](https://github.com/kaitai-io/ci_targets/blob/6aca1b7283577518a378a52f84387d86d7f646c6/publish)

I think that it totally makes sense to have a `publish` script in only one place and use it from all these repos.

Of course, we would need to make it accept parameters - I think CLI args (`./publish --outdir _build/html/ --repo formats-kaitai-io.github.io`) are the way to go. Environment vars would be easier to implement, but less transparent, they can be set on various places.

I'm not sure where should be this generic `publish` script placed though - https://github.com/kaitai-io/kaitai_struct seems to be a logical place, but I'm thinking about adding the repo with the script as a Git submodule to all the repos _(which is IMHO better than `git clone`-ing the repo, `curl`ing the file from raw.githubusercontent.com or other perversities)_, and it wouldn't make much sense to **add `kaitai_struct`** as a submodule to repo `kaitai_struct_tests` for example (it's supposed to be the other way around).

So maybe create a dedicated repository just for the `publish` script?

**Comment by GreyCat** [comment]
It would be even cooler if we could make a GitHub Action-compatible action. We can reuse existing shell script, wrapping it as [Docker action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action) or potentially rewrite it at all using [JavaScript action](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action).

**Comment by KOLANICH** [comment]
>wrapping it as Docker action

I am not sure that GH docker-based actions are as efficient as GitLab CI pipelines. I mean GH still loads an own Docker container with Ubuntu and a lot of build-related stuff. So loading an own container above it is just a waste of time and a bandwidth and other resources. Waste of bandwidth and resources is not our problem, if MS likes it, it is their choice, but waste of time is clearly not what we want.

**Comment by generalmimon** [comment]
Related: I've just deleted legacy script `update-ci-status` for the old CI (https://github.com/kaitai-io/kaitai_struct/commit/0068fe6df2f72cbb7a0373c631388430af2bf778).

**Comment by generalmimon** [comment]
I've created the repo https://github.com/kaitai-io/push-artifacts for the GitHub Action. I plan to run the action in a Docker container.

**Comment by generalmimon** [comment]
Hmm, I've just realized that it doesn't make much sense to package the script as a GitHub Action only, because we actually run most of the publish scripts in Travis CI, not GH Actions:

| repo / publish script | CI config invoking the script | CI running the script |
| - | - | - |
| [**kaitai_struct_tests** / publish-targets](https://github.com/kaitai-io/kaitai_struct_tests/blob/3cb98ecd6d7793ce412d53b210bc6f4b595ed544/publish-targets) | [**kaitai_struct** / .travis.yml](https://github.com/kaitai-io/kaitai_struct/blob/d9791ab1b4be5550783bd799ca3b71b085b3cff7/.travis.yml#L35) | Travis CI |
| [**kaitai_struct_webide** / publish](https://github.com/kaitai-io/kaitai_struct_webide/blob/7950b8df56dd36acaf56333add2aab270f439a37/publish) | [.travis.yml](https://github.com/kaitai-io/kaitai_struct_webide/blob/7950b8df56dd36acaf56333add2aab270f439a37/.travis.yml#L21) | Travis CI |
| [**kaitai_struct_doc** / publish](https://github.com/kaitai-io/kaitai_struct_doc/blob/e03f0b04de740015facf5acbcf6737ca54036161/publish) | [.travis.yml](https://github.com/kaitai-io/kaitai_struct_doc/blob/07197823bb832b7efbbe0dc792acfc563229594f/.travis.yml#L27) | Travis CI |
| [**kaitai_struct_formats** / .github/publish](https://github.com/kaitai-io/kaitai_struct_formats/blob/53a38bd530bcb41d4eded7983cda61238046844b/.github/publish) | [.github/workflows/main.yml](https://github.com/kaitai-io/kaitai_struct_formats/blob/53a38bd530bcb41d4eded7983cda61238046844b/.github/workflows/main.yml#L66) | GitHub Actions | 
| [**kaitai_ci_ui** / publish](https://github.com/kaitai-io/kaitai_ci_ui/blob/51a7d6f5a10d4d69e2dc1f0aaa6c51310b8659bc/publish) | [.travis.yml](https://github.com/kaitai-io/kaitai_ci_ui/blob/51a7d6f5a10d4d69e2dc1f0aaa6c51310b8659bc/.travis.yml#L11) | Travis CI |
| [**ci_targets** / publish](https://github.com/kaitai-io/ci_targets/blob/6aca1b7283577518a378a52f84387d86d7f646c6/publish) | [.travis.yml](https://github.com/kaitai-io/ci_targets/blob/6aca1b7283577518a378a52f84387d86d7f646c6/.travis.yml#L212) | Travis CI |

**Comment by generalmimon** [comment]
A checklist of the transition from `publish` script with hardcoded parameters to a parameterized script [**push-artifacts** / publish](https://github.com/kaitai-io/push-artifacts/blob/0a60b35/publish):

- [ ] [kaitai_struct_tests](https://github.com/kaitai-io/kaitai_struct_tests)
- [ ] [kaitai_struct_webide](https://github.com/kaitai-io/kaitai_struct_webide)
- [ ] [kaitai_struct_doc](https://github.com/kaitai-io/kaitai_struct_doc)
- [ ] [kaitai_struct_formats](https://github.com/kaitai-io/kaitai_struct_formats)
- [ ] [kaitai_ci_ui](https://github.com/kaitai-io/kaitai_ci_ui)
- [X] [ci_targets](https://github.com/kaitai-io/ci_targets)

**Comment by GreyCat** [comment]
I wonder if we can actually establish some kind of test bed for this script itself? In theory, it should be relatively straightforward: just publish a commit to some kind of scrap repo using Travis / AppVeyor / GH Actions for every PR to this script and/or every commit to master?

**Comment by GreyCat** [comment]
And, yeah, great work with extracting it, by the way! Looks really cool!

**Comment by GreyCat** [comment]
> Hmm, I've just realized that it doesn't make much sense to package the script as a GitHub Action only, because we actually run most of the publish scripts in Travis CI, not GH Actions

May be in some point in time it will make sense to fully migrate off Travis, actually, especially due to the [shutdown of travis-ci.org pending in ~2 months](https://discourse.julialang.org/t/reminder-travis-ci-org-shuts-down-on-december-31-2020/47234), so we'll need to migrate to either travis-ci.com or somewhere else.

**Comment by KOLANICH** [comment]
>fully migrate off Travis, actually, especially due to the shutdown of travis-ci.org pending in ~2 months

They are not closing Travis, they are forcing free users to go to `.com` domain, where they claim they now provide free services too. But it is a bad sign that a company cannot afford to pay for a yet another domain name.

IDK any good free CI, GitLab was the best, but since they continue to do bad things, like continue eliminating server-side HTML generatikn in favour of client-side JS, using Cloudflare and enabling their "Under attack" mode, that injects obfuscated JavaScript code, I cannot advice them anymore. SourceHut looks promising (also FOSS), but not the official service (I cannot say anything special about that, since I have personally never used that, but there is some info in the Net and some personal experience of chatting with Drew on IRC channel, where he told me that he decides if the feature itself is needed only after I implemented it, the nuance is that he gives free accounts to srchut to people who have contributed to its development by code).

There also some standalone gitlab instances, like gnome, kde and freedesktop, but KS is not a part of their ecosystem.

There is also "gitgud", but I personally don't trust them.

**Comment by generalmimon** [comment]
Closing as resolved, see https://github.com/kaitai-io/kaitai_struct/issues/819#issuecomment-717561553.
