### ISSUE TITLE
Migrate from Travis CI

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#824]
Following the discussion at Gitter (https://gitter.im/kaitai_struct/Lobby?at=5f9fe0f72a60f731f72da5b7):

> FYI, Travis CI now no longer provides unlimited CI for open-source projects, starting yesterday. Which they announce in a blog post today? https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> it might be easier to just migrate everything to GitHub Actions/CircleCI/whatever instead

Cc @dgelessus, @GreyCat 

I'll put a checklist here tracking the progress _(based on https://github.com/search?q=org%3Akaitai-io+path%3A**%2F.travis.yml&type=code)_:

- [x] [**ci_targets** / .travis.yml](https://github.com/kaitai-io/ci_targets/blob/4e2830c/.travis.yml)
- [x] [**kaitai_struct** / .travis.yml](https://github.com/kaitai-io/kaitai_struct/blob/4473547/.travis.yml)
- [x] [**kaitai_struct_doc** / .travis.yml](https://github.com/kaitai-io/kaitai_struct_doc/blob/f4bf35e/.travis.yml)
- [x] [**kaitai_struct_webide** / .travis.yml](https://github.com/kaitai-io/kaitai_struct_webide/blob/5b1ec3f/.travis.yml)
- [x] [**awesome-kaitai** / .travis.yml](https://github.com/kaitai-io/awesome-kaitai/blob/13d1834/.travis.yml)
- [x] [**kaitai_ci_ui** / .travis.yml](https://github.com/kaitai-io/kaitai_ci_ui/blob/f89dce4/.travis.yml)

**Comment by generalmimon** [comment]
I got an impression that @abitrolly doesn't understand why I suggest switching from Travis to GitHub Actions. Here is a bit more detailed justification:

@abitrolly If there is another CI service with significantly better conditions for OSS projects, please share it. We just can't use Travis CI. The point is that I don't have anything against Travis, but they do have something against us (i.e. OSS projects that use Travis for free) - please read the article https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing (mainly the [_Building on a public repositories only_](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only)  section). In my opinion, they made it quite clear that they want us to "pay or leave":

> * For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

Simple math is coming: our regular CI pipeline (if compiler is updated) consists of the following builds (I'm only counting those on Travis):

* [`kaitai_struct`](https://travis-ci.com/github/kaitai-io/kaitai_struct): ~6 min on Linux
* [`kaitai_struct_webide`](https://travis-ci.com/github/kaitai-io/kaitai_struct_webide): ~1 min on Linux
* [`ci_targets`](https://travis-ci.com/github/kaitai-io/ci_targets): ~42 min on Linux, ~10 min on macOS

As you can see, one CI build consumes approximately 49 minutes on Linux and 11 minutes on macOS. After they migrate us to the trial (free) plan with 10K credits, where one minute costs 10 credits on Linux and 50 credits on macOS, one build run will consume `49 * 10 + 11 * 50 = ~1000` credits, so we can run `10000 / 1000 = 10` builds.

After we run out of credits, we can refill 25K of them for $15, thus 10K cost $6. If you're willing to spend $6 monthly for this, then great, we would get 10 builds per month, which isn't much, we would have to tighten our belt (the more credits, the better, of course). If you don't want to do that, they say you can write e-mail requests for OSS credit allotment:

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
> * Your account name and VCS provider (like travis-ci.com/github/[your account name] )
> * How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or **discuss a renewable amount**)

The _renewable amount_ seems to be the most promising. If we were regularly getting a sufficient amount, the problem with credits could be done for good _(well, at least until the next change of their conditions)_, but I don't know if they would grant us that.

So even though there are some options how to stay on Travis, I don't think it's worth the trouble. As I said, I think their message is clear, and I suppose the situation is not gonna improve in the future - only worsen, if something.

**Comment by abitrolly** [comment]
@generalmimon while I understand your rage against Travis with 1000 free minutes and hardships of communicating the need with service that became not-so-friendly, I just want to remind of the good service they've made over these years to the open source community hosted on GitHub. Now that GitHub is owned by MS, who slowly and steadily kills all the competition. I don't see this act of Travis as inherently evil, but rather as a will to survive. The suggestion interface for GitHub doesn't propose to install Travis actions, you know, and the argument about "one less service" pops every time I send a PR for add CI/CD to another OSS project on GitHub. Now that MS provided container hosting, DockerHub also placed their own limits. MS has the money to shut all the competition, and commercial services tend follow what people are familiar with. I am no surprised if Travis and DockerHub are losing client, because of this. To me this is good case for anti-monopoly study in economics.

Now about the GitHub Actions. Yesterday I was indifferent about what service to use, but I discovered that GitHub Actions [retain build logs max for 90 days](https://github.blog/changelog/2020-10-08-github-actions-ability-to-change-retention-days-for-artifacts-and-logs/) and they propose to delete them sooner rather than retain longer. For Travis I've got an impression that they are keeping the build logs forever. Frankly, log data is something that is repeated from build to build with the exception of timestamps, and it could be very efficiently compressed with shared dictionaries across repos. This is what I would expect from a big company like MS to research. Not how to build a Docker Store with cached layers across repos (which any student can do).

To be truly open source, there are two public options - GitLab and https://sr.ht - the latest has all the messages you need. ) While I have strong opinion about MS and GitHub Actions, I don't mind getting the automation done its way. I am from Belarus, you know - sometimes there is nothing you can do.

**Comment by GreyCat** [comment]
Hey all, wanted to give some update as per current situation:

* Travis still works (kind of), but effectively we've lost control of it. At least for me, it requires me to sign on some kind of trial plan, which I don't really want to invest time exploring (and potentially lose money).
* [ci_targets](https://github.com/kaitai-io/ci_targets) is the most difficult thing to migrate, but there are some good news:
  * I've experimented porting more things in "traditional" way (by utilizing resources provided by CI, staying in CI's framework). C# on .NET Core (thanks to @generalmimon) and Java works this way — see [this run](https://github.com/kaitai-io/ci_targets/actions/runs/5406194401).
  * My experiments with [Docker images](https://github.com/kaitai-io/kaitai_struct_docker_images) seem to yield some good fruits in automated CI launches too. The good news is that we can reasonably easy switch from environments provided by GH Actions to builds 100% repeatable locally using Docker images we can build completely bypassing GH Actions (or any specific CI), so we're vendor lock-free.
  * Build times for "traditional" vs "dockerized" builds are very comparable, see [results of PR build here](https://github.com/kaitai-io/ci_targets/actions/runs/5442323179):
    * Java temurin11-temurin17 builds take ~41-43 seconds traditional vs ~41-50 seconds dockerized. The difference seems to be neglible.
    * Builds for lightweight languages which provide Alpine-based containers are even faster: 17-33 seconds for dockerized JavaScript, Python, Ruby. In reality, most of that time is taken by artifacts publishing / git update, rather than the build itself, so it looks like a very good result to me.

With this one, I'm planning to start sunsetting Travis at least for ci_targets, switching it completely to GH Actions dockerized. Please share any feedback you might have.

**Comment by generalmimon** [comment]
@GreyCat:

> * Travis still works (kind of), but effectively we've lost control of it. At least for me, it requires me to sign on some kind of trial plan, which I don't really want to invest time exploring (and potentially lose money).

Hmm... Can you elaborate on the "lost control" part - show screenshots and stuff? I must admit that I'm a bit worried right now, because at https://app.travis-ci.com/account/repositories where a week ago was the `kaitai-io` org tab is now this:

![image](https://github.com/kaitai-io/kaitai_struct/assets/47499687/64d2ed87-18e9-4782-bd90-f63c54bab595)

Were you adjusting some settings? What do you see there? What does the prompt to sign up for the "trial plan" as you mentioned look like?

**Comment by generalmimon** [comment]
Ad my previous comment: not sure what happened, but it's at least back as it was.

![image](https://github.com/kaitai-io/kaitai_struct/assets/47499687/918a5d23-a8db-4d9b-a217-8e9cf998975e)

**Comment by generalmimon** [comment]
@GreyCat:

> * It quickly runs out of minutes, though, and builds gets disabled: https://app.travis-ci.com/github/kaitai-io/ci_targets
>   > Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/kaitai-io/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/kaitai-io/plan?anchor=oss-consumption).

I agree that the experience with Travis is a bit strange, but last time I checked they declare that the service is still free for open-source projects. The first time we were low on credits was in December 2021, when I wrote to Travis Support (@GreyCat I believe I was forwarding all these e-mails to your inbox `greycat@kaitai.io`, but I'm not sure whether you're getting them) and we received one-off 25k credits, which in fact took us some time to consume because we usually aren't launching our main CI pipeline launches that often. I believe the number of credits consumed by our full CI pipeline is normally still ~1000 (as I roughly calculated in https://github.com/kaitai-io/kaitai_struct/issues/824#issuecomment-730686323). Of course it helps to cancel some jobs in the full early when you were only modifying one target language, so you can let only that one run and not the others.

A bit of a strange occurrence (which I believe impacted multiple, if not most, Travis users, because it happened on the `kaitai-io` account as well as on my personal account) was in January this year, when I found that our pipelines on Travis do not run with this message:

> Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/kaitai-io/plan) to replenish your credit balance.

Which was weird, because on January 31 we apparently still had 6620 credits on our `kaitai-io` account, so the "negative credit balance" didn't make sense. So I wrote to Travis support again and they resolved it very quickly (in the matter of minutes).

To summarize, even though it would be of course easier for us if we didn't have to worry about _how many credits_ we have, so far it didn't take more effort than one e-mail to resolve any problem with that and at least Travis Support in my experience responds in a timely manner. According to Travis FAQ, it should be also possible to negotiate "recurring allotment", which I've tried to pitch on both occasions when I wrote them, but they apparently prefer one-time allotment which I was satisfied with at the time.

---

@GreyCat I'm just saying that for now I believe it's possible to stay on Travis, if we want. But I can also well understand the decision to leave Travis. Even though I generally like the UI and features of Travis the most. GitHub Actions are a good choice too, but the maximum log retention of 90 days is annoying to say at least (in practice you get the "The logs for this run have expired and are no longer available." message most of the time). And Travis also has a wider support of supported platforms and architectures, for example, which may be particularly useful for testing the C++ runtime library.

**Comment by generalmimon** [comment]
@GreyCat:

> * My experiments with [Docker images](https://github.com/kaitai-io/kaitai_struct_docker_images) seem to yield some good fruits in automated CI launches too. The good news is that we can reasonably easy switch from environments provided by GH Actions to builds 100% repeatable locally using Docker images we can build completely bypassing GH Actions (or any specific CI), so we're vendor lock-free.

Good to hear! Although I'm a bit skeptical when it comes to Docker, mainly because despite my limited experience with it, I'm already used to getting all sort of issues on my Windows machine (Docker Engine crashes, Docker Engine takes forever to start, etc.). I've already had to reinstall it several times.

> 100% repeatable

That's what they say, but it's not entirely true in my experience. For example, when I tried to run [this image](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/cd8e2d0ce8fbe82c1b1fef8a2e9645457ea78257/.github/workflows/build.yml#L51) on my computer, both `sh` and `bash` (but not for example `ls`, which was working fine) were immediately segfaulting without any message (I just figured that it was a segfault because the exit code was 139). But the same image clearly works in GitHub Actions. Perhaps it has something to do with the Linux kernel (which Docker runs on top of), but that's just my wild guess.

> With this one, I'm planning to start sunsetting Travis at least for ci_targets, switching it completely to GH Actions dockerized.

Feel free to go ahead, I appreciate your effort! Despite what I wrote above, I believe (and hope) the positives will in fact outweigh the negatives (and I suppose that our CI jobs run in Docker containers implicitly used all the CI services we use). Just noting that it's most likely not the silver bullet and it certainly doesn't solve all problems (and in some cases, it may very well create some new problems).

**Comment by GreyCat** [comment]
> Good to hear! Although I'm a bit skeptical when it comes to Docker, mainly because despite my limited experience with it, I'm already used to getting all sort of issues on my Windows machine (Docker Engine crashes, Docker Engine takes forever to start, etc.). I've already had to reinstall it several times.

As far as I recall, realistically these are 3 different products: Docker for Linux, Docker for Mac, Docker for Windows. Windows one is, in theory, most universal (it can run both Windows containers and Linux containers using a WSL2-like VM), but I agree that I've heard more than once people saying it's not super stable. Docker for Linux (or any other containerization solution like [podman](https://podman.io/)) is rock solid and I've never heard of anybody encountering problems with it. Docker for Mac combines worst of both worlds (it has to run a Linux VM + there are no native features like running MacOS at all).

> For example, when I tried to run [this image](https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/blob/cd8e2d0ce8fbe82c1b1fef8a2e9645457ea78257/.github/workflows/build.yml#L51) on my computer, both sh and bash (but not for example ls, which was working fine) were immediately segfaulting without any message (I just figured that it was a segfault because the exit code was 139). But the same image clearly works in GitHub Actions. Perhaps it has something to do with the Linux kernel (which Docker runs on top of) unable to load and execute the ELF binary embedded in the Docker image, but that's just my wild guess.

I guess it indeed has something with a Windows implementation of Docker (or potentially WSL2). A Linux VM (remote or local) might be a simpler choice.

> Feel free to go ahead, I appreciate your effort! Despite what I wrote above, I believe (and hope) the positives will in fact outweigh the negatives (and I suppose that our CI jobs already run in Docker containers implicitly created in all the CI services we use). Just noting that it's most likely not the silver bullet and it certainly doesn't solve all problems (and in some cases, it may very well create some new problems).

Thanks for the feedback! I'm absolutely with you when you say that's not a silver bullet, and tons of different problems remain and some new problems will arise, but at least I'm confident that the net sum is making lives of both maintainers and people who want to start contributing to KS a bit better. Realistically, with zillions of languages we support, it's kind of pointless to expect people to install them all manually on their machine just to run tests locally, and this quickly kills the initiative.

**Comment by GreyCat** [comment]
Arguably, I'm ready to call "ci_targets" migration from Travis to GHA done.

The two last ones left there are:

1. rust 1.31.1 — doesn't seem to work, so probably better off starting from scratch as a separate item.
2. csharp/mono5.18.0 — relies on rather ancient Mono in Xenial distribution. Benefits of supporting Mono per se nowadays are not very clear to me. When I've set this up initially, my only motivation was to get C# somehow to compile on Linux — nowadays, .NET Core/Standard is cross-platform, and perfectly does that. Mono seems to be a very niche solution to run .NET Framework 4.5 builds on Linux, and I'm not sure if anybody is still interested in that. I've tried to build Docker image based on modern Mono 6.12, and so far I haven't got it to work due to many mysterious build errors. When and if at some point anybody will get interested in resurrecting this — feel free to take over.

**Comment by generalmimon** [comment]
@GreyCat:

> Arguably, I'm ready to call "ci_targets" migration from Travis to GHA done.

Thanks a lot for your tremendous work on this! Our presence on Travis was unsustainable in the long run, and it's clearly very liberating to stop worrying about when we'd run out of credits again and whether they would still grant us some credits for free this time or not.

And of course, on top of that, the approach with Docker images should in theory reduce our vendor lock-in in the future, as well as simplify local testing too, so those are great benefits as well.

**Comment by generalmimon** [comment]
This is now complete - all our [repos using Travis](https://github.com/kaitai-io/kaitai_struct/issues/824#issue-738273584) have been migrated to GitHub Actions.

The only remaining `.travis.yml` config is https://github.com/kaitai-io/ci_targets/blob/e39b87ec9fab62018ba77d06c13577b3b28cdc8f/.travis.yml, but that only serves as a reference for targets that didn't work anyway (probably it doesn't even have much value and we might as well remove it, though).
