### ISSUE TITLE
Large unsigned 64-bit integer literals are not generated correctly in Lua

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#837]
When targetting Lua, the compiler currently writes all integer literals as decimal (unsurprisingly). When the value of a decimal integer doesn't fit into a signed 64-bit integer, Lua silently converts it to a float, losing precision. This causes problems with the way Kaitai Struct represents unsigned 64-bit integers in Lua (see #836) - such unsigned integers are actually represented as negative *signed* 64-bit integers to maintain precision. As a result, equality checks between unsigned 64-bit integers read from a file and ones written literally in a KSY currently fail. This problem can be seen in the [`integers`](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/spec/ks/integers.kst#L10-L11) test ([generated Lua code](https://github.com/kaitai-io/kaitai_struct_tests/blob/0a5935def4af6615b6d7e60c75ea229eca8bec0c/spec/lua/test_integers.lua#L15)):

> Message: spec/lua/test_integers.lua:15: expected: 1.844674407371e+19, actual: -1

The solution would be to write large unsigned 64-bit integers (that are outside of the signed 64-bit integer range) as hexadecimal literals instead. Unlike decimal literals, Lua doesn't automatically convert hexadecimal literals to float, and instead wraps/overflows them in the same way that Kaitai Struct does when reading. A similar solution was also implemented for Java, which also doesn't have unsigned 64-bit integers and uses a similar workaround (see #835): kaitai-io/kaitai_struct_compiler@dbda9b765e1c57f8e2e5dcfcf7d33dc7b1e8e48e

Originally reported in kaitai-io/kaitai_struct_lua_runtime#13.

**Comment by generalmimon** [comment]
Resolved in https://github.com/kaitai-io/kaitai_struct_compiler/commit/fd7f308c67e8eacee98a647bbbbfb2792505bc64

Associated test cases were added in https://github.com/kaitai-io/kaitai_struct_compiler/commit/e33828a6d2dd7f41ed246f0bf80a3097d8f5c95e#diff-7c823ef11d5f6057f03870838146d08a796b5252bb5221db4b4df5fb0c79647c.
