### ISSUE TITLE
ksc: add option to save compilation output as json

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#85]
If we compile multiple files at once currently and we want to see which file for which platform was compiled successfully and which not then we have to parse the text output currently which could result further bugs.

One of the proposed solutions is to store the compilation result (success or failure) and the potential exception text into a strictly-typed file format (ex. json).

**Comment by GreyCat** [comment]
Just realized that it's a must for multi-file compilation units, such as ones that we've got with imports support. Will try to do something here.

**Comment by GreyCat** [comment]
Ok, here's what I propose to output:

```javascript
{
  "input.ksy": {     // name of input file
    "success": true, // if false, compilation result can't be used
    "errors": [      // an array of errors, missing if no errors encountered
      {
        "path": ["seq", "4", "type"],                // YAML path
        "message": "Something is wrong, blah, blah", // error message text
        "file": "input"                              // file or class where it happened
      }
    ],
    "type_top": "input",               // name of first type (i.e. top-level in main file)
    "output": {
      "cpp_stl": {                     // per lang objects
        "input": {                     // name of top-level type in source file
          "files": [                   // array of files generated due to this source
            "input.cpp",               // in no particular order
            "input.h"
          ],
          "id": "input_t"              // top-level type ID in target lang, i.e. top class name
        },
        "imported": {                  // this one wasn't on command line, but it was imported
          "files": [
            "imported.cpp",
            "imported.h"
          ],
          "id": "imported_t"
        }
      },
      "ruby": {                        // same stuff for another language
        "input": {
          "files": [
            "input.rb"
          ],
          "id": "Input"
        },
        "imported": {
          "files": [
            "imported.rb"
          ],
          "id": "Imported"
        }
      }
    }
  }
}
```

What do you think of this? It can be also used in theory as JS output.

**Comment by GreyCat** [comment]
Here's what I've got: https://gist.github.com/GreyCat/79f4d7499a39c5443935653afbb46369

Would it be helpful in JS API?

**Comment by GreyCat** [comment]
I've fixed console visualizer to use this structure, so I'm tempted now to close this issue as solved. Any objections?

**Comment by koczkatamas** [comment]
No. I think it can be closed.

We discussed privately that this will be available in JS too. Does that still stand?

Although I won't use it right now, if it needs any modification, I will create a new issue (probably in the not-that-near future).

**Comment by GreyCat** [comment]
Implementing it for JS will break current API, so it would need some updates in Web IDE as well. I suggest that we'll create a separate issue for that to coordinate ourselves.
