### ISSUE TITLE
Question: How to import multiple types from another file

### ISSUE THREAD

**Issue by kmrsh** [kaitai-io/kaitai_struct#850]
I wen through the documentation and it has provided how you can import a type from a different file. (for single type this is fine and we may have to have a file for each type with this, I've also noted that web IDE tool cannot have imports and correct me if I'm wrong)

What I want is group certain types which are related to certain records type into one file and then import that file to refer the types defined in that. How do you do that

ex: say I have a `main.ksy` as below

~~~yml
meta:
  id: event_x500
  endian: be
  imports:
    - file_header
    - chr_header

seq:
  - id: file_header
    type: t_file_header # this is from `file_header` import
  - id: chr_header
    type: t_chr_header # this is from `chr_header` import
    repeat: eos

types:
  ...
  ...
~~~

`file_header.ksy`

~~~yml
meta:
  id: t_file_header
  endian: be
seq:
  - id: main_version
    type: u1
  - id: sub_version
    type: u1
~~~

`chr_header.ksy`

~~~yml
meta:
  id: t_chr_header
  endian: be
seq:
  - id: event_id
    type: u2
  - id: event_length
    type: u4
~~~

Now the question is how can I put both `t_chr_header` and `t_file_header` into single file and import it. Can't we have `types` section without `seq`, which I tried but didn't work

ex: something like this

`common_headers.ksy`

~~~yml
meta:
  id: common_headers
  endian: be
types:
  t_chr_header:
   seq:
     - id: event_id
       type: u2
     - id: event_length
       type: u4 

  t_file_header:
    seq:
      - id: main_version
        type: u1
      - id: sub_version
        type: u1  
~~~

and then in `main.ksy`

~~~yml
meta:
  id: event_x500
  endian: be
  imports:
    - common_headers

seq:
  - id: file_header
    type: t_file_header # this is from `common_headers` import
  - id: chr_header
    type: t_chr_header # this is from `common_headers` import
    repeat: eos
~~~

**Comment by dgelessus** [comment]
> Now the question is how can I put both `t_chr_header` and `t_file_header` into single file and import it. Can't we have `types` section without `seq`, which I tried but didn't work

How exactly does it not work - what error do you get?

Your example here is almost correct - you just need to add an explicit `common_headers::` prefix when you use the types from the `common_headers` spec:

```ksy
seq:
  - id: file_header
    type: common_headers::t_file_header
  - id: chr_header
    type: common_headers::t_chr_header
    repeat: eos
```

Currently there's no way to avoid having to add this prefix - you can't directly import nested types from another spec.

> I've also noted that web IDE tool cannot have imports and correct me if I'm wrong

The Web IDE has some limitations/bugs with imports, specifically with directories - see kaitai-io/kaitai_struct_webide#30. But as long as your `imports` are just simple names (like in your examples) and don't use slashes, they should work in the Web IDE.

**Comment by kmrsh** [comment]
@dgelessus yes without `common_headers::` prefix it gives the following error
~~~
~~~
