### ISSUE TITLE
Flat representation of all fields

### ISSUE THREAD

**Issue by Fee0** [kaitai-io/kaitai_struct#858]
Hi, I created a simple grammar and a parser in python. Now would like to have a flat represention of all fields of my data. Basically, for every byte of my data I want to know the field of my grammar. Similar to the web Ide of Kaitai Struct in the hex view where every field is mapped to the data. Is there a way to get this information from my parser?

**Comment by KOLANICH** [comment]
>Basically, for every byte of my data I want to know the field of my grammar.

Very easy. Enable `store_pos` mode of compilation and the code will generate a dict mapping fields to bytes. Then you can use my lib `rangeslicetools` to create an index and map bytes to fields.

**Comment by KOLANICH** [comment]
>I created a simple grammar and a parser in python.

BTW, we have a collection of formats: https://github.com/kaitai-io/kaitai_struct_formats
