### ISSUE TITLE
Creating Substreams of unknown size

### ISSUE THREAD

**Issue by ElectricVersion** [kaitai-io/kaitai_struct#868]
I'm currently trying to parse a file format that uses a number of offsets from positions that are, themselves, offset. According to the documentation, the solution would be substreams - but the problem is that many of these sections do not have a fixed size or terminator. Their length can be calculated based on preexisting information, but this would lead to some very complex and unwieldy calculations. Is there a way to create a substream of unknown size? 

Example: I'm decoding a 3d model format, and one section's length depends on the number of objects, as well as certain flags within the section. Since I can't set the section's size based off something inside the section, how do I position it correctly?

**Comment by generalmimon** [comment]
> Is there a way to create a substream of unknown size?

No. See https://github.com/kaitai-io/kaitai_struct/issues/679#issuecomment-576713927:

> But you can create a substream only if you know its final size, as you can't resize it later. A resizable substream would kind of lose the main reason for creating a substream, i.e. limiting some structure in size when you know that size in advance.

Read that comment to see the solution of this problem. In essence, it is the following pattern, which stores the current offset in `seq` anywhere you need it (and you can subsequently use the value of `ofs_some_field` in `pos` of an `instance`):

```ksy
seq:
  - size: 0
    if: ofs_some_field < 0 # this expression does not actually matter,
                           # but has to involve 'ofs_some_field'
  - id: some_field
    type: ...
    size: ...
instances:
  ofs_some_field:
    value: _io.pos
  some_field_inst:
    pos: ofs_some_field
    # ...
```

It is a very versatile trick, so you'll be able to achieve any `instance` lookup even if everything is dynamic sized and you're not really able to calculate it with an arithmetic expression.

Also, if by chance you'd need to add/subtract the size of some structure which has a fixed size (known at compile time), you can use the virtual `sizeof` operator (https://github.com/kaitai-io/kaitai_struct/issues/84#issuecomment-486645268). See the [0.9 release notes](https://kaitai.io/news/2020/10/16/kaitai-struct-v0.9-released.html):

> - Implement compile-time `sizeof` and `bitsizeof` operators (#84)
>   - Type-based: `sizeof<u4>`, `bitsizeof<b13>`, `sizeof<user_type>`
>   - Value-based: `file_header._sizeof`, `flags._bitsizeof` (`file_header`, `flags` are fields defined in the current type)

**Comment by ElectricVersion** [comment]
Interesting. Thanks for the info, its very helpful!
