### ISSUE TITLE
how to pass enums in params?

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct#872]
Right now I am working on a spec where there are two data structures that are identical. The only difference is that they both use a different enum (with overlapping values, so I cannot merge them). I want to use params for this, so something like:

```ksy
type_a:
  params:
    - id: tag_enums
  seq:
    - id: tag
      enum: tag_enums
```

but this doesn't seem to work. What am I doing wrong?

**Comment by generalmimon** [comment]
> The only difference is that they both use a different enum (with overlapping values, so I cannot merge them). I want to use params for this

You can't. It would be nice to be able to define a "template" type and reuse it while one of the inside field has a variable type (or variable enum, makes no difference), but that's not trivial in static-typed languages. So we'll need to introduce a new concept of type templates (https://github.com/kaitai-io/kaitai_struct/issues/135) into the KS language.

In principle, we need something like this: https://stackoverflow.com/q/1735796

**Comment by armijnhemel** [comment]
Thanks, would indeed be good to have. In the meantime I will just have to put up with some duplication.
