### ISSUE TITLE
How to access pos of an element?

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct#873]
I am currently working on a spec where I have a list of offsets which are in a sibling object. The relative offsets are stored in "signature_index_records" but the data is in "storage_section". What I am doing now is this:

```ksy
  signature:
    seq:
      - id: header_record
        type: header_record
      - id: index_records
        type: signature_index_record
        repeat: expr
        repeat-expr: header_record.index_record_count
      - id: storage_section
        size: header_record.index_storage_size
  signature_index_record:
    seq:
      - id: tag
        type: u4
        enum: signature_tags
      - id: record_type
        type: u4
        enum: header_types
      - id: record_offset
        type: u4
      - id: count
        type: u4
    instances:
       body:
          #io: _parent.storage_section._io
          io: _parent._io
          #pos: _record_offset
          pos: _parent.storage_section.pos + record_offset
```

but that isn't working in the IDE. What am I doing wrong? How can I make sure that I can access the data in "storage_section" using the offsets?

**Comment by KOLANICH** [comment]
You can try to add `type: dummy` to `storage_section`. Then you would be able to use its `_io`.

**Comment by armijnhemel** [comment]
This worked beautifully. Thank you!
