### ISSUE TITLE
Trying to install kaitai-struct-compiler in Ubuntu 16 docker container, fails unmet dependency

### ISSUE THREAD

**Issue by kovar-ursa** [kaitai-io/kaitai_struct#884]
Greetings,

Due to Bintray's sunsetting, the best method for installing kaitai-struct-compiler is via the deb packages. Unfortunately, when I try that approach in a Ubuntu 16 docker container, I get:

`kaitai-struct-compiler : Depends: java8-runtime-headless but it is not installable`

Is there a short term fix or should I wait for the new hosting solution?

Thank you.

-David

**Comment by KOLANICH** [comment]
KS debs are already hosted on "another hosting".

**Comment by kovar-ursa** [comment]
Greetings,

This is what we used to do:

`RUN echo "deb https://dl.bintray.com/kaitai-io/debian jessie main" > /etc/apt/sources.list.d/kaitai.list \
     && apt-get update && apt-get install --assume-yes --no-install-recommends \
     kaitai-struct-compiler \
     default-jre \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*`

This no longer works.

The proposed solution:

`RUN curl -LO https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.9/kaitai-struct-compiler_0.9_all.deb \
    && apt-get install ./kaitai-struct-compiler_0.9_all.deb`
    
Fails due to the missing java8 dependency.

The kaitai web page says:

`We're currently setting up an alternative repository to replace Bintray, which will be available on a custom domain packages.kaitai.io to be future-proof, so stay tuned!`

Thus my reference to a new hosting solution.

-David

**Comment by KOLANICH** [comment]
https://cloudsmith.io/~kaitai/repos/debian-unstable/packages/?PageSpeed=noscript

**Comment by kovar-ursa** [comment]
Thank you very much.

For anyone else looking to do this:

`RUN apt-get install -y apt-transport-https \
    && curl -1sLf 'https://dl.cloudsmith.io/public/kaitai/debian-unstable/gpg.4BFDFCB07CCCBF29.key' | apt-key add - \ 
    && curl -1sLf 'https://dl.cloudsmith.io/public/kaitai/debian-unstable/config.deb.txt?distro=debian&codename=wheezy' > /etc/apt/sources.list.d/kaitai-debian-unstable.list \
    && apt-get update && apt-get install --assume-yes --no-install-recommends \
    kaitai-struct-compiler \
    default-jre \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*`

**Comment by GreyCat** [comment]
@KOLANICH @kovar-ursa  - I would seriously advise *not* to take dependencies on Cloudsmith URLs as these are going to change without any notice given.

If you want to install 0.9 in a pipeline - downloading it from GitHub releases and installing manually is a way to go. Please refer to Debian package installation documentation or at least to [this StackExchange question](https://superuser.com/questions/196864/how-to-install-local-deb-packages-with-apt-get/1244531) on how to install .deb package locally with the dependencies. `gdebi`, `apt install`, or `dpkg -i` + `apt-get -f install` would work.

**Comment by KOLANICH** [comment]
>I would seriously advise not to take dependencies on Cloudsmith URLs as these are going to change without any notice given.

Thanks for the info.
