### ISSUE TITLE
Add KSY schema to SchemaStore

### ISSUE THREAD

**Issue by jmerdich** [kaitai-io/kaitai_struct#906]
Kaitai has a schema in [its own repo](https://github.com/kaitai-io/ksy_schema)-- which is great! What'd be even more great is to automatically use it for code-completion in various IDEs, which involves keeping that schema up-to-date in the [SchemaStore](https://github.com/SchemaStore/schemastore) repo.

This can be set up manually from the kaitai repo today or by including the magic comment below in ksy files (only tested on VS Code), but it'd be awesome to get autocomplete "for free" by having a copy in their repo. 

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/kaitai-io/ksy_schema/master/ksy_schema.json
```

**Comment by KOLANICH** [comment]
Why do you ask us instead of just sending a PR doing that into their repo?

**Comment by jmerdich** [comment]
Long-term maintenance and that the stewards of the project may have their own opinions on this? Submitting a PR today is easy. Ensuring that it gets maintained takes buy-in (or at least awareness) from the folks who maintain the ksy_schema repo or me watching for changes on that repo and silently mirroring it behind their backs. Many specs have that as the only "canonical" place for their specs, and I certainly can't make that decision on my own.

Altogether, better to gauge interest first?

**Comment by GreyCat** [comment]
@jmerdich Thanks for raising awareness for that, I absolutely agree that in the long term it makes all the sense to do it. I believe we can use our kaitai.io domain for guaranteed location not taking dependency on any hosting solutions to be future proof. Something like https://schema.kaitai.io/0.9/ksy_schema.json should probably do the trick?

**Comment by rotu** [comment]
I submitted a PR here https://github.com/SchemaStore/schemastore/pull/3683

**Comment by generalmimon** [comment]
@rotu:

> I submitted a PR here https://github.com/SchemaStore/schemastore/pull/3683

Oh, it's just a link to our repo? That's great, I thought we'd have to copy the JSON schema to their repo (and keeping two copies in sync long-term is unrealistic, let alone when we don't have control over one of the repos), this is so much better.

**Comment by rotu** [comment]
This issue should now be resolved.

**Comment by generalmimon** [comment]
@rotu Thanks for taking care of this!
