### ISSUE TITLE
Fix-length zero-padded string handling

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#91]
Let's take an example first: Mach-O file (mach_o.ksy), `segment_command_64` type, `segname` field (`type: str`, `size: 16`).

If we want to switch on this value in Javascript, then we have to use a fully 16-length value in .ksy, for example: `"'__cstring\0\0\0\0\0\0\0'"`. 

Surprisingly this compiles in almost every language:
 - cpp_stl (g++): shows `warning: null character(s) preserved in literal`), 
 - python: breaks with error `SyntaxError: EOL while scanning string literal`

But I am not sure that putting zero character into the source code is a good idea, so we should escape these characters or support `strz` with `size` which reads exactly `size` bytes, but strips the trailing zeros (terminator char).

**Comment by GreyCat** [comment]
We need both, actually, and both issues are already there, AFAIR:

* #77 - proper support for stuff like `\n`, `\0`, etc in strings
* #13 - supporting padding / termination within fixed-length strings

**Comment by GreyCat** [comment]
I've [fixed Mach-O ksy](https://github.com/kaitai-io/kaitai_struct_formats/commit/f4086ff15f2d3d7d8e91472fb15f9658f0c17cd3) to use `pad-right` for a more natural string comparisons. Original constants like `"'__cstring\0\0\0\0\0\0\0'"` are now possible as well, but it's heavily advised to use KS interpolation, not YAML interpolation (although in this case both will work), so it's better to use `'"__cstring\0\0\0\0\0\0\0"'`, i.e. single quotes in YAML and double quotes in KS expresion language.

Please take a look, eh?

**Comment by GreyCat** [comment]
Looks like it's fixed. Please reopen if any concerns arise.
