### ISSUE TITLE
ksc: C# ReadBytes size expression type mismatch

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#93]
`ReadBytes`* expects `long`, but sometimes we try use an expression which is `ulong` (ex. a `u8` field).

I am not really sure what could be the correct solution here. Maybe casting every expression to `long` before calling `ReadBytes` would solve the problem.

*there are probably other affected methods

**Comment by GreyCat** [comment]
Can we just have 2 methods with different signatures? And add extra casting + checks for `ulong` method?

**Comment by arekbulski** [comment]
This was already solved a long time ago.
