### ISSUE TITLE
Cannot Add KaitaiStruct.Runtime.CSharp to Blazor using .NET 6.0

### ISSUE THREAD

**Issue by bearsystems** [kaitai-io/kaitai_struct#933]
I am able to add Kaitai to Web API and Console applications using .NET 6.0 but when I attempt to add the NuGet package to Blazor, I get the error Cannot find module 'source-map'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?

The error is pointing to the index.d.ts file and the following line:

import { SourceNode, RawSourceMap, SourceMapGenerator } from 'source-map';

I attempted to update the source-map but it is already up to date.

Can you please let me know how to fix this error?

Thank you!

**Comment by generalmimon** [comment]
@bearsystems Do you still have a problem with this? Sorry for the long delay.

**Comment by generalmimon** [comment]
No response for a week, closing.
