### ISSUE TITLE
ksc: io.size returns std::streampos in cpp-stl

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#95]
...which is not comparable with integer types.

And numeric operations does not work either.

Affected file: `quicktime_mov.ksy`:
 - `value: 'len32 == 0 ? (_io.size - 8) : (len32 == 1 ? len64 - 16 : len32 - 8)'`

**Comment by GreyCat** [comment]
Actually, fixed this some time ago: https://github.com/kaitai-io/kaitai_struct_cpp_stl_runtime/commit/443b790a946743a906c5214f7c7800ea2fd22356

Should be ok, although there are still problems compiling it for Windows and OS X :(
