### ISSUE TITLE
ksc: prohibit identifiers starting with digit

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#96]
Affected formats:
- quicktime_mov.ksy: `brand` enum, a lot of `3g*` enum names
- ipv4_packet.ksy: `protocol` enum: `3pc`

**Comment by GreyCat** [comment]
Added enum member names check in https://github.com/kaitai-io/kaitai_struct_compiler/commit/2309034b1132dac30fbe68186659a24a7adfcb8f — should show a clear error message now. Please take a look?

**Comment by GreyCat** [comment]
Seems to be working. Please reopen if you'll find any problems.
