### ISSUE TITLE
Nim: `encoding: ASCII` does not work on Windows

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#960]
Cc @sealmove

On my machine, the error looks like this:

```
C:\temp\kaitai_struct\tests\spec\nim\texpr_str_encodings.nim(7) texpr_str_encodings
C:\temp\kaitai_struct\tests\compiled\nim\expr_str_encodings.nim(122) fromFile
C:\temp\kaitai_struct\tests\compiled\nim\expr_str_encodings.nim(50) read
C:\temp\kaitai_struct\runtime\nim\kaitai_struct_nim_runtime.nim(332) encode
C:\Users\pp\.choosenim\toolchains\nim-1.6.4\lib\pure\encodings.nim(505) convert
C:\Users\pp\.choosenim\toolchains\nim-1.6.4\lib\pure\encodings.nim(354) open
Error: unhandled exception: cannot find encoding ASCII [EncodingError]
```

As I see [in `encodings.nim:338-355`](https://github.com/nim-lang/Nim/blob/v1.6.4/lib/pure/encodings.nim#L338-L355), the encoding is resolved differently on Windows. On non-Windows systems, apparently `iconv` is used, but on Windows the code uses a [`winEncodings`](https://github.com/nim-lang/Nim/blob/v1.6.4/lib/pure/encodings.nim#L75) lookup table for name and the corresponding code page number, and there's no `ascii`.

**Comment by sealmove** [comment]
Hello @generalmimon. It looks like there is an entry for `us-ascii` but not for `ascii`. The issue should be resolved now with [e0caf5](https://github.com/kaitai-io/kaitai_struct_nim_runtime/commit/e0caf578a9c7beba00c9b1bedaed34953b68878e). Please confirm, cheers.

**Comment by generalmimon** [comment]
@sealmove Thanks for the fix, it works fine except that `cmpIgnoreCase` returns `int`, not `bool`: https://github.com/kaitai-io/kaitai_struct_nim_runtime/commit/a3253fd465d45b657131294ccd51c65a8b5f0643

So this issue is now resolved.
