### ISSUE TITLE
Missing details for javascript in documentation

### ISSUE THREAD

**Issue by jumpjack** [kaitai-io/kaitai_struct#976]
In [documentation ](https://doc.kaitai.io/user_guide.html#opaque-types) it is stated;

> By default, specifying a plain name invokes a custom processing class in the same namespace/package where the code is generated. If you want to keep your generated code in a separate namespace/package than your custom hand-made code, you can specify it like this:

```
seq:
  - id: buf
    size: 50
    process: com.example.my_rle(5, 3) 
```

> For Java, this would result in an invocation of com.example.MyRle class. Other languages use similar rules of translation; **see language-specific notes for details**.

(bold is mine)

But in [javascript specific-notes](https://doc.kaitai.io/lang_javascript.html) there is no explanation about how to access a custom processor.

I wrote this code for testing:

```
function  MyCustomProcessor(a) {
	console.log("A=",a)

	function decode(a) {
	console.log("ricevo ",a);
	console.log("restituisco ", a+1);
		return a+1;
		}

	return { decode : decode}
}
```

And this KSY file:

```
seq:
  - id: buf
    size: 50
    process: MyCustomProcessor(1) 
```

But of course it works only if I put my code inside the auto-generated code, which is dangerous because my code could be overwritten "anytime" if I update the KSY file.

So, in pure client-side javascript , how do I make kaitai access a function outside of its generated .js file?

By the way: I think it should be underlined that line

`<script src="KaitaiStream.js"></script>`

shall be placed before any other kaitai-generated script...: at first run I spent hours figuring out why I could not get kaitai working...

**Comment by generalmimon** [comment]
> But of course it works only if I put my code inside the auto-generated code, which is dangerous because my code could be overwritten "anytime" if I update the KSY file.

Yes, that's not a good idea. Check the generated module - it should look similar to this ([`ProcessCustom.js:8-11`](https://github.com/kaitai-io/ci_targets/blob/45f467e153f189019926516112eb22738c54d076/compiled/javascript/ProcessCustom.js#L8-L11)):

```javascript
(function (root, factory) {
//...
  } else {
    root.ProcessCustom = factory(root.KaitaiStream, root.MyCustomFx, root.CustomFx);
  }
}(typeof self !== 'undefined' ? self : this, function (KaitaiStream, MyCustomFx, CustomFx) {
```

If you're using the parser in the browser, this branch will be selected. It means that it tries to find `MyCustomFx` and `CustomFx` (these are the names of custom processors in the global context - see the source spec [`process_custom.ksy`](https://github.com/kaitai-io/kaitai_struct_tests/blob/0934c60eaf8b2407093687e9ef39f4bf8dd7b80e/formats/process_custom.ksy)) in the **global context** (which is referenced as [`self`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self) or [`this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#global_context)).

First, I'll fix your .ksy snippet - you're supposed to refer to your processor as `my_custom_processor` from the .ksy specification (but it will be actually translated to `MyCustomProcessor` when you compile it to JavaScript, because that's a name convention that JS uses):

```diff
 seq:
   - id: buf
     size: 50
-    process: MyCustomProcessor(1) 
+    process: my_custom_processor(1)
```

This means that you can just declare `MyCustomProcessor` in the global scope before including the generated parser, and it will be used:

```html
<script src="KaitaiStream.js"></script>
<script>
function MyCustomProcessor(a) {
	console.log("A=", a);

	function decode(a) {
		console.log("ricevo ", a);
		console.log("restituisco ", a+1);
		return a+1;
	}

	return { decode : decode };
}
</script>
<script src="Gif.js"></script>
```

I cannot say that your custom processor does make sense in this state, though - the `decode()` method is supposed to **take** a byte array and **return** a byte array, and I don't think `x + 1` with `x` being a byte array does anything reasonable.

**Comment by jumpjack** [comment]
Thanks.
Yes, my "decoder" was just some nonsense code: I was just  trying to get rid of the "undefined" error, before placing something useful in the function.
Now I did put it inside an additional SCRIPT tag before my main scripts, and it works.

I take the chance to propose a full "hello world" html page (attached) for client-side  javascript, which allows processing local file rather than just online file; it's a standalone file, but I also attach a "minified" version which just links the various needed scripts, probably better for a tutorial.

Please note that I am not very expert in JS, so maybe there are much better ways to write example code for kaitai...  but this is what I can do.

**Comment by generalmimon** [comment]
@jumpjack:
> Please note that I am not very expert in JS

That's completely OK, I'm not an expert in most things but it never stops me from trying and learning new things. Yes, I make mistakes along the way, but who doesn't?

**Comment by jumpjack** [comment]
Last question: is there a method to use custom processors in Web Ide?

**Comment by generalmimon** [comment]
@jumpjack:
> Last question: is there a method to use custom processors in Web Ide?

Yes, I've already indicated this in my earlier comment (https://github.com/kaitai-io/kaitai_struct/issues/976#issuecomment-1173908830):

> See https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#opaque-type-support (it is described for opaque types, but it will work the same for custom processors).

**Comment by jumpjack** [comment]
Ah, that part.
I didn't understand a single word  :-)  , but I'll try studying it a bit...

**Comment by generalmimon** [comment]
> I didn't understand a single word :-) , but I'll try studying it a bit...

It shouldn't be so hard - you open the JS Console in the browser on the Web IDE page (usually <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>), paste and run something like this (this is just XORing each input byte with the `a` as the key - `^` is the [XOR operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_XOR) in JS):

```js
localStorage.setItem("userTypes", `
function MyCustomProcessor(a) {
	console.log("A=", a);

	function decode(input) {
		var len = input.length;
		var output = new Uint8Array(len);
		for (var i = 0; i < len; i++) {
			output[i] = input[i] ^ a;
		}
		return output;
	}

	return { decode : decode };
}
this.MyCustomProcessor = MyCustomProcessor;
`);
```

<details>
  <summary>`decode()` can be simplified</summary>

> **Note**: the `decode()` function can be significantly simplified (see below), but you have to know about the [`TypedArray.from()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from) function, so I rather used the long version first to make sure you can understand it:
> 
> ```js
> localStorage.setItem("userTypes", `
> function MyCustomProcessor(a) {
> 	console.log("A=", a);
> 
> 	function decode(input) {
> 		return Uint8Array.from(input, byte => byte ^ a);
> 	}
> 
> 	return { decode : decode };
> }
> this.MyCustomProcessor = MyCustomProcessor;
> `);
> ```

</details>

At this point, when you recompile the `.ksy` spec (either by making a change in it, which recompiles it automatically, or explicitly by pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd> with your cursor in the `.ksy` editor pane), the `MyCustomProcessor` will be included.

**Comment by generalmimon** [comment]
> But your proposal...

> With this KSY:
> 
> ```ksy
> meta:
>   id: pds
>   file-extension: img
>   endian: be
>   ks-opaque-types: true
> 
> seq:
>   - id : buf
>     type : my_custom_processor(1)
> ```
> 
> cannot work: due to missing _read definition, it results in:
> 
> ```
> Parse error: undefined
> Call stack: undefined TypeError: this.buf._read is not a function
> ```

Well, obviously - you literally said you'd like to know how to define and use a **custom processor** in the Web IDE, so I wrote you a `process`or. But know you attempt to use this *processor* as an opaque type, and I have no idea why, because I believe I provided you with almost a step-by-step guide. 

Okay, I haven't included a KSY snippet in my comment https://github.com/kaitai-io/kaitai_struct/issues/976#issuecomment-1175010286, but that was because I thought you already know that the processing routine can be selected with the `process` key, as you demonstrated in your initial comment https://github.com/kaitai-io/kaitai_struct/issues/976#issue-1293279164 and I only corrected the processor name in https://github.com/kaitai-io/kaitai_struct/issues/976#issuecomment-1173934419.

So now you really want an opaque type, or the custom processor we've been talking about all along (until now I guess)?

**Comment by jumpjack** [comment]
I need a custom processor working inside Web IDE (if possible).
Offline, outside IDE, I already wrote it (I attached the example), but in Web IDE I get an "undefined" error, and documentation only explains the hack for types, saying that for processors "it's similar".... but I don't get how to "hack" the local storage to get my processor compiled.

**Comment by jumpjack** [comment]
> Please don't be fooled by the key identifier "userTypes", it works for processors as well.

It does not for me, "_read" is undefined.

**Comment by generalmimon** [comment]
> It does not for me, "_read" is undefined.

```diff
 seq:
   - id : buf
-    type : my_custom_processor(1)
+    size: 50
+    process: my_custom_processor(1)
```

**Comment by jumpjack** [comment]
...and we are back to first post.

**Comment by generalmimon** [comment]
@jumpjack:
> ...and we are back to first post.

A very good observation, because IT WAS ACTUALLY CORRECT ALL THIS TIME and I have no idea what made you think otherwise.

**Comment by jumpjack** [comment]
I think I got it: for some reasons, Web IDE does not always clean up error console: sometimes all works fine, but last error remains visible! 

For example, using this code:

```
localStorage.setItem("userTypes", `
var myvar;
function MyCustomProcessor(a) {
	console.log("A=", a);

	function decode(input) {
		console.log("Input", input);
		var myvar = 1111;
		return myvar;
	}

	return { decode : decode };
}
this.MyCustomProcessor = MyCustomProcessor;
`);
```

I get an "undefined myvar" error.

But if I completely remove myvar...

```
localStorage.setItem("userTypes", `
function MyCustomProcessor(a) {
	console.log("A=", a);

	function decode(input) {
		console.log("Input", input);
		return 1;
	}

	return { decode : decode };
}
this.MyCustomProcessor = MyCustomProcessor;
`);
```

The error remains there, although I get back the "1" correctly!
CTRL+ENTER does not help.

Completely removing the SEQ definition and undoing the removal "unlocks something" and the error gets cleaned.

**Comment by generalmimon** [comment]
@jumpjack:
> I think I got it: for some reasons, Web IDE does not always clean up error console: sometimes all works fine, but last error remains visible!

Yes, that's very much possible, and I'm sorry for the confusion it caused you. Clearly I have a lot of work to do on the Web IDE, it's pretty neglected and there's a bunch of bugs 😞

> Completely removing the SEQ definition and undoing the removal "unlocks something" and the error gets cleaned.

You can use the small cross `×` button next to the **Errors** label. That will close the errors panel, and it will reappear only if another error actually occurs.

**Comment by jumpjack** [comment]
It's already an amazing tool as is, thanks for this great job you are doing. I would have avoided a lot of time and headaches if I did find it before... ;-)

**Comment by generalmimon** [comment]
@jumpjack Thanks for the praise. I'm glad that we finally solved your problem.

**Comment by jumpjack** [comment]
I am now thinking that it is not possibile to reach my objective: use kaitai to build a KSY file enabling any language to read an IMG file.
IMG files are strange; their structure is:
- 1st text label of unknown length (length defined inside label itself)
- 2nd text label of unknown length (length defined inside label itself)
- binary data structured as described in the labels

It looks like I should make all data extraction inside a processor... which makes the KSY file actually useless for other languages, as it only defines extraction of labels.
Is this correct?
I think should focus on the other files formats I am working with, which are just binary. I've already done it for [VST files](https://github.com/jumpjack/VST-converter/blob/main/VST.ksy) and [RGB files](https://github.com/jumpjack/VST-converter/blob/main/SGI_RGB.ksy), now I'll start investigating .PFB files, which have undocumented format but at least a  [basic C++ source available.](https://github.com/j3k0/OpenPFB/blob/master/OpenPfb.h)
