### ISSUE TITLE
_io.pos not working?

### ISSUE THREAD

**Issue by jumpjack** [kaitai-io/kaitai_struct#977]
Is **_io.pos** supposed to contain the offset of the substream in the root stream? I read same values for all substreams.
For example, in this structure:
```
 node
   | 
   + --- list
             |
             +---- element
```

I read always same value for _io.pos when I am in node, in list or in element.

**Comment by generalmimon** [comment]
See the chapter [8. Common pitfalls](https://doc.kaitai.io/user_guide.html#_common_pitfalls) in the User Guide: 

- [8.2. Not specifying size does not create a substream](https://doc.kaitai.io/user_guide.html#_not_specifying_size_does_not_create_a_substream)
- [8.1. Specifying size creates a substream](https://doc.kaitai.io/user_guide.html#_specifying_size_creates_a_substream)

Also [5. Streams and substreams](https://doc.kaitai.io/user_guide.html#stream).

**Comment by generalmimon** [comment]
From my side, this question has been answered.
