### ISSUE TITLE
ksc: java enum comparison: use ordinal

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct#98]
Currently javac throws the following exception:

```
target/java/src/Pyc.java:365: error: bad operand types for binary operator '>='
            if (opCode() >= OpCodeEnum.STORE_NAME) {
                         ^
  first type:  OpCodeEnum
  second type: OpCodeEnum
1 error 
```

for the following expression:

```if: "op_code >= op_code_enum::store_name" # store_name == have_arguments```

**Comment by GreyCat** [comment]
There are actually several problems there:

1. Compiler should report a compile-time error trying to apply `<`, `>`, `<=`, `>=` to enum type operands.
2. Expression language should support some syntax to convert enums back to integers to make such comparsions possible (actually, this is hard for some languages like Ruby). Probably something like:

```
if: "op_code.to_i >= op_code_enum::store_name.to_i"
```

3. pyc.ksy should be fixed accordingly.

**Comment by GreyCat** [comment]
Done (1) - see https://github.com/kaitai-io/kaitai_struct_compiler/commit/672d45e5d4b603c302ded1aea873d7bf7211866b.

**Comment by GreyCat** [comment]
Done (2) - now it's possible to use `.to_i` on any enums in any language.

**Comment by GreyCat** [comment]
Done (3) - see https://github.com/kaitai-io/kaitai_struct_formats/commit/22d28810d878d9f3c71d739d5f5f6b564570aadb - works for me now, even in Ruby :)

**Comment by GreyCat** [comment]
Looks like this can be closed. Feel free to reopen if any questions remain.
