### ISSUE TITLE
ES Modules output support for Javascript

### ISSUE THREAD

**Issue by raymond-h** [kaitai-io/kaitai_struct#994]
I think it's finally time to add support for outputting ES Modules. At this point they are widely supported across the entire ecosystem of browsers, NodeJS, and various tools that work with JS. It should probably be supported as an option alongside the existing UMD output for now.

**Comment by generalmimon** [comment]
I believe that https://github.com/kaitai-io/kaitai_struct/issues/267 is a superset of what you propose here, so perhaps you can look what's been already suggested and add your comment there? 

I'm closing _this_ issue as duplicate then.
